/* 원인 항목 2: 데이터센터 장비, 서버 NIC, 서버 OS, 소켓과 프로토콜 */
(function () {
  const add = (layer, list) => list.forEach(c => DATA.causes.push(Object.assign({ layer }, c)));

  /* ---------------- 5. 데이터센터 네트워크 장비 ---------------- */
  add('dc-net', [
    { id: 'dc-firewall', t: '방화벽 세션 테이블 포화', en: 'Firewall session table exhaustion',
      s: '방화벽은 통과시킨 모든 연결을 세션 테이블에 기록해 추적합니다. 테이블이 다 차면 새 연결을 받을 수 없습니다.',
      c: ['접속 폭주나 공격으로 세션 수가 한도에 도달', '새 연결을 기록할 빈 항목이 없어 거부', '새 접속 실패, 일부 기존 접속도 끊김'],
      sym: ['noconnect', 'disconnect'], fx: ['loss'], who: ['server'], when: ['login', 'event'],
      fix: '세션 테이블 크기 늘리기, 짧게 끝난 연결 빨리 정리, 공격 차단.',
      sim: 'rush' },
    { id: 'dc-ddos', t: 'DDoS 방어 경유·오탐', en: 'DDoS scrubbing latency, false positives',
      s: '공격을 막으려고 트래픽을 스크러빙 센터로 돌리면 경로가 길어지고, 정상 사용자를 공격으로 오인해 막기도 합니다.',
      c: ['공격 감지 후(또는 상시) 들어오는 트래픽을 스크러빙 센터로 우회', '경로가 길어지고, 일부 정상 패킷을 공격으로 판정', '전체 핑 상승, 특정 지역·통신사만 접속 불가'],
      sym: ['delay', 'noconnect', 'teleport'], fx: ['lat', 'loss'], who: ['server', 'region'], when: ['event', 'random'],
      num: '스크러빙 거점이 같은 나라에 있으면 수 ms, 다른 나라 거점을 거치면 30~100ms 넘게 더해집니다. 보통 들어오는 쪽만 돌아가고 서버의 응답은 곧바로 나갑니다. 걸러진 트래픽을 터널로 되돌려 받으면 한 번에 보낼 수 있는 크기(MTU)도 줄어, 큰 패킷만 사라지는 문제로 이어지기도 합니다.',
      fix: '게임 트래픽 패턴에 맞춘 방어 규칙, 지역별 스크러빙 거점, 터널 구간에서 TCP 패킷 크기 줄이기(MSS 조정).' },
    { id: 'dc-lb-idle', t: '로드밸런서 유휴 타임아웃', en: 'Load balancer idle timeout',
      s: '로드밸런서는 유휴 연결을 일정 시간 뒤 지웁니다. 게임은 연결이 유지된 것으로 간주하고 있다가 접속이 끊깁니다.',
      c: ['플레이어가 한동안 아무 패킷도 안 보냄(대화창, 자리 비움)', '로드밸런서가 유휴 연결을 정리(흔한 기본값 60~350초)', '다시 움직이는 순간 접속 끊김'],
      sym: ['disconnect'], fx: ['loss'], who: ['me', 'server'], when: ['idle'],
      num: 'AWS ALB는 60초, NLB는 TCP 350초·UDP 120초, Azure Load Balancer는 TCP 4분이 기본값입니다. ALB와 NLB의 TCP 값은 바꿀 수 있지만 NLB의 UDP 120초는 바꿀 수 없습니다. ALB는 시간이 되면 서버 쪽 연결도 닫지만, NLB는 조용히 지워 서버가 모르는 채로 남기 쉽습니다.',
      fix: '가장 짧은 유휴 타임아웃의 절반 이하 간격으로 하트비트 보내기(ALB 60초 뒤라면 30초 이하).',
      sim: 'timeouts' },
    { id: 'dc-cloud-conntrack', t: '클라우드 보안 그룹의 연결 추적 만료', en: 'Cloud security group connection tracking timeout',
      s: '클라우드 서버에 붙은 방화벽(보안 그룹)도 연결을 추적하고, 유휴 연결의 추적 항목은 정해진 시간 뒤 만료됩니다. 로드밸런서 없이 바로 붙는 서버도 가만히 있던 플레이어의 접속이 끊길 수 있습니다.',
      c: ['보안 그룹이 게임 연결을 추적하는 설정(특정 주소만 허용, 나가는 규칙 제한, NLB 경유 등)', '한동안 유휴 상태인 연결의 추적 항목이 만료되고, 그 뒤 오는 패킷을 보안 그룹이 조용히 버림', '자리 비움 뒤 다시 움직이면 반응이 없다가 접속 끊김. 서버 프로그램은 한참 모름'],
      sym: ['disconnect'], fx: ['loss'], who: ['me', 'server'], when: ['idle'],
      num: 'AWS 기준 6세대 Nitro 인스턴스는 유휴 TCP 연결의 추적 항목을 기본 350초 뒤 지웁니다(이전 세대는 5일). UDP는 양방향으로 오간 흐름 180초, 한 방향만 오간 흐름 30초가 기본입니다.',
      fix: '가장 짧은 유휴 타임아웃의 절반 이하 간격으로 하트비트 보내기(TCP 350초라면 3분 이하), 인스턴스의 연결 추적 시간(TcpEstablishedTimeout) 확인, 새 세대 인스턴스로 옮길 때 유휴 시험.',
      sim: 'timeouts' },
    { id: 'dc-lb-imbalance', t: '로드밸런서 쏠림·헬스체크 오판', en: 'LB imbalance, bad health checks',
      s: '연결이 한 서버에만 몰리거나, 이미 죽은 서버로 계속 사람을 보냅니다.',
      c: ['분배 규칙이 맞지 않거나 헬스체크가 실제 상태를 못 봄', '한 서버만 과부하, 또는 죽은 서버로 접속 시도', '일부 채널·일부 사람만 렉, 접속 불가'],
      sym: ['slowmo', 'noconnect'], fx: ['stall', 'loss'], who: ['zone'], when: ['login', 'event'],
      fix: '실제 게임 응답을 확인하는 헬스체크, 서버 부하 기반 분배.' },
    { id: 'dc-microburst', t: '스위치 마이크로버스트', en: 'Switch microburst drops',
      s: '여러 서버가 같은 순간 수천 명에게 패킷을 한꺼번에 보내면, 그 트래픽이 모이는 스위치 포트의 작은 버퍼가 1ms도 안 돼 넘칩니다.',
      c: ['월드 보스 등장·대규모 스킬, 또는 여러 서버의 틱이 같은 순간에 맞물려 한꺼번에 발송', '여러 포트가 한 포트로 모이거나 빠른 포트에서 느린 포트로 넘어가는 곳의 버퍼(포트당 수백 KB~수 MB)가 순간적으로 가득', '일부 패킷 폐기, 많은 사람이 동시에 순간이동·스킬 씹힘'],
      sym: ['teleport', 'dropped'], fx: ['loss'], who: ['zone'], when: ['event'],
      num: '10Gbps 포트로 1ms 동안 내보낼 수 있는 양은 약 1.25MB. 두 포트의 트래픽이 한 포트로 동시에 몰리면 1ms마다 1.25MB씩 쌓입니다. 1초 평균 사용률이 10%여도 1ms 단위로는 넘칠 수 있습니다.',
      fix: '전송을 틱 안에 고르게 나누기(페이싱), 버퍼 큰 스위치, 트래픽 분산.' },
    { id: 'dc-uplink', t: '데이터센터 회선 포화', en: 'Uplink saturation',
      s: '패치 배포·로그 전송·백업이 게임과 같은 회선을 쓰면 회선이 꽉 찹니다.',
      c: ['대용량 전송이 같은 회선을 점유', '회선 대기열과 손실 증가', '서버 전체 핑 상승과 순간이동'],
      sym: ['delay', 'teleport'], fx: ['lat', 'loss'], who: ['server'], when: ['periodic', 'event'],
      fix: '게임 트래픽 우선 처리(QoS), 대용량 전송 회선 분리.' },
    { id: 'dc-failover', t: '네트워크 장비 장애 전환(페일오버)', en: 'Network device failover',
      s: '라우터·방화벽 한 대가 고장 나 예비 장비로 전환(페일오버)되는 몇 초 동안 모두가 멈춥니다.',
      c: ['장비 고장 또는 점검으로 예비 장비로 전환', '전환에 수 초, 세션 정보가 동기화되지 않으면 연결 초기화', '서버의 모든 유저가 동시에 멈춤, 대량 접속 끊김'],
      sym: ['freeze', 'disconnect'], fx: ['loss'], who: ['server'], when: ['random'],
      num: '장비가 고장을 바로 감지하면 1~3초. 빠른 고장 감지(BFD) 없이 BGP 기본 타이머에만 맡기면 인접 장비가 감지하기까지 90~180초 동안 경로가 끊길 수 있습니다.',
      fix: '연결 상태를 공유하는 이중화, BFD로 고장을 1초 안에 감지, 짧은 끊김을 견디는 타임아웃.' },
    { id: 'dc-bad-cable', t: '불량 케이블·포트 오류', en: 'Bad cable / optics (CRC errors)',
      s: '광모듈이나 케이블이 불량이면 그 경로를 지나는 패킷이 일정 비율로 깨집니다.',
      c: ['광모듈·케이블 불량으로 비트 오류', '깨진 패킷은 장비가 조용히 폐기', '그 경로를 쓰는 일부 서버·사용자만 꾸준한 손실로 순간이동·고무줄'],
      sym: ['teleport', 'rubber'], fx: ['loss'], who: ['zone'], when: ['always'],
      fix: '포트 오류 카운터 모니터링, 부품 교체.' },
    { id: 'dc-mtu', t: 'MTU 불일치 (큰 패킷만 사라짐)', en: 'MTU black hole',
      s: '중간 구간의 MTU(한 번에 보낼 수 있는 크기)가 줄었는데 크기 초과 알림이 막히면, 큰 패킷만 계속 사라집니다.',
      c: ['터널·VPN 구간에서 MTU가 줄어듦', '크기 초과 알림(ICMP)이 방화벽에 막혀 보내는 쪽이 모름', '인벤토리·캐릭터 목록처럼 큰 화면을 열 때만 멈췄다가 접속 끊김'],
      sym: ['freeze', 'disconnect', 'noconnect'], fx: ['loss'], who: ['region', 'me'], when: ['action', 'login'],
      num: '보통 1500바이트, 터널을 지나면 1400 안팎으로 줄어듭니다.',
      fix: '패킷 크기 줄이기(MSS 조정), 크기 초과 알림 허용.' },
  ]);

  /* ---------------- 6. 서버 NIC ---------------- */
  add('nic', [
    { id: 'nic-irq', t: 'NIC 인터럽트 단일 코어 집중', en: 'Single-queue NIC / no RSS',
      s: 'NIC가 패킷 도착 인터럽트를 CPU 코어 하나에만 보내면 그 코어가 병목이 됩니다.',
      c: ['수신 큐가 하나이거나 여러 코어로 분산하는 RSS가 꺼져 있음', '코어 하나가 100%가 되어 패킷을 제때 못 꺼냄', '사람이 몰릴 때 서버 전체에서 손실과 지연(순간이동·입력 지연)'],
      sym: ['teleport', 'rubber', 'delay'], fx: ['loss', 'lat'], who: ['server'], when: ['event'],
      num: '코어 하나가 커널을 거쳐 처리할 수 있는 양은 패킷 크기와 설정에 따라 대략 초당 수십만~100만 패킷. 코어별 사용률에서 수신 처리 비중(mpstat의 %soft)이 한 코어에만 몰려 있으면 이 경우입니다.',
      fix: 'RSS(NIC가 분산)·RPS(커널이 분산) 설정, 인터럽트를 여러 코어에 분산, 인터럽트 처리 코어와 게임 틱 스레드 코어 분리.',
      more: '큐가 여러 개여도 게이트웨이·프록시처럼 몇 안 되는 주소에서 트래픽이 대부분 오면 한 큐로 몰립니다. UDP는 NIC 기본 설정이 주소만 보고 큐를 나누는 경우가 있어, 포트까지 보도록 바꿔야 고르게 퍼집니다.',
      sim: 'nic' },
    { id: 'nic-ring', t: '링 버퍼 부족', en: 'RX ring buffer overflow',
      s: 'NIC가 패킷을 잠시 담아 두는 링 버퍼가 작으면, 순간적으로 몰릴 때 버퍼가 넘쳐 버려집니다.',
      c: ['링 버퍼가 기본값(드라이버마다 슬롯 256~2,048개)으로 작음', '버스트 때 CPU가 꺼내기 전에 버퍼가 넘침', '버스트 순간에만 손실. 게임 서버 로그에는 흔적이 없음'],
      sym: ['teleport', 'dropped'], fx: ['loss'], who: ['server'], when: ['event'],
      num: '초당 100만 패킷이 몰리면 슬롯 1,024개는 약 1ms 만에 찹니다. 그 사이 CPU가 한 번만 늦게 와도 넘칩니다. 대부분의 NIC는 수천 개까지 늘릴 수 있습니다.',
      fix: '링 버퍼 크게(ethtool -G), 폐기(drop) 카운터 감시(ethtool -S의 rx_missed_errors 등, 이름은 드라이버마다 다름).',
      sim: 'nic' },
    { id: 'nic-coalesce', t: '인터럽트 병합 과다', en: 'Interrupt coalescing',
      s: 'CPU 부담을 줄이려고 패킷을 모았다 한 번에 알리면, 모으는 시간만큼 늦어집니다.',
      c: ['NIC가 일정 시간·개수만큼 모았다가 알림', '모으는 동안 패킷이 대기', '미세한 지연 증가. 보통은 작지만 과하면 ms 단위'],
      sym: ['delay'], fx: ['lat'], who: ['server'], when: ['always'],
      num: '보통 수십~수백 µs. 게임에는 대개 무시할 수준이지만 설정이 과하면 ms로 커집니다.',
      fix: '적응형 병합, 게임 서버에 맞는 값.',
      sim: 'nic' },
    { id: 'nic-cloud-pps', t: '클라우드 PPS 한도 초과', en: 'Cloud PPS / bandwidth allowance',
      s: '클라우드 서버는 종류마다 초당 패킷 수·대역폭 한도가 있고, 넘으면 조용히 버립니다.',
      c: ['동접이 늘어 초당 패킷 수가 인스턴스 한도를 넘음', '클라우드 네트워크가 초과분을 폐기', '원인을 알 수 없는 손실. 서버 CPU는 여유'],
      sym: ['teleport', 'dropped'], fx: ['loss'], who: ['server'], when: ['event', 'peak'],
      num: '한도는 인스턴스 크기마다 다르고, 초당 패킷 수 한도는 공개하지 않는 경우가 많습니다. 작은 인스턴스의 “최대 10Gbps”는 잠깐만 쓸 수 있는 순간 속도이고, 평소 기본 속도는 훨씬 낮습니다.',
      fix: '한도 초과 카운터 확인(AWS는 pps_allowance_exceeded, conntrack_allowance_exceeded 등), 더 큰 인스턴스, 패킷 합치기.',
      more: 'conntrack_allowance_exceeded는 연결 추적 테이블이 가득 차 새 연결을 버린 경우입니다. 테이블은 여유가 있는데 유휴 연결만 추적이 만료되어 끊긴다면 “클라우드 보안 그룹의 연결 추적 만료” 항목을 보세요.',
      sim: 'nic' },
    { id: 'nic-saturate', t: 'NIC 대역폭 포화', en: 'NIC bandwidth saturation',
      s: '1Gbps·10Gbps 카드의 한계까지 쓰면 송신 대기열이 길어지고 결국 버려집니다.',
      c: ['브로드캐스트 증가로 전송량이 카드 한계에 도달', '송신 대기열이 길어지고 넘치면 폐기', '서버 전체 지연·손실(입력 지연·순간이동)'],
      sym: ['delay', 'teleport'], fx: ['lat', 'loss'], who: ['server'], when: ['event'],
      fix: '전송량 줄이기(관심 영역, 압축, 변경분만), 카드 증설.' },
    { id: 'nic-noisy', t: '가상화 오버헤드·노이지 네이버', en: 'Noisy neighbors in virtualization',
      s: '같은 물리 서버의 다른 가상 머신이 네트워크·CPU를 많이 쓰면 내 서버의 처리가 불규칙하게 밀립니다.',
      c: ['같은 물리 서버의 다른 가상 머신이 자원을 많이 씀', '내 가상 머신의 패킷 처리가 불규칙하게 지연', '뚜렷한 원인 없이 가끔 지터(도착 간격의 흔들림)가 생겨 뚝뚝 끊김'],
      sym: ['stutter'], fx: ['jit'], who: ['server'], when: ['random'],
      fix: '전용 호스트, 성능 보장 인스턴스.' },
    { id: 'nic-reset', t: 'NIC 드라이버·펌웨어 문제', en: 'NIC hang / reset',
      s: '드라이버 버그나 기능 오동작으로 카드가 멈춰 재시작되는 동안 모든 송수신이 끊깁니다.',
      c: ['드라이버 버그, 오프로드 기능 오동작', 'NIC가 멈추고 재시작(수 초)', '그 서버의 모두가 함께 멈췄다가 순간이동하거나 접속 끊김'],
      sym: ['freeze', 'disconnect'], fx: ['loss'], who: ['server'], when: ['random', 'uptime'],
      fix: '커널 로그의 “transmit queue … timed out”, “Link is Down” 기록 확인, 드라이버·펌웨어 업데이트, 문제 기능 끄기.' },
    { id: 'nic-offload', t: 'GRO/LRO 병합 대기 지연', en: 'GRO/LRO batching',
      s: '여러 패킷을 하나로 묶어 CPU 부담을 줄이는 기능입니다. 설정에 따라 작은 게임 패킷이 함께 묶을 다음 패킷을 잠깐 기다리기도 합니다.',
      c: ['NIC·커널이 도착한 패킷을 묶어서 처리', '하드웨어 병합(LRO)이나 병합 대기 시간 설정이 켜져 있으면 다음 패킷을 기다리며 잠깐 대기', '미세한 지연 증가(대개 수십 µs 이하)'],
      sym: ['delay'], fx: ['lat'], who: ['server'], when: ['always'],
      fix: '게임 트래픽에 맞게 조정. 효과는 대개 작습니다.' },
  ]);

  /* ---------------- 7. 서버 OS ---------------- */
  add('server-os', [
    { id: 'so-backlog', t: '접속 대기열(backlog) 넘침', en: 'Listen backlog / SYN queue overflow',
      s: '점검 직후 수만 명이 동시에 접속하면, 커널의 접속 대기열(backlog)이 넘쳐 접속 시도가 버려집니다.',
      c: ['점검 종료와 동시에 게임 서버가 accept로 접속을 처리하는 속도보다 빨리 몰림', '커널의 접속 대기열(backlog. 서버 코드가 listen에 준 값과 커널 상한 중 작은 쪽)이 가득', '접속 시도가 버려지고 재시도가 반복되어 접속 불가·무한 로딩'],
      sym: ['noconnect'], fx: ['loss'], who: ['server'], when: ['login'],
      num: '리눅스 커널 상한(somaxconn)은 5.4부터 기본 4,096(그 전 128)이지만, 서버 코드가 listen에 더 작은 값을 주면 그 값이 한도입니다. 리눅스는 대기열이 차면 접속 요청을 오류 없이 조용히 버립니다. 클라이언트 OS가 1초 뒤부터 몇 차례 다시 보내므로, 플레이어에게는 “연결 실패”보다 긴 로딩으로 보입니다. 윈도우 서버는 거절 응답을 돌려보내 클라이언트가 곧바로 “연결 실패”를 봅니다.',
      fix: 'backlog 늘리기(커널 somaxconn과 서버 코드의 listen 값 둘 다), 접속을 받는 스레드가 다른 일로 멈추지 않게, 넘침 횟수 감시(nstat의 ListenOverflows), 로그인 대기열 시스템, 재시도 간격 늘리기.',
      sim: 'rush' },
    { id: 'so-fd', t: '파일 디스크립터 한도', en: 'File descriptor limit (ulimit)',
      s: '연결 하나마다 파일 디스크립터(fd, OS가 열린 파일·소켓에 붙이는 번호)가 필요한데, 한 프로세스가 열 수 있는 fd 수가 제한되어 있습니다.',
      c: ['동접이 프로세스의 파일 디스크립터 한도에 도달', '서버가 새 연결을 받지 못함(Too many open files). 로그·DB 연결 열기도 함께 실패', '정확히 일정 인원부터 아무도 못 들어오고 로딩만 계속됨'],
      sym: ['noconnect'], fx: ['loss'], who: ['server'], when: ['login', 'event'],
      num: '리눅스는 서비스 설정을 따로 하지 않으면 한도가 1,024인 경우가 아직 많습니다. 게임 서버는 보통 수만~수십만으로 올립니다. 윈도우에는 이렇게 낮은 기본 한도가 없습니다.',
      fix: 'ulimit·서비스 설정(systemd의 LimitNOFILE) 확인, 한도 근접 경보.',
      more: '받지 못한 접속은 커널 접속 대기열(backlog)에 그대로 남아 있어, 서버 코드에 따라 “새 접속 있음” 알림을 계속 받으며 CPU를 낭비하기도 합니다.',
      sim: 'rush' },
    { id: 'so-sockbuf', t: '커널 소켓 버퍼 부족', en: 'Small socket buffers',
      s: '송수신 버퍼가 작으면 버스트 트래픽이 몰릴 때 UDP로 받은 패킷은 버려지고, TCP 송신은 버퍼에 여유가 없어 막힙니다.',
      c: ['SO_SNDBUF·SO_RCVBUF가 기본값이거나 너무 작음', '버스트나 받는 스레드가 잠깐 멈춘 사이 UDP 수신 버퍼가 넘쳐 폐기, TCP는 송신 버퍼에 여유가 없어 대기', '순간이동(UDP 손실) 또는 몰아치기(TCP 대기)'],
      sym: ['teleport', 'burst'], fx: ['loss', 'stall'], who: ['server'], when: ['event'],
      num: '리눅스 UDP 수신 버퍼 기본값은 약 208KB입니다. 작은 패킷도 한 개가 커널 메모리를 실제 크기보다 훨씬 많이 차지해 수십~수백 개면 찹니다. 초당 10만 개를 받는 서버라면 받는 스레드가 몇 ms만 멈춰도 넘칩니다.',
      fix: '트래픽에 맞춘 버퍼 크기와 커널 상한(rmem_max·wmem_max) 조정, 버퍼 넘침 카운터(RcvbufErrors) 감시. TCP는 크기를 직접 정하면 리눅스의 자동 크기 조절이 꺼지니 주의. 너무 크게 잡으면 오래된 데이터가 버퍼에 쌓여 지연이 늘어나니 적당히.',
      sim: 'sndbuf' },
    { id: 'so-context', t: '스레드 과다와 컨텍스트 스위칭', en: 'Thread oversubscription, context switching',
      s: '코어보다 훨씬 많은 스레드를 돌리면 OS가 번갈아 실행시키는 데만 CPU를 씁니다.',
      c: ['연결마다 스레드를 만드는 등 스레드가 수백~수천 개', '컨텍스트 스위칭(실행 스레드 교체) 비용과 캐시 미스 증가', 'CPU는 바쁜데 처리량은 낮고 틱이 들쭉날쭉해 뚝뚝 끊김·슬로우모션'],
      sym: ['stutter', 'slowmo'], fx: ['stall', 'jit'], who: ['server'], when: ['event'],
      num: '컨텍스트 스위칭 한 번에 수 µs, 그 뒤 캐시 미스 비용까지 합치면 더 큽니다.',
      fix: '코어 수에 맞춘 스레드, 비동기 I/O(epoll·IOCP).' },
    { id: 'so-steal', t: 'CPU 스틸 (가상 머신)', en: 'CPU steal time',
      s: '물리 서버(하이퍼바이저)가 가상 머신의 CPU 시간을 잠시 다른 가상 머신에 넘기는 동안(CPU 스틸) 게임 서버가 멈춥니다.',
      c: ['같은 호스트의 다른 가상 머신이 CPU를 많이 씀', '내 가상 머신이 수 ms~수십 ms씩 실행 기회를 잃음', '원인 모를 틱 시간 급증으로 뚝뚝 끊김·멈춤'],
      sym: ['stutter', 'freeze'], fx: ['stall'], who: ['server'], when: ['random'],
      fix: 'steal 지표(top·vmstat의 st) 모니터링, 전용 코어·호스트, CPU 크레딧이 바닥나면 느려지는 버스트형 인스턴스 피하기.' },
    { id: 'so-cpu-quota', t: '컨테이너 CPU 스로틀링 (CFS 쿼터)', en: 'Container CPU throttling (CFS quota)',
      s: '컨테이너에 CPU 한도를 걸면, 정해진 주기(보통 100ms) 안에 할당량을 다 쓴 순간 남은 시간 동안 강제로 멈춥니다(스로틀링).',
      c: ['쿠버네티스 등에서 게임 서버 컨테이너에 CPU 한도(limit)를 걸어 둠', '틱 계산이 몰린 순간 할당량을 다 써서 다음 주기까지 수십 ms 정지', '평균 CPU는 낮은데 틱이 주기적으로 튀어 뚝뚝 끊김·슬로우모션'],
      sym: ['stutter', 'slowmo'], fx: ['stall', 'jit'], who: ['server'], when: ['event', 'random'],
      num: '한도 2코어인 서버에서 스레드 8개가 동시에 일하면, 100ms 주기의 할당량을 25ms 만에 다 쓰고 75ms를 멈춥니다.',
      fix: 'CPU 한도를 넉넉히 두거나 빼고 전용 코어 배정, 스로틀링된 횟수(nr_throttled) 감시.' },
    { id: 'so-oom', t: 'OOM 킬러', en: 'Out-of-memory killer',
      s: '리눅스는 메모리가 바닥나면 메모리를 가장 많이 쓰는 프로세스를 골라 강제로 죽입니다. 대개 게임 서버입니다.',
      c: ['누수나 폭증으로 메모리 고갈, 또는 컨테이너 메모리 한도 도달', '커널이 게임 서버 프로세스를 강제 종료', '그 서버의 모두가 동시에 접속 끊김, 최근 진행 롤백 가능'],
      sym: ['disconnect', 'dropped'], fx: ['stall'], who: ['server'], when: ['uptime', 'event'],
      num: '커널 로그(dmesg)에 “Out of memory: Killed process”가 남고, 쿠버네티스에서는 OOMKilled로 보입니다. 윈도우에는 OOM 킬러가 없고, 메모리 할당이 실패하면서 서버가 오류로 죽는 경우가 많습니다.',
      fix: '메모리 경보, 누수 수정, 메모리 상한과 정상 종료 절차, 먼저 죽일 순서 조정(oom_score_adj).',
      sim: 'leak' },
    { id: 'so-reclaim', t: '메모리 회수·컴팩션으로 인한 멈춤', en: 'Memory compaction / reclaim stalls (THP)',
      s: 'OS가 큰 페이지(huge page)를 만들려고 메모리를 컴팩션하거나 여유 메모리를 회수하는 동안 프로세스가 멈춥니다.',
      c: ['여유 메모리가 줄거나 큰 페이지 기능(THP)이 메모리 컴팩션 실행', '메모리를 요청한 스레드가 회수·컴팩션이 끝날 때까지 대기', '불규칙한 서버 멈춤(수 ms~수백 ms)'],
      sym: ['freeze', 'stutter'], fx: ['stall'], who: ['server'], when: ['uptime', 'random'],
      fix: '큰 페이지(THP)는 필요한 곳에만 쓰게(madvise) 설정, 여유 메모리 기준 높이기.' },
    { id: 'so-timejump', t: '시스템 시계 점프 (NTP 스텝)', en: 'Wall-clock jump (NTP step)',
      s: '서버 시계가 한 번에 몇 초 앞뒤로 조정되면 시스템 시계에 의존하는 타이머가 한꺼번에 발동하거나 멈춥니다.',
      c: ['시간 동기화가 시계를 한 번에 크게 조정', '타이머가 몰아서 발동하거나 멈추고, 타임아웃이 잘못 판정됨', '버프·쿨타임 이상, 일제히 접속 끊김, 몰아치기'],
      sym: ['burst', 'disconnect', 'dropped'], fx: ['stall'], who: ['server'], when: ['random'],
      num: 'ntpd는 차이가 0.128초를 넘으면 한 번에 맞추고, 그보다 작으면 1초 차이를 없애는 데 30분쯤 걸리는 속도로 서서히 맞춥니다. 요즘 많이 쓰는 chrony는 배포판 기본 설정에서 켜진 직후 몇 번만 한 번에 맞추고, 그 뒤에는 서서히 맞춥니다. 가상 머신이 잠깐 멈췄다 깨어날 때도 시계가 뜁니다.',
      fix: '경과 시간은 뛰거나 되돌아가지 않는 단조 시계(monotonic clock)로 계산, 시계는 서서히 조정.' },
    { id: 'so-cron', t: '예약 작업', en: 'Cron jobs (log rotation, backup, scans)',
      s: '매일 같은 시각에 도는 로그 압축·백업·보안 검사가 CPU와 디스크를 차지합니다.',
      c: ['정해진 시각에 OS 작업이 실행', 'CPU·디스크를 게임 서버와 나눠 씀', '매일 새벽 4시처럼 정해진 시각에 렉'],
      sym: ['stutter', 'slowmo'], fx: ['stall'], who: ['server'], when: ['periodic'],
      fix: '작업 시각 분산, 우선순위 낮추기(nice, ionice), 게임 서버와 분리.' },
    { id: 'so-conntrack', t: '서버 conntrack 테이블 포화', en: 'conntrack table full',
      s: '리눅스 방화벽이 모든 연결을 기록하는 연결 추적(conntrack) 테이블이 한도에 닿으면 새 패킷을 버립니다.',
      c: ['접속 폭주, 짧은 연결 반복으로 연결 기록 증가', '테이블이 가득 차 새 연결과 일부 패킷 폐기', '접속 불가, 원인 모를 손실로 순간이동'],
      sym: ['noconnect', 'teleport'], fx: ['loss'], who: ['server'], when: ['login', 'event'],
      num: '기본 한도는 서버 메모리에 따라 약 6만~26만 개입니다. 넘치면 커널 로그에 “nf_conntrack: table full, dropping packet”이 찍힙니다.',
      fix: '테이블 크기 늘리기, 게임 포트는 추적 제외, 짧은 연결 줄이기.' },
    { id: 'so-ports', t: '서버 간 연결의 임시 포트 고갈', en: 'Ephemeral port exhaustion (TIME_WAIT)',
      s: '게임 서버가 DB나 다른 서버에 연결을 짧게 자주 맺고 끊으면, 끊긴 연결이 한동안 포트를 점유해 새 연결을 못 엽니다.',
      c: ['요청마다 새 연결을 열고 닫음', '먼저 닫은 쪽이 약 60초(리눅스) 동안 포트를 점유해(TIME_WAIT) 쓸 포트가 바닥', '내부 요청 실패로 저장 실패·기능 오류'],
      sym: ['dropped', 'noconnect'], fx: ['loss'], who: ['server', 'feature'], when: ['event'],
      num: '리눅스 기본 포트 범위(32768~60999)는 약 2만 8천 개. 같은 상대 주소로 1초에 470번 넘게 새로 연결하면 바닥납니다. 윈도우는 기본 포트가 약 1만 6천 개(49152~65535)이고 TIME_WAIT도 더 길어 더 빨리 바닥납니다.',
      fix: '연결 재사용(커넥션 풀), 포트 범위 확장, 나가는 연결의 TIME_WAIT 재사용(리눅스 tcp_tw_reuse) 검토.',
      more: '리눅스의 TIME_WAIT 60초는 커널에 고정된 값입니다. 이름이 비슷한 tcp_fin_timeout을 줄여도 TIME_WAIT는 짧아지지 않습니다.' },
  ]);

  /* ---------------- 8. 소켓과 프로토콜 ---------------- */
  add('socket', [
    { id: 'sk-hol', t: 'TCP HOL 블로킹', en: 'Head-of-line blocking',
      s: 'TCP는 순서를 지키려고, 잃어버린 패킷 하나를 다시 받을 때까지 뒤에 도착한 패킷을 게임에 넘기지 않습니다.',
      c: ['패킷 하나가 사라짐', '뒤 패킷들은 도착했지만 수신 버퍼에서 대기', '멈췄다가 한꺼번에 풀리며 몰아치기'],
      sym: ['freeze', 'burst'], fx: ['loss', 'stall'], who: ['me'], when: ['random'],
      num: '패킷 하나를 잃으면 최소 왕복 시간 + α, 재전송까지 잃으면 수백 ms~수 초 멈춥니다.',
      fix: '실시간 위치는 UDP, 꼭 필요한 것만 신뢰성 전송, 스트림 여러 개로 나누기.',
      sim: 'hol' },
    { id: 'sk-rto', t: 'TCP RTO와 지수 백오프', en: 'RTO and exponential backoff',
      s: '재전송이 또 실패할 때마다 기다리는 시간이 두 배로 늘어, 짧은 회선 끊김이 긴 멈춤이 됩니다.',
      c: ['회선이 잠깐 끊겨 재전송도 연달아 실패', '다음 시도까지 0.3 → 0.6 → 1.2 → 2.4초처럼 두 배씩 늘어남(핑 100ms 기준)', '회선은 1초 끊겼는데 게임은 2초 넘게 멈춤. 더 길게 끊기면 결국 접속 끊김'],
      sym: ['freeze', 'disconnect'], fx: ['loss', 'stall'], who: ['me'], when: ['random', 'moving'],
      num: '리눅스 RTO(재전송 대기 시간)는 “핑 + 200ms”가 최소이고, 연결을 맺을 때는 1초부터 시작합니다. 기본 설정(tcp_retries2=15)이면 재전송이 계속 실패해도 약 15분 뒤에야 연결을 포기합니다.',
      fix: '게임 수준 하트비트로 빨리 감지 후 재접속, TCP_USER_TIMEOUT으로 포기 시점 줄이기, 신뢰성 UDP.',
      sim: 'hol' },
    { id: 'sk-nagle', t: 'Nagle 알고리즘 + 지연 ACK', en: 'Nagle + delayed ACK (TCP_NODELAY off)',
      s: '작은 패킷을 모아 보내는 Nagle 알고리즘과 ACK를 늦게 보내는 지연 ACK가 맞물려, 메시지를 나눠 쓸 때마다 40~200ms씩 지연됩니다.',
      c: ['TCP_NODELAY를 켜지 않은 채 작은 메시지를 나눠 씀', '보내는 쪽은 ACK를 기다리고, 받는 쪽은 ACK를 늦게 보냄', '회선 핑은 낮은데 모든 행동이 일정하게 굼뜸'],
      sym: ['delay'], fx: ['lat'], who: ['server', 'me'], when: ['always', 'action'],
      num: '지연 ACK는 리눅스가 보통 40ms(상황에 따라 최대 200ms), 윈도우가 200ms입니다. 지연 ACK는 받는 쪽 OS가 정하므로, 서버가 Nagle을 켠 채 윈도우 PC에 메시지를 나눠 보내면 200ms씩 지연될 수 있습니다.',
      fix: 'TCP_NODELAY 켜기(서버와 클라이언트 모두), 한 틱 동안의 메시지를 모아 한 번에 쓰기. 받는 쪽 지연 ACK를 끄는 방법(리눅스 TCP_QUICKACK은 잠깐만 유지, 윈도우는 PC마다 레지스트리 수정)은 게임이 확실히 통제할 수 없습니다.',
      sim: 'nagle' },
    { id: 'sk-block-send', t: '느린 클라이언트로 인한 블로킹 전송', en: 'Blocking send on a full socket',
      s: '회선이 느린 한 명의 송신 버퍼가 가득 찼는데 블로킹 방식(버퍼에 여유가 생길 때까지 호출이 반환되지 않는 전송)으로 보내면, 서버 스레드가 그 한 명을 기다립니다.',
      c: ['느린 클라이언트의 송신 버퍼가 가득', '블로킹 전송이라 서버 스레드가 버퍼에 여유가 생길 때까지 대기', '그 스레드가 맡은 모두가 멈추거나 느려짐'],
      sym: ['freeze', 'slowmo'], fx: ['stall'], who: ['zone', 'server'], when: ['random', 'event'],
      fix: '논블로킹 전송, 클라이언트별 송신 대기열 상한, 오래된 업데이트 버리기.',
      sim: 'sndbuf' },
    { id: 'sk-slow-client', t: '느린 클라이언트(slow consumer) 처리 정책', en: 'Slow-consumer policy',
      s: '보낼 게 계속 쌓이는 클라이언트에게 서버가 오래된 업데이트를 버리거나 연결을 끊습니다.',
      c: ['클라이언트의 회선이 서버가 보내는 양을 못 따라감', '서버가 오래된 업데이트를 버리거나 한도 초과 시 연결 해제', '그 사람만 순간이동 또는 접속 끊김'],
      sym: ['teleport', 'disconnect'], fx: ['loss'], who: ['me'], when: ['event'],
      num: '송신 버퍼가 256KB면 30KB/s 회선에서는 8초 넘게 밀린 데이터가 쌓입니다. 리눅스는 이 버퍼를 자동으로 수 MB까지 키우기도 합니다.',
      fix: '보내는 양 줄이기(거리별 갱신 빈도), 품질 낮춰 계속 보내기, 커널에 쌓아 두는 양 줄이기(리눅스 TCP_NOTSENT_LOWAT).',
      sim: 'sndbuf' },
    { id: 'sk-keepalive', t: 'keepalive 기본값 2시간', en: 'TCP keepalive defaults',
      s: '상대가 종료 신호 없이 사라지면 TCP는 한참 뒤에야 감지합니다. keepalive(유휴 연결이 살아 있는지 확인하는 TCP 기능)는 기본으로 꺼져 있고, 켜도 2시간 동안 유휴 상태여야 확인을 시작합니다.',
      c: ['클라이언트가 전원 꺼짐·회선 끊김으로 종료 신호 없이 사라짐', '서버는 연결이 살아 있다고 간주(keepalive 기본 7,200초. 보내던 데이터가 있으면 재전송 포기까지 약 15분)', '유령 캐릭터가 남고, 재접속하면 “이미 접속 중” 오류'],
      sym: ['noconnect', 'invisible'], fx: ['loss'], who: ['me'], when: ['idle', 'login'],
      num: '리눅스 기본값은 7,200초 유휴 상태면 확인을 시작해 75초 간격으로 프로브를 9번 보내고, 끝까지 응답이 없으면 연결을 끊습니다. 합치면 약 2시간 11분입니다. 윈도우도 기본으로 2시간 유휴 상태여야 확인을 시작합니다.',
      fix: '게임 수준 하트비트(수 초~수십 초 간격), TCP_KEEPIDLE·TCP_USER_TIMEOUT 조정, 재접속 시 기존 세션 교체.',
      sim: 'timeouts' },
    { id: 'sk-fragment', t: 'UDP 패킷의 IP 단편화', en: 'IP fragmentation of large UDP',
      s: 'MTU(한 번에 보낼 수 있는 크기)를 넘는 UDP 패킷은 IP 계층에서 단편화되고, 프래그먼트 하나만 잃어도 전체가 버려집니다.',
      c: ['사람 많은 곳의 스냅샷이 1,500바이트를 넘음', '여러 프래그먼트로 나뉘어 전송, 하나라도 잃으면 전체 폐기', '큰 패킷일수록 손실률이 몇 배. 붐비는 곳에서만 순간이동'],
      sym: ['teleport'], fx: ['loss'], who: ['zone', 'region'], when: ['event'],
      num: '손실 2%인 회선에서 프래그먼트 4개로 나뉜 패킷은 약 8%가 사라집니다. 단편화된 패킷을 아예 버리는 방화벽·통신사도 있어, 그 사용자는 큰 패킷을 하나도 받지 못합니다.',
      fix: '패킷을 1,200바이트 이하로 직접 나누기, 변경분만 보내기.' },
    { id: 'sk-reliable-udp', t: '신뢰성 UDP 재전송 설정', en: 'Reliable-UDP tuning (KCP, ENet…)',
      s: 'UDP 위에 직접 만든 재전송 규칙이 너무 보수적이면 복구가 늦고, 너무 공격적이면 회선을 더 막습니다.',
      c: ['재전송 간격·횟수·윈도우 크기 설정이 회선과 맞지 않음', '늦은 복구, 또는 중복 전송으로 혼잡 악화', '스킬 씹힘, 몰아치기, 혼잡 시 더 심한 렉'],
      sym: ['dropped', 'burst'], fx: ['loss', 'lat'], who: ['me'], when: ['random'],
      fix: '측정한 왕복 시간 기반 재전송, 중요도별 채널 분리.' },
    { id: 'sk-slowstart', t: '유휴 후 슬로 스타트', en: 'Slow start after idle',
      s: 'TCP는 한동안 유휴 상태면 혼잡 윈도우(한 번에 보낼 수 있는 양)를 다시 줄여, 갑자기 큰 데이터를 보낼 때 여러 번에 나눠 보냅니다.',
      c: ['유휴 상태이던 연결로 마을 입장 등 큰 데이터를 보냄', '혼잡 윈도우가 줄어 있어 여러 왕복에 나눠 전송', '입장 직후 주변 캐릭터와 NPC가 왕복 몇 번만큼 늦게 나타남(먼 서버일수록 눈에 띔)'],
      sym: ['delay', 'invisible'], fx: ['lat'], who: ['me'], when: ['moving', 'idle'],
      num: 'RTO보다 오래 유휴 상태면 혼잡 윈도우가 줄기 시작해, 오래 유휴 상태였다면 약 14KB(패킷 10개)까지 내려갑니다. 그러면 100KB는 한 번에 못 보내고 왕복 3번에 나눠 보냅니다.',
      fix: 'tcp_slow_start_after_idle 끄기(리눅스), 입장 데이터 줄이기.' },
    { id: 'sk-congestion', t: '혼잡 제어로 전송량 급감', en: 'Congestion control backoff',
      s: 'TCP는 손실을 혼잡 신호로 보고 전송 속도를 30~50% 줄입니다. 와이파이 손실에도 똑같이 반응합니다.',
      c: ['보낼 양이 많을 때 와이파이나 회선에서 약간의 손실 발생', 'TCP가 전송 속도를 크게 줄이고 천천히 회복(리눅스·윈도우 기본인 CUBIC은 30% 줄임)', '사람 많은 곳에서 업데이트가 밀려 몰아치기·입력 지연'],
      sym: ['burst', 'delay'], fx: ['lat', 'stall'], who: ['me'], when: ['event'],
      fix: 'BBR 같은 혼잡 제어, 보내는 양 줄이기.' },
    { id: 'sk-linger', t: 'RST 강제 종료로 마지막 데이터 유실', en: 'SO_LINGER, abrupt RST',
      s: '서버가 연결을 급히 끊으면 마지막으로 보낸 안내나 저장 완료 신호가 사라집니다.',
      c: ['서버가 연결을 강제 종료(RST)로 닫음. SO_LINGER를 0초로 두거나, 받은 데이터를 다 읽지 않고 닫으면 생김', '아직 전송 중이던 킥 사유·마지막 데이터가 버려짐', '이유 없는 “알 수 없는 오류로 연결 종료”'],
      sym: ['disconnect'], fx: ['loss'], who: ['me'], when: ['random'],
      fix: '사유를 보낸 뒤 송신 방향만 먼저 닫고(shutdown), 상대가 닫을 때까지 받은 데이터를 끝까지 읽은 다음 닫기, SO_LINGER 0초 피하기.' },
    { id: 'sk-blocking-io', t: '블로킹 I/O 구조', en: 'Blocking I/O model',
      s: '소켓 하나를 기다리는 동안 스레드가 다른 일을 못 하는 구조는 사람이 늘수록 전체가 느려집니다.',
      c: ['연결마다 읽기·쓰기를 기다리는 방식', '한 연결의 지연이 같은 스레드의 다른 연결로 번짐', '동접이 늘수록 전체 반응이 느려짐'],
      sym: ['slowmo', 'delay'], fx: ['stall'], who: ['server'], when: ['event', 'peak'],
      fix: 'epoll·IOCP·io_uring 기반 비동기 I/O.' },
    { id: 'sk-reuseport', t: 'SO_REUSEPORT 분배 쏠림', en: 'SO_REUSEPORT imbalance, stuck worker',
      s: '같은 포트를 여러 프로세스가 나눠 받으면, 커널은 접속마다 주소 해시로 담당 프로세스를 정해 두고 바꾸지 않습니다. 담당 프로세스 하나가 멈추면 거기에 배정된 사람만 기다립니다.',
      c: ['게이트웨이·로그인 서버가 SO_REUSEPORT로 프로세스 여러 개를 띄움', '한 프로세스가 GC·과부하로 멈춰도 거기에 배정된 새 접속과 UDP 패킷은 다른 프로세스로 넘어가지 않음', '일부 사람만 접속 불가·멈춤. 프로세스 수가 바뀌는 재시작 때는 일부 UDP 세션이 끊김'],
      sym: ['noconnect', 'freeze', 'disconnect'], fx: ['stall', 'loss'], who: ['me', 'server'], when: ['login', 'random'],
      fix: '받는 스레드는 절대 멈추지 않게, 프로세스별 접속 대기열 감시, 재시작 때 세션을 넘겨받는 절차.' },
    { id: 'sk-udp-connreset', t: '윈도우 UDP 소켓의 WSAECONNRESET 오류', en: 'WSAECONNRESET on a Windows UDP socket',
      s: '윈도우 서버가 이미 떠난 클라이언트에게 UDP를 보내면 “포트 없음”(ICMP) 알림이 돌아옵니다. 그 알림 때문에 다음 수신 호출이 오류로 끝나는데, 서버 코드가 이 오류를 소켓 자체의 고장으로 처리하면 그 소켓을 쓰는 모두가 영향을 받습니다.',
      c: ['막 나간 클라이언트의 주소로 계속 UDP를 보내 “포트 없음”(ICMP) 알림이 돌아옴', '윈도우가 그다음 수신 호출을 WSAECONNRESET(10054) 오류로 끝내고, 서버 코드가 수신을 멈추거나 소켓을 닫음', '그 소켓을 쓰던 모든 사람이 한꺼번에 멈춤·접속 끊김'],
      sym: ['disconnect', 'freeze'], fx: ['loss', 'stall'], who: ['server'], when: ['random', 'login'],
      fix: 'WSAIoctl로 SIO_UDP_CONNRESET을 꺼서 이 알림을 받지 않기, 수신 오류가 나도 로그만 남기고 수신을 계속하기.' },
  ]);
})();
