/* 원인 항목 6: TCP 재전송의 근본 원인
   재전송은 결과다. 여기에는 “왜 패킷이 사라졌나(진짜 손실)”, “왜 잃은 줄 착각했나(불필요한 재전송)”,
   “왜 복구가 유난히 느린가”를 원인별로 모은다. 각 층의 장에 있는 항목과 겹치는 부분은 재전송 관점에서 다시 쓴다. */
(function () {
  const add = (layer, list) => list.forEach(c => DATA.causes.push(Object.assign({ layer }, c)));

  add('retrans', [
    /* ---- 진짜 손실: 경로에서 사라짐 ---- */
    { id: 'rt-wireless', t: '무선 구간 손실', en: 'Wi-Fi / cellular link loss',
      s: '와이파이와 모바일망은 무선 구간에서 몇 번 재전송하다가, 그래도 안 되면 패킷을 버립니다. 버려진 패킷은 TCP가 한참 뒤에 다시 보냅니다.',
      c: ['전파가 약하거나 간섭이 심해 무선 구간 전송이 연달아 실패', '무선 장비의 재시도 한도(보통 수~십여 번)를 넘으면 패킷을 버림', 'TCP 재전송 대기만큼 멈춤, 뒤 패킷은 수신 버퍼에서 대기하다 몰아치기'],
      sym: ['freeze', 'burst', 'teleport'], fx: ['loss', 'jit'], who: ['me', 'home'], when: ['random', 'moving'],
      num: '무선 손실 1%면 게임 패킷 100개에 1개가 사라집니다. 1초에 10개를 받으면 10초에 한 번꼴로 멈칫합니다. RACK-TLP가 없으면 한 번마다 RTO(핑 + 200ms 이상)만큼 멈춥니다.',
      own: ['ext', 'sys', 'srv'],
      act: { game: 'TCP_NODELAY 켜기(Nagle이 켜져 있으면 RACK이 손실 판단에 쓸 뒤따르는 패킷이 없음), 재전송으로 막힌 동안 보낼 상태 업데이트는 쌓아 두지 말고 최신 것만 보내기(커널에 쌓이는 양은 TCP_NOTSENT_LOWAT로 제한).', infra: 'RACK-TLP로 손실 복구를 빠르게 하기(서버는 무선 손실을 막을 수 없고 복구를 빠르게 하는 것까지만 가능), 최신 리눅스 기본값인 net.ipv4.tcp_recovery=1(RACK)·net.ipv4.tcp_early_retrans=3(TLP)이 바뀌지 않았는지 확인.', ext: '유저에게 유선 연결, 5GHz·6GHz 사용, 공유기 위치·채널 바꾸기 안내.' },
      more: '무선 장비의 재시도는 지터를 만들고(재시도마다 수 ms), 재시도 한도를 넘은 경우만 손실이 됩니다. 그래서 무선 품질이 나빠질수록 “지터 → 가끔 멈춤 → 잦은 멈춤” 순서로 증상이 커집니다. 공유기(AP) 사이를 옮겨 가는 순간(로밍)에는 수십 ms~수 초 동안 연달아 잃기도 합니다. 모바일망은 기지국 구간에서 재전송을 많이 하므로, 손실보다 수백 ms 지연 급등으로 나타나는 경우가 많습니다.',
      sim: 'retrans',
      ref: [
        { t: 'net/wireless/core.c', u: 'https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/net/wireless/core.c', p: 'Linux kernel', n: '리눅스 무선 스택의 기본 재시도 한도: 짧은 프레임 7번, 긴 프레임 4번(dot11ShortRetryLimit·dot11LongRetryLimit)' },
        { t: 'RFC 3481: TCP over Second (2.5G) and Third (3G) Generation Wireless Networks', u: 'https://www.rfc-editor.org/rfc/rfc3481', p: 'IETF', n: '모바일망은 링크 계층 재전송 덕분에 IP 손실은 적지만, 그 복구가 지연 흔들림과 지연 급등으로 나타남' },
        { t: 'Wi-Fi roaming support in Apple devices', u: 'https://support.apple.com/guide/deployment/wi-fi-roaming-support-dep98f116c0f/web', p: 'Apple', n: 'AP를 옮길 때 새 AP 인증이 끝날 때까지 데이터를 보낼 수 없고, 802.1X 환경에서는 몇 초 걸릴 수 있음' },
        { t: 'RFC 8985: The RACK-TLP Loss Detection Algorithm for TCP', u: 'https://www.rfc-editor.org/rfc/rfc8985', p: 'IETF', n: 'RACK(시간 기준 손실 판단)과 TLP(끝 패킷 재전송)의 정의' },
        { t: 'IP Sysctl', u: 'https://docs.kernel.org/networking/ip-sysctl.html', p: 'Linux kernel', n: 'tcp_recovery 기본 0x1(RACK), tcp_early_retrans 기본 3(TLP 켜짐), TCP_NOTSENT_LOWAT·tcp_notsent_lowat로 아직 보내지 않은 데이터 양 제한' },
        { t: 'tcp(7) - Linux manual page', u: 'https://man7.org/linux/man-pages/man7/tcp.7.html', p: 'Linux man-pages', n: 'TCP_NODELAY는 Nagle 알고리즘을 꺼 작은 데이터도 바로 보냄' },
        { t: 'include/net/tcp.h', u: 'https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/net/tcp.h', p: 'Linux kernel', n: 'RTO 최소값 TCP_RTO_MIN = 200ms' },
      ] },
    { id: 'rt-queue-drop', t: '병목 대기열 넘침 (혼잡 손실)', en: 'Tail drop at a congested bottleneck',
      s: '공유기, 통신사 연결 구간, 데이터센터 회선처럼 가장 좁은 곳의 대기열이 가득 차면 새로 오는 패킷을 버립니다.',
      c: ['영상·다운로드·다른 사용자 트래픽으로 병목 구간이 꽉 참', '대기열이 찬 동안 새로 도착하는 패킷이 연달아 버려짐(tail drop). 버려지지 않은 패킷도 꽉 찬 대기열 끝에서 기다림', '여러 패킷이 한꺼번에 사라져 긴 멈춤 뒤 몰아치기, 저녁 시간에 잦음'],
      sym: ['freeze', 'burst', 'rubber'], fx: ['loss', 'lat'], who: ['home', 'region', 'server'], when: ['peak', 'event'],
      num: '대기열이 넘치는 순간에는 수십 ms 동안 들어오는 패킷의 상당수가 한꺼번에 사라집니다. 연달아 잃고 다시 보낸 것까지 잃기 쉬워 RTO까지 가는 경우가 많습니다.',
      own: ['net', 'ext', 'cli'],
      act: { game: '손실이 몰리거나 핑이 급등하면 화면에 네트워크 상태 표시(같은 회선의 대용량 전송 가능성 안내).', infra: '데이터센터 회선 여유 확보, 우리 회선·스위치 포트의 대기열 폐기(output drops) 카운터 확인, 통신사 구간이 막히면 다른 회선·피어링으로 우회.', ext: '유저에게 공유기 SQM(fq_codel, CAKE)과 ECN 사용 안내(대기열이 넘치기 전에 속도를 줄이게 함), 통신사에 병목 구간 증설 요청.' },
      sim: 'retrans',
      ref: [
        { t: 'RFC 7567: IETF Recommendations Regarding Active Queue Management', u: 'https://www.rfc-editor.org/rfc/rfc7567', p: 'IETF', n: 'tail drop은 대기열을 오래 가득 찬 채로 두어 지연을 늘리고 몰린 손실을 만든다는 설명과 AQM 권고' },
        { t: 'RFC 8290: The Flow Queue CoDel Packet Scheduler and Active Queue Management Algorithm', u: 'https://www.rfc-editor.org/rfc/rfc8290', p: 'IETF', n: 'fq_codel: 흐름별 대기열과 AQM으로 대기열을 짧게 유지해 버퍼블로트를 줄임' },
        { t: 'RFC 3168: The Addition of Explicit Congestion Notification (ECN) to IP', u: 'https://www.rfc-editor.org/rfc/rfc3168', p: 'IETF', n: 'ECN: 패킷을 버리는 대신 IP 헤더 표시로 혼잡을 알림' },
        { t: 'Smart Queue Management', u: 'https://www.bufferbloat.net/projects/cerowrt/wiki/Smart_Queue_Management/', p: 'Bufferbloat.net', n: 'SQM: 흐름별 스케줄링, 대기열 길이 관리(AQM), 셰이핑을 함께 쓰는 방식' },
        { t: 'Cake', u: 'https://www.bufferbloat.net/projects/codel/wiki/Cake/', p: 'Bufferbloat.net', n: 'CAKE: 셰이퍼와 fq_codel 계열 대기열 관리를 합친 공유기용 SQM' },
      ] },
    { id: 'rt-burst', t: '송신 버스트로 얕은 버퍼 넘침', en: 'Sender bursts overflow shallow buffers',
      s: '서버가 틱마다 수천 명분 업데이트를 한순간에 몰아 보내면, 스위치의 작은 버퍼나 클라우드의 순간 한도가 1ms도 안 돼 넘쳐 일부가 버려집니다.',
      c: ['틱 시작 순간 모든 사람에게 보낼 패킷을 한꺼번에 전송', '여러 서버의 트래픽이 모이는 스위치 포트 버퍼(포트당 수백 KB~수 MB)나 클라우드 인스턴스 한도가 순간적으로 넘침(평균 사용률은 낮음)', '여러 사람이 동시에 순간이동·멈칫, 평균 지표로는 원인이 안 보임'],
      sym: ['teleport', 'freeze', 'burst'], fx: ['loss'], who: ['zone', 'server'], when: ['event'],
      num: '10Gbps 포트로 1ms 동안 보낼 수 있는 양은 약 1.25MB. 여러 서버의 틱이 맞물려 한 포트로 몰리면 버퍼가 순식간에 찹니다.',
      own: ['srv', 'sys', 'net'],
      act: { game: '한 틱의 전송을 틱 안에 나눠 보내기(수천 개 연결이 틱 시작에 몰리는 것은 연결별 페이싱으로 잘 안 풀림), 서버마다 틱 시작 시각을 분산, 큰 데이터를 보내는 연결은 SO_MAX_PACING_RATE로 속도 상한.', infra: '서버 장비·OS: 서버 전체 송신 속도 상한(서버 OS의 셰이퍼, 리눅스 tc), 연결 하나가 몰아 보내는 것은 페이싱(리눅스 fq 큐, BBR)으로 고르게. 네트워크: 버퍼 큰 스위치, 스위치 포트의 출력 폐기 카운터를 짧은 간격으로 확인(평균 사용률로는 안 보임).' },
      more: '페이싱은 연결마다 따로 작동합니다. 수천 개 연결이 틱 시작에 한두 개씩 보내는 몰림은 연결별 페이싱으로 잘 안 풀리고, 게임 서버가 보내는 시점을 직접 나눠야 합니다. 반대로 한 연결이 큰 데이터를 보낼 때는 NIC가 수십 KB 데이터를 패킷 크기로 잘라 연달아 내보내는데(TSO), 이런 몰림은 페이싱이 잘 나눠 줍니다.',
      sim: 'retrans',
      ref: [
        { t: 'High-Resolution Measurement of Data Center Microbursts', u: 'https://research.facebook.com/publications/high-resolution-measurement-of-data-center-microbursts/', p: 'Meta', n: '데이터센터 랙 스위치 버스트의 70% 이상이 수십 µs 안에 끝나고, 분 단위 평균 사용률과 드롭의 관계가 약함(IMC 2017)' },
        { t: 'tc-fq(8) - Linux manual page', u: 'https://man7.org/linux/man-pages/man8/tc-fq.8.html', p: 'Linux man-pages', n: 'fq 큐는 소켓(연결)마다 페이싱하고, SO_MAX_PACING_RATE로 연결별 최대 속도를 정함' },
        { t: 'net/ipv4/tcp_bbr.c', u: 'https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/net/ipv4/tcp_bbr.c', p: 'Linux kernel', n: 'BBR은 추정한 병목 대역폭으로 pacing_rate를 정해 보냄' },
        { t: 'IP Sysctl', u: 'https://docs.kernel.org/networking/ip-sysctl.html', p: 'Linux kernel', n: 'TCP는 흐름 속도에 맞춰 TSO 프레임 크기를 정함(최대 64KB, tcp_min_tso_segs)' },
        { t: 'Monitor network performance for ENA settings on your EC2 instance', u: 'https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/monitoring-network-performance-ena.html', p: 'AWS', n: 'bw_out_allowance_exceeded·pps_allowance_exceeded: 인스턴스의 대역폭·초당 패킷 한도를 넘어 대기열에 넣거나 버린 패킷 수' },
      ] },
    { id: 'rt-policer', t: '폴리서의 초과분 폐기', en: 'Traffic policing',
      s: '통신사 요금제, 클라우드 인스턴스 한도, DDoS 방어 장비는 정해진 속도를 넘는 패킷을 대기열에 넣지 않고 즉시 버리기도 합니다.',
      c: ['순간 전송량이 허용 속도·허용 버스트를 넘음', '넘는 패킷을 대기열 없이 바로 폐기(폴리싱)', '버스트가 큰 순간마다 여러 개가 사라져 멈춤 뒤 몰아치기, 평균 속도는 한도 아래로 보임'],
      sym: ['freeze', 'burst', 'teleport'], fx: ['loss'], who: ['server', 'region', 'me'], when: ['event', 'peak'],
      num: '셰이퍼(대기열에 넣어 늦춤)는 지연을 늘리고, 폴리서(즉시 폐기)는 손실을 늘립니다. TCP 게임 연결은 손실 한 번에 수백 ms 멈출 수 있어, 한도를 잠깐 넘는 정도라면 대개 폴리서 쪽이 영향이 큽니다.',
      own: ['net', 'sys', 'srv'],
      act: { game: '틱마다 몰아 보내는 양을 틱 안에 나눠 보내 순간 전송량을 허용 버스트 아래로 낮추기, 초당 패킷 수 한도에 걸리면 한 틱의 메시지를 한 패킷에 합치기.', infra: '네트워크: 장비의 폴리서 초과 카운터 확인, 폴리서 대신 셰이퍼, 허용 버스트 늘리기. 서버 장비·OS: 클라우드 한도 초과 지표(AWS는 ethtool -S의 bw_out_allowance_exceeded·pps_allowance_exceeded) 확인, 인스턴스 상향, 서버 페이싱(리눅스 fq 큐).' },
      sim: 'retrans',
      ref: [
        { t: 'RFC 2475: An Architecture for Differentiated Services', u: 'https://www.rfc-editor.org/rfc/rfc2475', p: 'IETF', n: '셰이핑은 패킷을 늦춰 트래픽 프로파일에 맞추고, 폴리싱은 프로파일을 넘는 패킷을 버린다는 정의' },
        { t: 'An Internet-Wide Analysis of Traffic Policing', u: 'https://research.google/pubs/an-internet-wide-analysis-of-traffic-policing/', p: 'Google', n: '폴리싱이 걸린 전송은 손실률이 평균 6배 높고, 페이싱·셰이핑으로 같은 목적을 이룰 수 있음(SIGCOMM 2016)' },
        { t: 'Monitor network performance for ENA settings on your EC2 instance', u: 'https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/monitoring-network-performance-ena.html', p: 'AWS', n: 'ethtool -S의 bw_out_allowance_exceeded·pps_allowance_exceeded: 인스턴스 한도를 넘어 대기열에 넣거나 버린 패킷 수' },
        { t: 'tc-fq(8) - Linux manual page', u: 'https://man7.org/linux/man-pages/man8/tc-fq.8.html', p: 'Linux man-pages', n: '리눅스 fq 큐의 연결별 페이싱' },
      ] },
    { id: 'rt-physical', t: '물리 오류 (불량 선·광모듈·커넥터)', en: 'Bit errors: bad cable, optics, dirty fiber',
      s: '케이블 손상, 먼지 낀 광커넥터, 수명이 다한 광모듈은 비트 오류를 만들고, 깨진 패킷은 장비가 조용히 버립니다.',
      c: ['선·광모듈·커넥터 불량으로 비트가 뒤집힘', '체크섬(CRC)이 맞지 않는 패킷을 장비가 폐기', '그 경로를 지나는 사람만 꾸준히 짧게 멈칫했다 몰아치기, 시간대와 상관없음'],
      sym: ['freeze', 'burst', 'teleport'], fx: ['loss'], who: ['zone', 'home'], when: ['always'],
      num: '0.1% 손실도 게임 패킷 1,000개에 한 번입니다. 그 경로를 지나는 사람이 수십 명이면 몇 초마다 누군가 멈칫합니다. 비트 오류는 큰 패킷일수록 잘 걸립니다.',
      own: ['net', 'sys', 'ext'],
      act: { infra: 'CRC 오류는 깨진 방향의 받는 쪽에 쌓이므로 양쪽 끝을 모두 확인. 네트워크: 장비 포트의 CRC·입력 오류 카운터 확인, 광 신호 세기 점검(스위치의 광모듈 정보), 광커넥터 청소, 선·광모듈 교체. 서버 장비·OS: 서버 ethtool -S의 rx_crc_errors(드라이버마다 이름이 조금 다름) 확인, 광 신호 세기 점검(ethtool -m), 서버 쪽 선·NIC 교체.', ext: '유저 집 구간이면 랜선·공유기 교체 안내, 통신사 회선 구간이면 통신사에 회선 점검 요청.' },
      sim: 'retrans',
      ref: [
        { t: 'Interface statistics', u: 'https://docs.kernel.org/networking/statistics.html', p: 'Linux kernel', n: 'rx_crc_errors는 받는 쪽 인터페이스가 CRC 오류로 센 패킷 수, ip -s -s link와 ethtool -S로 확인' },
        { t: 'ethtool(8) - Linux manual page', u: 'https://man7.org/linux/man-pages/man8/ethtool.8.html', p: 'Linux man-pages', n: '-S로 NIC·드라이버별 통계, -m으로 광모듈(SFP+·QSFP) EEPROM과 광 진단 정보 확인' },
      ] },
    { id: 'rt-duplex', t: '듀플렉스 불일치', en: 'Duplex mismatch',
      s: '한쪽은 자동 협상, 다른 쪽은 속도·듀플렉스를 고정해 두면 한쪽이 반이중으로 동작하며 부하가 걸릴 때마다 충돌로 패킷을 잃습니다.',
      c: ['장비 한쪽만 속도·듀플렉스를 고정 설정', '한쪽은 전이중, 다른 쪽은 반이중으로 동작해 충돌·늦은 충돌 발생', '평소엔 멀쩡하다가 트래픽이 늘면 그 장비를 지나는 사람 모두가 멈췄다 몰아치기'],
      sym: ['freeze', 'burst'], fx: ['loss'], who: ['server', 'zone'], when: ['event', 'peak'],
      num: '1Gbps 구리선은 자동 협상이 필수이고, 10Gbps 이상에는 반이중이 아예 없습니다. 그래서 요즘은 주로 100Mbps 이하의 오래된 장비, 관리용 포트, 일부 회선 연결 구간에서 생깁니다.',
      own: ['net', 'sys'],
      act: { infra: '양쪽 모두 자동 협상 또는 양쪽 모두 같은 값으로 고정. 네트워크: 스위치 포트 상태에서 속도·듀플렉스 확인, 포트 카운터에서 반이중 쪽은 늦은 충돌, 전이중 쪽은 CRC 오류·너무 짧은 프레임(runt)이 느는지 확인. 서버 장비·OS: ethtool로 속도·듀플렉스 확인.' },
      sim: 'retrans',
      ref: [
        { t: 'Linux Base Driver for Intel(R) Ethernet Network Connection', u: 'https://docs.kernel.org/networking/device_drivers/ethernet/intel/e1000.html', p: 'Linux kernel', n: '1000BASE-T 규격은 자동 협상을 요구함' },
        { t: 'IEEE 802.3ae 10 Gigabit Ethernet: HSSG Objectives', u: 'https://www.ieee802.org/3/ae/objectives.pdf', p: 'IEEE', n: '10기가비트 이더넷은 전이중만 지원' },
        { t: 'IEEE P802.3ba Objectives', u: 'https://www.ieee802.org/3/ba/PAR/P802.3ba_Objectives_0709.pdf', p: 'IEEE', n: '40·100기가비트 이더넷도 전이중만 지원' },
        { t: 'Interface statistics', u: 'https://docs.kernel.org/networking/statistics.html', p: 'Linux kernel', n: 'tx_window_errors는 늦은 충돌(late collision)로 실패한 전송 수, rx_crc_errors는 CRC 오류로 받은 패킷 수' },
        { t: 'ethtool(8) - Linux manual page', u: 'https://man7.org/linux/man-pages/man8/ethtool.8.html', p: 'Linux man-pages', n: 'ethtool -s의 speed·duplex·autoneg로 속도·듀플렉스·자동 협상 설정' },
      ] },
    { id: 'rt-host-drop', t: '수신 서버 호스트의 패킷 폐기', en: 'Receiver host drops (ring, softirq, CPU)',
      s: '패킷은 서버까지 왔는데 NIC의 링 버퍼(도착한 패킷을 잠시 담아 두는 버퍼)가 넘치거나, 커널의 수신 처리 코어가 포화되어 버려집니다.',
      c: ['접속자 폭증·코어 하나에 몰린 인터럽트·가상 머신 CPU 스틸·가상 스위치 과부하', '링 버퍼(rx_missed_errors 등, 이름은 드라이버마다 다름)나 커널 수신 대기열(softnet dropped)에서 폐기', '사람 몰릴 때 서버 전체에서 동시에 입력이 늦게 먹히고 멈칫'],
      sym: ['delay', 'freeze', 'burst', 'teleport'], fx: ['loss', 'stall'], who: ['server'], when: ['event'],
      num: '서버가 받다가 버린 패킷은 클라이언트가 다시 보냅니다. 그래서 서버의 재전송 지표에는 잘 안 잡히고, ethtool -S의 rx_missed_errors 같은 폐기 카운터(이름은 드라이버마다 다름)와 /proc/net/softnet_stat의 dropped에 먼저 나타납니다.',
      own: ['sys'],
      act: { infra: 'ethtool -S의 rx_missed_errors 같은 폐기 카운터와 /proc/net/softnet_stat의 dropped를 모니터링에 추가, 링 버퍼 크기 늘리기(ethtool -G), RSS·인터럽트를 여러 코어로 분산, 게임 스레드와 수신 처리 코어 분리, CPU 여유 확보, 가상 머신이면 CPU 스틸·가상 스위치 부하 확인.' },
      sim: 'nic',
      ref: [
        { t: 'Interface statistics', u: 'https://docs.kernel.org/networking/statistics.html', p: 'Linux kernel', n: 'rx_missed_errors는 버퍼가 없어 호스트가 받지 못한 패킷 수(/proc/net/dev에서는 drop에 합산), ip -s -s link로 확인' },
        { t: 'drivers/net/ethernet/intel/igb/igb_ethtool.c', u: 'https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/net/ethernet/intel/igb/igb_ethtool.c', p: 'Linux kernel', n: 'ethtool -S 카운터 이름은 드라이버가 정함(예: igb의 rx_missed_errors·rx_no_buffer_count)' },
        { t: 'Ethtool counters', u: 'https://docs.kernel.org/networking/device_drivers/ethernet/mellanox/mlx5/counters.html', p: 'Linux kernel', n: 'mlx5 드라이버의 rx_out_of_buffer(수신 큐에 버퍼가 없음)·rx_discards_phy(포트 버퍼 부족으로 폐기)' },
        { t: 'net/core/net-procfs.c', u: 'https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/net/core/net-procfs.c', p: 'Linux kernel', n: '/proc/net/softnet_stat은 CPU마다 한 줄, 16진수이며 2번째 열이 dropped, 3번째 열이 time_squeeze' },
        { t: 'Documentation for /proc/sys/net/', u: 'https://docs.kernel.org/admin-guide/sysctl/net.html', p: 'Linux kernel', n: 'netdev_max_backlog: 커널이 처리하는 것보다 빨리 들어올 때 쌓아 두는 수신 대기열 한도' },
        { t: 'Scaling in the Linux Networking Stack', u: 'https://docs.kernel.org/networking/scaling.html', p: 'Linux kernel', n: 'RSS: NIC가 여러 수신 큐로 나눠 여러 CPU에서 처리' },
        { t: 'ethtool(8) - Linux manual page', u: 'https://man7.org/linux/man-pages/man8/ethtool.8.html', p: 'Linux man-pages', n: '-G(--set-ring)로 링 버퍼 크기 변경' },
        { t: 'proc_stat(5) - Linux manual page', u: 'https://man7.org/linux/man-pages/man5/proc_stat.5.html', p: 'Linux man-pages', n: '/proc/stat의 steal: 가상화 환경에서 다른 OS가 CPU를 쓴 시간' },
      ] },
    { id: 'rt-stateful-fw', t: '방화벽·연결 추적의 폐기', en: 'Stateful firewall / conntrack drops',
      s: '방화벽이나 리눅스 연결 추적(conntrack, 지나가는 연결을 테이블에 기록하는 기능)은 테이블이 가득 차거나, 연결 상태가 맞지 않는다고 판단하면 패킷을 버립니다.',
      c: ['연결 추적 테이블 가득(table full), 또는 오가는 경로가 달라 한쪽 방향만 방화벽을 지남(비대칭 경로)', '방화벽이 “모르는 연결”이나 “윈도우 범위를 벗어난 시퀀스 번호”의 패킷으로 보고 폐기', '테이블이 차면 새 접속이 막히고, 경로가 어긋나면 그 경로의 사람만 반복 재전송 끝에 접속 끊김'],
      sym: ['freeze', 'disconnect', 'noconnect'], fx: ['loss'], who: ['server', 'region'], when: ['event', 'login', 'random'],
      num: '리눅스 conntrack 기본 한도(nf_conntrack_max)는 메모리에 따라 수만~수십만 개. 현재 개수(nf_conntrack_count)가 한도에 닿으면 로그에 “nf_conntrack: table full, dropping packet”이 남습니다.',
      own: ['net', 'sys', 'srv'],
      act: { game: '테이블이 차는 경우에 대비해 로그인 대기열 시스템으로 몰리는 접속 조절, 짧은 연결을 반복하지 않게 연결 재사용(서버 간 호출 포함), 하트비트가 끊긴 연결은 먼저 정리.', infra: '네트워크: 방화벽의 연결 추적 테이블 크기 늘리기, 게임 포트는 연결 추적에서 빼기, 왕복 경로가 같은 방화벽을 지나게 라우팅 맞추기, 방화벽의 TCP 윈도우 검사 설정 확인. 서버 장비·OS: 리눅스 테이블 크기 늘리기(nf_conntrack_max), 게임 포트는 연결 추적에서 빼기(NOTRACK), TCP 윈도우 검사 설정 확인(nf_conntrack_tcp_be_liberal), AWS는 conntrack_allowance_exceeded도 확인.' },
      sim: 'retrans',
      ref: [
        { t: 'Netfilter Conntrack Sysfs variables', u: 'https://docs.kernel.org/networking/nf_conntrack-sysctl.html', p: 'Linux kernel', n: 'nf_conntrack_max 기본값은 해시 버킷 수(메모리÷16384, 1,024~262,144), 현재 개수는 nf_conntrack_count, nf_conntrack_tcp_be_liberal은 윈도우 밖 RST만 INVALID로 처리' },
        { t: 'net/netfilter/nf_conntrack_core.c', u: 'https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/net/netfilter/nf_conntrack_core.c', p: 'Linux kernel', n: '테이블이 가득 차면 “nf_conntrack: table full, dropping packet” 로그를 남기고 폐기' },
        { t: 'iptables-extensions(8) - Linux manual page', u: 'https://man7.org/linux/man-pages/man8/iptables-extensions.8.html', p: 'Linux man-pages', n: 'raw 테이블의 CT --notrack으로 연결 추적에서 제외' },
        { t: 'Amazon EC2 security group connection tracking', u: 'https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/security-group-connection-tracking.html', p: 'AWS', n: '인스턴스별 추적 연결 수 한도를 넘으면 패킷을 버리고 conntrack_allowance_exceeded로 확인, 비대칭 경로는 피하라는 권고' },
      ] },
    { id: 'rt-appliance-pps', t: '중간 장비 처리 한도 초과 (방화벽·IPS·DDoS 방어)', en: 'Inline appliance PPS / CPU overload',
      s: '방화벽, 침입 방지 장비(IPS), DDoS 방어 장비는 지나가는 패킷을 하나하나 검사합니다. 검사 능력을 넘는 순간부터 처리하지 못한 패킷을 버립니다.',
      c: ['피크 시간·이벤트에 작은 게임 패킷이 초당 수십만 개 넘게 몰림, 또는 검사 규칙이 무거움', '장비의 CPU·초당 패킷 수 한도가 차서 장비에서 폐기. 오탐이면 정상 패킷도 차단', '그 장비 뒤의 서버 전체에서 동시에 멈춤·순간이동, 사람 몰릴 때만 심해짐'],
      sym: ['freeze', 'burst', 'teleport', 'disconnect'], fx: ['loss', 'lat'], who: ['server', 'region'], when: ['peak', 'event'],
      num: '장비 사양의 “10Gbps”는 1,500바이트 큰 패킷 기준으로 적힌 경우가 많습니다. 100바이트 안팎인 게임 패킷은 같은 대역폭에서 패킷 수가 10배 넘게 많아, 회선이 한가해 보여도 초당 패킷 수 한도가 먼저 찹니다.',
      own: ['net', 'srv'],
      act: { game: '게임 트래픽 패턴(포트, 패킷 크기, 초당 패킷 수)을 인프라팀에 공유, 한 틱에 보낼 작은 메시지는 모아서 한 번에 보내 패킷 수 줄이기.', infra: '장비의 CPU·초당 패킷 수·드롭 카운터를 게임 지표와 함께 보기, 작은 패킷 기준으로 장비 용량 잡기, 게임 포트는 무거운 검사에서 빼기, DDoS 방어 규칙을 게임 트래픽 패턴에 맞추기.' },
      ref: [
        { t: 'RFC 2544: Benchmarking Methodology for Network Interconnect Devices', u: 'https://www.rfc-editor.org/rfc/rfc2544', p: 'IETF', n: '장비 성능은 최소·최대 크기를 포함한 여러 프레임 크기로 시험해야 함(패킷 크기에 따라 처리 성능이 달라짐)' },
      ] },
    { id: 'rt-mtu', t: 'MTU 블랙홀 (큰 패킷만 반복 손실)', en: 'PMTU black hole',
      s: '중간 구간이 받을 수 있는 크기가 작아졌는데 “너무 크다”는 알림(ICMP)이 막히면, 큰 패킷은 몇 번을 다시 보내도 계속 사라집니다.',
      c: ['VPN·터널 구간에서 최대 크기가 줄고, 크기 초과 알림은 방화벽에 막힘', '보내는 쪽은 이유를 모른 채 같은 큰 패킷을 계속 재전송, RTO는 두 배씩 증가', '평소엔 멀쩡하다가 인벤토리·사람 많은 곳·입장 로딩처럼 큰 데이터가 오가는 순간 뒤따르는 작은 패킷까지 전부 멈춤, 결국 접속 끊김이나 무한 로딩'],
      sym: ['freeze', 'disconnect', 'noconnect'], fx: ['loss'], who: ['region', 'me'], when: ['action', 'login'],
      num: '보통 1,500바이트, 터널을 지나면 1,400 안팎. 같은 패킷이 5~6번 재전송되면 멈춤이 10초를 넘습니다.',
      own: ['net', 'sys', 'srv'],
      act: { game: '서버 쪽에서 직접 낮추려면 소켓의 최대 세그먼트 크기(TCP_MAXSEG) 설정, 게임 코드에서 메시지를 잘게 쪼개는 것만으로는 안 막힘(TCP가 보낼 데이터를 MSS 크기로 다시 묶음).', infra: '네트워크: 경계 장비에서 MSS 조정(clamping), 방화벽·클라우드 네트워크 ACL에서 크기 초과 ICMP(유형 3 코드 4, fragmentation needed) 허용. 서버 장비·OS: 경로 MTU 설정, 서버 방화벽·클라우드 보안 그룹에서도 크기 초과 ICMP가 막히지 않는지 확인, 마지막 안전망으로 리눅스 tcp_mtu_probing=1.' },
      more: 'tcp_mtu_probing=1은 재전송 타임아웃이 몇 초(tcp_retries1=3에 해당) 이어진 뒤에야 블랙홀로 판단하고 MSS를 1,024바이트로 낮춥니다. 그 사이는 멈춤이므로 마지막 안전망으로 두고, 미리 막는 MSS 조정이 먼저입니다.',
      sim: 'retrans' },
    { id: 'rt-mapping', t: '연결 도중 NAT·로드밸런서 매핑 만료', en: 'NAT / load balancer mapping expired mid-connection',
      s: '유휴 연결의 매핑(이 연결을 어디로 전달할지 기록한 항목)을 중간 장비가 지우면, 다음에 보내는 패킷은 전달되지 못합니다. 재전송만 반복하다 접속이 끊기거나, 장비가 연결 거부(RST)를 돌려보내 곧바로 끊깁니다.',
      c: ['한동안 오가는 패킷이 없는 연결(자리 비움, 로비)', '공유기 NAT·통신사 CGNAT·방화벽·로드밸런서·클라우드 보안 그룹이 유휴 매핑을 삭제', '다시 움직이는 순간 재전송이 이어지다 접속 끊김, 또는 바로 접속 끊김'],
      sym: ['disconnect', 'freeze'], fx: ['loss'], who: ['me', 'region'], when: ['idle'],
      num: 'TCP 매핑을 유지하는 시간은 장비마다 수 분에서 몇 시간까지 제각각입니다. 클라우드 보안 그룹이 연결을 추적하는 설정이면 AWS Nitro v6 인스턴스 유형은 기본 350초 뒤 추적 항목을 지웁니다(그 밖의 유형은 5일, “클라우드 보안 그룹의 연결 추적 만료” 항목 참고). 리눅스 TCP keepalive는 기본값이 “2시간 유휴 상태면 확인”이라 대부분의 장비보다 늦습니다.',
      own: ['cli', 'srv', 'net', 'sys'],
      act: { game: '클라이언트: 가장 짧은 유휴 타임아웃의 절반 이하 간격으로 하트비트 보내기(유저 공유기·통신사 CGNAT의 매핑은 안에서 나가는 패킷으로만 확실히 갱신되고 타임아웃은 우리가 못 바꾸므로 클라이언트가 보냄), 끊기면 자동 재접속. 서버: 하트비트에 응답하고, 일정 시간 못 받으면 연결을 먼저 정리(TCP keepalive 간격 줄이기(TCP_KEEPIDLE 등 소켓 옵션), TCP_USER_TIMEOUT으로 빨리 감지), 세션 토큰으로 이어 받기.', infra: '네트워크: 경로에 있는 방화벽·로드밸런서의 유휴 타임아웃을 모아 게임팀에 공유, 우리 방화벽·로드밸런서는 필요하면 늘리기. 서버 장비·OS: 클라우드 보안 그룹의 연결 추적 시간을 확인해 게임팀에 공유.' },
      sim: 'timeouts' },
    { id: 'rt-path', t: '경로 변경·ECMP 불량 경로', en: 'Route change / bad ECMP member',
      s: '인터넷 경로가 바뀌는 몇 초 동안, 또는 여러 ECMP 경로 중 불량인 경로에 배정된 연결에서 패킷이 사라집니다.',
      c: ['BGP 경로 재계산, 또는 여러 경로(ECMP·LAG) 중 한 경로의 장비·회선 불량', '경로 전환 중 일시 손실, 또는 그 경로를 타는 연결만 꾸준한 손실', '갑자기 몇 초 멈춘 뒤 몰아치기, 또는 “재접속하면 나아짐”(다른 경로로 배정)'],
      sym: ['freeze', 'burst', 'teleport'], fx: ['loss'], who: ['region'], when: ['random'],
      own: ['net', 'srv', 'ext'],
      act: { game: '연결별 재전송 통계(TCP_INFO)를 남겨 겪는 사람의 IP·포트와 시각을 뽑을 수 있게 하기, 몇 초 멈춘 연결을 바로 끊지 않기.', infra: '지역·통신사별 재전송률 모니터링, 재접속으로 경로가 바뀌는지 확인, 여러 통신사 회선 확보, 우리 장비의 ECMP·LAG 경로 중 불량 링크 점검, 경로 측정도 게임과 같은 TCP 포트로(mtr --tcp --port. 경로는 주소·포트로 정해지므로 보통 핑은 다른 경로로 가서 멀쩡하게 나오기도 함).', ext: '통신사에 같은 TCP 포트로 잰 경로 측정 결과와 재접속 전후 비교를 붙여 불량 경로 보고.' },
      sim: 'retrans' },

    /* ---- 불필요한 재전송: 잃지 않았는데 다시 보냄 ---- */
    { id: 'rt-spurious-delay', t: '지연 급등으로 인한 불필요한 재전송', en: 'Spurious RTO from delay spikes',
      s: '패킷은 사라지지 않고 잠깐 아주 늦게 도착했을 뿐인데, 그 지연이 RTO보다 길면 보내는 쪽이 손실로 판단해 재전송합니다.',
      c: ['버퍼블로트, 와이파이 절전, 모바일 무선 상태 전환, 가상 머신 일시 정지로 순간 지연이 수백 ms', 'RTO가 먼저 만료되어 재전송, 원본도 곧 도착(받는 쪽은 중복으로 받음)', '멈춤·몰아치기는 지연 급등 자체 때문. 불필요한 재전송은 멈춤을 거의 늘리지 않고 재전송 지표만 올려 손실로 오해받음'],
      sym: ['freeze', 'burst', 'delay'], fx: ['lat', 'jit'], who: ['me', 'server'], when: ['random', 'idle'],
      num: '리눅스는 F-RTO로 불필요한 RTO를 감지하고 전송량 축소를 되돌리기도 합니다. nstat의 TCPSpuriousRTOs(불필요한 RTO로 판정한 횟수)와 TCPDSACKRecv(받는 쪽이 “이미 받은 것”이라고 알려 온 횟수)로 확인합니다.',
      own: ['ext', 'sys', 'cli'],
      act: { game: '안드로이드 10 이상 클라이언트는 게임 중 저지연 와이파이 모드(WIFI_MODE_FULL_LOW_LATENCY 와이파이 잠금, 화면이 켜져 있고 게임이 앞에 있을 때만 적용)를 요청해 절전으로 생기는 지연 급등 줄이기.', infra: '버스트형 인스턴스 피하기, RTO 최소값을 너무 낮추지 않기, F-RTO·타임스탬프 유지(tcp_frto, tcp_timestamps), 재전송 지표는 nstat의 TCPSpuriousRTOs·TCPDSACKRecv와 함께 봐서 손실로 오해하지 않기.', ext: '지연 급등 자체를 줄이도록 유저에게 공유기 SQM 사용, 와이파이 절전 끄기 안내.' },
      sim: 'retrans' },
    { id: 'rt-reorder', t: '순서 뒤바뀜으로 인한 불필요한 빠른 재전송', en: 'Reordering triggers spurious fast retransmit',
      s: '여러 경로나 묶인 링크를 지나며 패킷 순서가 바뀌면, 받는 쪽이 중복 ACK로 “빠진 패킷 있음”을 알리고 보내는 쪽은 멀쩡한 패킷을 다시 보냅니다.',
      c: ['패킷 단위로 경로를 나누는 장비, 패킷 단위로 나눠 싣는 링크 묶음, 경로가 바뀌는 순간이 순서를 뒤섞음', '뒤 패킷이 먼저 도착해 중복 ACK 3개가 쌓임 → 빠른 재전송', '드문드문 오가는 게임 패킷은 거의 영향 없음. 사람 많은 곳의 큰 업데이트와 패치 다운로드가 느려지고 가끔 뚝뚝 끊김'],
      sym: ['stutter', 'delay'], fx: ['jit'], who: ['region', 'server'], when: ['always', 'event'],
      own: ['net', 'sys'],
      act: { infra: '네트워크: 패킷 단위 분산 대신 연결 단위 분산(ECMP·LAG를 주소·포트 해시로). 서버 장비·OS: RACK(시간 기준 손실 판단, 순서 뒤바뀜에 강함. DSACK으로 불필요한 재전송을 감지하면 순서 뒤바뀜 허용 폭을 자동으로 늘림) 사용, 리눅스가 연결마다 자동으로 추정한 순서 뒤바뀜 정도 확인(ss -ti의 reordering 값, 시작값은 tcp_reordering=3).' },
      sim: 'retrans' },
    { id: 'rt-ack-path', t: 'ACK가 늦거나 사라짐 (업로드 포화)', en: 'ACK path congestion on asymmetric links',
      s: '데이터는 잘 도착했는데 “받았다”는 ACK가 꽉 찬 업로드 대기열에서 늦어지거나 사라지면, 보내는 쪽이 손실로 판단해 재전송합니다.',
      c: ['집에서 영상 업로드·클라우드 백업으로 업로드가 꽉 참', 'ACK가 공유기 대기열에서 수백 ms 늦어지거나 넘쳐서 버려짐', '서버가 보내는 게임 패킷은 대체로 제때 옴. 같은 업로드 대기열에 쌓인 내 입력이 늦어 입력 지연·고무줄, 가끔 불필요한 재전송'],
      sym: ['delay', 'rubber'], fx: ['lat', 'loss'], who: ['home'], when: ['random', 'peak'],
      num: 'ACK는 뒤의 ACK가 앞의 것을 대신 확인해 주므로 몇 개 사라지는 것은 대개 괜찮습니다. 문제는 대기열에서 늦어지는 쪽입니다.',
      own: ['ext', 'cli'],
      act: { game: '핑이 급등하면 화면에 네트워크 상태 표시, “업로드 중인 프로그램 확인” 안내 띄우기.', ext: '유저에게 공유기 SQM으로 업로드 대기열 짧게, 작은 패킷(ACK) 우선 처리, 업로드 속도 제한(영상 업로드·클라우드 백업) 안내.' },
      sim: 'retrans' },
    { id: 'rt-rto-setting', t: 'RTO 설정이 환경과 맞지 않음', en: 'RTO min too low or too high',
      s: 'RTO 최소값을 너무 낮추면 조금만 늦어도 불필요한 재전송이 나고, 기본값(200ms)은 게임 입장에서 너무 길어 한 번 잃을 때마다 오래 멈춥니다.',
      c: ['데이터센터용으로 RTO 최소값을 크게 낮춤, 또는 인터넷 구간에 기본값 그대로 사용', '낮으면 순간 지연에도 재전송 폭주, 높으면 손실마다 긴 대기', '기본값이면 손실 한 번에 수백 ms 멈춤 뒤 몰아치기, 너무 낮추면 멈춤은 줄지만 불필요한 재전송이 급증해 회선을 낭비'],
      sym: ['freeze', 'burst', 'delay'], fx: ['lat'], who: ['server'], when: ['always'],
      num: '리눅스 RTO = 왕복 시간 + max(200ms, RTT 편차×4). 실패할 때마다 두 배, 최대 120초. 리눅스 6.15 이상은 TCP_RTO_MAX_MS로 이 상한을 1초까지 낮출 수 있습니다.',
      own: ['sys', 'srv'],
      act: { game: '리눅스 6.15 이상이면 게임 연결에 TCP_RTO_MAX_MS로 RTO 상한 낮추기 검토(포기까지 걸리는 시간도 짧아지므로 TCP_USER_TIMEOUT으로 끊김 판정 시간을 함께 정하기), 소켓 옵션 TCP_THIN_LINEAR_TIMEOUTS로 게임 연결만 연속 RTO가 두 배로 늘지 않게 하기 검토.', infra: '서버 간 내부 연결만 경로별로 rto_min 낮추기, 인터넷 구간은 기본값 유지하되 RACK-TLP·thin stream 설정(tcp_thin_linear_timeouts)으로 보완.' },
      sim: 'retrans' },

    /* ---- 복구가 유난히 느린 이유 ---- */
    { id: 'rt-thin', t: 'thin stream의 느린 복구', en: 'Thin streams fall back to RTO',
      s: '게임처럼 작은 패킷을 드문드문 보내면 “뒤따르는 패킷 3개”가 모이기 전에 RTO가 먼저 옵니다. 대용량 전송보다 같은 손실에 훨씬 오래 멈춥니다.',
      c: ['패킷 간격이 100ms 안팎이라 아직 ACK를 받지 못한(in-flight) 패킷이 몇 개 없음', '중복 ACK 3개가 모이려면 300ms 넘게 걸려 RTO(핑 + 200ms)가 먼저 발동, 연속 손실이면 두 배씩', '손실 한 번에 0.3초 안팎 멈춤, 다시 보낸 것까지 잃으면 1초 가까이 멈춘 뒤 몰아치기'],
      sym: ['freeze', 'burst'], fx: ['loss', 'stall'], who: ['me', 'server'], when: ['random'],
      num: '패킷 간격 100ms, 핑 60ms면 빠른 재전송까지 약 360ms(뒤 패킷 3개가 도착하고 그 확인이 돌아올 때까지), RTO는 약 260ms. RACK을 쓰면 다음 패킷의 확인이 돌아오는 약 160ms에 바로 다시 보냅니다. 패킷 간격이 200ms를 넘으면 RACK도 RTO보다 빠르지 않습니다.',
      own: ['srv', 'sys', 'cli'],
      act: { game: '서버: TCP_NODELAY 켜기(Nagle이 켜져 있으면 RACK이 판단에 쓸 뒤따르는 패킷이 없음), 실시간 패킷은 UDP 위의 자체 재전송으로. 클라이언트: TCP_NODELAY 켜기, 실시간 패킷은 서버와 같은 방식(UDP)으로.', infra: 'RACK-TLP 사용(최신 리눅스 기본), tcp_thin_linear_timeouts로 연속 RTO가 두 배로 늘지 않게.' },
      more: '리눅스에는 예전에 thin stream용 중복 ACK 1개 재전송 옵션(tcp_thin_dupack)도 있었지만 2017년에 없어졌고, 지금은 RACK이 그 역할을 대신합니다. Nagle이 켜져 있으면(TCP_NODELAY 꺼짐) 잃은 패킷의 확인을 기다리는 동안 새 패킷도 보내지 않아, RACK이 판단에 쓸 뒤따르는 패킷이 없어 RTO까지 기다리게 됩니다.',
      sim: 'retrans' },
    { id: 'rt-sack-stripped', t: '중간 장비의 TCP 옵션 제거', en: 'Middlebox strips TCP options',
      s: '일부 방화벽·가속 장비가 TCP 옵션을 지우거나 고치면, 여러 개를 잃었을 때 한 왕복에 하나씩만 복구하거나 윈도우(한 번에 보낼 수 있는 양)가 작아져 느려집니다.',
      c: ['방화벽의 “TCP 정규화”, 오래된 가속 장비가 SACK·타임스탬프·윈도우 스케일 옵션을 제거', '잃은 패킷이 여러 개면 왕복마다 하나씩 복구, 윈도우가 64KB로 제한됨', '손실마다 멈춤이 훨씬 길어지고(SACK이 없으면 RACK-TLP도 못 씀) 풀리면 몰아치기. 패치 같은 대용량 전송도 느림'],
      sym: ['freeze', 'burst'], fx: ['stall', 'lat'], who: ['region', 'server'], when: ['always'],
      own: ['net', 'sys'],
      act: { infra: '네트워크: 해당 장비의 TCP 정규화 설정 끄기, 방화벽의 시퀀스 번호 무작위화도 확인, 양쪽 끝 패킷 캡처로 SYN의 옵션 비교. 서버 장비·OS: ss -ti에서 sack·wscale 표시가 빠진 연결이 특정 경로에 몰리는지 확인(ts는 윈도우 PC가 설정에 따라 쓰지 않으므로 ts만 빠진 것은 정상일 수 있음), 서버의 net.ipv4.tcp_sack이 1인지 확인.' },
      more: '옵션이 남아 있어도 SACK이 망가질 수 있습니다. 방화벽의 시퀀스 번호 무작위화(sequence randomization)가 헤더의 시퀀스 번호만 바꾸고 SACK 안의 번호는 그대로 두면, 보내는 쪽은 앞뒤가 맞지 않는 SACK을 버립니다. 2019년 SACK 보안 문제 때 서버에서 tcp_sack=0으로 꺼 두고 잊은 경우도 결과가 같습니다.',
      sim: 'retrans' },
    { id: 'rt-zero-window', t: '제로 윈도우 (재전송처럼 보이는 멈춤)', en: 'Zero window, often mistaken for retransmission',
      s: '받는 쪽 프로그램이 소켓을 제때 읽지 않아 버퍼가 가득 차면, 보내는 쪽은 전송을 멈추고 제로 윈도우 프로브만 보냅니다. 회선 문제가 아닙니다.',
      c: ['클라이언트 프레임 멈춤, 서버 스레드 막힘으로 소켓을 못 읽음', '수신 윈도우가 0이 되어 보내는 쪽이 전송을 멈추고 프로브만 보냄(간격이 점점 늘어남)', '멈춤 뒤 몰아치기. 패킷 캡처에 “ZeroWindow”가 보이고 손실은 없음'],
      sym: ['freeze', 'burst'], fx: ['stall'], who: ['me', 'server'], when: ['event', 'random'],
      own: ['cli', 'srv', 'sys'],
      act: { game: '패킷 캡처에서 ZeroWindow를 보낸 쪽(소켓을 못 읽는 쪽)부터 확인, 네트워크 수신은 별도 스레드에서 계속 읽기, 수신 버퍼 적정 크기. 클라이언트: 로딩·GC 같은 프레임 멈춤 원인 해결. 서버: 소켓을 읽는 스레드가 막히는 원인 해결.', infra: '서버의 nstat TcpExtTCPToZeroWindowAdv(서버가 수신 윈도우를 0으로 알린 횟수)를 모니터링에 추가(늘면 서버 쪽이므로 서버 개발에 전달), 서버 쪽 패킷 캡처 제공.' },
      sim: 'retrans' },
    { id: 'rt-syn', t: '접속 요청(SYN) 재전송', en: 'SYN retransmission on connect',
      s: '접속 요청이 접속 대기열(backlog) 넘침이나 방화벽 차단으로 사라지면, 클라이언트 OS가 1초 뒤부터 간격을 늘려 가며 다시 보냅니다.',
      c: ['점검 직후 접속 폭주로 서버 접속 대기열이 넘치거나, 방화벽·DDoS 방어가 SYN을 버림', '클라이언트 OS가 1초 뒤부터 정해진 간격으로 SYN 재전송(예전 리눅스는 1초 → 2초 → 4초)', '접속 버튼 뒤 1초, 3초처럼 초 단위로 딱 떨어지게 늦고, 계속 실패하면 접속 불가·무한 로딩'],
      sym: ['noconnect'], fx: ['loss'], who: ['server', 'region'], when: ['login'],
      num: '리눅스(안드로이드 포함) 첫 SYN 재전송은 1초 뒤입니다. 예전 커널은 이후 두 배씩(1, 3, 7, 15초 …), 6.5 이상은 1, 2, 3, 4, 5초에 다섯 번 다시 보낸 뒤 두 배씩(7, 11, 19초 …) 늘립니다(tcp_syn_linear_timeouts=4). 안드로이드 폰은 OS를 업데이트해도 출시 때의 커널을 계속 쓰는 경우가 많아, 같은 안드로이드 버전이라도 기기마다 다를 수 있습니다. 어느 쪽이든 모두 실패하면 약 2분 뒤 포기합니다. 윈도우는 버전과 설정에 따라 1초 또는 3초부터 늘어나고, 다시 보내는 횟수가 2~4번이라 20~30초 만에 포기합니다(그 PC의 값은 netsh int tcp show global의 Max SYN Retransmissions로 확인).',
      own: ['srv', 'sys', 'net', 'cli'],
      act: { game: '서버: listen의 backlog 인자 늘리기(somaxconn과 함께), 게임 서버가 accept를 제때 부르게 하기, 로그인 대기열 시스템. 클라이언트: 접속 재시도 간격 늘리기(무작위로 분산).', infra: '서버 장비·OS: 서버 접속 대기열 넘침은 nstat의 TcpExtListenOverflows·TcpExtListenDrops와 로그의 “Possible SYN flooding” 경고로 확인, somaxconn 늘리기(listen 인자와 함께), SYN 쿠키. 네트워크: 방화벽·DDoS 방어의 SYN 제한 완화.' },
      sim: 'rush' },
  ]);
})();
