/* 원인 항목 3: 서버 게임 프로세스, 메모리, 디스크, 데이터베이스, 서버 구성과 운영 */
(function () {
  const add = (layer, list) => list.forEach(c => DATA.causes.push(Object.assign({ layer }, c)));

  /* ---------------- 9. 서버 게임 프로세스 ---------------- */
  add('server-proc', [
    { id: 'sp-tick-overrun', t: '틱 예산 초과', en: 'Tick overrun',
      s: '한 틱 안에 할 일이 예산을 넘으면 서버의 틱 주기가 늘어지고, 그 지역 전체가 느리게 흐르거나 뚝뚝 끊깁니다.',
      c: ['한 틱(예: 50ms)에 처리할 일이 예산을 넘음', '1초에 20번 계산할 게임 상태를 8번만 계산', '그 지역 전체 슬로우모션(서버 설계에 따라 뚝뚝 끊김), 스킬 반응 늦음'],
      sym: ['slowmo', 'delay', 'stutter'], fx: ['stall'], who: ['zone', 'server'], when: ['event', 'peak'],
      num: '20틱 서버의 예산은 50ms, 30틱은 33ms, 60틱은 16.7ms. 갑자기 몰릴 때를 대비해 평소에는 예산의 절반 정도만 쓰도록 여유를 두는 편이 안전합니다.',
      own: ['srv', 'sys'],
      act: { game: '비싼 계산 줄이기, 틱을 여러 스레드로 나누기, 인원 분산(채널), 틱 처리 시간을 지표로 남기기.', infra: '틱 시간과 코어별 CPU 사용률을 모니터링·경보에 추가, 단일 코어 성능(클럭)이 높은 CPU·인스턴스 검토.' },
      more: '틱이 늦을 때의 모습은 서버 설계에 따라 다릅니다. 틱마다 게임 상태를 정해진 시간(예: 50ms)만큼 진행하는 서버는 게임 시간 자체가 느려져 슬로우모션이 됩니다. 실제로 흐른 시간만큼 한 번에 움직이는 서버는 게임 진행 속도는 지키지만, 패킷이 드물고 한 번에 크게 움직여 뚝뚝 끊김·순간이동으로 보입니다. 어느 쪽이든 입력 반응은 늦어집니다. 게임 스레드 하나가 서버 전체를 맡으면 서버 전체가, 지역마다 스레드를 나눴다면 그 지역이 느려집니다. EVE Online처럼 대규모 전투에서 일부러 게임 시간을 최대 10배까지 늦춰(Time Dilation) 계산을 따라잡게 하는 게임도 있습니다.',
      sim: 'tick',
      ref: [
        { t: 'VALORANT\'s 128-Tick Servers', u: 'https://www.riotgames.com/en/news/valorants-128-tick-servers', p: 'Riot Games', n: '128틱 서버는 한 프레임을 7.8125ms 안에 끝내야 함, 서버 프레임 시간을 하위 시스템별로 재고 예산을 나눠 관리' },
        { t: 'HED-GP Technical Retrospective: What a HED-ache', u: 'https://www.eveonline.com/news/view/what-a-hed-ache', p: 'CCP Games', n: 'EVE Online은 과부하 때 Time Dilation으로 게임 시간을 늦추고 하한은 10%(10배 느림), 평소 노드 CPU는 80% 아래' },
        { t: 'Handling variation in time', u: 'https://docs.unity3d.com/Manual/time-handling-variations.html', p: 'Unity', n: '고정 간격 시뮬레이션이 밀리면 따라잡는 단계를 몰아서 돌리고, 한도를 넘긴 시간은 버려 게임 시간이 실제보다 느리게 흐름' },
      ] },
    { id: 'sp-aoi', t: '시야(AOI) 계산 폭증 (N²)', en: 'Area-of-interest explosion',
      s: '누가 누구를 볼 수 있는지 모두끼리 비교하면, 인원이 10배가 될 때 계산은 100배가 됩니다.',
      c: ['모든 캐릭터끼리 거리를 비교하거나, 격자(그리드)로 나눠도 한 셀 근처에 수백 명이 몰림', '100명이면 약 1만 번, 1,000명이면 약 100만 번 비교', '월드 보스·공성전처럼 몰린 곳에서 틱이 폭증해 슬로우모션·뚝뚝 끊김'],
      sym: ['slowmo', 'stutter'], fx: ['stall'], who: ['zone', 'server'], when: ['event'],
      num: '거리 비교와 보임·안 보임 목록 갱신을 합쳐 한 번에 0.1µs(1천만 분의 1초)로 잡으면, 1,000명이면 한 틱에 100ms. 20틱 예산(50ms)의 두 배입니다.',
      own: ['srv'],
      act: { game: '격자·구역으로 나눠 근처만 비교, 멀리 있는 대상은 드물게 갱신, 한 사람이 보는 인원에 상한.' },
      sim: 'tick',
      ref: [
        { t: 'Comparing Interest Management Algorithms for Massively Multiplayer Games', u: 'https://www.sable.mcgill.ca/~clump/papers/boulanger-06-comparing.pdf', p: 'ACM', n: 'NetGames 2006 논문(저자 공개본). 모든 쌍의 거리를 재는 방식은 인원이 늘면 감당하지 못하고, 정사각형 격자로 나누면 주변 9칸만 확인' },
        { t: 'Replication Graph in Unreal Engine', u: 'https://dev.epicgames.com/documentation/en-us/unreal-engine/replication-graph-in-unreal-engine', p: 'Epic Games', n: '액터마다 모든 접속을 따져 보는 기본 방식은 인원·액터가 많으면 서버 CPU 병목, MMORPG 등은 월드를 격자로 나눠 셀별 목록을 재사용' },
      ] },
    { id: 'sp-broadcast', t: '브로드캐스트 폭증', en: 'Broadcast fan-out (N×N)',
      s: '한 명의 움직임을 그를 보는 모두에게 보내면, 모인 인원의 제곱만큼 보낼 업데이트가 생깁니다.',
      c: ['한 명의 변화를 볼 수 있는 모두에게 전송', '1,000명이 서로를 보면 틱마다 100만 개 업데이트', '전송 대기열과 대역폭이 포화되어 지연·손실(입력 지연·몰아치기·순간이동)'],
      sym: ['delay', 'teleport', 'burst'], fx: ['lat', 'loss'], who: ['zone', 'server'], when: ['event'],
      num: '1,000명 × 1,000명 × 20틱 = 초당 2,000만 개. 개당 40바이트면 서버 전체 약 6.4Gbps, 받는 사람 한 명당 약 6.4Mbps. 보이는 인원을 150명으로 제한하면 전체 약 1Gbps, 한 명당 약 1Mbps.',
      own: ['srv', 'sys'],
      act: { game: '거리·중요도별 갱신 빈도 낮추기(가까운 적은 매 틱, 먼 사람은 1초에 몇 번), 한 사람에게 보내는 양에 상한을 두고 중요한 것부터 채우기, 여러 업데이트를 한 패킷에 묶기, 표시 인원 상한.', infra: '서버별 송신 대역폭·초당 패킷 수를 NIC·인스턴스 네트워크 한도와 비교해 경보, 대규모 이벤트 전 여유 확인.' },
      sim: 'tick',
      ref: [
        { t: 'HED-GP Technical Retrospective: What a HED-ache', u: 'https://www.eveonline.com/news/view/what-a-hed-ache', p: 'CCP Games', n: 'n명이 한 행동을 n명이 봐야 하는 O(n²) 전송이 대규모 함대전의 피할 수 없는 한계 요인' },
        { t: 'Actor Priority in Unreal Engine', u: 'https://dev.epicgames.com/documentation/en-us/unreal-engine/actor-priority-in-unreal-engine', p: 'Epic Games', n: '연결 대역폭이 포화되면 액터마다 우선순위(거리·시선·마지막 전송 뒤 지난 시간)를 매겨 중요한 것부터 대역폭을 나눠 줌' },
        { t: 'Detailed Actor Replication Flow in Unreal Engine', u: 'https://dev.epicgames.com/documentation/en-us/unreal-engine/detailed-actor-replication-flow-in-unreal-engine', p: 'Epic Games', n: 'NetUpdateFrequency로 액터별 갱신 빈도를 정하고, 우선순위 순으로 보내다 연결이 포화되면 나머지는 다음 틱으로 미룸' },
      ] },
    { id: 'sp-hotzone', t: '단일 스레드 지역 과부하(핫스팟)', en: 'Single-threaded hot zone',
      s: '지역마다 스레드 하나가 맡는 구조에서 한곳에 사람이 몰리면 그 코어 하나만 100%가 됩니다.',
      c: ['한 지역(채널)을 스레드 하나가 담당', '사람이 한곳에 몰리면 그 코어만 포화, 나머지 코어는 여유', '그 지역만 렉, 다른 지역은 멀쩡'],
      sym: ['slowmo', 'delay'], fx: ['stall'], who: ['zone'], when: ['event'],
      num: '16코어 서버에서 코어 하나가 100%여도 서버 전체 CPU 사용률은 약 6%로 보입니다. 코어별 사용률을 봐야 찾을 수 있습니다.',
      own: ['srv', 'sys'],
      act: { game: '채널 분산, 지역 내부 병렬화, 인원 상한.', infra: '서버 전체 평균이 아닌 코어별 CPU 사용률을 모니터링·경보에 추가.' },
      more: '다른 지역이 멀쩡한 것은 지역마다 틱을 따로 돌릴 때의 이야기입니다. 여러 지역 스레드가 매 틱 서로를 기다렸다가 함께 다음 틱으로 넘어가는 구조라면, 가장 바쁜 지역 하나가 서버 전체의 틱을 늦춥니다.',
      sim: 'tick',
      ref: [
        { t: 'Time Dilation – How’s That Going?', u: 'https://www.eveonline.com/news/view/time-dilation-hows-that-going', p: 'CCP Games', n: 'EVE Online의 Time Dilation은 노드 단위라 한 노드에 함께 올라간 먼 성계까지 느려짐, 큰 전투는 성계 4개만 올린 강화 노드에서 처리' },
        { t: 'mpstat(1) - Linux manual page', u: 'https://man7.org/linux/man-pages/man1/mpstat.1.html', p: 'sysstat', n: '프로세서별 사용률과 전체 평균을 따로 보여 줌(-P ALL)' },
      ] },
    { id: 'sp-lock', t: '락 경합', en: 'Lock contention',
      s: '여러 스레드가 같은 데이터를 쓰려고 락 하나를 기다리면, 스레드를 늘려도 한 번에 하나씩만 실행됩니다.',
      c: ['경매장·길드 창고처럼 공용 데이터를 여러 스레드가 동시에 사용', '락을 쥔 스레드가 끝날 때까지 나머지는 대기', '특정 기능만 느림, 심하면 전체 틱 지연'],
      sym: ['delay', 'freeze'], fx: ['stall'], who: ['feature', 'server'], when: ['event'],
      num: '락 안의 일이 작업의 20%면 스레드를 아무리 늘려도 처리량은 1개일 때의 최대 5배, 40%면 2.5배에서 멈춥니다.',
      own: ['srv'],
      act: { game: '락을 잘게 나누기, 락 안에서 하는 일 줄이기, 메시지 기반 구조(데이터마다 담당 스레드를 정하고 다른 스레드는 메시지로 요청만 보내기).' },
      more: '여러 스레드가 게임 데이터를 함께 고치는 구조에서 생깁니다. 지역·기능마다 스레드 하나가 맡고 메시지로만 주고받는 구조는 락이 거의 없는 대신, 한 스레드에 일이 몰리는 문제(단일 스레드 지역 과부하)를 조심해야 합니다. 게임 스레드가 느린 저장 작업이 쥔 락을 기다리면 그 틱 전체가 멈춥니다.',
      sim: 'locks',
      ref: [
        { t: 'Amdahl\'s Law in the Multicore Era', u: 'https://research.cs.wisc.edu/multifacet/papers/ieeecomputer08_amdahl_multicore.pdf', p: 'IEEE', n: 'IEEE Computer 2008 논문(저자 공개본). 병렬로 나눌 수 없는 비율이 1−f면 코어를 아무리 늘려도 속도 향상은 1/(1−f)를 넘지 못함(암달의 법칙)' },
        { t: 'Request scheduling', u: 'https://learn.microsoft.com/en-us/dotnet/orleans/grains/request-scheduling', p: 'Microsoft', n: 'Orleans의 그레인(액터)은 요청을 하나씩 끝까지 처리하는 단일 스레드 실행 모델이라 상태를 동시에 고치지 않음, 서로의 응답을 기다리면 교착 가능' },
      ] },
    { id: 'sp-deadlock', t: '데드락', en: 'Deadlock',
      s: '두 스레드가 서로 상대가 쥔 락을 기다리면 영원히 멈춥니다.',
      c: ['스레드 A는 락1을 쥐고 락2를, B는 락2를 쥐고 락1을 기다림', '둘 다 영원히 멈추고 관련 스레드도 줄줄이 멈춤', '서버 전체 정지, 워치독이 재시작하며 전원 접속 끊김'],
      sym: ['freeze', 'disconnect'], fx: ['stall'], who: ['server', 'feature'], when: ['random', 'event'],
      own: ['srv'],
      act: { game: '락 순서 규칙, 타임아웃 있는 락, 워치독과 멈춘 순간의 스레드 덤프 남기기.' },
      sim: 'locks',
      ref: [
        { t: 'Runtime locking correctness validator', u: 'https://docs.kernel.org/locking/lockdep-design.html', p: 'Linux kernel', n: '두 락을 서로 반대 순서로 잡으면 순환 대기로 교착(lock inversion deadlock), 리눅스 커널은 락 순서를 검사해 미리 경고' },
        { t: 'Liveness, Readiness, and Startup Probes', u: 'https://kubernetes.io/docs/concepts/workloads/pods/probes/', p: 'Kubernetes', n: '실행 중이지만 진행하지 못하는 교착 상태를 라이브니스 검사로 잡아 컨테이너를 재시작' },
      ] },
    { id: 'sp-sync-call', t: '게임 스레드의 동기 호출', en: 'Synchronous DB / file I/O on the game loop',
      s: '틱 도중 DB 응답이나 파일 쓰기를 기다리면, 그 시간만큼 서버의 게임 진행 전체가 멈춥니다.',
      c: ['틱 안에서 DB 조회·저장, 로그 쓰기, 외부 API 호출을 기다림', 'DB가 100ms 걸리면 틱도 100ms 멈춤', 'DB·디스크가 느려질 때마다 필드 전체가 멈칫'],
      sym: ['freeze', 'stutter'], fx: ['stall'], who: ['zone', 'server'], when: ['action', 'random'],
      num: '같은 데이터센터 DB 왕복 0.5ms도 한 틱에 100번 부르면 50ms. 20틱 예산을 혼자 다 씁니다.',
      own: ['srv'],
      act: { game: '느린 일(DB 조회·저장, 로그 쓰기, 외부 API 호출)은 모두 비동기로 넘기고 결과는 다음 틱에 반영(타임아웃만 두면 기다리는 동안은 여전히 멈춤).' },
      sim: 'tick',
      ref: [
        { t: 'Designs, Lessons and Advice from Building Large Distributed Systems', u: 'https://www.cs.cornell.edu/projects/ladis2009/talks/dean-keynote-ladis2009.pdf', p: 'Google', n: 'LADIS 2009 기조연설(Jeff Dean). 같은 데이터센터 안 왕복 약 0.5ms(500,000ns)' },
        { t: 'ASP.NET Core Best Practices', u: 'https://learn.microsoft.com/en-us/aspnet/core/fundamentals/best-practices', p: 'Microsoft', n: '데이터 접근·I/O·오래 걸리는 작업은 비동기로 호출, 동기 블로킹 호출은 스레드 풀 고갈과 응답 지연을 부름' },
      ] },
    { id: 'sp-queue', t: '메시지 큐 적체', en: 'Mailbox / job queue backlog',
      s: '요청이 처리 속도보다 빨리 들어와 대기열에 쌓이면, 뒤쪽 요청은 몇 초 뒤에야 처리되거나 버려집니다.',
      c: ['요청이 처리 속도보다 빨리 도착', '대기열이 길어지고 한도를 넘으면 버림', '스킬·거래 반응이 늦거나 씹힘'],
      sym: ['delay', 'dropped'], fx: ['lat', 'loss'], who: ['zone', 'feature'], when: ['event'],
      own: ['srv'],
      act: { game: '대기열 길이 모니터링, 오래된 요청 우선 폐기 정책, 처리 병렬화.' },
      sim: 'queue',
      ref: [
        { t: 'Avoiding insurmountable queue backlogs', u: 'https://d1.awsstatic.com/builderslibrary/pdfs/avoiding-insurmountable-queue-backlogs.pdf', p: 'AWS', n: 'Amazon Builders\' Library. 적체는 대기 중인 메시지의 나이로 감시, 실시간 시스템은 새 데이터부터 처리(LIFO에 가깝게), 오래된 메시지는 버리기도 함' },
        { t: 'Site Reliability Engineering, Chapter 22: Addressing Cascading Failures', u: 'https://sre.google/sre-book/addressing-cascading-failures/', p: 'Google', n: '처리 속도보다 요청이 빠르면 큐가 차서 지연이 늘고, FIFO 대신 LIFO나 CoDel로 이미 쓸모없어진 오래된 요청을 덜어 냄' },
      ] },
    { id: 'sp-timer-burst', t: '타이머 동시 발동 몰림', en: 'Synchronized timers',
      s: '모든 몬스터 리스폰, 모든 버프 만료, 정각 보상이 같은 틱에 몰리면 그 틱만 수십 배 무거워집니다.',
      c: ['리스폰·만료·보상·자동 저장 타이머가 같은 시각에 맞춰짐', '그 한 틱에 평소의 수십 배 작업', '정해진 시각마다 한 번씩 멈칫'],
      sym: ['freeze', 'stutter'], fx: ['stall'], who: ['zone', 'server'], when: ['periodic'],
      own: ['srv'],
      act: { game: '타이머 시각을 무작위로 조금씩 분산, 여러 틱에 나눠 처리.' },
      ref: [
        { t: 'Timeouts, retries, and backoff with jitter', u: 'https://d1.awsstatic.com/builderslibrary/pdfs/timeouts-retries-and-backoff-with-jitter.pdf', p: 'AWS', n: 'Amazon Builders\' Library. 모든 타이머·주기 작업·지연 작업에 지터를 더해 같은 시각에 몰리는 부하를 흩뜨림, 여러 서버의 1분 주기 요청이 매분 첫 몇 초에 몰린 사례' },
      ] },
    { id: 'sp-pathfinding', t: '길찾기 폭주', en: 'Pathfinding storms',
      s: '수백 마리 몬스터가 동시에 플레이어를 쫓으며 경로를 계산하면 CPU를 크게 씁니다.',
      c: ['몰이 사냥, 대규모 스폰으로 몬스터가 동시에 추적', '몬스터마다 길찾기 계산', '그 사냥터만 슬로우모션'],
      sym: ['slowmo'], fx: ['stall'], who: ['zone'], when: ['event'],
      own: ['srv'],
      act: { game: '경로 캐시, 계산 횟수 상한, 여러 틱에 나누기.' },
      sim: 'tick',
      ref: [
        { t: 'AI.NavMesh.pathfindingIterationsPerFrame', u: 'https://docs.unity3d.com/ScriptReference/AI.NavMesh-pathfindingIterationsPerFrame.html', p: 'Unity', n: '길찾기를 프레임마다 정해진 노드 수만큼만 처리해 여러 프레임에 나눔, 경로가 길거나 요청이 한꺼번에 많을 때도 게임이 매끄러움' },
      ] },
    { id: 'sp-serialize', t: '직렬화·압축 비용', en: 'Serialization / compression cost',
      s: '보낼 데이터를 바이트로 바꾸고 압축하는 데도 CPU가 들고, 사람이 많으면 이 비용이 폭증합니다.',
      c: ['업데이트마다 구조체를 바이트로 변환·압축', '인원 제곱에 비례해 비용 증가', '전송이 늦어져 입력 지연'],
      sym: ['delay'], fx: ['stall', 'lat'], who: ['zone'], when: ['event'],
      own: ['srv'],
      act: { game: '한 번 만든 패킷을 여러 명에게 재사용, 가벼운 포맷.' },
      ref: [
        { t: 'Introduction to Iris in Unreal Engine', u: 'https://dev.epicgames.com/documentation/en-us/unreal-engine/introduction-to-iris-in-unreal-engine', p: 'Epic Games', n: '복제할 상태를 양자화한 사본 하나로 들고 있어 비싼 작업을 줄이고, 그 작업을 여러 접속이 나눠 씀' },
        { t: 'VALORANT\'s 128-Tick Servers', u: 'https://www.riotgames.com/en/news/valorants-128-tick-servers', p: 'Riot Games', n: '매 프레임 복제 변수를 클라이언트마다 비교해 바뀐 값을 묶는 방식은 메모리를 여기저기 읽는 느린 작업이라 서버 CPU를 크게 씀' },
      ] },
    { id: 'sp-crash', t: '서버 크래시', en: 'Server process crash',
      s: '처리하지 못한 오류로 서버 프로세스가 죽으면, 그 서버에 있던 모두의 접속이 동시에 끊깁니다.',
      c: ['없는 대상을 가리키는 오류(널 참조), 잘못된 데이터, 메모리 부족 등 치명적 오류', '서버(또는 존) 프로세스 종료', '모두 동시에 접속 끊김, 마지막 저장 이후 진행은 롤백될 수 있음'],
      sym: ['disconnect', 'dropped'], fx: ['stall'], who: ['zone', 'server'], when: ['random', 'action'],
      own: ['srv', 'sys'],
      act: { game: '크래시 덤프 분석으로 원인 수정, 자주 저장.', infra: '프로세스 자동 재시작, 크래시 덤프 수집·보관 환경, 서버 다운 즉시 경보.' },
      ref: [
        { t: 'Collecting User-Mode Dumps', u: 'https://learn.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps', p: 'Microsoft', n: '윈도우 오류 보고(WER)로 사용자 모드 프로그램이 크래시할 때 전체·미니 덤프를 로컬에 모으도록 설정' },
        { t: 'systemd.service(5) - Linux manual page', u: 'https://man7.org/linux/man-pages/man5/systemd.service.5.html', p: 'systemd', n: 'Restart=on-failure는 비정상 종료·신호 종료(코어 덤프 포함)·워치독 시간 초과 때 서비스를 자동 재시작, 오래 도는 서비스에 권장' },
      ] },
    { id: 'sp-threadpool', t: '스레드 풀 고갈', en: 'Thread pool starvation',
      s: '작업을 처리할 워커 스레드가 모두 느린 작업에 묶이면 새 요청은 무작정 기다립니다.',
      c: ['워커 스레드들이 외부 API·DB 응답을 기다리며 묶임', '새 요청이 배정받을 스레드가 없음', '로그인·상점 등 특정 기능 무한 로딩'],
      sym: ['noconnect', 'delay', 'freeze'], fx: ['stall'], who: ['feature', 'server'], when: ['event', 'login'],
      own: ['srv'],
      act: { game: '느린 호출에 타임아웃, 기능별 스레드 풀 분리, 비동기화.' },
      more: '패킷 받기와 게임 로직이 같은 워커 스레드 풀을 나눠 쓰는 구조라면, 느린 작업 몇 개가 워커를 모두 점유하는 순간 서버 전체의 패킷 처리가 멈춥니다.',
      ref: [
        { t: 'Debug ThreadPool Starvation', u: 'https://learn.microsoft.com/en-us/dotnet/core/diagnostics/debug-threadpool-starvation', p: 'Microsoft', n: '풀에 남은 스레드가 없어 새 작업이 대기하면 응답이 느려짐, 스레드를 붙잡는 블로킹 코드가 원인' },
        { t: 'Avoiding insurmountable queue backlogs', u: 'https://d1.awsstatic.com/builderslibrary/pdfs/avoiding-insurmountable-queue-backlogs.pdf', p: 'AWS', n: '동시 처리 수 = 도착률 × 지연(리틀의 법칙). 초당 100건에서 지연이 100ms에서 10초로 늘면 스레드 10개가 1,000개로 늘어 풀이 고갈' },
        { t: 'Bulkhead Pattern', u: 'https://learn.microsoft.com/en-us/azure/architecture/patterns/bulkhead', p: 'Microsoft Azure', n: '호출 대상마다 커넥션·스레드 풀을 따로 두면 한 대상의 장애가 그 풀만 막음' },
      ] },
    { id: 'sp-infinite-loop', t: '무한 루프·로직 폭주', en: 'Infinite loop / runaway logic',
      s: '버그로 한 틱이 끝나지 않으면 서버가 멈추고, 워치독이 강제로 재시작합니다.',
      c: ['잘못된 조건으로 반복이 끝나지 않거나 재귀 폭주', '틱이 끝나지 않아 서버 정지', '멈춤 후 전원 접속 끊김'],
      sym: ['freeze', 'disconnect'], fx: ['stall'], who: ['zone', 'server'], when: ['action', 'random'],
      own: ['srv'],
      act: { game: '반복 상한, 워치독, 문제 입력 재현 테스트.' },
      ref: [
        { t: 'systemd.service(5) - Linux manual page', u: 'https://man7.org/linux/man-pages/man5/systemd.service.5.html', p: 'systemd', n: 'WatchdogSec=: 서비스가 정한 시간 안에 살아 있다는 신호(WATCHDOG=1)를 보내지 않으면 실패로 보고 종료, Restart= 설정에 따라 자동 재시작' },
        { t: 'Liveness, Readiness, and Startup Probes', u: 'https://kubernetes.io/docs/concepts/workloads/pods/probes/', p: 'Kubernetes', n: '실행 중이지만 진행하지 못하는 상태를 라이브니스 검사로 잡아 재시작, 기본은 10초마다 검사해 3번 연속 실패하면 재시작' },
      ] },
    { id: 'sp-hot-entity', t: '한 대상에 몰린 전투 (월드 보스)', en: 'Hot entity / combat event fan-out',
      s: '수백 명이 보스 하나를 동시에 때리면, 보스 한 마리의 계산이 한곳에 몰리고 타격 정보가 보는 모두에게 전송됩니다.',
      c: ['수백 명이 한 보스에게 스킬·버프·디버프를 쉬지 않고 사용', '보스의 체력·어그로 목록·디버프 계산이 한곳에 몰리고, 타격마다 데미지 숫자·이펙트 패킷을 보는 모두에게 전송', '스킬이 늦게 들어가고 데미지 숫자가 몰아서 뜸, 보스 주변만 슬로우모션'],
      sym: ['delay', 'burst', 'slowmo'], fx: ['stall', 'lat'], who: ['zone'], when: ['event'],
      num: '800명이 초당 2번씩 때리면 초당 1,600번의 타격. 이를 보는 800명에게 모두 알리면 초당 128만 개의 메시지입니다.',
      own: ['srv'],
      act: { game: '남의 데미지 숫자·이펙트는 묶거나 생략, 한 대상에 걸리는 디버프 수 상한, 타격 처리를 여러 틱에 나누기.' },
      ref: [
        { t: 'HED-GP Technical Retrospective: What a HED-ache', u: 'https://www.eveonline.com/news/view/what-a-hed-ache', p: 'CCP Games', n: '공격 한 번도 보는 모든 클라이언트에 알려야 해서 n명이 n명에게 알리는 O(n²) 부담이 생기고, 메시지가 많은 드론 공격은 이 부담이 더 빨리 커짐' },
      ] },
    { id: 'sp-spawn-burst', t: '밀집 지역 진입 시 스폰 폭주', en: 'Spawn burst when entering a crowd',
      s: '사람이 가득한 마을로 순간이동하면, 서버는 새로 보이게 된 수백 명의 외형·장비·상태를 한꺼번에 보내야 합니다.',
      c: ['텔레포트·접속·채널 이동으로 붐비는 곳에 갑자기 나타남', '수백 명분의 전체 정보를 한 번에 만들어 보내고, 내 PC도 한 번에 불러옴', '도착 직후 잠깐 멈춤, 캐릭터가 늦게 하나씩 나타나고 입력이 늦음'],
      sym: ['freeze', 'delay', 'burst'], fx: ['stall', 'lat'], who: ['me', 'zone'], when: ['moving', 'login'],
      num: '한 명의 외형·장비·버프 정보가 300바이트면 500명은 약 150KB. 평소 한 틱 전송량(수 KB)의 수십 배가 한순간에 몰립니다.',
      own: ['srv', 'cli'],
      act: { game: '서버: 가까운 순서로 여러 틱에 나눠 보내기, 외형 정보 캐시. 클라이언트: 로딩 화면 동안 미리 받기, 받은 캐릭터를 여러 프레임에 나눠 생성.' },
      ref: [
        { t: 'Detailed Actor Replication Flow in Unreal Engine', u: 'https://dev.epicgames.com/documentation/en-us/unreal-engine/detailed-actor-replication-flow-in-unreal-engine', p: 'Epic Games', n: '액터 채널을 처음 열 때 초기 위치·회전 같은 정보를 함께 보내고, 연결이 포화되면 남은 액터는 다음 틱으로 미룸' },
        { t: 'Actor Priority in Unreal Engine', u: 'https://dev.epicgames.com/documentation/en-us/unreal-engine/actor-priority-in-unreal-engine', p: 'Epic Games', n: '거리와 시선 방향으로 우선순위를 매겨 가깝고 보이는 액터부터 보냄' },
      ] },
    { id: 'sp-entity-buildup', t: '개체 누적 (정리되지 않은 아이템·소환물)', en: 'Entity / timer buildup over uptime',
      s: '사라져야 할 바닥 아이템, 소환수, 끝난 타이머가 정리되지 않고 쌓이면, 서버를 오래 켜 둘수록 매 틱 할 일이 늘어납니다.',
      c: ['바닥 아이템·소환물·만료된 타이머·빈 파티 정보가 제때 지워지지 않음', '틱마다 순회하는 목록이 날마다 길어짐', '점검 직후엔 멀쩡하다가 며칠 지나면 그 서버·지역만 점점 굼뜸'],
      sym: ['slowmo', 'stutter', 'delay'], fx: ['stall'], who: ['server', 'zone'], when: ['uptime'],
      num: '틱마다 모든 개체를 한 번씩 순회하는 서버라면, 개체 수가 두 배가 되면 그 부분의 틱 시간도 두 배가 됩니다.',
      own: ['srv'],
      act: { game: '지역별 개체 수를 지표로 남겨 추세 보기, 개체마다 수명과 개수 상한, 주기적 정리.' },
      more: '메모리 누수와 비슷하게 오래 켤수록 나빠지지만, 메모리는 넉넉한데 틱 시간만 늘어난다는 점이 다릅니다. 개체 수 그래프가 점검 주기마다 톱니 모양이면 이 경우입니다.',
      ref: [
        { t: 'Actor Ticking in Unreal Engine', u: 'https://dev.epicgames.com/documentation/en-us/unreal-engine/actor-ticking-in-unreal-engine', p: 'Epic Games', n: '액터·컴포넌트는 따로 간격을 정하지 않으면 매 프레임 한 번씩 틱을 돌고, 필요 없으면 틱을 끌 수 있음' },
        { t: 'AActor::SetLifeSpan', u: 'https://dev.epicgames.com/documentation/en-us/unreal-engine/API/Runtime/Engine/AActor/SetLifeSpan', p: 'Epic Games', n: '액터에 수명을 정하면 만료될 때 자동으로 파괴' },
      ] },
  ]);

  /* ---------------- 10. 메모리 ---------------- */
  add('memory', [
    { id: 'mem-gc', t: '서버 GC 전체 멈춤', en: 'Stop-the-world GC pause',
      s: 'Java·C# 서버가 가비지를 수집하려고 모든 스레드를 멈추는 동안(stop-the-world) 서버 전체가 멈춥니다.',
      c: ['힙이 차서 GC 시작', '모든 게임 스레드를 멈추고 수집(살아 있는 데이터가 많을수록 오래)', '서버의 모두가 동시에 멈췄다가 몰아치기'],
      sym: ['freeze', 'burst'], fx: ['stall'], who: ['server'], when: ['periodic', 'uptime'],
      num: '새 객체(Young 영역)만 수집하는 Minor GC는 수~수십 ms. 살아 있는 데이터가 수 GB인 힙 전체를 수집하는 Full GC는 1초를 넘기도 합니다. ZGC·Shenandoah는 힙 크기와 거의 상관없이 보통 1ms 안팎입니다.',
      own: ['srv', 'sys'],
      act: { game: '멈춤이 짧은 GC(ZGC, Shenandoah, 목표 시간을 줄인 G1)를 실행 옵션으로 직접 지정, 할당 줄이기, 힙 크기 조정.', infra: '힙을 넉넉히 줄 수 있는 메모리의 인스턴스, 컨테이너에는 CPU 2개 이상·메모리 약 1.8GB 이상 배정(JDK 26 이하는 그보다 작으면 Serial GC를 기본으로 고름), GC 멈춤 시간 모니터링.' },
      more: 'Java의 G1은 한 번 멈춤 목표가 기본 200ms라, 20틱 서버에서는 틱 4개에 해당합니다. 컨테이너에 CPU를 2개 미만이나 메모리를 약 1.8GB 미만으로 주면 JDK 26 이하의 Java는 기본 GC로 G1 대신 단일 스레드로 수집하는 Serial GC를 골라 멈춤이 훨씬 길어집니다. C#(.NET) 서버는 보통 서버 GC와 백그라운드 GC를 켜지만, 젊은 세대(Gen0·1) 수집과 압축을 동반한 Full GC는 여전히 모든 스레드를 멈춥니다. Go는 멈춤이 보통 1ms 미만이지만, 할당이 많으면 메모리를 요청한 쪽이 GC 작업을 분담해야 해서 틱이 느려집니다. 어느 방식이든 할당이 수집보다 빠르면 결국 게임 스레드가 멈춥니다. G1은 Full GC로 넘어가고, ZGC는 메모리를 요청한 스레드를 수집이 끝날 때까지 멈춥니다.',
      sim: 'gc' },
    { id: 'mem-script-gc', t: '스크립트 엔진의 GC 멈춤', en: 'Scripting VM GC (Lua, etc.)',
      s: 'C++ 서버라도 퀘스트·AI·스킬을 Lua 같은 스크립트로 돌리면, 스크립트 엔진의 GC가 도는 동안 그 존이 멈춥니다.',
      c: ['존마다 스크립트 엔진이 퀘스트·AI·이벤트를 실행하며 임시 객체를 대량 생성', '스크립트 엔진의 GC가 한 번에 많이 수집하면 그 존의 틱이 멈춤', '특정 존·특정 이벤트 중에만 주기적으로 멈칫'],
      sym: ['stutter', 'freeze'], fx: ['stall'], who: ['zone'], when: ['event', 'periodic'],
      num: '스크립트 힙이 수백 MB로 커지면 한 번에 수십~수백 ms가 걸리기도 합니다.',
      own: ['srv'],
      act: { game: '점진적·세대별 GC 설정, 틱마다 조금씩 GC 진행, 스크립트의 임시 객체 줄이기.' },
      sim: 'gc' },
    { id: 'mem-alloc', t: '할당 폭주', en: 'Allocation storms',
      s: '이벤트 중 임시 객체를 대량으로 만들면 GC가 평소보다 훨씬 자주 돕니다.',
      c: ['아이템 드롭·전투 로그·이벤트 보상으로 임시 객체 폭증', 'GC가 몇 배 자주 돌고, 미처 버려지지 않은 객체가 Old 영역으로 넘어가 Full GC도 앞당겨짐', '이벤트 때만 주기적으로 멈칫'],
      sym: ['stutter', 'freeze'], fx: ['stall'], who: ['server', 'zone'], when: ['event'],
      own: ['srv'],
      act: { game: '오브젝트 풀, 재사용 버퍼, 할당 프로파일링.' },
      sim: 'gc' },
    { id: 'mem-leak', t: '메모리 누수', en: 'Memory leak',
      s: '해제되지 않는 메모리가 조금씩 쌓여, 며칠 뒤 GC 폭주·스왑·강제 종료로 이어집니다.',
      c: ['접속 종료한 캐릭터 정보·이벤트 핸들러가 해제되지 않음', '며칠에 걸쳐 여유 메모리가 줄어듦', '점검 직후엔 멀쩡, 날이 갈수록 렉, 결국 서버 다운'],
      sym: ['slowmo', 'freeze', 'disconnect'], fx: ['stall'], who: ['server'], when: ['uptime', 'peak'],
      own: ['srv', 'sys'],
      act: { game: '힙 덤프 분석, 장시간 부하 테스트.', infra: '프로세스별 메모리 사용량 추세 모니터링과 경보.' },
      more: '정기 점검으로 매주 재시작하면 누수가 가려져 오래 발견되지 않습니다. 점검이 한 번 미뤄지거나 이벤트로 인원이 늘었을 때 갑자기 드러나는 경우가 많습니다.',
      sim: 'leak' },
    { id: 'mem-gc-thrash', t: 'GC 스래싱 (힙 여유 부족)', en: 'GC thrashing (heap nearly full)',
      s: '살아 있는 데이터가 힙 한도에 가까워지면, GC가 돌아도 회수할 것이 거의 없어 GC가 쉬지 않고 반복됩니다.',
      c: ['이벤트 인원 증가나 누수로 살아 있는 데이터가 힙 한도 가까이 참', 'GC가 조금밖에 회수하지 못해 곧바로 다시 Full GC, CPU 대부분을 GC가 씀', '서버 전체가 몇 분간 슬로우모션·멈춤을 반복하다 메모리 부족으로 종료'],
      sym: ['slowmo', 'freeze', 'disconnect'], fx: ['stall'], who: ['server'], when: ['peak', 'event', 'uptime'],
      num: '실행 시간의 10% 넘게 GC가 쓰면 위험 신호입니다. Java의 일부 GC는 시간의 98%를 GC에 쓰고도 거의 회수하지 못하면 메모리 부족 오류를 냅니다.',
      own: ['srv', 'sys'],
      act: { game: '힙을 피크 때 살아 있는 데이터보다 넉넉하게(보통 2배 이상) 설정, 오래 쥐고 있는 데이터·누수 줄이기.', infra: 'GC 시간 비율 경보, 버티지 말고 빨리 재시작, 힙을 키울 수 있게 메모리가 넉넉한 인스턴스.' },
      sim: 'gc' },
    { id: 'mem-swap', t: '스왑', en: 'Swapping',
      s: '메모리가 모자라 OS가 일부를 디스크로 내보내면, 그 메모리를 쓸 때마다 1,000배 넘게 느린 디스크를 기다립니다.',
      c: ['사용 메모리가 실제 램을 넘음', 'OS가 일부를 디스크로 내보내고 필요할 때 다시 읽음', '틱이 수백 ms로 폭증해 서버의 모든 유저가 슬로우모션·멈춤'],
      sym: ['slowmo', 'freeze'], fx: ['stall'], who: ['server'], when: ['uptime', 'peak'],
      num: 'RAM 읽기 약 100ns, SSD에서 되읽기 약 100µs(1,000배), 네트워크 너머 클라우드 디스크는 약 1ms(1만 배), HDD는 10ms(10만 배).',
      own: ['sys', 'srv'],
      act: { game: '프로세스 메모리 사용량에 상한(힙 크기 등)을 두고 누수 점검.', infra: '게임 서버는 스왑을 쓰지 않도록 설정, 메모리 경보로 대응, 스왑을 끄면 곧바로 강제 종료(OOM)되므로 피크 사용량보다 램을 넉넉히 확보.' },
      more: 'GC를 쓰는 서버는 수집할 때 힙 곳곳을 읽기 때문에, 힙 일부만 스왑돼도 GC 한 번이 수 초~수십 초로 늘어날 수 있습니다. 스왑을 끄면 느려지는 단계 없이 곧바로 강제 종료(OOM)되므로, 여유 메모리를 먼저 확보해야 합니다. 스왑이 없어도 메모리가 바닥에 가까우면 OS가 실행 파일의 코드 페이지까지 메모리에서 내렸다가 다시 읽느라, 강제 종료 전에 한동안 서버 전체가 심하게 느려질 수 있습니다.',
      sim: 'leak' },
    { id: 'mem-cache-miss', t: '캐시 미스', en: 'CPU cache misses',
      s: '데이터가 메모리 여기저기 흩어져 있으면 CPU가 매번 느린 RAM까지 가서 기다립니다.',
      c: ['객체가 포인터로 흩어져 있고 순서 없이 접근', 'CPU 캐시에 없어서 매번 RAM에서 읽음(100배 느림)', '같은 일을 해도 틱 비용이 몇 배, 심하면 슬로우모션'],
      sym: ['slowmo'], fx: ['stall'], who: ['server'], when: ['always', 'event'],
      own: ['srv'],
      act: { game: '자주 함께 쓰는 데이터를 연속으로 배치(데이터 지향 설계).' },
      sim: 'ladder' },
    { id: 'mem-fragment', t: '메모리 단편화', en: 'Heap fragmentation',
      s: '할당과 해제를 반복해 빈 공간이 잘게 쪼개지면, 실제로 쓰는 양보다 훨씬 많은 메모리를 점유하게 됩니다.',
      c: ['크기가 제각각인 메모리를 여러 스레드가 오랫동안 할당·해제', '빈 공간이 잘게 흩어져 OS에 돌려주지 못하고, 사용량이 누수처럼 계속 늘어남', '오래 켤수록 스왑·메모리 부족으로 느려지다 강제 종료'],
      sym: ['slowmo', 'disconnect'], fx: ['stall'], who: ['server'], when: ['uptime'],
      own: ['srv'],
      act: { game: '크기별 메모리 풀, 단편화에 강한 할당기(jemalloc, mimalloc 등).' },
      more: '누수와 모양이 같아서 힙 분석으로는 누수 지점이 안 보입니다. 리눅스 기본 할당기(glibc)는 스레드가 많은 서버에서 특히 심해, 할당기만 바꿔도 사용량이 크게 줄기도 합니다.' },
    { id: 'mem-numa', t: 'NUMA 원격 메모리', en: 'Remote NUMA access',
      s: 'CPU가 두 개인 서버에서 반대편 CPU에 붙은 메모리를 쓰면 접근이 느려집니다.',
      c: ['스레드와 메모리가 서로 다른 CPU 소켓에 배치', '메모리 접근이 1.5~2배 느려짐', '같은 사양인데 프로세스마다 성능 차이'],
      sym: ['slowmo'], fx: ['stall'], who: ['server'], when: ['always'],
      own: ['sys'],
      act: { infra: '프로세스·메모리를 한 소켓에 고정(numactl), 소켓이 둘이면 소켓마다 게임 서버 프로세스를 나눠 배치.' },
      sim: 'ladder' },
  ]);

  /* ---------------- 11. 디스크 ---------------- */
  add('disk', [
    { id: 'dk-sync-log', t: '동기 로그 쓰기', en: 'Synchronous logging',
      s: '게임 스레드가 로그 한 줄마다 디스크 완료를 기다리면, 디스크가 바쁠 때 게임 진행도 같이 멈춥니다.',
      c: ['전투·거래 로그를 게임 스레드에서 바로 파일에 씀', '확실한 저장(fsync)을 요구하거나 OS의 쓰기 버퍼(페이지 캐시)가 한도에 차면, 디스크가 바쁠 때 쓰기 한 번이 수십 ms', '로그 많은 전투에서 멈칫'],
      sym: ['stutter', 'freeze'], fx: ['stall'], who: ['zone', 'server'], when: ['event'],
      own: ['srv', 'sys'],
      act: { game: '비동기 로깅(메모리 버퍼 + 별도 스레드), 로그 양 줄이기, 게임 스레드에서 fsync 하지 않기.', infra: '로그 로테이션·압축은 I/O 우선순위를 낮춰 실행, 로그를 데이터와 다른 디스크에, 디스크 쓰기 지연 모니터링.' },
      more: '보통 OS는 쓰기를 먼저 메모리(페이지 캐시)에 받아 두고 나중에 디스크로 내려보내서, 로그 한 줄은 대개 곧바로 끝납니다. 멈춤은 fsync로 확실한 저장을 요구할 때, 밀린 쓰기가 한도를 넘어 OS가 쓰기 호출을 블로킹할 때, 로그 파일을 로테이션하거나 압축할 때 생깁니다. 그래서 평소엔 멀쩡하다가 디스크가 바쁜 순간에만 튑니다.',
      sim: 'disk' },
    { id: 'dk-fsync', t: 'fsync 폭주', en: 'fsync storms',
      s: '데이터를 “확실히” 디스크에 쓰도록 요청하면 디스크에 따라 한 번에 0.1ms~수십 ms가 걸리고, 몰리면 대기열이 길어집니다.',
      c: ['정기 저장·로그아웃 러시로 확실한 쓰기 요청이 몰림', '디스크 대기열이 길어짐', '저장 시각마다 렉, 로그아웃·채널 이동 지연'],
      sym: ['stutter', 'delay'], fx: ['stall', 'lat'], who: ['server'], when: ['periodic', 'event'],
      num: '한 번에 서버용 SSD(전원 보호 기능) 약 0.1ms, 보통 SSD 1~수 ms, 클라우드 디스크 1~2ms, HDD 10ms 이상. 한 스레드가 하나씩 기다리면 HDD는 1초에 100번도 못 합니다.',
      own: ['srv', 'sys', 'dba'],
      act: { game: '저장 묶어서 한 번에(여러 저장을 fsync 한 번으로), 저장 시각 분산.', infra: '서버 장비·OS: 전원 보호 기능이 있는 서버용 SSD, 디스크 대기열 길이·fsync 지연 모니터링. DB 장비: 저장이 DB로 가면 DB 로그 디스크도 같은 SSD로, 커밋 지연 모니터링.' },
      sim: 'disk' },
    { id: 'dk-burst', t: '클라우드 디스크 버스트 크레딧 소진', en: 'Burst credit depletion',
      s: '일부 클라우드 디스크와 작은 서버 사양은 잠깐 기준보다 빠르게 쓸 수 있는 버스트 크레딧이 있어서, 바쁜 시간이 길어져 크레딧이 바닥나면 속도가 갑자기 떨어집니다.',
      c: ['기준 성능 이상으로 오래 사용', '버스트 크레딧이 바닥나 기준 성능으로 급락', '매일 저녁 몇 시간 지나서부터 렉 시작'],
      sym: ['stutter', 'slowmo', 'delay'], fx: ['stall', 'lat'], who: ['server'], when: ['peak', 'uptime'],
      num: 'AWS gp2 100GB 디스크는 평소 300, 버스트 3,000 IOPS이고, 크레딧이 가득 차 있으면 약 30분 버팁니다. gp3는 크레딧 없이 늘 3,000입니다. Azure의 작은 Premium SSD도 크레딧으로 최대 30분 버스트합니다.',
      own: ['sys', 'dba'],
      act: { infra: '서버 장비·OS: 성능 보장형 디스크(gp3, IOPS 지정형), 크레딧 잔량 경보, 인스턴스의 디스크 대역폭 버스트 한도와 CPU 크레딧도 함께 확인. DB 장비: 관리형 DB를 포함한 DB 디스크도 성능 보장형으로 바꾸고 크레딧 잔량 경보.' },
      more: '디스크가 멀쩡해도 작은 가상 서버는 인스턴스의 디스크 대역폭 자체에 버스트 한도(하루 최소 30분 등)가 있어 같은 모양이 나옵니다. CPU 크레딧을 쓰는 저가형 서버도 크레딧이 바닥나면 똑같이 갑자기 느려집니다.',
      sim: 'disk' },
    { id: 'dk-iops', t: 'IOPS 한도·대기열 포화', en: 'IOPS limit / queue saturation',
      s: '디스크가 1초에 처리할 수 있는 요청 수를 넘으면 대기열이 길어져 지연이 폭증합니다.',
      c: ['읽기·쓰기 요청이 디스크 처리 능력에 근접', '대기열이 길어짐(이용률 90% 이상에서 폭증)', '저장·로딩 지연, 동기 호출이면 멈춤'],
      sym: ['delay', 'freeze'], fx: ['lat', 'stall'], who: ['server'], when: ['event', 'peak'],
      num: 'HDD 약 150, SATA SSD 수만, NVMe 수십만 IOPS. 클라우드 기본 디스크(AWS gp3)는 3,000 IOPS, 초당 125MB이고, IOPS와 별도인 초당 전송량 한도를 큰 파일 복사가 채우면 작은 쓰기까지 밀립니다.',
      own: ['sys', 'srv', 'dba'],
      act: { game: '요청 합치기, 자주 읽는 데이터는 캐시, 게임 스레드에서 디스크를 기다리지 않게 비동기로.', infra: '서버 장비·OS: 더 빠른 디스크, 인스턴스 유형별 디스크 대역폭·IOPS 한도 확인, 디스크 이용률·대기열 경보, 큰 파일 복사는 한가한 시간에. DB 장비: DB 디스크도 IOPS·처리량 이용률 경보, DB 인스턴스 사양의 디스크 한도 확인.' },
      more: '클라우드에서는 디스크 한도와 별도로 서버 사양(인스턴스 유형)마다 디스크 대역폭·IOPS 한도가 있습니다. 비싼 디스크를 붙여도 서버가 작으면 인스턴스 한도에서 막힙니다.',
      sim: 'disk' },
    { id: 'dk-full', t: '디스크 가득 참', en: 'Disk full',
      s: '로그와 덤프가 쌓여 디스크가 가득 차면 쓰기가 실패하고, 대비가 없으면 서버가 죽습니다.',
      c: ['로그·덤프·임시 파일이 쌓여 100%', '쓰기 실패. 오류 처리가 없으면 크래시, 있으면 저장 실패', '접속 끊김, 진행 롤백'],
      sym: ['disconnect', 'dropped'], fx: ['stall'], who: ['server'], when: ['uptime'],
      own: ['sys', 'dba', 'srv'],
      act: { game: '쓰기 실패를 처리해 크래시 대신 저장 재시도와 경보, 불필요한 로그·덤프 줄이기.', infra: '서버 장비·OS: 로그 로테이션, 용량 경보, 로그와 데이터 디스크 분리. DB 장비: DB 트랜잭션 로그(WAL, binlog)가 복제 중단·로그 백업 누락으로 쌓이지 않는지 감시.' },
      more: 'DB의 트랜잭션 로그(WAL, binlog 등)는 복제본이 멈추거나 로그 백업이 빠지면 지워지지 않고 계속 쌓입니다. 이 디스크가 차면 DB의 모든 쓰기가 멈춰 저장·거래가 한꺼번에 실패합니다.' },
    { id: 'dk-backup', t: '백업·압축·검사 작업', en: 'Backup / compression / scans',
      s: '새벽 백업, 로그 압축, 보안 검사가 디스크를 독점하면 게임 서버의 읽기·쓰기가 밀립니다.',
      c: ['예약된 백업·압축 작업 시작', '디스크 대역폭과 IOPS를 대부분 차지', '매일 같은 시각 렉'],
      sym: ['stutter', 'delay'], fx: ['stall', 'lat'], who: ['server'], when: ['periodic'],
      own: ['sys', 'dba'],
      act: { infra: '서버 장비·OS: 백업·압축·검사 작업의 I/O 우선순위 낮추기, 시각 분산. DB 장비: 백업은 복제본에서.' },
      sim: 'disk' },
    { id: 'dk-lazy-load', t: '서버의 지연 로딩', en: 'Lazy loading on the server',
      s: '서버가 던전·맵 데이터를 처음 요청받을 때 디스크에서 읽으면, 그 틱 동안 모두가 멈춥니다.',
      c: ['누군가 처음으로 던전·지역에 입장', '서버가 게임 스레드에서 데이터를 디스크에서 읽음', '그 서버의 모두가 잠깐 멈춤'],
      sym: ['freeze'], fx: ['stall'], who: ['zone', 'server'], when: ['moving'],
      own: ['srv', 'sys'],
      act: { game: '서버 시작 때 미리 로딩, 비동기 로딩.', infra: '스냅숏으로 막 만든 서버는 서비스 투입 전 디스크 예열(전체 블록을 한 번 읽기) 또는 빠른 스냅숏 복원 기능 사용.' },
      more: '클라우드에서 스냅숏(디스크 사본)으로 막 만든 서버는 처음 읽는 블록마다 원격 스토리지에서 받아 와 평소보다 훨씬 느립니다. 오토스케일링으로 새로 뜬 서버에서만 첫 입장이 유독 오래 걸린다면 이것을 의심합니다.' },
    { id: 'dk-coredump', t: '코어 덤프 기록', en: 'Core dump writing',
      s: '서버가 죽을 때 수 GB 메모리를 디스크에 기록하느라 재시작이 몇 분 늦어집니다.',
      c: ['서버 크래시로 메모리 전체를 파일로 기록', '수 GB를 쓰는 동안 재시작 불가', '서버가 죽어 접속이 끊긴 뒤 한참 동안 접속 불가'],
      sym: ['noconnect'], fx: ['stall'], who: ['server'], when: ['random'],
      own: ['sys', 'srv'],
      act: { game: '필요한 메모리만 담는 작은 덤프(미니 덤프) 방식 검토, 크래시 원인 수정.', infra: '덤프 크기 제한(OS 코어 덤프 설정), 빠른 디스크, 재시작과 덤프 분리(덤프 압축·업로드는 재시작 뒤 따로 처리).' } },
    { id: 'dk-hdd', t: 'HDD 탐색 지연', en: 'HDD seek latency',
      s: 'HDD는 헤드가 플래터 위를 움직여야(탐색, seek) 해서 흩어진 데이터를 읽고 쓰는 데 한 번에 10ms 가까이 걸립니다.',
      c: ['오래된 서버나 저가 스토리지에서 HDD 사용', '흩어진 읽기·쓰기마다 약 10ms', '전반적인 저장·로딩 지연'],
      sym: ['delay'], fx: ['lat'], who: ['server'], when: ['always'],
      own: ['sys', 'dba', 'srv'],
      act: { game: '순차 쓰기 위주 설계.', infra: '서버 장비·OS: SSD로 교체(흩어진 읽기·쓰기가 많은 저장 디스크부터). DB 장비: 흩어진 읽기·쓰기가 가장 많은 DB 디스크를 먼저 SSD로 교체.' },
      sim: 'ladder' },
  ]);

  /* ---------------- 12. 데이터베이스 ---------------- */
  add('db', [
    { id: 'db-no-index', t: '인덱스 없는 쿼리', en: 'Missing index / full table scan',
      s: '인덱스 없이 조건에 맞는 행을 찾으려면 테이블 전체를 읽어야 합니다(풀 스캔).',
      c: ['새 기능 배포로 인덱스가 없는 조건 검색 추가', '수백만 행을 모두 스캔해 쿼리 하나에 수백 ms~수 초', '우편함·거래 기록 로딩 지연, 커넥션이 묶여 다른 요청까지 대기'],
      sym: ['delay', 'noconnect'], fx: ['lat', 'stall'], who: ['feature', 'server'], when: ['action'],
      num: '인덱스가 있으면 수 ms, 없으면 데이터 크기에 비례해 수백~수만 배.',
      own: ['srv', 'dba'],
      act: { game: '새 쿼리는 배포 전 실행 계획 검토, 인덱스 추가, 고치는 쿼리(UPDATE·DELETE)도 인덱스를 타는지 확인.', infra: '느린 쿼리 로그 감시, 풀 스캔 쿼리를 찾아 게임팀에 공유, 운영 중 인덱스 추가는 잠금이 짧은 온라인 방식으로 적용.' },
      more: '읽기만 느려지는 것이 아닙니다. 인덱스 없이 고치는 쿼리(UPDATE·DELETE)는 DB에 따라 스캔한 행까지 잠가, 상관없는 플레이어의 저장까지 막을 수 있습니다.',
      sim: 'dbpool' },
    { id: 'db-hot-row', t: '핫 로우 잠금 경합', en: 'Hot row lock contention',
      s: '모두가 같은 행(길드 창고, 경매장 인기 아이템, 서버 전체 카운터)을 고치려 하면 한 명씩만 잠금을 얻습니다.',
      c: ['이벤트·인기 아이템으로 같은 행에 수정이 몰림', '잠금을 얻을 때까지 요청이 대기', '거래 실패, “잠시 후 다시 시도”, 타임아웃'],
      sym: ['dropped', 'delay'], fx: ['stall', 'lat'], who: ['feature'], when: ['event'],
      num: '한 요청이 잠금을 10ms 쥐면 그 행은 1초에 최대 100번만 고칠 수 있습니다. 트랜잭션 안에 다른 서버 왕복이 끼면 그만큼 더 줄어듭니다.',
      own: ['srv', 'dba'],
      act: { game: '행을 나누기(샤딩된 카운터), 트랜잭션 짧게, 메모리에서 모아 한 번에 반영.', infra: '행 잠금 대기 시간·건수를 모니터링해 경합이 몰리는 행을 찾아 공유.' },
      sim: 'dbpool' },
    { id: 'db-deadlock', t: 'DB 데드락', en: 'Database deadlock',
      s: '두 트랜잭션(한 묶음으로 처리되는 DB 작업)이 서로 상대가 잠근 행을 기다리면 DB가 한쪽을 강제로 취소합니다.',
      c: ['거래 A는 아이템→재화, B는 재화→아이템 순서로 잠금', 'DB가 데드락을 감지해 한쪽을 롤백', '거래·제작이 가끔 실패, 아이템이 되돌아감'],
      sym: ['dropped', 'delay'], fx: ['loss', 'stall'], who: ['feature'], when: ['event', 'action'],
      num: '감지까지 MySQL(InnoDB)은 거의 즉시, PostgreSQL은 기본 1초, SQL Server는 최대 5초쯤 걸립니다. 그동안 두 요청 모두 멈춰 있습니다. 동시 요청이 아주 많아 MySQL의 감지를 꺼 둔 서버라면 잠금 대기 한도(기본 50초)까지 기다립니다.',
      own: ['srv', 'dba'],
      act: { game: '잠금 순서 통일, 트랜잭션 짧게, 실패 시 자동 재시도.', infra: '데드락 감지를 켜 두고 데드락 기록을 수집해 공유, 감지를 끈 MySQL 서버는 잠금 대기 한도(기본 50초) 줄이기.' } },
    { id: 'db-pool', t: '커넥션 풀 고갈', en: 'Connection pool exhaustion',
      s: 'DB와 맺어 둔 연결 수가 정해져 있어서, 느린 쿼리가 연결을 점유하면 나머지는 대기합니다.',
      c: ['느린 쿼리나 요청 폭주로 모든 연결이 사용 중', '새 요청은 연결이 날 때까지 대기', '로그인 무한 로딩, 저장 지연, 타임아웃'],
      sym: ['noconnect', 'delay'], fx: ['stall', 'lat'], who: ['server', 'feature'], when: ['login', 'event'],
      num: '필요한 연결 수는 “초당 요청 × 한 건이 연결을 점유하는 시간”으로 어림합니다. 1초에 2,000건, 건당 5ms면 평균 10개가 늘 바쁩니다. 몰릴 때를 생각해 그 두세 배를 둡니다. 쿼리가 150ms로 느려지면 같은 요청에 300개가 필요해집니다.',
      own: ['srv', 'dba'],
      act: { game: '느린 쿼리 제거, 풀 크기와 대기 타임아웃 조정(풀을 무작정 키우지 않기), 기능별 풀 분리.', infra: 'DB의 최대 연결 수와 CPU·IOPS 여유 확인, 증설·오토스케일링 전에 서버 수 × 풀 크기가 최대 연결 수 안인지 확인, 커넥션 대기·락 대기 지표를 모니터링에 추가.' },
      more: '풀을 무작정 키우면 DB CPU와 잠금 경쟁만 늘어 모두가 같이 느려집니다. 또 서버 수 × 풀 크기가 DB의 최대 연결 수를 넘으면, 증설한 서버나 재시작한 서버가 연결조차 못 맺습니다. 오토스케일링이나 점검 직후에 흔합니다.',
      sim: 'dbpool' },
    { id: 'db-replica-lag', t: '복제 지연', en: 'Replication lag',
      s: '쓰기는 주 DB에, 읽기는 복제본에서 하는데 복제본이 늦게 따라오면 방금 쓴 내용이 안 보입니다.',
      c: ['주 DB에 쓰기가 몰려 복제본이 수 초 뒤처짐', '방금 저장한 내용을 복제본에서 읽으면 아직 없음', '방금 산 아이템이 안 보임, 거래소 가격이 옛날 값, 중복 지급 버그'],
      sym: ['dropped'], fx: ['lat'], who: ['feature'], when: ['event', 'peak'],
      own: ['dba', 'srv'],
      act: { game: '방금 쓴 데이터는 주 DB에서 읽기, 지급 여부 확인과 지급은 주 DB에서 한 트랜잭션으로(유니크 키나 조건부 UPDATE로 중복 차단).', infra: '복제 지연 경보, 복제본 사양을 주 DB 이상으로 두고 병렬 복제 적용, 대량 삭제는 잘게 나눠 실행, 복제본에서 오래 도는 집계 쿼리 관리.' },
      more: '쓰기가 많지 않아도 뒤처질 수 있습니다. 주 DB에서 10분 걸린 대량 삭제 하나는 복제본에서도 다시 실행되는 동안 그만큼 뒤처지게 만들고, 복제본에서 오래 도는 집계 쿼리도 따라가기를 늦춥니다.',
      sim: 'arch' },
    { id: 'db-checkpoint', t: '체크포인트·로그 플러시', en: 'Checkpoint / log flush stalls',
      s: 'DB가 메모리의 변경분을 주기적으로 디스크에 몰아서 쓰는 순간 쿼리가 느려집니다.',
      c: ['변경분이 쌓여 주기적으로 디스크에 기록', '그 순간 디스크가 바빠져 쿼리 지연', '주기적으로 저장·로딩이 느려짐'],
      sym: ['delay', 'stutter'], fx: ['lat'], who: ['server', 'feature'], when: ['periodic'],
      own: ['dba'],
      act: { infra: '체크포인트를 잘게 나눠 고르게, 트랜잭션 로그(redo 로그, WAL)를 넉넉하게, 빠른 디스크.' },
      more: '변경 기록을 담는 트랜잭션 로그(MySQL의 redo 로그, PostgreSQL의 WAL)를 너무 작게 잡으면, 로그가 찰 때마다 DB가 급하게 체크포인트를 몰아 하느라 모든 쓰기가 잠깐씩 멈춥니다.' },
    { id: 'db-cold-cache', t: '콜드 캐시 (재시작 직후)', en: 'Cold buffer pool after restart',
      s: 'DB를 재시작하면 메모리 캐시가 비어 있어서, 한동안 모든 조회가 디스크에서 읽힙니다.',
      c: ['점검으로 DB 재시작', '자주 쓰던 데이터가 메모리에 없어 디스크에서 읽음', '점검 직후 한동안 로그인·로딩이 느림'],
      sym: ['noconnect', 'delay'], fx: ['lat'], who: ['server'], when: ['login'],
      own: ['dba', 'srv'],
      act: { game: '점진적 오픈(접속 대기열로 로그인 인원을 단계적으로 늘리기).', infra: '재시작 후 캐시 예열(워밍, 버퍼 풀 저장·복원 설정 확인), 스냅숏으로 되살린 DB는 디스크도 미리 읽기.' },
      more: 'MySQL은 꺼질 때 버퍼 풀의 페이지 목록을 저장했다가 켜질 때 백그라운드에서 다시 읽어 오지만, 다 채우기까지는 시간이 걸립니다. 클라우드에서 DB를 스냅숏(디스크 사본)으로 되살렸다면 디스크 자체도 처음 읽는 블록마다 느려서 더 오래 갑니다.' },
    { id: 'db-login-storm', t: '로그인 폭주와 N+1 쿼리', en: 'Login storm, N+1 queries',
      s: '캐릭터 하나를 불러올 때 수십 번 따로 조회하면, 수만 명 동시 로그인이 쿼리 수백만 개가 됩니다.',
      c: ['캐릭터 로딩 때 아이템·스킬·퀘스트를 따로따로 조회', '점검 직후 동시 로그인으로 쿼리 폭증', '로그인 무한 로딩, 게임 중인 사람의 저장까지 밀림'],
      sym: ['noconnect', 'delay'], fx: ['stall', 'lat'], who: ['server'], when: ['login'],
      own: ['srv', 'dba'],
      act: { game: '한 번에 묶어서 조회, 접속 대기열, 캐시, ORM 지연 로딩이 만드는 조회 수 점검.', infra: '호출 횟수가 많은 쿼리 순위를 뽑아 공유, 점검 직후 로그인 시간대의 쿼리 수·커넥션 수 모니터링.' },
      more: 'ORM(DB 조회를 대신 만들어 주는 라이브러리)의 지연 로딩이 개발자도 모르는 사이 이런 조회를 만듭니다. 개발 서버에서는 캐릭터 몇 개라 티가 안 나고, 라이브의 동시 로그인에서 처음 드러납니다.',
      sim: 'dbpool' },
    { id: 'db-batch', t: '대량 배치 작업', en: 'Batch jobs during service',
      s: '랭킹 집계, 우편 일괄 발송, 오래된 데이터 정리를 운영 중에 돌리면 잠금과 디스크를 차지합니다.',
      c: ['운영 시간에 대량 작업 실행', '넓은 범위 잠금, 디스크·CPU 점유', '특정 시간대 거래·저장 실패, 로딩 지연'],
      sym: ['delay', 'dropped'], fx: ['lat', 'stall'], who: ['feature', 'server'], when: ['periodic'],
      own: ['srv', 'dba'],
      act: { game: '잘게 나눠 조금씩, 집계는 복제본에서.', infra: '집계용 복제본 제공, 배치는 한가한 시간대로 예약, 잠금 에스컬레이션·갭 락 대기 감시.' },
      more: 'SQL Server는 한 문장이 행 잠금을 약 5,000개 넘게 잡으면 테이블 잠금으로 바꿉니다(잠금 에스컬레이션). 그 순간 같은 테이블을 쓰는 모든 요청이 멈춥니다. MySQL도 기본 설정에서 범위 조건으로 고치면 행 사이 빈틈까지 잠가(갭 락) 새 행 추가를 막습니다.' },
    { id: 'db-failover', t: 'DB 장애 전환', en: 'Database failover',
      s: '주 DB가 죽어 예비 DB로 전환되는 동안 쓰기가 안 되고, 복제되지 못한 마지막 데이터는 사라질 수 있습니다.',
      c: ['주 DB 장애로 예비 DB가 승격', '전환 중 수 초~몇 분 쓰기 불가, 비동기 복제라면 미복제 데이터 유실 가능', '잠깐 모든 저장 실패, 아이템·경험치 롤백'],
      sym: ['dropped', 'freeze', 'disconnect', 'noconnect'], fx: ['stall', 'loss'], who: ['server'], when: ['random'],
      num: '관리형 DB의 자동 전환은 보통 수십 초~2분. 비동기 복제라면 복제 지연만큼(1초 미만~수 초) 최근 저장을 잃을 수 있습니다.',
      own: ['dba', 'srv'],
      act: { game: '재시도 가능한 저장, 끊긴 연결을 빨리 버리고 새 주소로 다시 맺는 설정(커넥션 풀·DNS 캐시), 전환 훈련 때 재연결 확인.', infra: '동기·반동기 복제(쓰기 지연과 맞바꿈), 전환 훈련, 전환 시간·복제 지연 모니터링.' } },
    { id: 'db-save-interval', t: '긴 저장 주기로 인한 진행 유실', en: 'Periodic save window',
      s: '부하를 줄이려 몇 분에 한 번만 저장하면, 그 사이 서버가 죽을 때 진행이 사라집니다.',
      c: ['캐릭터 상태를 몇 분마다 한 번 저장', '그 사이 서버 크래시·장애 발생', '다시 접속하니 몇 분 전 상태(롤백)'],
      sym: ['dropped'], fx: ['loss'], who: ['server', 'zone'], when: ['random'],
      own: ['srv', 'dba'],
      act: { game: '중요 이벤트(거래, 희귀 획득)는 즉시 저장, 변경 로그 기록.', infra: '저장 주기를 줄였을 때 늘어나는 쓰기를 감당할 DB의 IOPS·CPU 여유 확인.' } },
    { id: 'db-cache-stampede', t: '캐시 스탬피드', en: 'Cache stampede / thundering herd',
      s: '인기 데이터의 캐시가 동시에 만료되면 수천 개 요청이 한꺼번에 DB로 몰립니다.',
      c: ['Redis 등에 저장된 인기 데이터가 동시에 만료', '같은 데이터를 다시 만들려는 요청이 DB로 한꺼번에 몰림', 'DB 과부하로 여러 기능이 줄줄이 느려지거나 멈춤'],
      sym: ['delay', 'freeze', 'noconnect'], fx: ['stall', 'lat'], who: ['server'], when: ['periodic', 'event'],
      own: ['srv', 'dba'],
      act: { game: '만료 시각을 무작위로 분산, 한 요청만 갱신하고 나머지는 옛 값 사용.', infra: 'Redis 재시작·장애 때 캐시가 통째로 비지 않게 복제본·자동 전환 구성, 캐시가 비어도 버틸 DB 여유 확인.' },
      more: 'Redis가 재시작되거나 장애로 캐시가 통째로 비어도 같은 일이 생깁니다. 캐시를 믿고 DB를 작게 잡아 둔 구조일수록 위험합니다.',
      sim: 'arch' },
    { id: 'db-long-tx', t: '오래 열린 트랜잭션', en: 'Long-running transaction / MVCC purge lag',
      s: '트랜잭션 하나가 오래 열려 있으면 잠금을 계속 쥐고, DB가 옛 버전 데이터를 정리(purge)하지 못해 전체가 점점 느려집니다.',
      c: ['트랜잭션을 연 채 다른 서버 응답을 기다리거나, 운영 중 주 DB에서 긴 집계 쿼리 실행', '쥔 잠금이 풀리지 않고, 정리해야 할 옛 버전 데이터가 계속 쌓임', '그 행을 쓰는 기능 타임아웃, 몇 시간에 걸쳐 저장·조회가 전반적으로 느려짐'],
      sym: ['delay', 'dropped'], fx: ['lat', 'stall'], who: ['feature', 'server'], when: ['uptime', 'random'],
      own: ['srv', 'dba'],
      act: { game: '트랜잭션 안에서 네트워크 호출·사용자 입력 기다리지 않기, 집계 쿼리는 복제본에서.', infra: '오래 열린 트랜잭션 경보와 강제 종료, 집계용 복제본 제공, 언두 로그·죽은 행 증가 감시.' },
      more: 'DB는 읽는 쪽이 고치기 전 모습을 볼 수 있도록 옛 버전을 남겨 둡니다(MVCC). 가장 오래된 트랜잭션이 끝나야 이 기록을 지울 수 있어서, 트랜잭션 하나가 몇 시간 열려 있으면 MySQL은 언두 로그가, PostgreSQL은 VACUUM이 정리하지 못한 죽은 행(dead tuple)이 쌓입니다. SQL Server는 트랜잭션 로그가 줄지 않아 디스크를 채우기도 합니다.' },
    { id: 'db-redis-block', t: 'Redis 느린 명령', en: 'Redis blocking commands (single-threaded)',
      s: 'Redis는 명령을 한 번에 하나씩 처리해서, 느린 명령 하나가 그 뒤의 모든 요청을 막습니다.',
      c: ['운영 중 KEYS로 전체 검색, 원소 수백만 개짜리 랭킹·목록을 통째로 읽거나 지움', '그 명령이 끝날 때까지 다른 모든 요청이 대기(수십 ms~수 초)', '세션·랭킹·캐시를 쓰는 기능이 동시에 멈칫, 로그인 지연'],
      sym: ['freeze', 'delay', 'noconnect'], fx: ['stall', 'lat'], who: ['server', 'feature'], when: ['random', 'periodic'],
      num: '보통 명령은 1ms 미만. 원소 수백만 개를 한 번에 다루면 수백 ms~수 초.',
      own: ['srv', 'dba'],
      act: { game: 'KEYS 대신 SCAN, 큰 키 쪼개기, 지우기는 UNLINK(백그라운드 삭제), 같은 초에 몰리는 만료 시각 분산.', infra: '느린 명령 기록(SLOWLOG) 감시, KEYS 같은 위험 명령은 운영 서버에서 막기, 큰 키 정기 점검, THP 끄고 fork할 메모리 여유 확보, RDB·AOF 저장은 복제본에서.' },
      more: '저장 파일(RDB 스냅샷)을 만들거나 AOF를 다시 쓰려고 프로세스를 복제(fork)하는 순간에도 멈춥니다. 요즘 서버에서 메모리 1GB당 약 10ms라, 30GB면 300ms쯤입니다. 큰 페이지(THP)를 켜 두면 fork 뒤 쓰기마다 큰 페이지를 통째로 복사해(copy-on-write) 멈춤과 메모리 사용이 크게 늘어서, 보통 THP를 끄고 메모리 여유를 넉넉히 둡니다. 같은 초에 만료되는 키가 아주 많을 때도 Redis가 지우느라 잠깐 멈춥니다.',
      sim: 'arch' },
    { id: 'db-plan-flip', t: '실행 계획 변경으로 인한 쿼리 지연', en: 'Query plan regression (stats, parameter sniffing)',
      s: '코드는 그대로인데 DB가 같은 쿼리를 처리하는 방법(실행 계획)을 바꾸면, 어제 2ms였던 쿼리가 오늘 수백 ms가 됩니다.',
      c: ['통계 자동 갱신, DB 재시작, 데이터 분포 변화로 DB가 실행 계획을 새로 세움', '인덱스를 안 타는 계획이 골라져 같은 쿼리가 수십~수백 배 느려지고 커넥션이 묶임', '배포도 없었는데 특정 기능 로딩이 갑자기 느려지고 다른 요청까지 대기'],
      sym: ['delay', 'noconnect'], fx: ['lat', 'stall'], who: ['feature', 'server'], when: ['random'],
      own: ['dba', 'srv'],
      act: { game: '값에 따라 결과 수가 크게 다른 쿼리는 나눠 쓰거나 계획 힌트 검토, 인덱스를 확실히 타는 쿼리 설계.', infra: '느린 쿼리와 실행 계획 기록 감시, 좋은 계획 고정(SQL Server 쿼리 저장소 등), 통계 갱신 시각 관리.' },
      more: 'SQL Server는 처음 들어온 값에 맞춰 세운 계획을 다시 씁니다(파라미터 스니핑). 아이템이 몇 개뿐인 새 캐릭터로 세운 계획이 아이템 수만 개인 오래된 캐릭터에게 쓰이면 크게 느려지고, 반대 경우도 흔합니다. 재시작으로 계획이 지워지면 멀쩡해졌다가 다시 나빠지기도 합니다.',
      sim: 'dbpool' },
    { id: 'db-ddl-lock', t: '운영 중 스키마 변경(DDL) 잠금', en: 'Schema change lock (DDL / metadata lock)',
      s: '서비스 중에 테이블에 컬럼이나 인덱스를 추가하면, 잠깐 필요한 잠금 하나 때문에 그 테이블을 쓰는 모든 요청이 대기할 수 있습니다.',
      c: ['핫픽스로 운영 중인 테이블에 컬럼·인덱스 추가', '스키마 변경이 앞서 열린 긴 트랜잭션을 기다리고, 뒤에 오는 모든 요청은 그 스키마 변경을 기다림', '그 테이블을 쓰는 기능(인벤토리, 우편 등)이 통째로 멈추고 타임아웃'],
      sym: ['delay', 'dropped', 'noconnect'], fx: ['stall'], who: ['feature', 'server'], when: ['random', 'login'],
      own: ['dba', 'srv'],
      act: { game: '스키마 변경이 든 핫픽스는 DB 인프라와 일정 협의, 새 컬럼이 없어도 동작하는 코드를 먼저 배포.', infra: '잠금 대기 한도를 짧게 걸고 실패하면 다시 시도, 긴 트랜잭션이 없을 때 실행, 온라인 변경 도구 사용, 큰 테이블은 점검 시간에.' },
      more: 'MySQL은 스키마를 바꿀 때 메타데이터 잠금을, PostgreSQL은 가장 강한 테이블 잠금을 잠깐 잡습니다. 변경 자체는 순식간이어도, 앞에 끝나지 않은 트랜잭션이 하나 있으면 그 뒤로 모든 요청이 대기합니다.' },
  ]);

  /* ---------------- 13. 서버 구성과 운영 ---------------- */
  add('infra', [
    { id: 'in-gateway', t: '게이트웨이·프록시 경유', en: 'Gateway / proxy hop',
      s: '클라이언트와 게임 서버 사이에 중간 서버를 두면, 한 번 거칠 때마다 처리 시간이 붙고 그 서버가 단일 장애 지점이 됩니다.',
      c: ['클라이언트 ↔ 게이트웨이 ↔ 게임 서버 구조', '중간 서버의 처리·대기 추가, 과부하 시 모두에게 영향', '전체 핑 상승, 게이트웨이 장애 시 그곳을 거치는 사용자 전원 접속 끊김'],
      sym: ['delay', 'disconnect'], fx: ['lat', 'stall'], who: ['server'], when: ['event', 'always'],
      num: '같은 데이터센터 안이라 평소에는 한 번 거칠 때 1ms 미만. 게이트웨이가 과부하면 수십~수백 ms로 늘어납니다.',
      own: ['srv', 'sys', 'cli'],
      act: { game: '서버: 게이트웨이를 여러 대로 늘릴 수 있는 구조, 게이트웨이가 죽어도 다른 게이트웨이로 다시 붙으면 캐릭터가 그대로 이어지는 구조(세션 재연결). 클라이언트: 게이트웨이가 끊기면 자동 재접속.', infra: '게이트웨이 수평 확장(대수 추가), 게이트웨이별 CPU·연결 수·처리 지연 모니터링.' },
      sim: 'arch',
      ref: [
        { t: 'The Unique Architecture behind Amazon Games’ Seamless MMO New World', u: 'https://aws.amazon.com/blogs/gametech/the-unique-architecture-behind-amazon-games-seamless-mmo-new-world/', p: 'AWS', n: 'New World는 클라이언트가 공개 주소를 가진 입구 서버(REP) 4대 중 하나로 접속하고, 그 뒤의 시뮬레이션 서버(허브)와 통신' },
        { t: 'Designs, Lessons and Advice from Building Large Distributed Systems', u: 'https://www.cs.cornell.edu/projects/ladis2009/talks/dean-keynote-ladis2009.pdf', p: 'Google', n: 'LADIS 2009 기조연설(Jeff Dean). 같은 데이터센터 안 왕복 약 0.5ms' },
        { t: 'Site Reliability Engineering, Chapter 22: Addressing Cascading Failures', u: 'https://sre.google/sre-book/addressing-cascading-failures/', p: 'Google', n: '과부하로 큐가 길어지면 대기 시간이 처리 시간의 몇 배로 늘어남(처리 100ms, 큐가 스레드 수의 10배면 1.1초)' },
      ] },
    { id: 'in-zone-transfer', t: '존 이동 (서버 간 이관)', en: 'Zone / server handoff',
      s: '다른 지역·던전에 들어갈 때 캐릭터 정보를 다른 서버로 넘기는 과정에서 지연과 실패가 생깁니다.',
      c: ['던전 입장, 대륙 이동으로 담당 서버가 바뀜', '저장 → 전달 → 불러오기, 대상 서버가 붐비거나 빈 던전 인스턴스가 없으면 대기', '긴 로딩, 입장 실패, 이동 중 접속 끊김'],
      sym: ['noconnect', 'freeze', 'disconnect', 'rubber'], fx: ['lat', 'stall'], who: ['me', 'zone'], when: ['moving'],
      own: ['srv', 'sys'],
      act: { game: '이관 데이터 줄이기, 대상 서버 미리 예약, 실패 시 원래 자리로 복귀.', infra: '던전·존 서버의 빈 인스턴스 여유 모니터링, 피크 전 대수 확보.' },
      more: '로딩 없이 이어진 심리스 월드도 서버 경계를 넘을 때 담당 서버가 바뀝니다. 경계 근처에서 잠깐 멈칫하거나 뒤로 당겨지는 고무줄이 생길 수 있습니다.',
      ref: [
        { t: 'The Unique Architecture behind Amazon Games’ Seamless MMO New World', u: 'https://aws.amazon.com/blogs/gametech/the-unique-architecture-behind-amazon-games-seamless-mmo-new-world/', p: 'AWS', n: '로딩 없는 월드를 격자로 나눠 여러 서버(허브)가 맡고 플레이어가 이동하면 상태를 허브에서 허브로 넘김, 세션형 모드는 공유 풀에서 남는 서버를 받아 씀' },
      ] },
    { id: 'in-cascade', t: '연쇄 장애', en: 'Cascading failure',
      s: '한 서비스가 느려지면 그걸 부르는 서버들이 응답을 기다리며 묶이고, 상관없는 기능까지 멈춥니다.',
      c: ['DB·인증 같은 한 서비스가 느려짐', '호출하는 서버들의 스레드와 연결이 응답을 기다리며 묶이고, 실패한 요청의 재시도가 부하를 더함', '상관없어 보이는 기능까지 전부 느려지거나 멈춤'],
      sym: ['freeze', 'delay', 'noconnect'], fx: ['stall'], who: ['server'], when: ['event', 'random'],
      own: ['srv', 'net'],
      act: { game: '모든 호출에 타임아웃, 서킷 브레이커, 기능별 격리(벌크헤드), 재시도는 간격을 늘리며 횟수 제한, 헬스체크 응답은 바쁜 작업과 분리.', infra: '로드밸런서 헬스체크가 잠깐 느린 서버를 바로 빼지 않도록 실패 횟수·간격에 여유, 한꺼번에 빠지는 서버 수 제한.' },
      more: '헬스체크(살아 있는지 확인하는 검사)도 연쇄를 키웁니다. 바쁜 서버가 검사에 늦게 답하면 로드밸런서가 멀쩡한 서버를 빼 버리고, 그 트래픽이 남은 서버로 몰려 다음 서버도 늦어집니다.',
      sim: 'arch',
      ref: [
        { t: 'Site Reliability Engineering, Chapter 22: Addressing Cascading Failures', u: 'https://sre.google/sre-book/addressing-cascading-failures/', p: 'Google', n: '과부하 서버가 헬스체크에 실패해 빠지면 남은 서버에 부하가 몰리고 재시도가 부하를 키움, 재시도 횟수 제한·무작위 지수 백오프·데드라인 권장' },
        { t: 'Circuit Breaker Pattern', u: 'https://learn.microsoft.com/en-us/azure/architecture/patterns/circuit-breaker', p: 'Microsoft Azure', n: '타임아웃까지 막힌 요청이 스레드·DB 연결을 붙잡아 상관없는 기능까지 실패시킴, 정해진 시간 안에 실패가 쌓이면 호출을 바로 거부' },
        { t: 'Timeouts, retries, and backoff with jitter', u: 'https://d1.awsstatic.com/builderslibrary/pdfs/timeouts-retries-and-backoff-with-jitter.pdf', p: 'AWS', n: 'Amazon Builders\' Library. 5단 호출에서 층마다 3번씩 재시도하면 DB 부하가 243배, 재시도는 한 곳에서만 하고 토큰 버킷으로 제한' },
      ] },
    { id: 'in-subservice', t: '부가 서버 장애', en: 'Auxiliary service outage',
      s: '채팅·파티·경매장처럼 게임 서버와 따로 도는 서버에 장애가 나면 그 기능만 동작하지 않습니다.',
      c: ['기능 전용 서버가 느려지거나 죽음', '해당 기능 요청만 응답 없음', '채팅 안 됨, 파티 초대 무반응, 거래소 무한 로딩(전투는 정상)'],
      sym: ['dropped', 'noconnect'], fx: ['stall', 'loss'], who: ['feature'], when: ['random', 'event'],
      own: ['srv', 'sys'],
      act: { game: '실패해도 게임은 계속되게 설계, 기능별 상태 표시, 여러 기능을 중앙 서버 한 대에 몰지 않기.', infra: '부가 서버별 헬스체크·경보, 이중화와 자동 재시작.' },
      more: '파티·길드·귓속말·서버 간 이동을 한 대의 중앙 서버(월드·매니저 서버)가 모두 중계하는 구조라면, 그 서버 하나가 느려질 때 여러 기능이 한꺼번에 멈춥니다.',
      sim: 'arch',
      ref: [
        { t: 'Bulkhead Pattern', u: 'https://learn.microsoft.com/en-us/azure/architecture/patterns/bulkhead', p: 'Microsoft Azure', n: '구성 요소를 풀로 격리하면 하나가 실패해도 나머지는 계속 동작하고 장애가 번지지 않음' },
        { t: 'REL05-BP01 Implement graceful degradation to transform applicable hard dependencies into soft dependencies', u: 'https://docs.aws.amazon.com/wellarchitected/latest/reliability-pillar/rel_mitigate_interaction_failure_graceful_degradation.html', p: 'AWS', n: 'AWS Well-Architected. 의존 대상이 장애여도 핵심 기능은 약간 오래된 데이터나 대체 데이터로 계속 동작하도록 설계' },
      ] },
    { id: 'in-deploy', t: '배포·재시작', en: 'Deploy / rolling restart',
      s: '업데이트를 위해 서버를 재시작할 때 연결을 옮기지 않으면 그 서버에 있던 사람들의 접속이 끊기고, 종료 직전 저장과 재접속이 한꺼번에 몰립니다.',
      c: ['핫픽스 배포로 서버를 순서대로 재시작', '연결을 다른 서버로 옮기지 않고 종료, 그 서버에 있던 모든 유저의 저장이 DB에 몰림', '공지 없는 접속 끊김, 재접속 폭주'],
      sym: ['disconnect', 'noconnect', 'delay'], fx: ['stall'], who: ['server', 'zone'], when: ['random', 'login'],
      num: '서버 한 대에 5,000명이면 종료 직전 몇 초 안에 저장 5,000건이 DB로 몰립니다.',
      own: ['srv', 'sys'],
      act: { game: '드레인 기능(새 접속만 막고 기존 사람이 빠질 때까지 기다리기), 캐릭터를 다른 서버로 옮기기, 종료 전 저장 나눠 하기, 재시작 뒤 캐시 로딩·JIT 워밍업을 마치고 준비 완료 알리기, 핫 리로드는 별도 스레드에서 미리 읽어 두고 틱 사이에 한 번에 교체.', infra: '배포 도구가 한 대씩 드레인을 기다린 뒤 재시작, 재시작한 서버는 준비 완료(예열 끝)를 확인한 뒤 트래픽 받기, 배포 시각 공지.' },
      more: '다시 켠 직후 몇 분도 느립니다. 캐시가 비어 DB 조회가 몰리고, Java·C# 서버는 실행하면서 코드를 최적화하는 과정(JIT 워밍업)이 끝나기 전이라 같은 일에 시간이 더 듭니다. 서버를 끄지 않고 스크립트·데이터 테이블을 다시 읽는 방식(핫 리로드)도 읽는 동안 틱이 멈춰 잠깐 멈춤이 생깁니다.',
      ref: [
        { t: 'Site Reliability Engineering, Chapter 20: Load Balancing in the Datacenter', u: 'https://sre.google/sre-book/load-balancing-datacenter/', p: 'Google', n: 'SIGTERM을 받은 서버는 lame duck 상태로 새 요청을 다른 서버로 돌리고 진행 중인 요청만 마침, 재시작 직후 몇 분은 JIT 최적화 전이라 자원이 더 들어 예열 뒤 트래픽을 받게 함' },
        { t: 'Liveness, Readiness, and Startup Probes', u: 'https://kubernetes.io/docs/concepts/workloads/pods/probes/', p: 'Kubernetes', n: '레디니스 검사로 연결 수립·파일 로딩·캐시 예열이 끝날 때까지 트래픽을 보내지 않음' },
        { t: 'Edit target group attributes for your Network Load Balancer', u: 'https://docs.aws.amazon.com/elasticloadbalancing/latest/network/edit-target-group-attributes.html', p: 'AWS', n: '대상을 등록 해제하면 새 연결은 보내지 않고 기존 연결은 드레인(기본 300초)' },
      ] },
    { id: 'in-autoscale', t: '오토스케일링 지연', en: 'Autoscaling lag',
      s: '사람이 몰리면 서버를 자동으로 늘리지만 준비에 몇 분이 걸리고, 그동안 기존 서버가 과부하입니다.',
      c: ['이벤트 시작으로 접속 급증', '새 서버가 켜지고 준비되기까지 수 분', '이벤트 시작 직후 몇 분간 슬로우모션·접속 불가'],
      sym: ['slowmo', 'noconnect'], fx: ['stall'], who: ['server'], when: ['event', 'login'],
      num: '부하를 감지하는 데 1~몇 분(지표를 몇 분 평균해서 보기 때문), 새 서버를 켜고 게임 데이터를 읽고 캐시를 채우는 데 또 수 분.',
      own: ['sys', 'srv'],
      act: { game: '채널 분산(이미 붐비는 채널에 있는 사람은 새 서버로 옮길 수 없음), 새 서버의 시작·데이터 로딩 시간 줄이기.', infra: '이벤트 전 미리 확장, 예열된 예비 서버, 줄일 때는 남은 사람이 빠진 뒤 끄기.' },
      more: '오토스케일링은 주로 로그인·게이트웨이·던전처럼 새 서버에 새 사람을 받으면 되는 곳에 씁니다. 줄일 때도 탈이 납니다. 사람이 빠진 새벽에 서버를 줄이면서 남은 사람이 빠지기를 기다리지 않고 끄면 그 사람들의 접속이 끊깁니다.',
      ref: [
        { t: 'Target tracking scaling policies for Amazon EC2 Auto Scaling', u: 'https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-scaling-target-tracking.html', p: 'AWS', n: 'EC2 기본 지표는 5분 간격(상세 모니터링을 켜면 1분)이라, 빨리 반응하려면 1분 이하 간격의 지표 권장' },
        { t: 'Scheduled scaling for Amazon EC2 Auto Scaling', u: 'https://docs.aws.amazon.com/autoscaling/ec2/userguide/ec2-auto-scaling-scheduled-scaling.html', p: 'AWS', n: '예측할 수 있는 부하 변화에 맞춰 정한 시각에 용량을 미리 늘리고 줄임' },
        { t: 'Decrease latency for applications with long boot times using warm pools', u: 'https://docs.aws.amazon.com/autoscaling/ec2/userguide/ec2-auto-scaling-warm-pools.html', p: 'AWS', n: '부팅이 오래 걸리는 앱은 미리 초기화해 둔 인스턴스 풀(웜 풀)로 확장 지연을 줄임' },
      ] },
    { id: 'in-monitoring', t: '로그·모니터링 과부하', en: 'Logging / monitoring overhead',
      s: '장애가 나면 로그가 폭증하고, 로그를 동기로 넘기는 서버는 로그 때문에 더 느려집니다.',
      c: ['오류가 나며 로그·지표 전송량 폭증', '로그 수집기가 밀리고 동기 전송하는 서버는 대기', '장애 때 뚝뚝 끊김·멈춤이 로그 때문에 더 심해짐'],
      sym: ['stutter', 'freeze'], fx: ['stall'], who: ['server'], when: ['event', 'random'],
      own: ['srv', 'sys'],
      act: { game: '비동기 전송, 샘플링, 버퍼 넘치면 버리기, 같은 오류 로그는 묶어서 보내기.', infra: '로그 수집기 용량을 장애 때 폭증량 기준으로 확보, 수집기 적체 경보.' },
      sim: 'arch',
      ref: [
        { t: 'Logging in C#', u: 'https://learn.microsoft.com/en-us/dotnet/core/extensions/logging', p: 'Microsoft', n: '.NET 로그 메서드는 동기라서, 저장소가 느리면 바로 쓰지 말고 빠른 저장소에 먼저 쓴 뒤 나중에 옮기도록 권장' },
        { t: 'Asynchronous loggers', u: 'https://logging.apache.org/log4j/2.x/manual/async.html', p: 'Apache Software Foundation', n: '비동기 로깅은 짧은 폭증을 큐로 흡수하지만, 출력이 계속 느리면 큐가 차서 가장 느린 출력 속도로 떨어지거나 정책에 따라 로그를 버림(Discard)' },
      ] },
    { id: 'in-clock-skew', t: '서버 간 시계 차이', en: 'Clock skew between servers',
      s: '서버마다 시계가 조금씩 다르면 쿨타임·버프·이벤트 시작 판정이 서버마다 어긋납니다.',
      c: ['시간 동기화가 멈춘 서버의 시계가 다른 서버와 수백 ms~수 초 벌어짐', '버프 끝나는 시각 같은 절대 시각을 서버 사이에 넘기면 판정이 어긋남', '이동하니 버프가 사라지거나 쿨타임이 다시 참'],
      sym: ['dropped'], fx: ['lat'], who: ['me'], when: ['moving'],
      num: '시간 동기화(NTP·chrony)가 정상이면 같은 데이터센터 서버끼리는 보통 수 ms 안쪽입니다. 동기화가 멈추거나 가상 서버가 오래 멈췄다 풀리면 수백 ms~수 초로 벌어집니다.',
      own: ['sys', 'srv'],
      act: { game: '서버 사이에는 절대 시각 대신 남은 시간으로 전달.', infra: '시간 동기화(NTP·chrony) 감시, 서버 간 시계 차이 경보.' },
      more: '한 서버의 시계가 한 번에 앞뒤로 뛰는 일은 서버 OS 층의 “시스템 시계 점프 (NTP 스텝)”에서 다룹니다.',
      ref: [
        { t: 'RFC 5905: Network Time Protocol Version 4: Protocol and Algorithms Specification', u: 'https://www.rfc-editor.org/rfc/rfc5905', p: 'IETF', n: '빠른 LAN의 NTP 클라이언트는 보통 수백 µs 안으로 맞음' },
        { t: 'chrony – Frequently Asked Questions', u: 'https://chrony-project.org/faq.html', p: 'chrony', n: '보통 컴퓨터 시계의 드리프트는 100ppm 미만이지만 가상 머신은 더 클 수 있음, 일시 정지했다 재개한 가상 머신은 시각이 틀어져 스텝 보정이 필요할 수 있음' },
        { t: 'clock_getres(2) - Linux manual page', u: 'https://man7.org/linux/man-pages/man2/clock_gettime.2.html', p: 'Linux man-pages', n: 'CLOCK_REALTIME은 수동 변경·NTP 보정으로 불연속하게 뛸 수 있고, CLOCK_MONOTONIC은 그런 점프의 영향을 받지 않음' },
      ] },
    { id: 'in-bots', t: '매크로·봇 과다', en: 'Bots and macros',
      s: '봇은 사람보다 훨씬 자주 요청을 보내 서버 처리량을 잠식합니다.',
      c: ['사냥·이동·거래를 쉬지 않고 반복하는 봇 대량 접속', '서버 처리량과 DB 부하 증가', '특정 사냥터나 서버 전체가 느려짐(슬로우모션·입력 지연)'],
      sym: ['slowmo', 'delay'], fx: ['stall'], who: ['server', 'zone'], when: ['always', 'peak'],
      own: ['srv', 'net'],
      act: { game: '봇 탐지, 계정·캐릭터별 요청 빈도 제한.', infra: 'IP별 접속·요청 빈도 제한(PC방·모바일망은 여러 명이 한 IP를 쓰므로 여유 있게), 방화벽·WAF로 봇 대역 차단.' },
      ref: [
        { t: 'Using rate-based rule statements in AWS WAF', u: 'https://docs.aws.amazon.com/waf/latest/developerguide/waf-rule-statement-type-rate-based.html', p: 'AWS', n: 'IP 등 기준별로 요청 수를 세어 정한 시간 창 안에 너무 많으면 속도 제한' },
        { t: 'RFC 6269: Issues with IP Address Sharing', u: 'https://www.rfc-editor.org/rfc/rfc6269', p: 'IETF', n: '여러 가입자가 IP 하나를 함께 쓰면 IP 기준 차단·제한이 다른 사용자까지 막음' },
      ] },
    { id: 'in-external', t: '외부 서비스 의존', en: 'External dependencies (auth, billing, platform)',
      s: '플랫폼 로그인, 결제, 본인 인증 같은 외부 서비스가 느리거나 멈추면 그 단계에서 막힙니다.',
      c: ['외부 인증·결제 서비스 장애나 지연', '해당 단계에서 응답을 기다림', '로그인 불가, 결제 실패. 이미 게임 중인 사람은 멀쩡'],
      sym: ['noconnect', 'dropped'], fx: ['stall'], who: ['server', 'feature'], when: ['login', 'action'],
      own: ['ext', 'srv'],
      act: { game: '외부 호출에 타임아웃과 친절한 안내, 인증 결과 캐시, 결제 재시도·보상 절차.', ext: '인증·결제·플랫폼 사업자에 장애 확인과 복구 요청, 유저에게 외부 서비스 장애임을 안내.' },
      sim: 'arch',
      ref: [
        { t: 'Timeouts, retries, and backoff with jitter', u: 'https://d1.awsstatic.com/builderslibrary/pdfs/timeouts-retries-and-backoff-with-jitter.pdf', p: 'AWS', n: 'Amazon Builders\' Library. 응답을 기다리는 동안 스레드·연결 같은 자원을 붙잡으므로 타임아웃을 두고, 부작용이 있는 API는 멱등성이 보장될 때만 재시도' },
        { t: 'Circuit Breaker Pattern', u: 'https://learn.microsoft.com/en-us/azure/architecture/patterns/circuit-breaker', p: 'Microsoft Azure', n: '실패할 가능성이 큰 호출은 타임아웃까지 기다리지 않고 바로 거부해 응답 시간을 지킴' },
        { t: 'REL05-BP01 Implement graceful degradation to transform applicable hard dependencies into soft dependencies', u: 'https://docs.aws.amazon.com/wellarchitected/latest/reliability-pillar/rel_mitigate_interaction_failure_graceful_degradation.html', p: 'AWS', n: 'AWS Well-Architected. 의존 서비스가 장애여도 약간 오래된 데이터로라도 핵심 기능을 유지(인증 결과 캐시의 근거)' },
      ] },
  ]);
})();
