/* 원인 항목 3: 서버 게임 프로세스, 메모리, 디스크, 데이터베이스, 서버 구성과 운영 */
(function () {
  const add = (layer, list) => list.forEach(c => DATA.causes.push(Object.assign({ layer }, c)));

  /* ---------------- 9. 서버 게임 프로세스 ---------------- */
  add('server-proc', [
    { id: 'sp-tick-overrun', t: '틱 예산 초과', en: 'Tick overrun',
      s: '한 틱 안에 할 일이 예산을 넘으면 서버의 박자가 느려지고, 그 지역 전체가 느리게 흐릅니다.',
      c: ['한 틱(예: 50ms)에 처리할 일이 예산을 넘음', '1초에 20번 계산할 세계를 8번만 계산', '그 지역 전체 슬로우모션, 스킬 반응 늦음'],
      sym: ['slowmo', 'delay'], fx: ['stall'], who: ['zone'], when: ['event'],
      num: '20틱 서버의 예산은 50ms, 30틱은 33ms, 60틱은 16.7ms.',
      fix: '비싼 계산 줄이기, 틱을 여러 스레드로 나누기, 인원 분산(채널).',
      sim: 'tick' },
    { id: 'sp-aoi', t: '시야 계산 폭발 (N²)', en: 'Area-of-interest explosion',
      s: '누가 누구를 볼 수 있는지 모두끼리 비교하면, 인원이 10배가 될 때 계산은 100배가 됩니다.',
      c: ['한곳에 모인 모든 캐릭터 쌍을 비교', '100명이면 1만 쌍, 1,000명이면 100만 쌍', '월드 보스·공성전에서만 틱이 폭증해 슬로우모션'],
      sym: ['slowmo', 'stutter'], fx: ['stall'], who: ['zone'], when: ['event'],
      fix: '격자·구역으로 나눠 근처만 비교, 멀리 있는 대상은 드물게 갱신.',
      sim: 'tick' },
    { id: 'sp-broadcast', t: '브로드캐스트 폭증', en: 'Broadcast fan-out (N×N)',
      s: '한 명의 움직임을 그를 보는 모두에게 보내면, 모인 인원의 제곱만큼 패킷이 생깁니다.',
      c: ['한 명의 변화를 볼 수 있는 모두에게 전송', '1,000명이 서로를 보면 틱마다 100만 개 업데이트', '전송 대기열과 대역폭이 포화되어 지연·손실'],
      sym: ['delay', 'teleport', 'burst'], fx: ['lat', 'loss'], who: ['zone'], when: ['event'],
      num: '1,000명 × 1,000명 × 20틱 = 초당 2,000만 개. 개당 40바이트면 약 6.4Gbps.',
      fix: '거리별 갱신 빈도 낮추기, 여러 업데이트를 한 패킷에 묶기, 표시 인원 상한.',
      sim: 'tick' },
    { id: 'sp-hotzone', t: '한 스레드에 몰린 지역', en: 'Single-threaded hot zone',
      s: '지역마다 스레드 하나가 맡는 구조에서 한곳에 사람이 몰리면 그 코어 하나만 100%가 됩니다.',
      c: ['한 지역(채널)을 스레드 하나가 담당', '사람이 한곳에 몰리면 그 코어만 포화, 나머지 코어는 여유', '그 지역만 렉, 다른 지역은 멀쩡'],
      sym: ['slowmo', 'delay'], fx: ['stall'], who: ['zone'], when: ['event'],
      fix: '채널 분산, 지역 내부 병렬화, 인원 상한.',
      sim: 'tick' },
    { id: 'sp-lock', t: '락 경합', en: 'Lock contention',
      s: '여러 스레드가 같은 데이터를 쓰려고 열쇠 하나를 기다리면, 스레드를 늘려도 한 명씩만 들어갑니다.',
      c: ['경매장·길드 창고처럼 공용 데이터를 여러 스레드가 동시에 사용', '열쇠(락)를 가진 스레드가 끝날 때까지 나머지는 대기', '특정 기능만 느림, 심하면 전체 틱 지연'],
      sym: ['delay', 'freeze'], fx: ['stall'], who: ['feature', 'server'], when: ['event'],
      fix: '락을 잘게 나누기, 락 안에서 하는 일 줄이기, 메시지 기반 구조.',
      sim: 'locks' },
    { id: 'sp-deadlock', t: '데드락', en: 'Deadlock',
      s: '두 스레드가 서로 상대가 가진 열쇠를 기다리면 영원히 멈춥니다.',
      c: ['스레드 A는 열쇠1을 쥐고 열쇠2를, B는 열쇠2를 쥐고 열쇠1을 기다림', '둘 다 영원히 멈추고 관련 스레드도 줄줄이 멈춤', '서버 전체 정지, 감시 타이머가 재시작하며 전원 접속 끊김'],
      sym: ['freeze', 'disconnect'], fx: ['stall'], who: ['server'], when: ['random', 'event'],
      fix: '락 순서 규칙, 타임아웃 있는 락, 감시 타이머와 덤프.',
      sim: 'locks' },
    { id: 'sp-sync-call', t: '게임 스레드의 동기 호출', en: 'Synchronous DB / file I/O on the game loop',
      s: '틱 도중 DB 응답이나 파일 쓰기를 기다리면, 그 시간만큼 세계 전체가 멈춥니다.',
      c: ['틱 안에서 DB 조회·저장, 로그 쓰기, 외부 API 호출을 기다림', 'DB가 100ms 걸리면 틱도 100ms 멈춤', 'DB·디스크가 느려질 때마다 필드 전체가 멈칫'],
      sym: ['freeze', 'stutter'], fx: ['stall'], who: ['zone', 'server'], when: ['action', 'random'],
      fix: '느린 일은 모두 비동기로 넘기고 결과는 다음 틱에 반영.',
      sim: 'tick' },
    { id: 'sp-queue', t: '메시지 큐 적체', en: 'Mailbox / job queue backlog',
      s: '요청이 처리 속도보다 빨리 들어와 대기열에 쌓이면, 뒤쪽 요청은 몇 초 뒤에야 처리되거나 버려집니다.',
      c: ['요청이 처리 속도보다 빨리 도착', '대기열이 길어지고 한도를 넘으면 버림', '스킬·거래 반응이 늦거나 씹힘'],
      sym: ['delay', 'dropped'], fx: ['lat', 'loss'], who: ['zone', 'feature'], when: ['event'],
      fix: '대기열 길이 모니터링, 오래된 요청 우선 폐기 정책, 처리 병렬화.',
      sim: 'queue' },
    { id: 'sp-timer-burst', t: '정각 이벤트 몰림', en: 'Synchronized timers',
      s: '모든 몬스터 리스폰, 모든 버프 만료, 정각 보상이 같은 틱에 몰리면 그 틱만 수십 배 무거워집니다.',
      c: ['리스폰·만료·보상 타이머가 같은 시각에 맞춰짐', '그 한 틱에 평소의 수십 배 작업', '정해진 시각마다 한 번씩 멈칫'],
      sym: ['freeze', 'stutter'], fx: ['stall'], who: ['zone', 'server'], when: ['periodic'],
      fix: '타이머 시각을 조금씩 흩뿌리기, 여러 틱에 나눠 처리.' },
    { id: 'sp-pathfinding', t: '길찾기 폭주', en: 'Pathfinding storms',
      s: '수백 마리 몬스터가 동시에 플레이어를 쫓으며 경로를 계산하면 CPU를 크게 씁니다.',
      c: ['몰이 사냥, 대규모 스폰으로 몬스터가 동시에 추적', '몬스터마다 길찾기 계산', '그 사냥터만 슬로우모션'],
      sym: ['slowmo'], fx: ['stall'], who: ['zone'], when: ['event'],
      fix: '경로 캐시, 계산 횟수 상한, 여러 틱에 나누기.',
      sim: 'tick' },
    { id: 'sp-serialize', t: '직렬화·압축 비용', en: 'Serialization / compression cost',
      s: '보낼 데이터를 바이트로 바꾸고 압축하는 데도 CPU가 들고, 사람이 많으면 이 비용이 폭증합니다.',
      c: ['업데이트마다 구조체를 바이트로 변환·압축', '인원 제곱에 비례해 비용 증가', '전송이 늦어져 입력 지연'],
      sym: ['delay'], fx: ['stall', 'lat'], who: ['zone'], when: ['event'],
      fix: '한 번 만든 패킷을 여러 명에게 재사용, 가벼운 포맷.' },
    { id: 'sp-crash', t: '서버 크래시', en: 'Server process crash',
      s: '처리하지 못한 오류로 서버 프로세스가 죽으면, 그 서버에 있던 모두가 동시에 끊깁니다.',
      c: ['널 참조, 잘못된 데이터, 메모리 부족 등 치명적 오류', '서버(또는 존) 프로세스 종료', '동시에 튕김, 마지막 저장 이후 진행 롤백 가능'],
      sym: ['disconnect', 'dropped'], fx: ['stall'], who: ['zone', 'server'], when: ['random', 'action'],
      fix: '크래시 덤프 분석, 자동 재시작, 자주 저장.' },
    { id: 'sp-threadpool', t: '스레드 풀 고갈', en: 'Thread pool starvation',
      s: '작업을 맡길 일꾼 스레드가 모두 느린 작업에 묶이면 새 요청은 무작정 기다립니다.',
      c: ['일꾼 스레드들이 외부 API·DB 응답을 기다리며 묶임', '새 요청이 배정받을 스레드가 없음', '로그인·상점 등 특정 기능 무한 로딩'],
      sym: ['noconnect', 'delay'], fx: ['stall'], who: ['feature'], when: ['event', 'login'],
      fix: '느린 호출에 타임아웃, 기능별 스레드 풀 분리, 비동기화.' },
    { id: 'sp-infinite-loop', t: '무한 루프·로직 폭주', en: 'Infinite loop / runaway logic',
      s: '버그로 한 틱이 끝나지 않으면 서버가 멈추고, 감시 타이머가 강제로 재시작합니다.',
      c: ['잘못된 조건으로 반복이 끝나지 않거나 재귀 폭주', '틱이 끝나지 않아 서버 정지', '멈춤 후 전원 접속 끊김'],
      sym: ['freeze', 'disconnect'], fx: ['stall'], who: ['zone', 'server'], when: ['action', 'random'],
      fix: '반복 상한, 감시 타이머, 문제 입력 재현 테스트.' },
  ]);

  /* ---------------- 10. 메모리 ---------------- */
  add('memory', [
    { id: 'mem-gc', t: '서버 GC 전체 멈춤', en: 'Stop-the-world GC pause',
      s: 'Java·C# 서버가 쓰레기를 청소하려고 모든 스레드를 세우는 동안 서버 전체가 멈춥니다.',
      c: ['힙이 차서 GC가 청소 시작', '모든 게임 스레드를 멈추고 청소(힙이 클수록 오래)', '서버의 모두가 동시에 멈췄다가 몰아치기'],
      sym: ['freeze', 'burst'], fx: ['stall'], who: ['server'], when: ['periodic', 'uptime'],
      num: '작은 힙은 수 ms, 수십 GB 힙의 전체 청소는 1초를 넘기도 합니다.',
      fix: '저지연 GC(G1, ZGC 등), 할당 줄이기, 힙 크기 조정.',
      sim: 'gc' },
    { id: 'mem-alloc', t: '할당 폭주', en: 'Allocation storms',
      s: '이벤트 중 임시 객체를 대량으로 만들면 GC가 평소보다 훨씬 자주 돕니다.',
      c: ['아이템 드롭·전투 로그·이벤트 보상으로 임시 객체 폭증', 'GC 빈도가 몇 배로 증가', '이벤트 때만 주기적으로 멈칫'],
      sym: ['stutter', 'freeze'], fx: ['stall'], who: ['server', 'zone'], when: ['event'],
      fix: '오브젝트 풀, 재사용 버퍼, 할당 프로파일링.',
      sim: 'gc' },
    { id: 'mem-leak', t: '메모리 누수', en: 'Memory leak',
      s: '해제되지 않는 메모리가 조금씩 쌓여, 며칠 뒤 GC 폭주·스왑·강제 종료로 이어집니다.',
      c: ['접속 종료한 캐릭터 정보·이벤트 핸들러가 해제되지 않음', '며칠에 걸쳐 여유 메모리가 줄어듦', '점검 직후엔 멀쩡, 날이 갈수록 렉, 결국 서버 다운'],
      sym: ['slowmo', 'freeze', 'disconnect'], fx: ['stall'], who: ['server'], when: ['uptime', 'peak'],
      fix: '메모리 추세 모니터링, 힙 덤프 분석, 장시간 부하 테스트.',
      more: '정기 점검으로 매주 재시작하면 누수가 가려져 오래 발견되지 않습니다. 점검이 한 번 미뤄지거나 이벤트로 인원이 늘었을 때 갑자기 드러나는 경우가 많습니다.',
      sim: 'leak' },
    { id: 'mem-swap', t: '스왑', en: 'Swapping',
      s: '메모리가 모자라 OS가 일부를 디스크로 내보내면, 그 메모리를 쓸 때마다 수천 배 느린 디스크를 기다립니다.',
      c: ['사용 메모리가 실제 램을 넘음', 'OS가 일부를 디스크로 내보내고 필요할 때 다시 읽음', '틱이 수백 ms로 폭증해 서버 전원 슬로우모션·멈춤'],
      sym: ['slowmo', 'freeze'], fx: ['stall'], who: ['server'], when: ['uptime', 'peak'],
      num: 'RAM 읽기 약 100ns, SSD에서 되읽기 약 100µs(1,000배), HDD는 10ms(10만 배).',
      fix: '게임 서버는 스왑을 쓰지 않도록 설정하고 메모리 경보로 대응.',
      sim: 'leak' },
    { id: 'mem-cache-miss', t: '캐시 미스', en: 'CPU cache misses',
      s: '데이터가 메모리 여기저기 흩어져 있으면 CPU가 매번 느린 RAM까지 가서 기다립니다.',
      c: ['객체가 포인터로 흩어져 있고 순서 없이 접근', 'CPU 캐시에 없어서 매번 RAM에서 읽음(100배 느림)', '같은 일을 해도 틱 비용이 몇 배'],
      sym: ['slowmo'], fx: ['stall'], who: ['server'], when: ['event'],
      fix: '자주 함께 쓰는 데이터를 연속으로 배치(데이터 지향 설계).',
      sim: 'ladder' },
    { id: 'mem-fragment', t: '메모리 단편화', en: 'Heap fragmentation',
      s: '할당과 해제를 반복해 빈 공간이 잘게 쪼개지면, 여유는 있는데 큰 덩어리를 못 구합니다.',
      c: ['크기가 제각각인 메모리를 오랫동안 할당·해제', '빈 공간이 잘게 흩어져 큰 할당이 느리거나 실패', '오래 켤수록 느려지고, 메모리 부족 크래시'],
      sym: ['slowmo', 'disconnect'], fx: ['stall'], who: ['server'], when: ['uptime'],
      fix: '크기별 메모리 풀, 단편화에 강한 할당기(jemalloc 등).' },
    { id: 'mem-numa', t: 'NUMA 원격 메모리', en: 'Remote NUMA access',
      s: 'CPU가 두 개인 서버에서 반대편 CPU에 붙은 메모리를 쓰면 접근이 느려집니다.',
      c: ['스레드와 메모리가 서로 다른 CPU 소켓에 배치', '메모리 접근이 1.5~2배 느려짐', '같은 사양인데 프로세스마다 성능 차이'],
      sym: ['slowmo'], fx: ['stall'], who: ['server'], when: ['always'],
      fix: '프로세스·메모리를 한 소켓에 고정(numactl).',
      sim: 'ladder' },
  ]);

  /* ---------------- 11. 디스크 ---------------- */
  add('disk', [
    { id: 'dk-sync-log', t: '동기 로그 쓰기', en: 'Synchronous logging',
      s: '게임 스레드가 로그 한 줄마다 디스크 완료를 기다리면, 디스크가 바쁠 때 세계도 같이 멈춥니다.',
      c: ['전투·거래 로그를 게임 스레드에서 바로 파일에 씀', '디스크가 바쁘면 쓰기 한 번이 수십 ms', '로그 많은 전투에서 멈칫'],
      sym: ['stutter', 'freeze'], fx: ['stall'], who: ['zone', 'server'], when: ['event'],
      fix: '비동기 로깅(메모리 버퍼 + 별도 스레드), 로그 양 줄이기.',
      sim: 'disk' },
    { id: 'dk-fsync', t: '저장 폭주 (fsync)', en: 'fsync storms',
      s: '데이터를 “확실히” 디스크에 쓰도록 요청하면 한 번에 수 ms가 걸리고, 몰리면 줄이 섭니다.',
      c: ['정기 저장·로그아웃 러시로 확실한 쓰기 요청이 몰림', '디스크 대기열이 길어짐', '저장 시각마다 렉, 로그아웃·채널 이동 지연'],
      sym: ['stutter', 'delay'], fx: ['stall', 'lat'], who: ['server'], when: ['periodic', 'event'],
      fix: '저장 묶어서 한 번에, 저장 시각 분산.',
      sim: 'disk' },
    { id: 'dk-burst', t: '클라우드 디스크 버스트 크레딧 소진', en: 'Burst credit depletion',
      s: '클라우드 기본 디스크는 잠깐 빨리 달릴 “체력”이 있어서, 바쁜 시간이 길어지면 속도가 갑자기 떨어집니다.',
      c: ['기준 성능 이상으로 오래 사용', '버스트 크레딧이 바닥나 기준 성능으로 급락', '매일 저녁 몇 시간 지나서부터 렉 시작'],
      sym: ['stutter', 'slowmo', 'delay'], fx: ['stall', 'lat'], who: ['server'], when: ['peak', 'uptime'],
      fix: '성능 보장형 디스크, 크레딧 잔량 경보.',
      sim: 'disk' },
    { id: 'dk-iops', t: 'IOPS 한도·대기열 포화', en: 'IOPS limit / queue saturation',
      s: '디스크가 1초에 처리할 수 있는 요청 수를 넘으면 대기열이 길어져 지연이 폭증합니다.',
      c: ['읽기·쓰기 요청이 디스크 처리 능력에 근접', '대기열이 길어짐(이용률 90% 이상에서 폭증)', '저장·로딩 지연, 동기 호출이면 멈춤'],
      sym: ['delay', 'freeze'], fx: ['lat', 'stall'], who: ['server'], when: ['event', 'peak'],
      num: 'HDD 약 150, SATA SSD 수만, NVMe 수십만 IOPS.',
      fix: '요청 합치기, 캐시, 더 빠른 디스크.',
      sim: 'disk' },
    { id: 'dk-full', t: '디스크 가득 참', en: 'Disk full',
      s: '로그와 덤프가 쌓여 디스크가 가득 차면 쓰기가 실패하고, 대비가 없으면 서버가 죽습니다.',
      c: ['로그·덤프·임시 파일이 쌓여 100%', '쓰기 실패. 오류 처리가 없으면 크래시, 있으면 저장 실패', '접속 끊김, 진행 롤백'],
      sym: ['disconnect', 'dropped'], fx: ['stall'], who: ['server'], when: ['uptime'],
      fix: '로그 로테이션, 용량 경보, 로그와 데이터 디스크 분리.' },
    { id: 'dk-backup', t: '백업·압축·검사 작업', en: 'Backup / compression / scans',
      s: '새벽 백업, 로그 압축, 보안 검사가 디스크를 독점하면 게임 서버의 읽기·쓰기가 밀립니다.',
      c: ['예약된 백업·압축 작업 시작', '디스크 대역폭과 IOPS를 대부분 차지', '매일 같은 시각 렉'],
      sym: ['stutter', 'delay'], fx: ['stall', 'lat'], who: ['server'], when: ['periodic'],
      fix: '백업은 복제본에서, I/O 우선순위 낮추기, 시각 분산.',
      sim: 'disk' },
    { id: 'dk-lazy-load', t: '서버의 지연 로딩', en: 'Lazy loading on the server',
      s: '서버가 던전·맵 데이터를 처음 요청받을 때 디스크에서 읽으면, 그 틱 동안 모두가 멈춥니다.',
      c: ['누군가 처음으로 던전·지역에 입장', '서버가 게임 스레드에서 데이터를 디스크에서 읽음', '그 서버의 모두가 잠깐 멈춤'],
      sym: ['freeze'], fx: ['stall'], who: ['zone'], when: ['moving'],
      fix: '서버 시작 때 미리 로딩, 비동기 로딩.' },
    { id: 'dk-coredump', t: '크래시 덤프 기록', en: 'Core dump writing',
      s: '서버가 죽을 때 수 GB 메모리를 디스크에 기록하느라 재시작이 몇 분 늦어집니다.',
      c: ['서버 크래시로 메모리 전체를 파일로 기록', '수 GB를 쓰는 동안 재시작 불가', '튕긴 뒤 한참 동안 접속 불가'],
      sym: ['noconnect'], fx: ['stall'], who: ['server'], when: ['random'],
      fix: '덤프 크기 제한, 빠른 디스크, 재시작과 덤프 분리.' },
    { id: 'dk-hdd', t: 'HDD 탐색 지연', en: 'HDD seek latency',
      s: 'HDD는 바늘이 원판 위를 움직여야 해서 흩어진 데이터를 읽고 쓰는 데 한 번에 10ms 가까이 걸립니다.',
      c: ['오래된 서버나 저가 스토리지에서 HDD 사용', '흩어진 읽기·쓰기마다 약 10ms', '전반적인 저장·로딩 지연'],
      sym: ['delay'], fx: ['lat'], who: ['server'], when: ['always'],
      fix: 'SSD로 교체, 순차 쓰기 위주 설계.',
      sim: 'ladder' },
  ]);

  /* ---------------- 12. 데이터베이스 ---------------- */
  add('db', [
    { id: 'db-no-index', t: '인덱스 없는 쿼리', en: 'Missing index / full table scan',
      s: '색인 없이 조건에 맞는 행을 찾으려면 표 전체를 훑어야 합니다.',
      c: ['새 기능 배포로 인덱스가 없는 조건 검색 추가', '수백만 행을 모두 훑어 쿼리 하나에 수백 ms~수 초', '우편함·거래 기록 로딩 지연, 커넥션이 묶여 다른 요청까지 대기'],
      sym: ['delay', 'noconnect'], fx: ['lat', 'stall'], who: ['feature', 'server'], when: ['action'],
      num: '인덱스가 있으면 수 ms, 없으면 데이터 크기에 비례해 수백 배.',
      fix: '실행 계획 검토, 인덱스 추가, 느린 쿼리 로그 감시.',
      sim: 'dbpool' },
    { id: 'db-hot-row', t: '인기 행 잠금 경합', en: 'Hot row lock contention',
      s: '모두가 같은 행(길드 창고, 경매장 인기 아이템, 서버 전체 카운터)을 고치려 하면 한 명씩만 잠금을 얻습니다.',
      c: ['이벤트·인기 아이템으로 같은 행에 수정이 몰림', '잠금을 얻을 때까지 요청이 줄 섬', '거래 실패, “잠시 후 다시 시도”, 타임아웃'],
      sym: ['dropped', 'delay'], fx: ['stall', 'lat'], who: ['feature'], when: ['event'],
      fix: '행을 나누기(샤딩된 카운터), 트랜잭션 짧게, 메모리에서 모아 한 번에 반영.',
      sim: 'dbpool' },
    { id: 'db-deadlock', t: 'DB 데드락', en: 'Database deadlock',
      s: '두 트랜잭션이 서로 상대가 잠근 행을 기다리면 DB가 한쪽을 강제로 취소합니다.',
      c: ['거래 A는 아이템→재화, B는 재화→아이템 순서로 잠금', 'DB가 교착을 감지해 한쪽을 롤백', '거래·제작이 가끔 실패, 아이템이 되돌아감'],
      sym: ['dropped'], fx: ['loss'], who: ['feature'], when: ['event', 'action'],
      fix: '잠금 순서 통일, 실패 시 자동 재시도.' },
    { id: 'db-pool', t: '커넥션 풀 고갈', en: 'Connection pool exhaustion',
      s: 'DB와 맺어 둔 연결 수가 정해져 있어서, 느린 쿼리가 연결을 붙잡으면 나머지는 줄을 섭니다.',
      c: ['느린 쿼리나 요청 폭주로 모든 연결이 사용 중', '새 요청은 연결이 날 때까지 대기', '로그인 무한 로딩, 저장 지연, 타임아웃'],
      sym: ['noconnect', 'delay'], fx: ['stall', 'lat'], who: ['server', 'feature'], when: ['login', 'event'],
      fix: '느린 쿼리 제거, 풀 크기와 대기 타임아웃 조정, 기능별 풀 분리.',
      sim: 'dbpool' },
    { id: 'db-replica-lag', t: '복제 지연', en: 'Replication lag',
      s: '쓰기는 주 DB에, 읽기는 복제본에서 하는데 복제본이 늦게 따라오면 방금 쓴 내용이 안 보입니다.',
      c: ['주 DB에 쓰기가 몰려 복제본이 수 초 뒤처짐', '방금 저장한 내용을 복제본에서 읽으면 아직 없음', '방금 산 아이템이 안 보임, 거래소 가격이 옛날 값, 중복 지급 버그'],
      sym: ['dropped'], fx: ['lat'], who: ['feature'], when: ['event', 'peak'],
      fix: '방금 쓴 데이터는 주 DB에서 읽기, 복제 지연 경보.',
      sim: 'arch' },
    { id: 'db-checkpoint', t: '체크포인트·로그 플러시', en: 'Checkpoint / log flush stalls',
      s: 'DB가 메모리의 변경분을 주기적으로 디스크에 몰아서 쓰는 순간 쿼리가 느려집니다.',
      c: ['변경분이 쌓여 주기적으로 디스크에 기록', '그 순간 디스크가 바빠져 쿼리 지연', '주기적으로 저장·로딩이 느려짐'],
      sym: ['delay', 'stutter'], fx: ['lat'], who: ['server', 'feature'], when: ['periodic'],
      fix: '체크포인트를 잘게 나눠 고르게, 빠른 디스크.' },
    { id: 'db-cold-cache', t: '차가운 캐시', en: 'Cold buffer pool after restart',
      s: 'DB를 재시작하면 메모리 캐시가 비어 있어서, 한동안 모든 조회가 디스크에서 읽힙니다.',
      c: ['점검으로 DB 재시작', '자주 쓰던 데이터가 메모리에 없어 디스크에서 읽음', '점검 직후 한동안 로그인·로딩이 느림'],
      sym: ['noconnect', 'delay'], fx: ['lat'], who: ['server'], when: ['login'],
      fix: '재시작 후 캐시 예열(워밍), 점진적 오픈.' },
    { id: 'db-login-storm', t: '로그인 폭주 쿼리', en: 'Login storm, N+1 queries',
      s: '캐릭터 하나를 불러올 때 수십 번 따로 조회하면, 수만 명 동시 로그인이 쿼리 수백만 개가 됩니다.',
      c: ['캐릭터 로딩 때 아이템·스킬·퀘스트를 따로따로 조회', '점검 직후 동시 로그인으로 쿼리 폭증', '로그인 무한 로딩, 게임 중인 사람의 저장까지 밀림'],
      sym: ['noconnect', 'delay'], fx: ['stall', 'lat'], who: ['server'], when: ['login'],
      fix: '한 번에 묶어서 조회, 접속 대기열, 캐시.',
      sim: 'dbpool' },
    { id: 'db-batch', t: '대량 배치 작업', en: 'Batch jobs during service',
      s: '랭킹 집계, 우편 일괄 발송, 오래된 데이터 정리를 운영 중에 돌리면 잠금과 디스크를 차지합니다.',
      c: ['운영 시간에 대량 작업 실행', '넓은 범위 잠금, 디스크·CPU 점유', '특정 시간대 거래·저장 실패, 로딩 지연'],
      sym: ['delay', 'dropped'], fx: ['lat', 'stall'], who: ['feature', 'server'], when: ['periodic'],
      fix: '잘게 나눠 조금씩, 복제본에서 집계, 한가한 시간대.' },
    { id: 'db-failover', t: 'DB 장애 전환', en: 'Database failover',
      s: '주 DB가 죽어 예비 DB로 넘어가는 동안 쓰기가 안 되고, 복제되지 못한 마지막 데이터는 사라질 수 있습니다.',
      c: ['주 DB 장애로 예비 DB가 승격', '전환 중 수 초~수십 초 쓰기 불가, 미복제 데이터 유실 가능', '잠깐 모든 저장 실패, 아이템·경험치 롤백'],
      sym: ['dropped', 'freeze', 'disconnect'], fx: ['stall', 'loss'], who: ['server'], when: ['random'],
      fix: '동기 복제(성능과 맞바꿈), 재시도 가능한 저장, 전환 훈련.' },
    { id: 'db-save-interval', t: '몰아서 저장하는 주기', en: 'Periodic save window',
      s: '부하를 줄이려 몇 분에 한 번만 저장하면, 그 사이 서버가 죽을 때 진행이 사라집니다.',
      c: ['캐릭터 상태를 몇 분마다 한 번 저장', '그 사이 서버 크래시·장애 발생', '다시 접속하니 몇 분 전 상태(롤백)'],
      sym: ['dropped'], fx: ['loss'], who: ['server', 'zone'], when: ['random'],
      fix: '중요 이벤트(거래, 희귀 획득)는 즉시 저장, 변경 로그 기록.' },
    { id: 'db-cache-stampede', t: '캐시 만료 쇄도', en: 'Cache stampede / thundering herd',
      s: '인기 데이터의 캐시가 동시에 만료되면 수천 개 요청이 한꺼번에 DB로 몰립니다.',
      c: ['Redis 등에 저장된 인기 데이터가 동시에 만료', '같은 데이터를 다시 만들려는 요청이 DB로 쇄도', 'DB 과부하로 연쇄 지연'],
      sym: ['delay', 'freeze', 'noconnect'], fx: ['stall', 'lat'], who: ['server'], when: ['periodic', 'event'],
      fix: '만료 시각 흩뿌리기, 한 요청만 갱신하고 나머지는 옛 값 사용.',
      sim: 'arch' },
  ]);

  /* ---------------- 13. 서버 구성과 운영 ---------------- */
  add('infra', [
    { id: 'in-gateway', t: '게이트웨이·프록시 경유', en: 'Gateway / proxy hop',
      s: '클라이언트와 게임 서버 사이에 중간 서버를 두면, 한 번 거칠 때마다 처리 시간이 붙고 그 서버가 약점이 됩니다.',
      c: ['클라이언트 ↔ 게이트웨이 ↔ 게임 서버 구조', '중간 서버의 처리·대기 추가, 과부하 시 모두에게 영향', '전체 핑 상승, 게이트웨이 장애 시 그 사용자 전원 끊김'],
      sym: ['delay', 'disconnect'], fx: ['lat', 'stall'], who: ['server'], when: ['event', 'always'],
      fix: '게이트웨이 수평 확장, 연결 이전 가능한 구조.',
      sim: 'arch' },
    { id: 'in-zone-transfer', t: '존 이동 (서버 간 이관)', en: 'Zone / server handoff',
      s: '다른 지역·던전에 들어갈 때 캐릭터 정보를 다른 서버로 넘기는 과정에서 지연과 실패가 생깁니다.',
      c: ['던전 입장, 대륙 이동으로 담당 서버가 바뀜', '저장 → 전달 → 불러오기, 대상 서버가 붐비면 대기', '긴 로딩, 입장 실패, 이동 중 튕김'],
      sym: ['noconnect', 'freeze', 'disconnect'], fx: ['lat', 'stall'], who: ['me', 'zone'], when: ['moving'],
      fix: '이관 데이터 줄이기, 대상 서버 미리 예약, 실패 시 원래 자리로 복귀.' },
    { id: 'in-cascade', t: '연쇄 장애', en: 'Cascading failure',
      s: '한 서비스가 느려지면 그걸 부르는 서버들이 응답을 기다리며 묶이고, 상관없는 기능까지 멈춥니다.',
      c: ['DB·인증 같은 한 서비스가 느려짐', '호출하는 서버들의 스레드와 연결이 응답을 기다리며 묶임', '상관없어 보이는 기능까지 전부 느려지거나 멈춤'],
      sym: ['freeze', 'delay', 'noconnect'], fx: ['stall'], who: ['server'], when: ['event', 'random'],
      fix: '모든 호출에 타임아웃, 서킷 브레이커, 기능별 격리(벌크헤드).',
      sim: 'arch' },
    { id: 'in-subservice', t: '부가 서버 장애', en: 'Auxiliary service outage',
      s: '채팅·파티·경매장처럼 게임 서버와 따로 도는 서버가 아프면 그 기능만 먹통이 됩니다.',
      c: ['기능 전용 서버가 느려지거나 죽음', '해당 기능 요청만 응답 없음', '채팅 안 됨, 파티 초대 무반응, 거래소 무한 로딩(전투는 정상)'],
      sym: ['dropped', 'noconnect'], fx: ['stall', 'loss'], who: ['feature'], when: ['random', 'event'],
      fix: '기능별 상태 표시, 실패해도 게임은 계속되게 설계.',
      sim: 'arch' },
    { id: 'in-deploy', t: '배포·재시작', en: 'Deploy / rolling restart',
      s: '업데이트를 위해 서버를 재시작할 때 연결을 옮기지 않으면 접속 중인 사람이 끊깁니다.',
      c: ['핫픽스 배포로 서버를 순서대로 재시작', '연결을 다른 서버로 옮기지 않고 종료', '공지 없는 튕김, 재접속 폭주'],
      sym: ['disconnect', 'noconnect'], fx: ['loss'], who: ['server', 'zone'], when: ['random'],
      fix: '연결 드레인, 세션 이전, 배포 시각 공지.' },
    { id: 'in-autoscale', t: '자동 확장 지연', en: 'Autoscaling lag',
      s: '사람이 몰리면 서버를 자동으로 늘리지만 준비에 몇 분이 걸리고, 그동안 기존 서버가 과부하입니다.',
      c: ['이벤트 시작으로 접속 급증', '새 서버가 켜지고 준비되기까지 수 분', '이벤트 시작 직후 몇 분간 렉·접속 불가'],
      sym: ['slowmo', 'noconnect'], fx: ['stall'], who: ['server'], when: ['event', 'login'],
      fix: '이벤트 전 미리 확장, 예열된 예비 서버.' },
    { id: 'in-monitoring', t: '로그·모니터링 과부하', en: 'Logging / monitoring overhead',
      s: '장애가 나면 로그가 폭증하고, 로그를 동기로 넘기는 서버는 로그 때문에 더 느려집니다.',
      c: ['오류가 나며 로그·지표 전송량 폭증', '로그 수집기가 밀리고 동기 전송하는 서버는 대기', '장애가 로그 때문에 더 악화'],
      sym: ['stutter', 'freeze'], fx: ['stall'], who: ['server'], when: ['event', 'random'],
      fix: '비동기 전송, 표본 추출, 버퍼 넘치면 버리기.',
      sim: 'arch' },
    { id: 'in-clock-skew', t: '서버 간 시계 차이', en: 'Clock skew between servers',
      s: '서버마다 시계가 조금씩 다르면 쿨타임·버프·이벤트 시작 판정이 서버마다 어긋납니다.',
      c: ['서버들의 시계가 수백 ms~수 초 차이', '서버를 옮길 때 시간 기준 판정이 어긋남', '이동하니 버프가 사라지거나 쿨타임이 다시 참'],
      sym: ['dropped'], fx: ['lat'], who: ['me'], when: ['moving'],
      fix: '시간 동기화 감시, 절대 시각 대신 남은 시간으로 전달.' },
    { id: 'in-bots', t: '매크로·봇 과다', en: 'Bots and macros',
      s: '봇은 사람보다 훨씬 자주 요청을 보내 서버 처리량을 잠식합니다.',
      c: ['사냥·이동·거래를 쉬지 않고 반복하는 봇 대량 접속', '서버 처리량과 DB 부하 증가', '특정 사냥터·서버 전체 체감 부하 증가'],
      sym: ['slowmo', 'delay'], fx: ['stall'], who: ['server', 'zone'], when: ['always', 'peak'],
      fix: '요청 빈도 제한, 봇 탐지.' },
    { id: 'in-external', t: '외부 서비스 의존', en: 'External dependencies (auth, billing, platform)',
      s: '플랫폼 로그인, 결제, 본인 인증 같은 외부 서비스가 느리거나 멈추면 그 단계에서 막힙니다.',
      c: ['외부 인증·결제 서비스 장애나 지연', '해당 단계에서 응답을 기다림', '로그인 불가, 결제 실패. 이미 게임 중인 사람은 멀쩡'],
      sym: ['noconnect', 'dropped'], fx: ['stall'], who: ['server', 'feature'], when: ['login', 'action'],
      fix: '타임아웃과 친절한 안내, 인증 결과 캐시, 결제 재시도·보상 절차.',
      sim: 'arch' },
  ]);
})();
