/* 원인 항목 5: 일부에게만 생기는 문제
   - 한 사람(또는 한 회선)만 느릴 때 그 사람과 다른 사람에게 각각 보이는 것
   - 같은 PC의 두 클라이언트 중 한쪽만 NPC가 안 보이는 등 “한쪽만 이상한” 현상 */
(function () {
  const add = (layer, list) => list.forEach(c => DATA.causes.push(Object.assign({ layer }, c)));

  add('partial', [
    /* ---- 한 사람만 느릴 때 ---- */
    { id: 'pt-slow-burst', t: '느린 사람이 남의 화면에서 몰아서 움직임', en: 'Laggy player seen by others (bursty inputs)',
      s: '회선이 나쁜 사람의 입력은 들쭉날쭉 몰려서 서버에 도착합니다. 서버가 틱마다 받은 만큼 적용하면, 다른 사람 눈에는 그 캐릭터가 멈칫했다가 한 번에 여러 걸음을 갑니다.',
      c: ['느린 사람의 이동 명령이 어떤 틱엔 0개, 어떤 틱엔 2~3개씩 도착', '서버가 받은 틱에 한꺼번에 적용해 그 캐릭터 위치가 계단처럼 변함', '다른 사람 화면에서 그 캐릭터만 멈칫하다 파파팍. 나머지는 멀쩡'],
      sym: ['burst', 'teleport'], fx: ['jit', 'loss'], who: ['onechar', 'region'], when: ['always', 'moving'],
      num: '지터 80ms면 20틱(50ms) 서버에서 틱당 명령 수가 0~3개로 흔들립니다.',
      fix: '플레이어별 입력 버퍼로 명령을 고르게 펴서 적용, 입력 순번을 보고 원래 간격대로 적용. 다른 사람 화면의 보간 버퍼만 늘려서는 잘 가려지지 않습니다. 서버의 위치 기록 자체가 계단 모양이기 때문입니다.',
      more: '서버 권위 구조에서는 이것이 정상 동작입니다. 느린 한 사람의 렉은 “그 사람이 이상하게 움직이는 모습”으로만 남에게 보이고, 다른 사람의 조작이나 몬스터 움직임에는 영향을 주지 않습니다. 다만 그 사람과 직접 주고받는 일(거래, 파티 기믹, PvP 판정)은 함께 늦어집니다.',
      sim: 'oneslow' },
    { id: 'pt-event-server', t: '도착 즉시 처리하는 서버의 몰아치기', en: 'Event-driven processing of bursty inputs',
      s: '패킷이 도착하는 대로 바로 처리하고 알리는 서버에서는, 느린 사람의 몰려 온 행동이 연달아 즉시 실행됩니다.',
      c: ['느린 사람의 스킬·이동 요청이 몰려서 도착', '서버가 받는 즉시 순서대로 실행하고 바로 모두에게 알림', '다른 사람 눈에 그 사람이 스킬 여러 개를 한순간에 쓰거나 빨리 감기처럼 움직임'],
      sym: ['burst'], fx: ['jit'], who: ['onechar'], when: ['action', 'always'],
      fix: '행동에 클라이언트 입력 시각을 붙여 간격을 유지하거나(시각은 서버가 허용 범위 안에서만 인정), 행동 사이 최소 간격(쿨다운)을 서버가 강제.',
      sim: 'oneslow' },
    { id: 'pt-input-buffer', t: '플레이어별 입력 버퍼 크기', en: 'Per-player server input buffer (jitter buffer)',
      s: '서버가 사람마다 입력을 조금 모아 두었다가 한 틱에 하나씩 꺼내 쓰면, 다른 사람 눈에는 매끄럽지만 본인 행동이 서버에서 확정되는 시점은 그만큼 늦어집니다.',
      c: ['서버가 느린 사람의 입력을 버퍼에 모아 한 틱에 하나씩 적용', '버퍼가 작으면 자주 비어 그 캐릭터가 제자리, 크면 본인 입력이 늦게 확정', '작으면 남 눈에 멈칫, 크면 본인의 스킬 결과가 늦게 나옴(입력 지연)'],
      sym: ['stutter', 'delay'], fx: ['jit'], who: ['onechar', 'me'], when: ['always'],
      num: '보통 1~3틱 분량. 회선이 흔들리는 사람만 버퍼를 늘리는 적응형이 흔합니다.',
      fix: '사람마다 회선 상태에 맞춰 버퍼 크기를 자동 조절, 밀리면 두 개씩 꺼내 따라잡기. 버퍼가 자주 비는 사람의 클라이언트에는 입력을 조금 더 앞당겨 보내라고 지시하는 방식(클라이언트 시간 조절)도 씁니다.',
      sim: 'oneslow' },
    { id: 'pt-isp-validation', t: '특정 통신사 사용자에게 몰리는 검증 오탐', en: 'Anti-cheat / movement validation false positives on bad ISPs',
      s: '지터가 큰 회선을 쓰는 사람들은 입력이 몰려 도착해서, 서버의 속도·쿨타임 검사에 자주 걸립니다.',
      c: ['특정 통신사·지역 회선이 저녁에 흔들림', '몰려 도착한 정상 입력을 서버가 과속·쿨타임 위반으로 판단', '그 통신사 사용자만 고무줄, 스킬 거절, 심하면 강제 종료'],
      sym: ['rubber', 'dropped', 'disconnect'], fx: ['jit'], who: ['region', 'me'], when: ['peak', 'moving'],
      fix: '검사를 짧은 순간이 아닌 누적 허용량으로, 회선 상태를 참고해 기준을 완화, 강제 종료 전 경고 단계.',
      sim: 'oneslow' },
    { id: 'pt-raid-member', t: '느린 파티원 한 명과 보스 기믹', en: 'One laggy member in a synchronized mechanic',
      s: '모두가 정해진 순간에 함께 반응해야 하는 레이드 기믹에서는, 느린 한 사람의 늦은 반응이 파티 전체의 실패가 됩니다.',
      c: ['“모두 동시에 흩어지기”, “한 명이 버튼 누르기” 같은 공동 기믹', '느린 사람은 예고를 늦게 보고 입력도 늦게 도착', '그 사람 한 명 때문에 전멸, 다른 파티원은 “렉 걸린 사람 때문”이라고 느낌'],
      sym: ['dropped', 'delay'], fx: ['lat'], who: ['zone', 'onechar'], when: ['event', 'action'],
      fix: '기믹 판정 창을 핑만큼 여유 있게, 예고는 서버 시각으로 미리 보내기, 한 명 실패가 전멸로 이어지지 않는 설계.',
      sim: 'windows' },
    { id: 'pt-mob-control', t: '느린 사람이 몬스터 조종을 맡은 구조', en: 'Monster movement delegated to a player client',
      s: '서버 부하를 줄이려고 몬스터 이동 계산을 근처 플레이어 한 명의 클라이언트에 맡기는 게임이 있습니다. 그 사람 회선이 나쁘면 그 몬스터가 모두의 화면에서 이상하게 움직입니다.',
      c: ['서버가 몬스터 이동 계산을 가장 가까운(또는 먼저 온) 플레이어의 클라이언트에 맡김', '맡은 사람의 결과 보고가 늦거나 몰려서 서버에 도착', '그 몬스터만 주변 모두의 화면에서 멈칫하다 순간이동. 맡은 사람 본인 화면에서는 멀쩡'],
      sym: ['teleport', 'stutter', 'burst'], fx: ['jit', 'loss'], who: ['onechar', 'zone'], when: ['always', 'random'],
      fix: '조종 권한을 회선이 좋은 사람에게 넘기기(핑·손실 기준), 보고가 끊기면 서버가 즉시 회수, 보스처럼 중요한 몬스터는 서버가 직접 계산.',
      more: '맡은 사람은 멀쩡하다고 느끼므로 제보는 “몬스터가 이상하다”로만 들어옵니다. 한 사람만 빼고 모두가 같은 몬스터를 이상하게 본다면, 그 몬스터의 조종 권한을 누가 가졌는지부터 확인합니다.' },
    { id: 'pt-heavy-char', t: '특정 캐릭터의 데이터가 비대함', en: 'One character with oversized data (inventory, mail, buffs)',
      s: '아이템·우편이 수천 개 쌓였거나 친구·차단 목록, 버프가 유난히 많은 캐릭터는 접속하고 저장하고 주변에 알릴 양이 남보다 몇 배 큽니다. 회선과 상관없이 그 캐릭터로만 느립니다.',
      c: ['오래 키운 캐릭터나 이벤트 보상이 인벤토리·우편함에 수천 개 쌓임', '접속·지역 이동·저장 때마다 그만큼 DB를 읽고 쓰고, 주변에 보낼 장비·버프 정보도 큼', '그 캐릭터만 입장 로딩이 길고 인벤토리·우편을 열 때 멈칫. 저장을 게임 스레드에서 기다리는 서버라면 주변 사람까지 잠깐 멈춤'],
      sym: ['noconnect', 'delay', 'freeze'], fx: ['stall'], who: ['me', 'feature'], when: ['login', 'action', 'moving'],
      num: '아이템 한 개가 DB 한 줄이라면, 아이템 5,000개짜리 캐릭터는 접속할 때마다 5,000줄을 읽습니다. 평범한 캐릭터의 수십 배입니다.',
      fix: '인벤토리·우편 보관 한도와 오래된 우편 자동 정리, 필요한 부분만 나눠 불러오기, 저장은 바뀐 부분만 게임 스레드 밖에서.',
      more: '같은 캐릭터로 다른 PC·회선에서 접속해도 똑같이 느리고 같은 계정의 다른 캐릭터는 멀쩡하다면, 회선이 아니라 캐릭터 데이터를 의심합니다. 제보에 캐릭터 이름이 꼭 필요한 이유입니다.' },

    /* ---- 같은 PC 두 클라이언트, 한쪽만 이상할 때 ---- */
    { id: 'pt-phase', t: '채널·인스턴스·페이즈 차이', en: 'Different channel / instance / phase',
      s: '두 캐릭터가 다른 채널이나 인스턴스에 있거나, 퀘스트 진행도에 따라 보이는 NPC가 다른 “페이즈”에 있으면 서로 다른 세상을 봅니다.',
      c: ['두 번째 캐릭터가 다른 채널로 배정되거나 퀘스트 단계가 다름', '서버가 그 캐릭터에게는 해당 NPC를 보내지 않음(정상)', '한쪽에만 NPC가 없음. 버그처럼 보이지만 설계대로'],
      sym: ['invisible'], fx: ['loss'], who: ['oneclient', 'me'], when: ['always', 'login'],
      fix: '채널·페이즈를 화면에 표시, QA 체크리스트에 “두 캐릭터의 채널·퀘스트 단계 확인” 추가.',
      more: '퀘스트 진행을 계정 단위로 저장하는지 캐릭터 단위로 저장하는지도 확인합니다. 같은 계정의 두 캐릭터라면 한쪽의 진행이 다른 쪽의 페이즈를 바꿀 수 있습니다.',
      sim: 'npcmissing' },
    { id: 'pt-loading-drop', t: '로딩 중 도착한 등장 알림 폐기', en: 'Spawn messages dropped before the client is ready',
      s: '존에 들어가자마자 서버가 주변 NPC 등장 알림을 보내는데, 클라이언트가 아직 맵을 불러오는 중이라 그 알림을 버립니다.',
      c: ['서버가 입장 처리 직후 주변 개체 등장 알림을 발송', '클라이언트는 로딩 중이라 처리기가 없어 알림을 버림', '서버는 이미 보냈다고 믿어 다시 안 보냄. 시야를 벗어났다 오기 전까지 NPC가 안 보임'],
      sym: ['invisible'], fx: ['loss'], who: ['oneclient', 'me'], when: ['login', 'moving'],
      num: '같은 PC에서 두 클라이언트가 동시에 로딩하거나 로딩하는 쪽이 뒤에 깔린 창이면, CPU·디스크를 나눠 쓰고 처리도 제한되어 그쪽 로딩이 몇 배 길어질 수 있습니다. 서버 입장 처리가 빨라져도 같은 버그가 드러납니다.',
      fix: '클라이언트가 “준비 완료”를 보낸 뒤 주변 정보 전송, 또는 로딩 중 받은 패킷을 보관했다가 처리.',
      sim: 'npcmissing' },
    { id: 'pt-aoi-race', t: '시야 등록 순서 꼬임', en: 'Interest-management race on enter/leave',
      s: '캐릭터가 시야 격자에 등록되는 순간과 NPC가 격자를 옮기는 순간이 겹치면, 그 NPC의 등장 알림이 누락될 수 있습니다.',
      c: ['입장·채널 이동·순간이동 처리와 NPC 이동이 같은 순간에 겹침', '“새로 보이게 된 개체” 계산에서 그 NPC가 빠짐', '특정 NPC 몇 마리만 안 보이거나 이미 떠난 NPC가 남아 있음'],
      sym: ['invisible'], fx: ['loss'], who: ['oneclient', 'me'], when: ['moving', 'random'],
      fix: '시야 갱신을 한 스레드·한 순서로 처리, 주기적으로 “보이는 목록” 전체를 다시 맞추기.',
      sim: 'npcmissing' },
    { id: 'pt-baseline', t: '기준 스냅샷 유실', en: 'Lost baseline for delta compression',
      s: '서버가 “지난번과 달라진 것만” 보내는 방식에서, 처음 한 번 보내는 전체 정보(기준)를 잃으면 그 뒤 변화분을 적용할 수 없습니다.',
      c: ['개체의 전체 정보(기준) 패킷이 손실되거나 처리 전에 버려짐', '클라이언트가 이후의 변화분을 적용할 대상이 없어 무시', '그 개체가 안 보이거나, 한참 뒤 갑자기 나타남'],
      sym: ['invisible', 'teleport'], fx: ['loss'], who: ['oneclient', 'me'], when: ['random'],
      fix: '기준은 반드시 확인 응답을 받을 때까지 재전송, 클라이언트가 모르는 개체의 변화분을 받으면 서버에 다시 요청.',
      sim: 'npcmissing' },
    { id: 'pt-ghost', t: '퇴장 알림 유실 (유령 개체)', en: 'Missed despawn (ghost entity)',
      s: '반대로 “사라졌다”는 알림을 놓치면, 이미 죽었거나 떠난 NPC·플레이어가 내 화면에만 남습니다.',
      c: ['죽음·퇴장·시야 이탈 알림이 손실되거나 순서가 꼬임', '클라이언트는 그 개체가 아직 있다고 믿음', '때려도 반응 없는 몬스터, 이미 나간 플레이어가 서 있음'],
      sym: ['invisible'], fx: ['loss'], who: ['oneclient', 'me'], when: ['random', 'event'],
      fix: '서버가 주기적으로 “지금 보이는 목록”을 보내 목록에 없는 개체는 지우기, 움직여야 할 개체가 오래 갱신이 없으면 숨기기.',
      sim: 'npcmissing' },
    { id: 'pt-spawn-burst', t: '입장 직후 몰리는 등장 정보 유실', en: 'Initial spawn burst lost (unreliable channel, receive buffer, fragmentation)',
      s: '존에 들어서는 순간 서버는 주변 개체 수십~수백 개의 등장 정보를 한꺼번에 보냅니다. 이것을 손실 허용 채널로 보내거나, 로딩 중이라 소켓을 못 읽는 사이 수신 버퍼가 넘치면 일부가 사라지고 다시 오지 않습니다.',
      c: ['입장 직후 등장 정보가 짧은 순간에 몰려 도착', '로딩 중인 클라이언트가 소켓을 늦게 읽어 OS 수신 버퍼가 넘치거나, 큰 UDP 패킷이 조각나 조각 하나만 잃어도 통째로 사라짐. 손실 허용(비신뢰) 채널이면 다시 보내 주지도 않음', '로딩이 느린 쪽 클라이언트에서만 NPC 몇 마리가 빠짐. 시야를 벗어났다 돌아오면 보임'],
      sym: ['invisible'], fx: ['loss'], who: ['oneclient', 'me'], when: ['login', 'moving'],
      num: 'PC의 UDP 수신 버퍼 기본값은 수십~수백 KB입니다. 사람 많은 마을의 입장 정보가 이보다 크면, 로딩 때문에 소켓을 잠깐만 못 읽어도 넘칩니다.',
      fix: '등장·퇴장 알림은 반드시 재전송이 보장되는 신뢰 채널로, 초기 정보는 나눠서 보내기, 수신은 로딩과 별개의 스레드에서, 수신 버퍼 크기 늘리기.',
      sim: 'npcmissing' },
    { id: 'pt-id-reuse', t: '개체 번호 재사용 혼동', en: 'Entity ID reused without a generation counter',
      s: '죽은 NPC가 다시 나타날 때 서버가 같은 개체 번호를 다시 쓰면, 그 사이 퇴장 알림을 놓친 클라이언트는 새 NPC를 옛 NPC로 착각합니다.',
      c: ['NPC가 죽고 같은 개체 번호로 다시 등장', '퇴장 알림을 놓친 클라이언트는 “이미 아는 개체”라며 등장 알림을 무시하거나 죽은 상태를 그대로 둠', '한쪽 화면에만 NPC가 없거나 쓰러진 채로 보임, 다른 NPC의 모습으로 보이기도 함'],
      sym: ['invisible'], fx: ['loss'], who: ['oneclient', 'me'], when: ['random', 'event'],
      fix: '개체 번호에 세대 번호를 붙여 재사용을 구분, 이미 아는 번호의 등장 알림을 받으면 기존 개체를 지우고 새로 만들기.',
      more: '서버 쪽에서도 생깁니다. 시야 안 개체 목록을 번호로만 비교하면, 두 번의 시야 갱신 사이에 죽고 같은 번호로 다시 난 NPC를 “변화 없음”으로 보고 퇴장·등장 알림을 둘 다 보내지 않습니다. 시야 갱신 시점이 사람마다 어긋나 있으면 그 순간에 걸린 클라이언트만 겪습니다.',
      sim: 'npcmissing' },
    { id: 'pt-port-collision', t: '고정 UDP 포트 충돌', en: 'Two clients bound to the same local UDP port',
      s: '클라이언트가 정해진 로컬 포트를 쓰도록 만들어져 있으면, 같은 PC의 두 번째 클라이언트는 포트를 못 쓰거나 첫 번째와 패킷을 나눠 받습니다.',
      c: ['두 클라이언트가 같은 로컬 UDP 포트를 열려고 함(재사용 옵션으로 억지로 공유)', 'OS가 들어온 패킷을 한쪽 소켓에만 넘기거나 번갈아 넘김. 공유기와 서버도 두 클라이언트를 같은 주소로 봄', '한쪽은 월드 소식을 못 받아 NPC·다른 플레이어가 안 보이거나 접속이 끊김'],
      sym: ['invisible', 'disconnect', 'noconnect'], fx: ['loss'], who: ['oneclient'], when: ['login', 'always'],
      fix: '로컬 포트는 OS가 자동으로 고르게(0번 바인드), 세션 토큰으로 연결 구분.',
      sim: 'npcmissing' },
    { id: 'pt-session-key', t: 'IP·기기 기준 세션 구분 버그', en: 'Session keyed by IP or machine ID',
      s: '서버나 중간 서버가 연결을 IP나 기기 ID로 구분하면, 같은 PC(같은 공인 IP)의 두 클라이언트를 한 사람으로 착각합니다.',
      c: ['세션 표를 IP 또는 IP+기기 ID로 만듦', '두 번째 클라이언트의 정보가 첫 번째 세션에 덮어써지거나 섞임', '한쪽은 NPC가 안 보이고, 다른 쪽이 튕기거나 남의 정보를 받음'],
      sym: ['invisible', 'disconnect'], fx: ['loss'], who: ['oneclient', 'home', 'region'], when: ['login'],
      fix: '연결마다 고유 세션 토큰 사용. 같은 집(공유기 NAT 뒤)의 여러 사람과, 통신사가 IP 하나를 여러 가입자에게 나눠 주는 모바일 회선(CGNAT) 사용자도 같은 문제를 겪으므로 꼭 고쳐야 합니다.',
      sim: 'npcmissing' },
    { id: 'pt-multiclient', t: '멀티 클라이언트 제한', en: 'Multi-client restriction policy',
      s: '보안 모듈이나 서버 정책이 한 PC의 여러 클라이언트를 제한하면, 두 번째 클라이언트는 일부 정보만 받거나 기능이 막힙니다.',
      c: ['보안 모듈이 중복 실행을 감지, 또는 서버가 같은 기기의 추가 접속을 제한', '두 번째 클라이언트의 패킷을 줄이거나 일부 기능 차단', '한쪽만 NPC·상점이 안 보이거나 접속이 끊김'],
      sym: ['noconnect', 'invisible', 'disconnect'], fx: ['loss'], who: ['oneclient'], when: ['login'],
      fix: '제한할 거면 명확한 안내 메시지, QA용 예외 설정.',
      sim: 'npcmissing' },
    { id: 'pt-background', t: '뒤에 깔린 창의 처리 제한', en: 'Background window throttling',
      s: '활성 창이 아닌 클라이언트는 게임·엔진·OS가 프레임과 처리를 줄입니다. 받은 패킷을 제때 처리하지 못해 밀리거나 넘칩니다.',
      c: ['게임 옵션이나 그래픽 드라이버의 백그라운드 프레임 제한(예: 초당 5~10), 절전, 엔진의 백그라운드 정지 설정. OS도 앞에 있는 창에 CPU·GPU를 먼저 줌', '프레임마다 처리하는 패킷 수가 줄어 대기열이 쌓이고, 수신 버퍼가 넘치면 버려짐', '창을 앞으로 가져오면 몰아서 나타나거나, 일부 NPC가 끝내 안 보임'],
      sym: ['invisible', 'burst', 'disconnect'], fx: ['stall', 'loss'], who: ['oneclient'], when: ['idle', 'always'],
      num: 'Unity는 runInBackground 설정이 꺼져 있으면 창이 포커스를 잃는 순간 게임 루프가 멈춥니다. 수신을 그 루프에서만 하면 그동안 패킷이 전혀 처리되지 않습니다.',
      fix: '네트워크 수신은 별도 스레드에서 계속, 백그라운드에서도 최소 처리량 보장.',
      sim: 'npcmissing' },
    { id: 'pt-asset-lock', t: '캐시·에셋 파일 동시 접근 충돌', en: 'Shared cache / asset file lock conflicts',
      s: '두 클라이언트가 같은 캐시 폴더에 동시에 쓰거나 파일을 잠그면, 한쪽이 NPC 모델·텍스처를 못 불러옵니다.',
      c: ['두 클라이언트가 같은 설치 폴더의 캐시·패치 파일을 동시에 씀', '파일 잠금 실패나 반쯤 쓰인 파일을 읽어 로딩 실패', '이름표는 있는데 몸이 없거나 투명한 NPC'],
      sym: ['invisible'], fx: ['stall'], who: ['oneclient'], when: ['login', 'moving'],
      fix: '클라이언트별 캐시 폴더, 파일 잠금 실패 시 재시도, 로딩 실패 시 기본 모델이라도 표시.',
      sim: 'npcmissing' },
    { id: 'pt-vram', t: '메모리·VRAM 부족으로 스트리밍 실패', en: 'Memory / VRAM exhaustion',
      s: '클라이언트 두 개가 그래픽 메모리를 나눠 쓰면, 새로 필요한 모델·텍스처를 올릴 자리가 없어 일부가 안 그려집니다.',
      c: ['두 클라이언트가 VRAM·RAM을 나눠 씀. OS는 뒤에 깔린 창의 그래픽 메모리 몫을 먼저 줄이기도 함', '엔진이 새 모델·텍스처를 올리지 못하거나 계속 내렸다 올림', 'NPC가 늦게 나타나거나 흐릿하거나 안 보임, 끊김'],
      sym: ['invisible', 'stutter'], fx: ['stall'], who: ['oneclient'], when: ['moving', 'event'],
      fix: '메모리 예산에 맞춘 품질 자동 조절, 로딩 실패 시 대체 모델 표시.',
      sim: 'npcmissing' },
    { id: 'pt-display-option', t: '표시 옵션 차이', en: 'Different display settings',
      s: '표시 인원 제한, NPC 이름표·모델 숨김, 저사양 모드 같은 옵션이 두 클라이언트에서 다르면 보이는 것이 다릅니다.',
      c: ['한쪽 클라이언트만 “주변 캐릭터 표시 수 제한”이나 저사양 모드', '멀리 있거나 우선순위 낮은 NPC를 그리지 않음(정상)', '한쪽에만 NPC가 없음'],
      sym: ['invisible'], fx: ['stall'], who: ['oneclient', 'me'], when: ['event', 'always'],
      fix: '옵션으로 숨긴 개체임을 알 수 있게 표시, 설정 파일을 클라이언트별로 분리해 섞이지 않게.',
      sim: 'npcmissing' },
    { id: 'pt-version', t: '클라이언트 버전·데이터 불일치', en: 'Client version / data table mismatch',
      s: '두 번째 클라이언트가 다른 설치본이거나 패치가 덜 되었으면, 서버가 보낸 새 NPC 번호를 몰라 조용히 무시합니다.',
      c: ['다른 폴더의 설치본, 또는 패치 중 실행한 클라이언트', '모르는 NPC 번호·모델 번호를 받으면 건너뜀', '새로 추가된 NPC만 한쪽에 안 보임'],
      sym: ['invisible'], fx: ['loss'], who: ['oneclient'], when: ['login'],
      fix: '접속 시 데이터 버전 확인, 모르는 번호를 받으면 로그를 남기고 대체 표시.',
      sim: 'npcmissing' },
    { id: 'pt-priority', t: '연결별 전송 예산·우선순위', en: 'Per-connection bandwidth budget and priority',
      s: '서버가 연결마다 보낼 양에 한도를 두고 가까운 것부터 보내면, 한도가 낮게 잡힌 쪽은 멀리 있는 NPC를 늦게 받거나 못 받습니다.',
      c: ['사람 많은 곳에서 서버가 연결별 전송량 한도 안에서 중요도 순으로 전송', '대역폭 추정이 낮게 잡힌 연결(예: 뒤에 깔려 수신 확인이 늦은 쪽)은 뒤쪽 개체를 계속 미룸', '멀리 있는 NPC가 한쪽에서만 늦게 보이거나 안 보임'],
      sym: ['invisible', 'delay'], fx: ['lat'], who: ['oneclient', 'zone'], when: ['event'],
      fix: '밀린 개체의 우선순위를 시간이 지날수록 올리기(굶주림 방지), 최소 갱신 주기 보장.',
      sim: 'npcmissing' },
    { id: 'pt-clock-hold', t: '시계 추정 오차로 개체 보류', en: 'Clock estimate error holds or discards entities',
      s: '클라이언트가 추정한 서버 시각이 틀리면, 막 도착한 개체 정보를 “아직 미래”라며 보류하거나 “너무 옛날”이라며 버립니다.',
      c: ['한쪽 클라이언트의 서버 시각 추정이 크게 어긋남(로딩 중 측정, 절전 복귀)', '보간 기준 시각과 개체 정보 시각이 맞지 않음', '개체가 늦게 나타나거나 멈춘 채로 보임'],
      sym: ['invisible', 'stutter'], fx: ['lat'], who: ['oneclient'], when: ['idle', 'login'],
      fix: '시간 동기화를 주기적으로 다시 하고, 차이가 크면 즉시 재설정.',
      sim: 'npcmissing' },
  ]);
})();
