/* 원인 항목 4: 동기화 설계 (특정 층이 아니라 클라이언트·서버의 동기화 설계에서 생기는 렉) */
(function () {
  const add = (layer, list) => list.forEach(c => DATA.causes.push(Object.assign({ layer }, c)));

  add('sync', [
    { id: 'sy-request-response', t: '서버 응답 후에만 연출 (요청-응답 방식)', en: 'Request-response (no client-side feedback)',
      s: '버튼을 누르면 서버 답이 올 때까지 애니메이션도 소리도 없습니다. 핑이 곧 반응 속도가 됩니다.',
      c: ['스킬·이동·줍기를 서버 확인이 온 뒤에 재생', '누른 순간부터 왕복 시간 + 틱 대기만큼 아무 반응 없음', '핑 150ms면 모든 행동이 0.2초씩 굼뜸'],
      sym: ['delay'], fx: ['lat'], who: ['me'], when: ['always', 'action'],
      num: '반응 시간 ≈ 핑 + 틱 간격의 절반 + 한 프레임. 20틱·핑 150ms면 약 190ms.',
      own: ['cli', 'srv'],
      act: { game: '클라이언트: 애니메이션·소리·이펙트는 누르는 즉시 시작(선연출), 결과(데미지·보상)만 서버 확정 뒤 표시, 이동·기본 공격은 예측해 바로 반영, 서버의 위치 보정을 받으면 그 위치에서 아직 확인받지 못한 입력을 다시 적용. 서버: 받은 입력으로 이동을 직접 계산해 클라이언트가 예측한 위치와 차이가 기준을 넘을 때만 보정 값 보내기.' },
      more: '턴제, 카드, 방치형처럼 빠른 반응이 필요 없는 게임은 이 방식이 가장 단순하고 안전합니다. 문제는 실시간 조작이 있는 게임에서 이동이나 기본 공격까지 이렇게 만들었을 때입니다.',
      sim: 'syncmodels',
      ref: [
        { t: 'Latency Compensating Methods in Client/Server In-game Protocol Design and Optimization (Yahn W. Bernier, GDC 2001)', u: 'https://web.cs.wpi.edu/~claypool/courses/4513-B03/papers/games/bernier.pdf', p: 'Valve', n: '서버 결과만 기다리는 클라이언트는 지연이 500ms면 모든 행동이 500ms 뒤에야 보임. 클라이언트 예측과 서버 보정으로 해결' },
        { t: 'Using Gameplay Abilities in Unreal Engine', u: 'https://dev.epicgames.com/documentation/en-us/unreal-engine/using-gameplay-abilities-in-unreal-engine', p: 'Epic Games', n: 'Local Predicted는 누르는 즉시 실행하고 서버가 최종 결정, Server Initiated는 예측이 없어 쓰는 사람에게 지연이 보임' },
        { t: 'Understanding Networked Movement in the Character Movement Component for Unreal Engine', u: 'https://dev.epicgames.com/documentation/en-us/unreal-engine/understanding-networked-movement-in-the-character-movement-component-for-unreal-engine', p: 'Epic Games', n: '클라이언트가 이동을 예측·저장해 두고, 서버 오차가 허용치(MAXPOSITIONERRORSQUARED)를 넘을 때만 보정하며 보정 뒤 저장한 이동을 다시 적용' },
      ] },
    { id: 'sy-chatty', t: '순차 왕복이 많은 프로토콜 (chatty)', en: 'Chatty protocol / sequential round trips',
      s: '한 번의 조작에 서버 왕복이 여러 번 순서대로 필요하면, 핑이 그 횟수만큼 곱해집니다.',
      c: ['상점 열기 → 목록 요청 → 가격 확인 → 구매 → 인벤토리 갱신을 각각 따로 요청', '앞 요청의 답을 받아야 다음 요청을 보냄', '핑 150ms에서 한 번 사는 데 1초 가까이. 로딩이 유난히 김'],
      sym: ['delay', 'noconnect'], fx: ['lat'], who: ['feature', 'me'], when: ['action', 'login'],
      num: '걸리는 시간 ≈ 왕복 수 × (핑 + 서버 처리 + 틱 대기). 5번이면 핑 150ms에서 약 0.85~1초.',
      own: ['srv', 'cli'],
      act: { game: '서버: 여러 단계를 한 번에 묶어 요청·응답하도록 프로토콜 변경(예: 구매 응답에 갱신된 인벤토리를 함께 담기). 클라이언트: 필요한 데이터를 미리 받아 두기, 결과를 기다리지 않는 UI.' },
      sim: 'chain',
      ref: [
        { t: 'Chatty I/O antipattern', u: 'https://learn.microsoft.com/en-us/azure/architecture/antipatterns/chatty-io/', p: 'Microsoft Azure', n: '작은 I/O 요청이 많으면 누적 지연이 응답성을 크게 떨어뜨림. 요청을 더 크고 적게 묶으라는 권고' },
      ] },
    { id: 'sy-no-queue', t: '스킬 선입력 없음', en: 'No input/spell queue',
      s: '앞 스킬이 서버에서 끝났다는 확인을 받아야 다음 스킬을 누를 수 있으면, 연계마다 왕복 시간이 끼어듭니다.',
      c: ['다음 스킬 입력을 “이전 스킬 확정 후”에만 받음', '스킬 사이마다 핑만큼 빈 시간이 생김', '연계가 뚝뚝 끊기고, 핑이 높을수록 DPS가 줄어듦'],
      sym: ['delay', 'dropped'], fx: ['lat'], who: ['me', 'feature'], when: ['action'],
      num: '쿨다운 1초짜리 연계에서 핑 150ms면 스킬 사이마다 0.15초 이상 비어, 같은 시간에 쓰는 스킬이 13% 넘게 줄어듭니다.',
      own: ['cli', 'srv'],
      act: { game: '클라이언트: 쿨다운 끝나기 전 일정 시간(예: 0.3~0.4초) 안의 입력도 받아 바로 서버에 보내는 선입력 허용 시간. 서버: 조금 일찍 도착한 입력을 거절하지 말고 쿨다운이 끝나는 순간 실행.' },
      more: '예를 들어 월드 오브 워크래프트는 선입력 허용 시간을 두고 플레이어가 설정에서 조절할 수 있게 했습니다(기본값은 0.4초로 알려져 있습니다). 허용 시간이 왕복 시간보다 길면 연계 사이에 핑이 거의 끼지 않습니다.',
      sim: 'chain',
      ref: [
        { t: 'Latency and Player Actions in Online Games (Communications of the ACM, 2006)', u: 'https://web.cs.wpi.edu/~claypool/papers/precision-deadline/final.pdf', p: 'ACM', n: '에버퀘스트 2에서 지연이 커질수록 캐릭터가 주는 피해가 줄어 전투가 길어짐(0→500ms에서 약 2분 전투에 5초 추가)' },
      ] },
    { id: 'sy-short-window', t: '핑에 먹히는 짧은 판정 구간', en: 'Timing window too short for latency + reaction',
      s: '회피·패링·가드처럼 반응해야 하는 시간이 짧으면, 핑이 그 시간을 먹어 버려 피할 수 없는 공격이 생깁니다.',
      c: ['보스 공격 예고 0.5초, 패링 판정 0.2초처럼 짧은 판정 구간', '예고를 늦게 보고(내려오는 지연 + 보간), 내 입력도 늦게 도착(올라가는 지연 + 틱 대기)', '분명 피했는데 맞음, 패링이 씹힘'],
      sym: ['dropped', 'delay'], fx: ['lat'], who: ['me', 'feature'], when: ['action'],
      num: '핑 150ms, 보간 100ms면 예고가 내 화면에 뜨기까지 약 0.18초, 내 입력이 서버에 닿기까지 약 0.1초가 듭니다. 사람 반응 0.25초를 더하면 0.5초 예고는 거의 불가능.',
      own: ['srv', 'cli', 'sys'],
      act: { game: '서버: 공격 예고를 서버 시각으로 예약해 미리 보내기, 판정 구간을 핑만큼 늘리기(지연 보상). 클라이언트: 받은 예고를 예약된 서버 시각에 맞춰 재생.', infra: '유저가 많은 지역 가까이에 서버 배치(지역 서버)해 핑 자체를 줄이기.' },
      sim: 'windows',
      ref: [
        { t: 'Factors influencing the latency of simple reaction time (Frontiers in Human Neuroscience, 2015)', u: 'https://doi.org/10.3389/fnhum.2015.00131', p: 'Frontiers', n: '단순 반응 시간 평균 약 231ms(장비 지연 보정 시 213ms), 최근 대규모 연구들은 233~400ms' },
        { t: 'Latency and Player Actions in Online Games (Communications of the ACM, 2006)', u: 'https://web.cs.wpi.edu/~claypool/papers/precision-deadline/final.pdf', p: 'ACM', n: '정밀하고 마감 시간이 짧은 행동일수록 지연에 민감(1인칭 약 100ms, 3인칭 약 500ms, 전지적 시점 약 1,000ms에서 한계)' },
        { t: 'NetworkTime and ticks (Netcode for GameObjects 2.5)', u: 'https://docs.unity3d.com/Packages/com.unity.netcode.gameobjects@2.5/manual/advanced-topics/networktime-ticks.html', p: 'Unity', n: '서버 시각(ServerTime)에 맞춰 이벤트를 예약해 모든 클라이언트가 같은 순간에 재생하는 방법' },
      ] },
    { id: 'sy-no-lagcomp', t: '지연 보상 없는 판정', en: 'Server-now hit validation',
      s: '서버가 “지금 서버에서의 위치”로만 명중을 판정하면, 내가 본 화면과 판정이 어긋납니다.',
      c: ['내 화면의 상대는 약 0.2초 과거 위치(핑 150ms, 보간 100ms일 때)', '서버는 현재 위치로 판정해 내가 조준한 곳엔 이미 없음', '분명 맞혔는데 빗나감. 움직이는 대상을 앞질러 쏴야 함'],
      sym: ['dropped'], fx: ['lat'], who: ['me'], when: ['action'],
      own: ['srv', 'cli'],
      act: { game: '서버: 공격자가 보던 시점으로 되감아 판정(지연 보상), 또는 대상 지정 방식으로 바꾸기. 클라이언트: 공격할 때 자기가 보던 시점(보간 중인 서버 시각)을 함께 보내기.' },
      sim: 'windows',
      ref: [
        { t: 'Latency Compensating Methods in Client/Server In-game Protocol Design and Optimization (Yahn W. Bernier, GDC 2001)', u: 'https://web.cs.wpi.edu/~claypool/courses/4513-B03/papers/games/bernier.pdf', p: 'Valve', n: '지연 보상이 없으면 지연만큼 앞질러 쏴야 함. 서버가 지연과 보간 시간만큼 되감아 판정하는 지연 보상' },
        { t: 'Peeking into VALORANT\'s Netcode', u: 'https://www.riotgames.com/en/news/peeking-valorants-netcode', p: 'Riot Games', n: '서버가 사격 순간 플레이어가 보던 세계 상태로 되감아 명중 판정, 클라이언트가 보던 시뮬레이션 시각을 함께 보냄' },
        { t: 'Source SDK 2013: player_lagcompensation.cpp', u: 'https://raw.githubusercontent.com/ValveSoftware/source-sdk-2013/master/src/game/server/player_lagcompensation.cpp', p: 'Valve', n: 'Source 엔진의 되감는 시간 = 네트워크 지연 + 보간 시간' },
      ] },
    { id: 'sy-lagcomp-overreach', t: '지연 보상 과다', en: 'Excessive lag compensation',
      s: '공격자 기준으로 너무 멀리 되감아 주면, 맞는 쪽은 이미 숨었는데도 맞습니다.',
      c: ['핑 높은 공격자를 위해 서버가 크게 되감아 판정', '맞는 사람 화면에서는 이미 엄폐한 뒤', '“벽 뒤에서 맞았다”, 핑 높은 사람이 유리'],
      sym: ['dropped'], fx: ['lat'], who: ['me', 'region'], when: ['action'],
      own: ['srv'],
      act: { game: '되감기 상한 두기(예: 200~250ms), 그보다 핑이 높은 공격자는 되감아 주지 않고 스스로 앞질러 쏘게 두기.' },
      more: '되감기 판정은 “쏜 사람 우선”입니다. 회피기·방어기를 쓴 직후처럼 맞는 쪽의 행동이 중요한 순간에는 “맞는 쪽 우선”으로 예외를 두는 방식도 제안되어 있습니다.',
      sim: 'windows',
      ref: [
        { t: 'Peeking into VALORANT\'s Netcode', u: 'https://www.riotgames.com/en/news/peeking-valorants-netcode', p: 'Riot Games', n: '되감기에 한도가 없으면 지연 500ms인 사람이 엄폐 0.5초 뒤에도 맞힐 수 있어 한도를 둠' },
        { t: 'A Survey and Taxonomy of Latency Compensation Techniques for Network Computer Games (ACM Computing Surveys, 2022)', u: 'https://web.cs.wpi.edu/~claypool/papers/lag-taxonomy/paper.pdf', p: 'ACM', n: '“코너 뒤에서 맞음(shot around the corner)” 현상, 상용 FPS의 되감기 한도, 맞는 쪽이 안전하면 되감지 않는 기법 제안' },
        { t: 'Source SDK 2013: player_lagcompensation.cpp', u: 'https://raw.githubusercontent.com/ValveSoftware/source-sdk-2013/master/src/game/server/player_lagcompensation.cpp', p: 'Valve', n: 'Source 엔진의 되감기 상한 sv_maxunlag 기본 1초(최대 1초)' },
      ] },
    { id: 'sy-client-auth', t: '클라이언트 권위', en: 'Client-authoritative results',
      s: '각자 자기 결과를 결정하면 내 화면은 쾌적하지만, 다른 사람 화면과 결과가 어긋나고 해킹에 약합니다.',
      c: ['위치·명중을 클라이언트가 정하고 서버는 전달만', '두 사람이 서로 먼저 맞혔다고 주장, 서버는 검증 못 함', '상대가 순간이동·벽 통과, “나는 맞혔는데 안 맞음”'],
      sym: ['teleport', 'dropped'], fx: ['lat'], who: ['server'], when: ['always'],
      own: ['srv', 'cli'],
      act: { game: '서버: 중요한 결과(명중 등)는 직접 검증, 이동은 속도·거리 검사. 클라이언트: 서버가 거절·보정한 결과를 받으면 그 값으로 되돌리기.' },
      sim: 'syncmodels',
      ref: [
        { t: 'Latency Compensating Methods in Client/Server In-game Protocol Design and Optimization (Yahn W. Bernier, GDC 2001)', u: 'https://web.cs.wpi.edu/~claypool/courses/4513-B03/papers/games/bernier.pdf', p: 'Valve', n: '클라이언트가 결과를 보고하는 방식은 클라이언트를 믿을 수 있을 때만 가능. 해킹 우려로 권위 서버를 둠' },
        { t: 'Peeking into VALORANT\'s Netcode', u: 'https://www.riotgames.com/en/news/peeking-valorants-netcode', p: 'Riot Games', n: '서버 권위 모델: 서버는 클라이언트가 본 세계를 절대 믿지 않음' },
        { t: 'Distributed authority topologies (Netcode for GameObjects 2.5)', u: 'https://docs.unity3d.com/Packages/com.unity.netcode.gameobjects@2.5/manual/terms-concepts/distributed-authority.html', p: 'Unity', n: '권한을 클라이언트에 나누면 치팅이 쉬워지고 모든 개체를 다스리는 단일 시뮬레이션이 없어짐' },
      ] },
    { id: 'sy-lockstep', t: '락스텝에서 가장 느린 플레이어 대기', en: 'Lockstep waits for the slowest peer',
      s: '모두가 같은 턴을 함께 계산하는 구조에서는, 한 명의 입력이 늦으면 모두가 기다립니다.',
      c: ['턴마다 모든 플레이어의 입력이 모여야 계산 가능', '한 명의 입력이 지터·손실로 늦게 도착', '모든 사람이 동시에 멈칫, 심하면 “플레이어 기다리는 중” 창'],
      sym: ['freeze', 'stutter', 'delay'], fx: ['jit', 'loss', 'stall'], who: ['zone'], when: ['random'],
      num: '입력 지연을 “입력이 상대에게 닿는 시간 + 지터”보다 짧게 잡으면 멈춤이 잦아집니다. 닿는 시간은 서로 직접 주고받으면 핑의 절반, 중계 서버를 거치면 두 사람 핑을 더한 값의 절반쯤입니다.',
      own: ['srv', 'cli'],
      act: { game: '서버: 입력 지연을 핑에 맞춰 자동 조절, 늦는 사람만 잠깐 떨어뜨려 나머지는 기다리지 않고 진행. 클라이언트: 정해진 입력 지연 적용, 중계 서버 없는 P2P라면 입력 지연 조절과 늦는 사람 처리도 호스트 클라이언트가 맡기.' },
      sim: 'syncmodels',
      ref: [
        { t: 'Deterministic Lockstep', u: 'https://gafferongames.com/post/deterministic_lockstep/', p: 'Gaffer On Games', n: '프레임 n의 입력이 모두 와야 계산할 수 있어 늦으면 기다림. 지터를 흡수하는 재생 지연 버퍼가 작으면 멈칫함' },
        { t: '1500 Archers on a 28.8: Network Programming in Age of Empires and Beyond', u: 'https://www.gamedeveloper.com/programming/1500-archers-on-a-28-8-network-programming-in-age-of-empires-and-beyond', p: 'Game Developer', n: '명령을 두 턴 뒤에 실행하도록 예약하고, 가장 느린 컴퓨터와 핑에 맞춰 턴 길이를 조절(Speed Control)' },
        { t: 'A Survey and Taxonomy of Latency Compensation Techniques for Network Computer Games (ACM Computing Surveys, 2022)', u: 'https://web.cs.wpi.edu/~claypool/papers/lag-taxonomy/paper.pdf', p: 'ACM', n: '입력 지연(incoming delay)을 “A→서버 + 서버→B” 지연만큼 두어 모두가 같은 순간에 적용' },
      ] },
    { id: 'sy-rollback', t: '롤백 넷코드의 예측 실패', en: 'Rollback misprediction',
      s: '상대 입력을 예측해 먼저 보여 주다가 틀리면 되감아 다시 계산합니다. 핑이 클수록 되감는 폭이 커집니다.',
      c: ['상대가 입력을 바꿈(예측과 다름)', '실제 입력이 핑의 절반만큼 늦게 도착해 그만큼 되감아 재계산', '상대 동작이 몇 프레임 건너뛰거나 갑자기 바뀜'],
      sym: ['teleport'], fx: ['lat', 'jit'], who: ['me'], when: ['action', 'random'],
      num: '핑 100ms(한쪽 50ms)면 60fps에서 약 3프레임을 되감습니다. 입력 지연을 2프레임 두면 1프레임으로 줄어듭니다.',
      own: ['cli'],
      act: { game: '입력 지연을 1~3프레임 섞어 되감기 폭 줄이기, 되감기 상한 두기.' },
      sim: 'syncmodels',
      ref: [
        { t: 'GGPO Rollback Networking SDK', u: 'https://www.ggpo.net/', p: 'GGPO', n: '상대 입력을 예측해 먼저 진행하고, 실제 입력이 다르면 어긋난 시점부터 현재까지 다시 계산' },
        { t: '8 Frames in 16ms: Rollback Networking in \'Mortal Kombat\' and \'Injustice 2\'', u: 'https://www.gdcvault.com/play/1025471/8-Frames-in-16ms-Rollback', p: 'GDC', n: '롤백으로 락스텝의 로컬 입력 지연을 없애고, 16ms 안에 최대 8프레임을 되감아 재계산' },
      ] },
    { id: 'sy-no-timestamp', t: '타임스탬프 없는 도착 즉시 재생', en: 'Events played on arrival (no timestamps)',
      s: '서버 이벤트에 발생 시각을 붙이지 않고 받자마자 재생하면, 네트워크 지터 때문에 연출 타이밍이 그대로 들쭉날쭉해집니다.',
      c: ['“공격 시작”, “이펙트 재생” 이벤트를 도착 즉시 실행', '패킷마다 도착 시간이 달라 간격이 들쭉날쭉', '연속 공격 모션이 빨라졌다 느려졌다, 보스 패턴 타이밍이 매번 다름'],
      sym: ['stutter', 'burst'], fx: ['jit'], who: ['me'], when: ['always'],
      own: ['cli', 'srv'],
      act: { game: '클라이언트: 도착 즉시가 아니라 붙은 시각에 맞춰 재생(이벤트 예약·보간 버퍼). 서버: 이벤트에 발생 시각(서버 시각)을 붙여 보내기.' },
      sim: 'windows',
      ref: [
        { t: 'Latency Compensating Methods in Client/Server In-game Protocol Design and Optimization (Yahn W. Bernier, GDC 2001)', u: 'https://web.cs.wpi.edu/~claypool/courses/4513-B03/papers/games/bernier.pdf', p: 'Valve', n: '업데이트마다 서버 시각을 붙이고, 현재 시각에서 보간 시간(100ms)을 뺀 목표 시각의 위치로 그림' },
        { t: 'Snapshot Interpolation', u: 'https://gafferongames.com/post/snapshot_interpolation/', p: 'Gaffer On Games', n: '받은 스냅샷을 바로 그리면 지터 때문에 끊기고, 보간 버퍼에 잠깐 모았다 그리면 매끄러움' },
        { t: 'NetworkTime and ticks (Netcode for GameObjects 2.5)', u: 'https://docs.unity3d.com/Packages/com.unity.netcode.gameobjects@2.5/manual/advanced-topics/networktime-ticks.html', p: 'Unity', n: 'RPC에 보낸 시각을 담아 받는 쪽이 서버 시각에 맞춰 효과를 재생하는 예' },
      ] },
    { id: 'sy-double-tick', t: '이중 틱 대기', en: 'Double tick quantization',
      s: '요청을 다음 틱까지 모았다가 처리하고, 결과도 그다음 틱에 보내면 틱 간격이 두 번 더해집니다.',
      c: ['받은 요청은 다음 틱에서 처리', '처리 결과도 다음 전송 틱에 모아서 보냄', '회선 핑은 낮은데 반응이 틱 간격의 1.5배쯤 일정하게 늦음. 10틱 서버면 평균 0.15초, 최악 0.2초'],
      sym: ['delay'], fx: ['lat'], who: ['server'], when: ['always'],
      num: '10틱 서버는 한 틱이 100ms라 틱 대기만으로 평균 150ms, 최악 200ms가 더해집니다. 한 번만 기다리면 평균 50ms입니다.',
      own: ['srv'],
      act: { game: '처리한 틱에 바로 응답 보내기, 틱레이트 올리기, 중요한 응답은 즉시 전송.' },
      ref: [
        { t: 'Peeking into VALORANT\'s Netcode', u: 'https://www.riotgames.com/en/news/peeking-valorants-netcode', p: 'Riot Games', n: '도착한 입력은 틱 경계까지 최대 한 틱을 기다리고, 적용·전송에 다시 한 프레임이 듦. 틱레이트가 높을수록 줄어듦' },
        { t: 'VALORANT\'s 128-Tick Servers', u: 'https://www.riotgames.com/en/news/valorants-128-tick-servers', p: 'Riot Games', n: '지연의 일부는 네트워크, 일부는 서버 틱레이트에서 옴' },
        { t: 'NetworkTime and ticks (Netcode for GameObjects 2.5)', u: 'https://docs.unity3d.com/Packages/com.unity.netcode.gameobjects@2.5/manual/advanced-topics/networktime-ticks.html', p: 'Unity', n: 'NetworkVariable 변경은 즉시 보내지 않고 네트워크 틱마다 모아 전송' },
      ] },
    { id: 'sy-strict-check', t: '너무 엄격한 서버 검증', en: 'Over-strict server validation',
      s: '이동 속도·쿨타임·사거리를 서버가 너무 엄격하게 검사하면, 지터로 몰려 온 정상 입력까지 거절합니다.',
      c: ['“한 틱에 이동 가능한 거리”, “쿨타임 0ms 허용” 같은 엄격한 기준', '지터로 명령 두 개가 한 틱에 몰려 도착하면 규칙 위반으로 판정', '고무줄, 쿨타임 됐는데 스킬 거절'],
      sym: ['rubber', 'dropped'], fx: ['jit'], who: ['me'], when: ['random', 'moving'],
      own: ['srv'],
      act: { game: '누적 허용량(토큰 버킷) 방식으로 검사, 핑·지터만큼 여유 두기.' },
      sim: 'lab',
      ref: [
        { t: 'Source SDK 2013: player.cpp', u: 'https://raw.githubusercontent.com/ValveSoftware/source-sdk-2013/master/src/game/server/player.cpp', p: 'Valve', n: '틱마다 쌓이는 명령 처리 예산(최대 sv_maxusrcmdprocessticks 24틱)으로 몰려 온 명령을 허용. 더 엄격하게 막으면 정상 유저도 끊겼다는 개발 주석' },
        { t: 'RFC 2697: A Single Rate Three Color Marker', u: 'https://www.rfc-editor.org/rfc/rfc2697', p: 'IETF', n: '토큰 버킷: 평균 속도(CIR)와 한 번에 허용하는 버스트 크기(CBS)로 판정' },
      ] },
    { id: 'sy-host', t: '호스트(방장) 구조', en: 'Listen server / host advantage',
      s: '한 플레이어의 PC가 서버 역할을 하면, 그 사람의 회선과 PC 성능이 모두의 체감을 정합니다.',
      c: ['방장 PC가 서버 역할(P2P, 리슨 서버)', '방장 회선이나 PC가 느리면 모두에게 전파, 방장은 핑 0', '방장만 유리, 방장이 나가면 모두 멈춤·접속 끊김'],
      sym: ['stutter', 'freeze', 'disconnect'], fx: ['lat', 'stall'], who: ['zone'], when: ['random'],
      own: ['srv', 'cli', 'sys'],
      act: { game: '서버: 판정을 맡는 전용 서버로 전환, 그 전까지는 매칭 때 회선·PC가 좋은 사람을 방장으로 고르기. 클라이언트: 호스트 이전(마이그레이션) 지원, 매칭 때 다른 참가자와의 핑·업로드 속도·PC 성능을 측정해 보내기.', infra: '전용 서버용 서버 장비·인스턴스 확보, 유저가 많은 지역 가까이에 배치.' },
      ref: [
        { t: 'Networking Overview for Unreal Engine', u: 'https://dev.epicgames.com/documentation/en-us/unreal-engine/networking-overview-for-unreal-engine', p: 'Epic Games', n: '리슨 서버의 호스트는 다른 클라이언트보다 유리하고, 서버와 렌더링을 함께 맡아 부하가 큼' },
        { t: 'Distributed authority topologies (Netcode for GameObjects 2.5)', u: 'https://docs.unity3d.com/Packages/com.unity.netcode.gameobjects@2.5/manual/terms-concepts/distributed-authority.html', p: 'Unity', n: '세션 소유자가 나가면 남은 클라이언트 중에서 새 소유자를 자동 선출' },
        { t: 'A Survey and Taxonomy of Latency Compensation Techniques for Network Computer Games (ACM Computing Surveys, 2022)', u: 'https://web.cs.wpi.edu/~claypool/papers/lag-taxonomy/paper.pdf', p: 'ACM', n: 'P2P 게임도 호스트가 서버 역할을 겸하는 클라이언트-서버 구조로 볼 수 있음' },
      ] },
    { id: 'sy-optimistic-reject', t: '선연출 뒤 서버 거절', en: 'Client-side feedback rejected by server',
      s: '내 화면에서 먼저 보여 준 타격·스킬을 서버가 나중에 인정하지 않으면, 분명히 본 결과가 없던 일이 됩니다.',
      c: ['타격 이펙트·스킬 모션을 서버 확인 전에 먼저 재생(선연출)', '서버가 사거리·대상 위치·쿨다운·자원을 다시 따져 보고 거절', '피가 튀었는데 데미지 없음, 스킬 모션만 나가고 효과 없음, 쿨다운만 돎'],
      sym: ['dropped', 'rubber'], fx: ['lat'], who: ['me', 'feature'], when: ['action'],
      num: '거절 응답은 누른 뒤 핑 + 틱 대기만큼 늦게 옵니다. 핑 150ms면 약 0.2초 동안 “맞힌 줄” 압니다.',
      own: ['cli', 'srv'],
      act: { game: '클라이언트: 데미지 숫자·사망·보상처럼 확정이 필요한 부분만 서버 결과로 표시, 흔한 거절 사유는 먼저 검사, 거절되면 쿨다운·자원을 되돌리고 이유를 보여 주기. 서버: 사거리·대상 위치 검사에 핑만큼 여유 두기, 거절 응답에 사유를 담아 보내기, 스킬별 거절 비율을 지표로 모으기.' },
      more: '선연출은 핑을 가리는 가장 좋은 방법입니다. 다만 클라이언트와 서버가 판단에 쓰는 정보(상대 위치, 남은 자원)가 다를수록 거절이 잦아집니다. 스킬별 거절 비율을 지표로 모아 두면 판정이 어긋나는 곳을 찾기 쉽습니다.',
      sim: 'syncmodels',
      ref: [
        { t: 'Using Gameplay Abilities in Unreal Engine', u: 'https://dev.epicgames.com/documentation/en-us/unreal-engine/using-gameplay-abilities-in-unreal-engine', p: 'Epic Games', n: 'Local Predicted 능력은 클라이언트에서 즉시 실행하지만 서버가 최종 결정하고 결과를 뒤집을 수 있음' },
        { t: 'Latency Compensating Methods in Client/Server In-game Protocol Design and Optimization (Yahn W. Bernier, GDC 2001)', u: 'https://web.cs.wpi.edu/~claypool/courses/4513-B03/papers/games/bernier.pdf', p: 'Valve', n: '무기 발사를 클라이언트에서 예측해 효과를 먼저 재생하고, 서버 결과로 예측 오차를 바로잡음' },
      ] },
    { id: 'sy-path-mismatch', t: '명령 동기화의 경로 계산 불일치', en: 'Command sync with divergent pathing',
      s: '“여기로 가라”만 주고받고 경로는 양쪽이 각자 계산하면, 계산이 조금만 달라도 캐릭터나 몬스터가 다른 경로로 가다가 제자리로 끌려옵니다.',
      c: ['클릭 이동·몬스터 추적에서 목적지만 보내고 경로는 클라이언트가 따로 계산', '지형 데이터 차이, 다른 캐릭터와의 충돌, 계산 순서 차이로 서버와 다른 경로로 이동', '몬스터가 벽을 뚫고 가다 휙 옮겨짐, 클릭한 캐릭터가 미끄러지듯 방향을 틂'],
      sym: ['teleport', 'rubber'], fx: ['lat'], who: ['zone', 'me'], when: ['moving'],
      own: ['srv', 'cli'],
      act: { game: '서버: 경로의 중간 지점(웨이포인트)까지 함께 보내기, 주기적으로 위치 맞추기. 클라이언트: 어긋남은 부드럽게 수렴, 서버와 같은 지형 데이터 사용.' },
      more: '클릭 이동·탭 타겟 게임이 핑에 둔감한 이유가 이 방식입니다. 대신 양쪽 결과가 같다는 보장이 없어서, 가끔 위치를 맞춰 주는 장치가 꼭 필요합니다.',
      ref: [
        { t: 'Deterministic Lockstep', u: 'https://gafferongames.com/post/deterministic_lockstep/', p: 'Gaffer On Games', n: '같은 기계에서 결정적이어도 컴파일러·OS·CPU가 다르면 부동소수점 결과가 달라질 수 있음' },
        { t: 'State Synchronization', u: 'https://gafferongames.com/post/state_synchronization/', p: 'Gaffer On Games', n: '입력과 함께 상태를 보내면 완벽한 결정성 없이도 양쪽을 맞출 수 있음' },
        { t: 'Peeking into VALORANT\'s Netcode', u: 'https://www.riotgames.com/en/news/peeking-valorants-netcode', p: 'Riot Games', n: '패킷 손실이나 두 캐릭터가 같은 자리로 가려 할 때 서버·클라이언트 시뮬레이션이 어긋나 보정이 필요' },
      ] },
    { id: 'sy-low-send-rate', t: '낮은 스냅샷 전송률', en: 'Low snapshot / update rate',
      s: '서버가 위치 업데이트(스냅샷)를 1초에 몇 번만 보내면 보간 버퍼를 그만큼 길게 잡아야 해서, 다른 캐릭터를 더 먼 과거로 보게 됩니다.',
      c: ['전송량을 아끼려고 위치 업데이트를 1초에 5~10번만 보냄', '매끄럽게 그리려면 버퍼를 패킷 간격의 2배(200~400ms)로 잡아야 하고, 짧게 잡으면 패킷 하나만 놓쳐도 멈춤', '상대의 방향 전환이 늦게 보이고 판정과 어긋남. 버퍼가 짧으면 뚝뚝 끊기고 손실 때 순간이동'],
      sym: ['stutter', 'teleport', 'dropped'], fx: ['lat', 'loss'], who: ['server'], when: ['always'],
      num: '1초에 10번이면 패킷 간격 100ms, 버퍼 200ms. 핑 150ms의 한쪽 지연 75ms를 더하면 상대를 약 0.3초 과거로 봅니다.',
      own: ['srv', 'cli'],
      act: { game: '서버: 가깝거나 전투 중인 대상은 자주, 먼 대상은 드물게 보내기, 바뀐 부분만 보내(델타 압축) 한 번의 크기를 줄이고 주기를 올리기. 클라이언트: 보간 버퍼 길이를 패킷 간격에 맞춰 자동 조절.' },
      sim: 'lab',
      ref: [
        { t: 'Latency Compensating Methods in Client/Server In-game Protocol Design and Optimization (Yahn W. Bernier, GDC 2001)', u: 'https://web.cs.wpi.edu/~claypool/courses/4513-B03/papers/games/bernier.pdf', p: 'Valve', n: '초당 10회 업데이트면 보간 200ms로 한 번의 누락을 견딤. Half-Life 기본은 초당 20회·보간 100ms' },
        { t: 'Snapshot Interpolation', u: 'https://gafferongames.com/post/snapshot_interpolation/', p: 'Gaffer On Games', n: '초당 10개면 두 개 연속 손실까지 견디려 350ms 지연이 필요, 초당 30개면 150ms로 줄어듦' },
        { t: 'State Synchronization', u: 'https://gafferongames.com/post/state_synchronization/', p: 'Gaffer On Games', n: '우선순위 누적으로 중요한 개체를 더 자주 보내고, 대역폭 한도 안에서 나머지를 돌아가며 전송' },
      ] },
  ]);
})();
