/* 원인 항목 2: 데이터센터 장비, 서버 NIC, 서버 OS, 소켓과 프로토콜 */
(function () {
  const add = (layer, list) => list.forEach(c => DATA.causes.push(Object.assign({ layer }, c)));

  /* ---------------- 5. 데이터센터 네트워크 장비 ---------------- */
  add('dc-net', [
    { id: 'dc-firewall', t: '방화벽 세션 테이블 포화', en: 'Firewall session table exhaustion',
      s: '방화벽은 통과시킨 모든 연결을 세션 테이블에 기록해 추적합니다. 테이블이 다 차면 새 연결을 받을 수 없습니다.',
      c: ['접속 폭주나 공격으로 세션 수가 한도에 도달', '새 연결을 기록할 빈 항목이 없어 거부', '새로 들어오려는 사람은 접속 불가·무한 로딩, 일부 기존 연결도 접속 끊김'],
      sym: ['noconnect', 'disconnect'], fx: ['loss'], who: ['server'], when: ['login', 'event'],
      own: ['net', 'srv', 'cli'],
      act: { game: '서버: 로그인 대기열 시스템으로 한꺼번에 몰리는 접속 조절, 짧은 연결을 반복하지 않게 연결 재사용, 하트비트가 끊긴 연결은 먼저 정리(죽은 연결이 세션 테이블을 오래 차지하지 않게). 클라이언트: 가장 짧은 유휴 타임아웃의 절반 이하 간격으로 하트비트 보내기, 끊기면 자동 재접속하되 재시도 간격을 늘려 가며 무작위로 분산(한꺼번에 다시 몰리지 않게).', infra: '세션 테이블 크기 늘리기, 짧게 끝난 연결 빨리 정리(종료된 세션의 타임아웃 단축), 유휴 세션 타임아웃을 줄일 때는 그 값을 게임팀에 알려 하트비트 간격 맞추기, 공격 차단, 세션 수 사용률 경보.' },
      sim: 'rush',
      sig: { k: 'ceiling', g: '방화벽 세션 수, 새 연결 실패 수' },
      chk: {
        look: '방화벽 장비의 동시 세션 수를 세션 한도와 함께 그래프로 보고, 장비 로그에서 세션을 만들지 못해 버린 기록을 찾음. 리눅스 방화벽이면 nf_conntrack_count를 nf_conntrack_max와 비교하고 dmesg의 “nf_conntrack: table full, dropping packet”을, AWS 인스턴스면 ethtool -S의 conntrack_allowance_exceeded를 봄',
        yes: '세션 수가 한도에서 평평해진 시각부터 새 연결 실패가 늘고, 세션 생성 실패 기록이나 폐기 카운터가 함께 늘어남',
        no: '세션 수가 한도에 한참 못 미치는데 접속이 안 되면 “접속 대기열(backlog) 넘침”이나 로그인 서버 쪽. 유휴 연결만 끊기면 “클라우드 보안 그룹의 연결 추적 만료”',
        by: 'ops',
      },
      ref: [
        { t: 'Netfilter Conntrack Sysfs variables', u: 'https://docs.kernel.org/networking/nf_conntrack-sysctl.html', p: 'Linux kernel', n: '연결 추적 테이블의 최대 항목 수(nf_conntrack_max), 종료 중인 연결의 유지 시간(TIME_WAIT·FIN_WAIT 기본 120초), 성립된 TCP 기본 5일, 현재 항목 수(nf_conntrack_count)' },
        { t: 'Amazon EC2 security group connection tracking', u: 'https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/security-group-connection-tracking.html', p: 'AWS', n: '인스턴스당 추적할 수 있는 연결 수를 넘으면 새 연결의 패킷을 버림, 유휴 연결이 추적 테이블을 고갈시킬 수 있음' },
        { t: 'Infrastructure layer attacks', u: 'https://docs.aws.amazon.com/whitepapers/latest/aws-best-practices-ddos-resiliency/infrastructure-layer-attacks.html', p: 'AWS', n: 'SYN 플러드 같은 공격은 서버·방화벽·로드밸런서의 자원을 묶어 둠' },
        { t: 'net/netfilter/nf_conntrack_core.c (Linux v6.12)', u: 'https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/net/netfilter/nf_conntrack_core.c?h=v6.12', p: 'Linux kernel', n: '연결 추적 테이블이 가득 차면 “nf_conntrack: table full, dropping packet”을 남기고 새 연결의 패킷을 버림' },
        { t: 'Monitor network performance for ENA settings on your EC2 instance', u: 'https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/monitoring-network-performance-ena.html', p: 'AWS', n: 'conntrack_allowance_exceeded: 인스턴스의 연결 추적 한도를 넘어 버린 패킷 수, ethtool -S로 확인' },
      ] },
    { id: 'dc-ddos', t: 'DDoS 방어 경유·오탐', en: 'DDoS scrubbing latency, false positives',
      s: '공격을 막으려고 트래픽을 스크러빙 센터로 돌리면 경로가 길어지고, 정상 사용자를 공격으로 오인해 막기도 합니다.',
      c: ['공격 감지 후(또는 상시) 들어오는 트래픽을 스크러빙 센터로 우회', '경로가 길어지고, 일부 정상 패킷을 공격으로 판정', '전체 핑 상승, 특정 지역·통신사만 접속 불가'],
      sym: ['delay', 'noconnect', 'teleport'], fx: ['lat', 'loss'], who: ['server', 'region'], when: ['event', 'random'],
      num: '스크러빙 거점이 같은 나라에 있으면 수 ms, 다른 나라 거점을 거치면 30~100ms 넘게 더해집니다. 보통 들어오는 쪽만 돌아가고 서버의 응답은 곧바로 나갑니다. 걸러진 트래픽을 터널로 되돌려 받으면 한 번에 보낼 수 있는 크기(MTU)도 줄어, 큰 패킷만 사라지는 문제로 이어지기도 합니다.',
      own: ['net', 'srv'],
      act: { game: '게임 트래픽 패턴(포트, 패킷 크기, 초당 패킷 수)을 정리해 인프라팀에 공유, UDP 패킷은 1,200바이트 이하로 유지.', infra: '게임 트래픽 패턴에 맞춘 방어 규칙, 지역별 스크러빙 거점, 터널 구간에서 TCP 패킷 크기 줄이기(MSS 조정), 지역·통신사별 접속 실패율로 오탐 확인.' },
      sig: { k: 'step', g: 'RTT(핑), 지역·통신사별 접속 실패율' },
      chk: {
        look: '방어 장비·서비스의 우회(스크러빙) 시작·종료 기록과 차단 로그를 RTT 그래프, 지역·통신사별 접속 실패율과 같은 시간축에 놓고 봄. 문제 지역에서 mtr·traceroute로 경로에 스크러빙 거점이 끼었는지 확인',
        yes: '우회가 켜진 시각에 RTT가 한 단계 올라 머물다가 꺼지면 돌아옴. 또는 차단 로그에 정상 유저 주소가 있고 그 지역·통신사만 접속 실패율이 오름',
        no: '우회·차단 기록이 없는 시각에 RTT가 오르면 “우회 라우팅”이나 “BGP 경로 변경·수렴”. 큰 패킷만 사라지면 “MTU 불일치 (큰 패킷만 사라짐)”',
        by: 'ops',
      },
      ref: [
        { t: 'Maximum transmission unit and maximum segment size', u: 'https://developers.cloudflare.com/magic-transit/reference/mtu-mss/', p: 'Cloudflare', n: '들어오는 트래픽은 걸러진 뒤 GRE 터널(MTU 1,476)로 전달, 나가는 응답은 인터넷으로 바로(DSR), TCP MSS 1,436 이하로 제한 권장, 안 맞추면 큰 패킷이 버려지거나 단편화됨' },
        { t: 'Azure network round-trip latency statistics', u: 'https://learn.microsoft.com/en-us/azure/networking/azure-network-latency', p: 'Microsoft Azure', n: '거점 위치별 왕복 지연 규모: 서울–부산 지역 8ms, 서울–도쿄 30ms, 서울–싱가포르 68ms' },
      ] },
    { id: 'dc-lb-idle', t: '로드밸런서 유휴 타임아웃', en: 'Load balancer idle timeout',
      s: '로드밸런서는 유휴 연결을 일정 시간 뒤 지웁니다. 게임은 연결이 유지된 것으로 간주하고 있다가 접속이 끊깁니다.',
      c: ['플레이어가 한동안 아무 패킷도 안 보냄(대화창, 자리 비움)', '로드밸런서가 유휴 연결을 정리(흔한 기본값 60~350초)', '다시 움직이는 순간 접속 끊김'],
      sym: ['disconnect'], fx: ['loss'], who: ['me', 'server'], when: ['idle'],
      num: 'AWS ALB는 60초, NLB는 TCP 350초·UDP 120초, Azure Load Balancer는 TCP 4분이 기본값입니다. ALB와 NLB의 TCP 값은 바꿀 수 있지만 NLB의 UDP 120초는 바꿀 수 없습니다. ALB는 시간이 되면 서버 쪽 연결도 닫지만, NLB는 조용히 지워 서버가 모르는 채로 남기 쉽습니다.',
      own: ['net', 'cli', 'srv'],
      act: { game: '클라이언트: 가장 짧은 유휴 타임아웃의 절반 이하 간격으로 하트비트 보내기(ALB 60초 뒤라면 30초 이하), 끊기면 자동 재접속. 서버: 하트비트에 응답하고, 일정 시간 못 받으면 연결을 먼저 정리, 세션 토큰으로 이어 받기.', infra: '경로에 있는 로드밸런서의 유휴 타임아웃 값을 확인해 게임팀에 공유하고, 필요하면 늘리기.' },
      sim: 'timeouts',
      sig: { k: 'drop', g: '끊김 수, 끊기기 전 유휴 시간' },
      chk: {
        look: '경로에 있는 로드밸런서의 유휴 타임아웃 설정값을 확인하고, 끊긴 연결마다 마지막 패킷 뒤 끊기기까지 걸린 시간을 모아 봄. AWS NLB면 CloudWatch의 TCP_ELB_Reset_Count(로드밸런서가 보낸 RST 수)도 봄',
        yes: '끊긴 연결의 유휴 시간이 설정값(ALB 60초, NLB TCP 350초 등) 바로 뒤에 몰리고, 그 시간보다 오래 가만히 있다 움직이면 재현됨. NLB는 그 시각에 TCP_ELB_Reset_Count가 늘어남',
        no: '유휴 시간과 상관없이 끊기면 이 원인이 아님. 로드밸런서 없이 바로 붙는 서버에서 350초 근처로 몰리면 “클라우드 보안 그룹의 연결 추적 만료”, 유저 집 공유기 쪽이면 “NAT 매핑 만료”',
        by: 'ops',
      },
      ref: [
        { t: 'Edit attributes for your Application Load Balancer', u: 'https://docs.aws.amazon.com/elasticloadbalancing/latest/application/edit-load-balancer-attributes.html', p: 'AWS', n: 'ALB 유휴 타임아웃 기본 60초(1~4,000초), 클라이언트·대상 연결이 이 시간 동안 조용하면 로드밸런서가 연결을 닫음' },
        { t: 'Network Load Balancers', u: 'https://docs.aws.amazon.com/elasticloadbalancing/latest/network/network-load-balancers.html', p: 'AWS', n: 'NLB TCP 유휴 기본 350초(60~6,000초), 지나면 추적만 멈추고 그 뒤 데이터가 오면 RST, UDP 흐름 120초는 변경 불가' },
        { t: 'Configure load balancer TCP reset and idle timeout', u: 'https://learn.microsoft.com/en-us/azure/load-balancer/load-balancer-tcp-idle-timeout', p: 'Microsoft Azure', n: 'Azure Load Balancer 유휴 타임아웃 기본 4분(4~100분), 넘으면 세션 유지 보장 없음, TCP 리셋은 선택 설정' },
        { t: 'CloudWatch metrics for your Network Load Balancer', u: 'https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-cloudwatch-metrics.html', p: 'AWS', n: 'TCP_ELB_Reset_Count: 로드밸런서가 만들어 보낸 RST 패킷 수' },
      ] },
    { id: 'dc-cloud-conntrack', t: '클라우드 보안 그룹의 연결 추적 만료', en: 'Cloud security group connection tracking timeout',
      s: '클라우드 서버에 붙은 방화벽(보안 그룹)도 연결을 추적하고, 유휴 연결의 추적 항목은 정해진 시간 뒤 만료됩니다. 로드밸런서 없이 바로 붙는 서버도 가만히 있던 플레이어의 접속이 끊길 수 있습니다.',
      c: ['보안 그룹이 게임 연결을 추적하는 설정(특정 주소만 허용, 나가는 규칙 제한, NLB 경유 등)', '한동안 유휴 상태인 연결의 추적 항목이 만료되고, 그 뒤 오는 패킷을 보안 그룹이 조용히 버림', '자리 비움 뒤 다시 움직이면 반응이 없다가 접속 끊김. 서버 프로그램은 한참 모름'],
      sym: ['disconnect'], fx: ['loss'], who: ['me', 'server'], when: ['idle'],
      num: 'AWS 기준 Nitro v6 인스턴스 유형은 유휴 TCP 연결의 추적 항목을 기본 350초 뒤 지웁니다(그 밖의 유형은 5일). UDP는 요청과 응답이 여러 번 오간 흐름(스트림) 180초, 한 방향으로만 갔거나 요청·응답이 한 번뿐인 흐름 30초가 기본입니다.',
      own: ['sys', 'cli', 'srv'],
      act: { game: '클라이언트: 가장 짧은 유휴 타임아웃의 절반 이하 간격으로 하트비트 보내기(TCP 350초라면 175초 이하, UDP 스트림 180초라면 90초 이하), 끊기면 자동 재접속. 서버: 하트비트에 응답하고, 일정 시간 못 받으면 연결을 먼저 정리, 세션 토큰으로 이어 받기.', infra: '인스턴스의 연결 추적 시간(TcpEstablishedTimeout) 확인·필요하면 늘리기(UDP는 180초가 최대라 못 늘림), 추적이 생기지 않는 보안 그룹 구성 검토(게임 포트는 모든 주소 허용, 나가는 규칙은 전체 허용. NLB를 거치는 연결은 그래도 추적됨), 새 세대 인스턴스로 옮길 때 유휴 시험.' },
      sim: 'timeouts',
      sig: { k: 'drop', g: '끊김 수, 끊기기 전 유휴 시간' },
      chk: {
        look: '인스턴스의 연결 추적 시간 설정과 보안 그룹 규칙(추적이 생기는 구성인지)을 확인하고, 끊긴 연결의 유휴 시간을 모아 봄. 끊긴 직후 서버에서 ss -tnoi로 그 연결이 ESTABLISHED로 남아 재전송 타이머(timer:(on,…))가 돌고 backoff가 커지는지 봄',
        yes: '끊긴 연결의 유휴 시간이 TCP 350초, UDP 스트림 180초, UDP 한 방향 30초 바로 뒤에 몰리고, 서버 쪽 소켓은 끊김을 감지하지 못한 채 ESTABLISHED로 남음(서버가 보낼 데이터가 있으면 재전송만 반복)',
        no: '보안 그룹이 추적하지 않는 구성(게임 포트를 모든 주소에 허용, 나가는 규칙 전체 허용, NLB를 거치지 않음)이면 이 원인이 아님. NLB를 거치면 “로드밸런서 유휴 타임아웃”과 값을 비교',
        by: 'ops',
      },
      ref: [
        { t: 'Amazon EC2 security group connection tracking', u: 'https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/security-group-connection-tracking.html', p: 'AWS', n: 'TCP 유휴 추적 기본 350초(Nitro v6, 그 외 43만 2,000초=5일), UDP 한 방향 30초·스트림 180초(최대 180), 모든 주소 허용 규칙이면 추적 안 함, NLB 경유 연결은 항상 추적' },
        { t: 'Update the TCP idle timeout for your Network Load Balancer listener', u: 'https://docs.aws.amazon.com/elasticloadbalancing/latest/network/update-idle-timeout.html', p: 'AWS', n: 'NLB 유휴 타임아웃이 대상 인스턴스의 연결 추적 시간보다 길면 인스턴스 쪽이 먼저 조용히 연결 상태를 버림' },
        { t: 'ss(8) — Linux manual page', u: 'https://man7.org/linux/man-pages/man8/ss.8.html', p: 'iproute2', n: '-o의 timer:(on,…)은 재전송 타이머, -i의 backoff는 재전송 대기를 두 배씩 늘린 횟수' },
      ] },
    { id: 'dc-nat-gateway', t: '클라우드 NAT 게이트웨이 연결·포트 한도', en: 'Cloud NAT gateway connection / port limits',
      s: '사설 서브넷의 서버가 외부(플랫폼 인증·결제·외부 API)로 나가는 연결은 NAT 게이트웨이가 주소와 포트를 바꿔 내보냅니다. 같은 목적지로 가는 동시 연결이 게이트웨이의 포트 한도를 넘으면 새 연결이 실패합니다.',
      c: ['서버들이 플랫폼 인증·결제처럼 같은 외부 주소로 짧은 연결을 많이 열거나 연결을 오래 열어 둠', 'NAT 게이트웨이가 그 목적지에 쓸 원본 포트를 더 할당하지 못해 새 연결이 실패함', '게임 안은 멀쩡한데 로그인·결제·보상 지급처럼 외부를 부르는 기능만 실패하거나 늦어짐(접속 불가·무한 로딩, 씹힘·롤백)'],
      sym: ['noconnect', 'dropped'], fx: ['loss', 'lat'], who: ['feature', 'server'], when: ['login', 'peak', 'event'],
      num: 'AWS NAT 게이트웨이는 IP 주소 하나로 같은 목적지(IP·포트·프로토콜)에 동시 연결 5만 5천 개까지 열 수 있고, IP를 8개까지 붙여 늘립니다. 350초 동안 조용한 연결은 지우고, 그 뒤 이 연결로 보내는 패킷에는 RST를 돌려줍니다. Azure NAT Gateway는 공인 IP 하나당 SNAT 포트 64,512개(IP 최대 16개)입니다. Google Cloud NAT는 NAT IP 하나당 64,512포트를 VM마다 나눠 주는데 VM당 최소 포트 기본값이 64개(정적 할당)라, 기본 설정이면 VM 하나가 같은 목적지로 여는 동시 연결이 64개 안팎으로 묶입니다.',
      more: '서버 한 대의 임시 포트가 바닥나는 “서버 간 연결의 임시 포트 고갈”과 달리, 이 한도는 NAT 게이트웨이에 걸리고 게이트웨이 뒤의 서버들이 함께 씁니다(Google Cloud NAT는 VM마다 나눠 줌). 서버 쪽 TIME_WAIT와 임시 포트 범위는 여유가 있는데도 외부 호출만 실패하면 이쪽입니다. 닫힌 연결의 포트도 곧바로 같은 목적지에 다시 쓰이지 않아(Azure는 쿨다운, Google Cloud는 TIME_WAIT 동안 사용 불가) 짧은 연결을 반복할수록 한도에 빨리 닿습니다.',
      own: ['net', 'srv'],
      act: { game: '서버: 외부 API는 연결을 재사용(HTTP keep-alive, 커넥션 풀)하고 요청마다 새 연결을 열지 않기, 풀에 남겨 둔 유휴 연결은 NAT 유휴 타임아웃(AWS 350초)보다 짧은 간격으로 keepalive를 보내거나 먼저 닫기, 실패하면 재시도 간격을 늘려 가며 무작위로 분산, 외부 호출별 실패율·지연 기록.', infra: 'NAT 게이트웨이에 IP 주소 추가, 가용 영역·서브넷별로 게이트웨이 나누기, 포트 할당 실패 지표(AWS ErrorPortAllocation, Azure SNAT Connection Count의 Failed, Google Cloud dropped_sent_packets_count의 OUT_OF_RESOURCES) 경보, Google Cloud NAT는 VM당 최소 포트 수를 늘리거나 동적 포트 할당 사용.' },
      sig: { k: 'ceiling', g: 'NAT 게이트웨이 동시 연결 수, 포트 할당 실패 수' },
      chk: {
        look: 'CloudWatch의 NAT 게이트웨이 지표 ErrorPortAllocation·ActiveConnectionCount·PacketsDropCount(Azure는 SNAT Connection Count를 Failed 상태로 거른 값과 Dropped Packets, Google Cloud는 dropped_sent_packets_count의 reason OUT_OF_RESOURCES)를 게임 서버의 외부 호출 실패 시각과 나란히 봄',
        yes: '외부 호출이 실패한 시각에 ErrorPortAllocation(또는 Failed·OUT_OF_RESOURCES)이 0보다 커지고, 같은 목적지로 가는 동시 연결 수가 한도 근처에서 더 오르지 못함',
        no: '포트 할당 실패가 0인데 게임 서버의 connect가 EADDRNOTAVAIL로 실패하고 TIME_WAIT가 임시 포트 범위에 가까우면 “서버 간 연결의 임시 포트 고갈”. 연결은 되는데 응답만 느리면 “외부 서비스 의존”',
        by: 'ops',
      },
      ref: [
        { t: 'NAT gateway basics', u: 'https://docs.aws.amazon.com/vpc/latest/userguide/nat-gateway-basics.html', p: 'AWS', n: 'IPv4 주소 하나당 같은 목적지(목적지 IP·포트·프로토콜)로 동시 연결 5만 5천 개, IP를 8개까지 붙여 늘림, 대역폭 5→100Gbps·초당 100만→1,000만 패킷을 넘으면 폐기' },
        { t: 'NAT gateway metrics and dimensions', u: 'https://docs.aws.amazon.com/vpc/latest/userguide/metrics-dimensions-nat-gateway.html', p: 'AWS', n: 'ErrorPortAllocation: 원본 포트를 할당하지 못한 횟수(0보다 크면 동시 연결 과다), ActiveConnectionCount, IdleTimeoutCount(350초 유휴로 정리된 연결), PacketsDropCount' },
        { t: 'Troubleshoot NAT gateways', u: 'https://docs.aws.amazon.com/vpc/latest/userguide/nat-gateway-troubleshooting.html', p: 'AWS', n: '350초 유휴면 연결이 만료되고 이어서 보내면 RST를 돌려줌, 350초보다 짧은 keepalive 권장, 연결 한도에 닿으면 가용 영역별 게이트웨이·IP 추가·연결 수 줄이기' },
        { t: 'Source Network Address Translation (SNAT) with Azure NAT Gateway', u: 'https://learn.microsoft.com/en-us/azure/nat-gateway/nat-gateway-snat', p: 'Microsoft Azure', n: '공인 IP 하나당 SNAT 포트 64,512개(IP 최대 16개), 같은 목적지로 가는 연결마다 다른 포트가 필요, 닫힌 포트는 같은 목적지에 다시 쓰기 전 쿨다운' },
        { t: 'Metrics and alerts for Azure NAT Gateway', u: 'https://learn.microsoft.com/en-us/azure/nat-gateway/nat-metrics', p: 'Microsoft Azure', n: 'SNAT Connection Count를 Failed 상태로 거른 값이 0보다 크면 SNAT 포트 고갈 가능성, Dropped Packets' },
        { t: 'IP addresses and ports', u: 'https://cloud.google.com/nat/docs/ports-and-addresses', p: 'Google Cloud', n: 'NAT IP 하나당 TCP·UDP 각각 64,512포트, VM당 최소 포트 기본 64(정적 할당)·32(동적 할당), VM에 예약된 포트 수가 같은 목적지로의 동시 연결 수를 제한, 닫힌 연결은 TIME_WAIT 동안 못 씀' },
        { t: 'Logs and metrics', u: 'https://cloud.google.com/nat/docs/monitoring', p: 'Google Cloud', n: 'dropped_sent_packets_count의 reason OUT_OF_RESOURCES: NAT IP나 포트가 모자라 버린 패킷' },
      ] },
    { id: 'dc-lb-imbalance', t: '로드밸런서 쏠림·헬스체크 오판', en: 'LB imbalance, bad health checks',
      s: '연결이 한 서버에만 몰리거나, 이미 죽은 서버로 계속 사람을 보냅니다.',
      c: ['분배 규칙이 맞지 않거나 헬스체크가 실제 상태를 못 봄', '한 서버만 과부하, 또는 죽은 서버로 접속 시도', '일부 채널·일부 사람만 슬로우모션, 접속 불가·무한 로딩'],
      sym: ['slowmo', 'noconnect'], fx: ['stall', 'loss'], who: ['zone'], when: ['login', 'event'],
      own: ['net', 'srv'],
      act: { game: '로드밸런서의 확인 요청에 실제 게임 상태(틱 진행, DB 연결)를 보고 답하는 헬스체크 구현, 서버 부하 값을 함께 알려 주기.', infra: '헬스체크를 실제 게임 응답을 확인하는 방식으로 바꾸기, 서버 부하 기반 분배, 서버별 연결 수 차이 모니터링.' },
      sig: { k: 'outlier', g: '서버별 연결 수·CPU 사용률' },
      chk: {
        look: '로드밸런서 뒤 서버마다 연결 수(ss -s)와 CPU 사용률을 한 그래프에 겹쳐 보고, 로드밸런서의 대상 헬스 상태(AWS는 CloudWatch의 HealthyHostCount·UnHealthyHostCount)를 게임 서버의 실제 상태와 비교',
        yes: '서버 한두 대만 연결 수·CPU가 다른 서버보다 크게 높거나, 틱이 멈춘 서버가 헬스 상태 “정상”으로 남아 새 접속을 계속 받음',
        no: '서버별 연결 수가 고른데 한 채널만 느리면 그 채널 안의 부하(“단일 스레드 지역 과부하(핫스팟)”)',
        by: 'ops',
      },
      ref: [
        { t: 'Load Balancing in the Datacenter', u: 'https://sre.google/sre-book/load-balancing-datacenter/', p: 'Google', n: '단순 라운드 로빈은 작업 간 CPU 사용량이 최대 2배까지 벌어짐, 백엔드가 응답·헬스체크에 부하를 실어 보내는 가중 분배, 요청을 그만 받겠다는 lame duck 상태' },
        { t: 'Health checks for Network Load Balancer target groups', u: 'https://docs.aws.amazon.com/elasticloadbalancing/latest/network/target-group-health-checks.html', p: 'AWS', n: '헬스체크 기본 30초 간격·2회 실패로 제외, UDP 서비스는 TCP·HTTP 헬스체크로 확인하므로 실제 서비스 상태를 반영하도록 구성 권장' },
        { t: 'CloudWatch metrics for your Network Load Balancer', u: 'https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-cloudwatch-metrics.html', p: 'AWS', n: 'HealthyHostCount·UnHealthyHostCount: 정상·비정상으로 판정된 대상 수' },
      ] },
    { id: 'dc-microburst', t: '스위치 마이크로버스트', en: 'Switch microburst drops',
      s: '여러 서버가 같은 순간 수천 명에게 패킷을 한꺼번에 보내면, 그 트래픽이 모이는 스위치 포트의 작은 버퍼가 1ms도 안 돼 넘칩니다.',
      c: ['월드 보스 등장·대규모 스킬, 또는 여러 서버의 틱이 같은 순간에 맞물려 한꺼번에 발송', '여러 포트가 한 포트로 모이거나 빠른 포트에서 느린 포트로 넘어가는 곳의 버퍼(포트당 수백 KB~수 MB)가 순간적으로 가득', '일부 패킷 폐기, 많은 사람이 동시에 순간이동·스킬 씹힘'],
      sym: ['teleport', 'dropped'], fx: ['loss'], who: ['zone'], when: ['event'],
      num: '10Gbps 포트로 1ms 동안 내보낼 수 있는 양은 약 1.25MB. 두 포트의 트래픽이 한 포트로 동시에 몰리면 1ms마다 1.25MB씩 쌓입니다. 1초 평균 사용률이 10%여도 1ms 단위로는 넘칠 수 있습니다.',
      own: ['srv', 'net', 'sys'],
      act: { game: '전송을 틱 안에 고르게 나누기(페이싱), 서버마다 틱 시작 시점을 조금씩 어긋나게.', infra: '네트워크: 버퍼 큰 스위치, 트래픽 분산(서버를 여러 스위치·포트에 나눠 배치), 스위치 포트별 폐기 카운터 감시. 서버 장비·OS: 서버 전체 송신 속도 상한(리눅스 tc 셰이퍼).' },
      sig: { k: 'load', g: '스위치 포트 출력 폐기 수' },
      chk: {
        look: '서버가 붙은 스위치 포트와 그 트래픽이 모이는 포트의 출력 폐기 카운터(ifOutDiscards, 장비에 따라 output drops)를 가능한 짧은 간격으로 모아 보스 등장·대규모 전투 시각과 맞춰 봄. 1초·1분 평균 사용률 그래프만으로는 보이지 않음',
        yes: '평균 사용률은 낮은데 사람이 한곳에 몰리는 순간마다 출력 폐기가 늘고, 그때 여러 유저가 동시에 순간이동·스킬 씹힘을 제보함',
        no: '폐기가 평균 사용률이 높은 시간대에 꾸준히 늘면 “데이터센터 회선 포화”. 입력 오류(CRC)가 늘면 “불량 케이블·포트 오류”',
        by: 'ops',
      },
      ref: [
        { t: 'High-Resolution Measurement of Data Center Microbursts (IMC 2017)', u: 'https://conferences.sigcomm.org/imc/2017/papers/imc17-final60.pdf', p: 'ACM', n: '데이터센터 버스트의 70% 이상이 수십 µs 안에 끝남, 평균 사용률이 약 9%인 포트에서도 버스트로 패킷 폐기' },
        { t: 'Data Center TCP (DCTCP) (SIGCOMM 2010)', u: 'https://conferences.sigcomm.org/sigcomm/2010/papers/sigcomm/p63.pdf', p: 'ACM', n: '범용 스위치는 버퍼가 얕음(48포트가 4MB 공유, 한 포트가 약 700KB까지 사용), 여러 흐름이 짧은 순간 한 포트로 몰리면 손실' },
        { t: 'RFC 2863: The Interfaces Group MIB', u: 'https://www.rfc-editor.org/rfc/rfc2863', p: 'IETF', n: 'ifOutDiscards: 오류가 없는데도 버퍼 공간 확보 등의 이유로 내보내지 못하고 버린 패킷 수' },
      ] },
    { id: 'dc-uplink', t: '데이터센터 회선 포화', en: 'Uplink saturation',
      s: '패치 배포·로그 전송·백업이 게임과 같은 회선을 쓰면 회선이 꽉 찹니다.',
      c: ['대용량 전송이 같은 회선을 점유', '회선 대기열과 손실 증가', '서버 전체 핑 상승과 순간이동'],
      sym: ['delay', 'teleport'], fx: ['lat', 'loss'], who: ['server'], when: ['periodic', 'event'],
      own: ['net', 'sys'],
      act: { infra: '네트워크: 게임 트래픽 우선 처리(QoS), 대용량 전송 회선 분리, 회선 사용률 경보. 서버 장비·OS: 백업·로그 전송·배포에 속도 제한을 걸고 한산한 시간에 실행.' },
      sig: { k: 'ceiling', g: '회선 사용률, RTT(핑)' },
      chk: {
        look: '데이터센터 회선(업링크) 인터페이스의 사용률(SNMP ifHCInOctets·ifHCOutOctets로 계산)과 출력 폐기(ifOutDiscards)를 백업·배포·로그 전송 일정과 같은 시간축에 놓고 봄',
        yes: '회선 사용률이 대역폭 한도에 붙어 평평해진 시각에 서버 전체 RTT와 폐기가 오르고, 그 시각이 대용량 전송 작업과 겹침',
        no: '분 단위 사용률이 한도에 한참 못 미치는데 폐기가 있으면 “스위치 마이크로버스트”',
        by: 'ops',
      },
      ref: [
        { t: 'RFC 4594: Configuration Guidelines for DiffServ Service Classes', u: 'https://www.rfc-editor.org/rfc/rfc4594', p: 'IETF', n: '게임 같은 실시간 대화형 트래픽과 백업 같은 대용량 전송을 서로 다른 서비스 등급으로 나눠 처리' },
        { t: 'RFC 7567: IETF Recommendations Regarding Active Queue Management', u: 'https://www.rfc-editor.org/rfc/rfc7567', p: 'IETF', n: '장비로 들어오는 양이 내보내는 속도를 넘으면 대기열이 쌓이고, 과도한 대기열이 지연의 주요 원인' },
        { t: 'RFC 2863: The Interfaces Group MIB', u: 'https://www.rfc-editor.org/rfc/rfc2863', p: 'IETF', n: 'ifHCInOctets·ifHCOutOctets: 인터페이스로 받고 보낸 바이트 수(64비트), ifOutDiscards: 내보내지 못하고 버린 패킷 수' },
      ] },
    { id: 'dc-failover', t: '네트워크 장비 장애 전환(페일오버)', en: 'Network device failover',
      s: '라우터·방화벽 한 대가 고장 나 예비 장비로 전환(페일오버)되는 몇 초 동안 모두가 멈춥니다.',
      c: ['장비 고장 또는 점검으로 예비 장비로 전환', '전환에 수 초, 세션 정보가 동기화되지 않으면 연결 초기화', '서버의 모든 유저가 동시에 멈춤, 대량 접속 끊김'],
      sym: ['freeze', 'disconnect'], fx: ['loss'], who: ['server'], when: ['random'],
      num: '장비가 고장을 바로 감지하면 1~3초 안팎. 빠른 고장 감지(BFD) 없이 BGP 기본 타이머에만 맡기면 인접 장비가 감지하기까지 90~180초 동안 경로가 끊길 수 있습니다.',
      own: ['net', 'srv', 'cli'],
      act: { game: '서버: 짧은 끊김(수 초)을 견디는 타임아웃, 끊겨도 재접속하면 세션 토큰으로 세션을 이어 받게. 클라이언트: 끊기면 자동 재접속(한꺼번에 몰리지 않게 재시도 간격을 무작위로 분산).', infra: '연결 상태를 공유하는 이중화, BFD로 고장을 1초 안에 감지, 전환 시험을 정기적으로.' },
      sig: { k: 'drop', g: '접속 수, 서버 전체 송수신량' },
      chk: {
        look: '라우터·방화벽의 이벤트 로그(VRRP 역할 변경, BFD·BGP 세션 다운, 장애 전환 기록)와 같은 시각의 서버 전체 접속 수·송수신량을 봄',
        yes: '장비 로그의 전환 시각에 그 장비 뒤 모든 서버의 트래픽이 몇 초간 0이 되거나 접속 수가 동시에 떨어짐',
        no: '한 서버의 접속만 떨어지면 “서버 크래시”나 “NIC 드라이버·펌웨어 문제”. 장비 로그가 깨끗하고 멈춘 서버가 클라우드 가상 머신 한 대면 “클라우드 호스트 점검·라이브 마이그레이션”',
        by: 'ops',
      },
      ref: [
        { t: 'RFC 5880: Bidirectional Forwarding Detection (BFD)', u: 'https://www.rfc-editor.org/rfc/rfc5880', p: 'IETF', n: '라우팅 프로토콜의 Hello 방식은 고장 감지에 1초 이상 걸려, 더 짧은 시간에 감지하려고 만든 BFD' },
        { t: 'RFC 7938: Use of BGP for Routing in Large-Scale Data Centers', u: 'https://www.rfc-editor.org/rfc/rfc7938', p: 'IETF', n: 'BGP keepalive에만 기대면 수렴이 느리고, 링크 다운을 바로 받아 세션을 끊으면 ms 단위로 감지해 재수렴' },
        { t: 'RFC 5798: Virtual Router Redundancy Protocol (VRRP) Version 3 for IPv4 and IPv6', u: 'https://www.rfc-editor.org/rfc/rfc5798', p: 'IETF', n: 'VRRP 광고 기본 1초, 예비 장비는 광고가 약 3배 간격 넘게 끊기면 역할을 넘겨받음(기본 설정으로 3초 남짓)' },
      ] },
    { id: 'dc-bad-cable', t: '불량 케이블·포트 오류', en: 'Bad cable / optics (CRC errors)',
      s: '광모듈이나 케이블이 불량이면 그 경로를 지나는 패킷이 일정 비율로 깨집니다.',
      c: ['광모듈·케이블 불량으로 비트 오류', '깨진 패킷은 장비가 조용히 폐기', '그 경로를 쓰는 일부 서버·사용자만 꾸준한 손실로 순간이동·고무줄'],
      sym: ['teleport', 'rubber'], fx: ['loss'], who: ['zone'], when: ['always'],
      own: ['net'],
      act: { infra: '포트 오류(CRC) 카운터 모니터링·경보, 광모듈·케이블 등 부품 교체, 교체 전까지 문제 링크를 빼서 우회.' },
      sig: { k: 'outlier', g: '포트별 CRC 오류 수, 서버·경로별 손실률' },
      chk: {
        look: '링크 양쪽의 CRC 카운터를 봄. 스위치는 포트의 FCS 오류(dot3StatsFCSErrors)·입력 오류(ifInErrors), 서버는 ip -s -s link의 RX errors 중 crc(커널 통계 rx_crc_errors)',
        yes: '한 포트의 CRC 오류가 트래픽 양·시간대와 상관없이 꾸준히 늘고, 그 포트를 지나는 서버·유저만 손실이 있음',
        no: 'CRC 오류가 없고 출력 폐기만 늘면 혼잡(“스위치 마이크로버스트”, “데이터센터 회선 포화”)',
        by: 'ops',
      },
      ref: [
        { t: 'Understanding and Mitigating Packet Corruption in Data Center Networks (SIGCOMM 2017)', u: 'https://www.microsoft.com/en-us/research/wp-content/uploads/2017/06/CorrOpt_SIGCOMM2017.pdf', p: 'ACM', n: '데이터센터 35만 링크 분석: 깨짐 원인은 불량 광모듈·손상된 광섬유·더러운 커넥터, 깨짐률은 사용량과 무관하게 꾸준, 경로 수를 지키며 문제 링크를 빼고 수리' },
        { t: 'RFC 3635: Definitions of Managed Objects for the Ethernet-like Interface Types', u: 'https://www.rfc-editor.org/rfc/rfc3635', p: 'IETF', n: '프레임 검사(FCS) 실패 카운터(dot3StatsFCSErrors), 이 오류는 입력 오류(ifInErrors)로 합산' },
        { t: 'Interface statistics', u: 'https://docs.kernel.org/networking/statistics.html', p: 'Linux kernel', n: 'rx_crc_errors: CRC 오류로 받은 패킷 수, ip -s -s link로 오류 종류별 확인' },
      ] },
    { id: 'dc-mtu', t: 'MTU 불일치 (큰 패킷만 사라짐)', en: 'MTU black hole',
      s: '중간 구간의 MTU(한 번에 보낼 수 있는 크기)가 줄었는데 크기 초과 알림이 막히면, 큰 패킷만 계속 사라집니다.',
      c: ['터널·VPN 구간에서 MTU가 줄어듦', '크기 초과 알림(ICMP)이 방화벽에 막혀 보내는 쪽이 모름', '인벤토리·캐릭터 목록처럼 큰 화면을 열 때만 멈췄다가 접속 끊김'],
      sym: ['freeze', 'disconnect', 'noconnect'], fx: ['loss'], who: ['region', 'me'], when: ['action', 'login'],
      num: '보통 1500바이트, 터널을 지나면 1400 안팎으로 줄어듭니다.',
      own: ['net', 'sys', 'srv'],
      act: { game: '서버 쪽에서 직접 낮추려면 소켓의 최대 세그먼트 크기(TCP_MAXSEG) 설정(게임 코드에서 메시지를 잘게 쪼개는 것만으로는 안 막힘), UDP 패킷은 1,200바이트 이하로 유지.', infra: '네트워크: 터널 구간에서 TCP 패킷 크기 줄이기(MSS 조정), 방화벽·클라우드 네트워크 ACL에서 크기 초과 알림(ICMP) 허용. 서버 장비·OS: 서버 방화벽·클라우드 보안 그룹에서도 크기 초과 알림(ICMP) 허용, 서버 커널의 MTU 탐색(tcp_mtu_probing=1) 켜기(몇 초 멈춘 뒤에야 작동하는 마지막 안전망).' },
      sig: { k: 'outlier', g: '지역·통신사별 접속 끊김, 큰 응답 실패' },
      chk: {
        look: '문제 유저 PC에서 서버로 쪼개지 말라는 표시(DF)를 켠 핑을 크기를 바꿔 가며 보냄. 윈도우는 ping /f /l 1472 서버주소, 리눅스는 ping -M do -s 1472 서버주소(1,472는 MTU 1,500에서 IP 헤더 20바이트와 ICMP 헤더 8바이트를 뺀 값). 크기를 줄여 가며 통과하는 최대 크기를 찾고, 서버 쪽 보안 그룹·방화벽이 ICMP 크기 초과 알림(Fragmentation Needed)을 허용하는지 확인',
        yes: '작은 핑은 가는데 1,472바이트 DF 핑은 실패하고(응답 없음 또는 단편화가 필요하다는 오류), 통과하는 최대 크기가 1,400 안팎으로 작음. 같은 지역 유저들이 큰 화면을 열 때만 멈춤',
        no: '1,472바이트 DF 핑도 잘 가면 경로 MTU 문제가 아님. 작은 핑도 안 가면 ICMP 자체가 막힌 것이라 이 방법으로는 판단할 수 없음',
        by: 'user',
      },
      ref: [
        { t: 'RFC 2923: TCP Problems with Path MTU Discovery', u: 'https://www.rfc-editor.org/rfc/rfc2923', p: 'IETF', n: '방화벽이 ICMP(Fragmentation Needed)를 막으면 경로 MTU 탐색이 실패해 큰 패킷만 계속 사라짐(블랙홀), 핑·작은 통신은 되어 진단이 어려움' },
        { t: 'Maximum transmission unit and maximum segment size', u: 'https://developers.cloudflare.com/magic-transit/reference/mtu-mss/', p: 'Cloudflare', n: '인터넷 경로 MTU 1,500, GRE 터널을 지나면 1,476, TCP MSS는 1,436 이하로 제한 권장' },
        { t: 'IP Sysctl', u: 'https://docs.kernel.org/networking/ip-sysctl.html', p: 'Linux kernel', n: 'tcp_mtu_probing=1은 평소 꺼져 있다가 ICMP 블랙홀을 감지했을 때 TCP 경로 MTU 탐색을 켬' },
        { t: 'ping(8) — Linux manual page', u: 'https://man7.org/linux/man-pages/man8/ping.8.html', p: 'iputils', n: '-M do는 DF 표시를 켜고 경로 MTU보다 큰 패킷을 거부, -s로 데이터 크기 지정(기본 56바이트에 ICMP 헤더 8바이트)' },
        { t: 'ping', u: 'https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/ping', p: 'Microsoft', n: '/f는 DF 표시를 켜서 경로 MTU 문제를 찾는 데 쓰고, /l로 데이터 크기 지정' },
      ] },
  ]);

  /* ---------------- 6. 서버 NIC ---------------- */
  add('nic', [
    { id: 'nic-irq', t: 'NIC 인터럽트 단일 코어 집중', en: 'Single-queue NIC / no RSS',
      s: 'NIC가 패킷 도착 인터럽트를 CPU 코어 하나에만 보내면 그 코어가 병목이 됩니다.',
      c: ['수신 큐가 하나이거나 여러 코어로 분산하는 RSS가 꺼져 있음', '코어 하나가 100%가 되어 패킷을 제때 못 꺼냄', '사람이 몰릴 때 서버 전체에서 손실과 지연(순간이동·입력 지연)'],
      sym: ['teleport', 'rubber', 'delay'], fx: ['loss', 'lat'], who: ['server'], when: ['event'],
      num: '코어 하나가 커널을 거쳐 처리할 수 있는 양은 패킷 크기와 설정에 따라 대략 초당 수십만 패킷. 코어별 사용률에서 수신 처리 비중(mpstat의 %soft)이 한 코어에만 몰려 있으면 이 경우입니다.',
      own: ['sys'],
      act: { infra: 'RSS(NIC가 분산)·RPS(커널이 분산) 설정, 인터럽트를 여러 코어에 분산, UDP는 포트까지 보고 큐를 나누게 설정(ethtool -N의 rx-flow-hash udp4 sdfn), 인터럽트 처리 코어와 게임 틱 스레드 코어 분리, 코어별 %soft 감시.' },
      more: '큐가 여러 개여도 게이트웨이·프록시처럼 몇 안 되는 주소에서 트래픽이 대부분 오면 한 큐로 몰립니다. UDP는 NIC 기본 설정이 주소만 보고 큐를 나누는 경우가 있어, 포트까지 보도록 바꿔야 고르게 퍼집니다.',
      sim: 'nic',
      sig: { k: 'ceiling', g: '코어별 %soft, 초당 수신 패킷 수' },
      chk: {
        look: 'mpstat -P ALL 1로 코어별 %soft(소프트웨어 인터럽트 처리 비율)를 보고, /proc/interrupts로 NIC 큐별 인터럽트가 어느 코어로 가는지, ethtool -l로 큐 수, ethtool -S로 큐별 패킷 수(이름은 드라이버마다 다름)를 확인',
        yes: '한 코어만 %soft가 100% 가까이에 붙어 있고 나머지는 한가하며, 인터럽트와 패킷이 큐 하나에 몰림. 그때부터 초당 수신 패킷 수가 더 오르지 못함',
        no: '%soft가 여러 코어에 고르게 퍼져 있으면 이 원인이 아님. CPU는 한가한데 손실이 있으면 “클라우드 PPS 한도 초과”나 “링 버퍼 부족”',
        by: 'ops',
      },
      ref: [
        { t: 'Scaling in the Linux Networking Stack', u: 'https://docs.kernel.org/networking/scaling.html', p: 'Linux kernel', n: 'RSS(NIC가 여러 수신 큐로 분산)·RPS(커널이 분산), 큐마다 인터럽트를 따로 두고 여러 코어에 나누는 설정, 수신 인터럽트 처리가 병목이면 RSS 권장' },
        { t: 'How to receive a million packets per second', u: 'https://blog.cloudflare.com/how-to-receive-a-million-packets/', p: 'Cloudflare', n: '수신 큐 하나가 코어 하나로만 가면 그 코어가 초당 약 35만~43만 패킷에서 막힌 측정, NIC가 UDP를 IP 주소로만 해시해 한 큐로 몰린 사례' },
        { t: 'ethtool(8) — Linux manual page', u: 'https://man7.org/linux/man-pages/man8/ethtool.8.html', p: 'ethtool', n: 'ethtool -N rx-flow-hash udp4로 UDP 해시에 포트(f·n)까지 넣는 옵션' },
        { t: 'mpstat(1) — Linux manual page', u: 'https://man7.org/linux/man-pages/man1/mpstat.1.html', p: 'sysstat', n: '%soft: CPU가 소프트웨어 인터럽트 처리에 쓴 시간 비율, -P ALL로 코어별' },
      ] },
    { id: 'nic-ring', t: '링 버퍼 부족', en: 'RX ring buffer overflow',
      s: 'NIC가 패킷을 잠시 담아 두는 링 버퍼가 작으면, 순간적으로 몰릴 때 버퍼가 넘쳐 버려집니다.',
      c: ['링 버퍼가 기본값(드라이버마다 슬롯 256~2,048개)으로 작음', '버스트 때 CPU가 꺼내기 전에 버퍼가 넘침', '버스트 순간에만 손실(순간이동·스킬 씹힘). 게임 서버 로그에는 흔적이 없음'],
      sym: ['teleport', 'dropped'], fx: ['loss'], who: ['server'], when: ['event'],
      num: '초당 100만 패킷이 몰리면 슬롯 1,024개는 약 1ms 만에 찹니다. 그 사이 CPU가 한 번만 늦게 와도 넘칩니다. 대부분의 NIC는 수천 개까지 늘릴 수 있습니다.',
      own: ['sys'],
      act: { infra: '링 버퍼 크게(ethtool -G), 폐기(drop) 카운터 감시(ethtool -S의 rx_missed_errors 등, 이름은 드라이버마다 다름).' },
      sim: 'nic',
      sig: { k: 'random', g: 'NIC 수신 폐기 카운터' },
      chk: {
        look: 'ethtool -S의 수신 폐기 카운터(rx_missed_errors, rx_fifo_errors 등, 이름은 드라이버마다 다름)와 ip -s -s link의 missed를 짧은 간격으로 모으고, ethtool -g로 현재 링 크기와 최대값을 확인',
        yes: '버스트 순간에 폐기 카운터가 늘고, 현재 링 크기가 최대값보다 한참 작음. 링을 키우면 폐기가 줄어듦',
        no: '폐기 카운터가 그대로인데 손실이 있으면 커널 다음 단계(“커널 소켓 버퍼 부족”)나 네트워크 구간. 한 코어의 %soft가 100%면 “NIC 인터럽트 단일 코어 집중”',
        by: 'ops',
      },
      ref: [
        { t: 'Linux Base Driver for Intel(R) Ethernet Network Connection (e1000)', u: 'https://docs.kernel.org/networking/device_drivers/ethernet/intel/e1000.html', p: 'Linux kernel', n: 'e1000 수신 디스크립터(링 슬롯) 기본 256개, 4,096개까지 늘릴 수 있음' },
        { t: 'drivers/net/ethernet/intel/ice/ice.h (Linux v6.12)', u: 'https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/net/ethernet/intel/ice/ice.h?h=v6.12', p: 'Linux kernel', n: 'ice 드라이버 수신 디스크립터 기본 2,048개, 최대 8,160개' },
        { t: 'Interface statistics', u: 'https://docs.kernel.org/networking/statistics.html', p: 'Linux kernel', n: '버퍼가 모자라 장치가 버린 패킷은 rx_missed_errors로 집계, 드라이버별 통계는 ethtool -S로 확인' },
        { t: 'ethtool(8) — Linux manual page', u: 'https://man7.org/linux/man-pages/man8/ethtool.8.html', p: 'ethtool', n: '-g로 링 크기(현재값·최대값) 확인, -G로 변경, -S로 드라이버별 통계' },
      ] },
    { id: 'nic-coalesce', t: '인터럽트 병합 과다', en: 'Interrupt coalescing',
      s: 'CPU 부담을 줄이려고 패킷을 모았다 한 번에 알리면, 모으는 시간만큼 늦어집니다.',
      c: ['NIC가 일정 시간·개수만큼 모았다가 알림', '모으는 동안 패킷이 대기', '미세한 지연 증가. 보통은 작지만 과하면 ms 단위'],
      sym: ['delay'], fx: ['lat'], who: ['server'], when: ['always'],
      num: '보통 수십~수백 µs. 게임에는 대개 무시할 수준이지만 설정이 과하면 ms로 커집니다.',
      own: ['sys'],
      act: { infra: '적응형 병합, 게임 서버에 맞는 값으로 조정(ethtool -C).' },
      sim: 'nic',
      sig: { k: 'high', g: '같은 데이터센터 안 왕복 시간' },
      chk: {
        look: 'ethtool -c로 현재 병합 설정(adaptive-rx, rx-usecs, rx-frames)을 보고, 같은 데이터센터의 다른 서버와 ping 왕복 시간을 설정을 바꾸기 전후로 비교',
        yes: 'rx-usecs가 수백 µs 이상으로 크게 잡혀 있고, 값을 줄이면 같은 데이터센터 안 왕복 시간이 그만큼 줄어듦',
        no: '줄여도 왕복 시간이 그대로면 이 원인이 아님',
        by: 'ops',
      },
      ref: [
        { t: 'Linux Driver for Intel(R) Ethernet Network Connection (e1000e)', u: 'https://docs.kernel.org/networking/device_drivers/ethernet/intel/e1000e.html', p: 'Linux kernel', n: '기본은 적응형 인터럽트 조절로 초당 4,000~20,000번(간격 50~250µs), 인터럽트를 줄이면 CPU는 아끼지만 지연이 늘어남' },
        { t: 'Linux Base Driver for Intel(R) Ethernet Network Connection (e1000)', u: 'https://docs.kernel.org/networking/device_drivers/ethernet/intel/e1000.html', p: 'Linux kernel', n: 'RxIntDelay로 수신 인터럽트를 1.024µs 단위로 최대 65,535까지(약 67ms) 늦출 수 있고, 값을 키우면 수신 지연이 늘어남' },
        { t: 'ethtool(8) — Linux manual page', u: 'https://man7.org/linux/man-pages/man8/ethtool.8.html', p: 'ethtool', n: 'ethtool -C의 adaptive-rx·rx-usecs·rx-frames 설정' },
      ] },
    { id: 'nic-cloud-pps', t: '클라우드 PPS 한도 초과', en: 'Cloud PPS / bandwidth allowance',
      s: '클라우드 서버는 종류마다 초당 패킷 수·대역폭 한도가 있고, 넘으면 조용히 버립니다.',
      c: ['동접이 늘어 초당 패킷 수가 인스턴스 한도를 넘음', '클라우드 네트워크가 초과분을 폐기', '원인을 알 수 없는 손실로 순간이동·스킬 씹힘. 서버 CPU는 여유'],
      sym: ['teleport', 'dropped'], fx: ['loss'], who: ['server'], when: ['event', 'peak'],
      num: '한도는 인스턴스 크기마다 다르고, 초당 패킷 수 한도는 공개하지 않는 경우가 많습니다. 작은 인스턴스의 “최대 10Gbps”는 크레딧이 남아 있는 동안(보통 5~60분)만 쓸 수 있는 버스트 속도이고, 평소 기본 속도는 훨씬 낮습니다.',
      own: ['sys', 'srv', 'ext'],
      act: { game: '패킷 합치기(한 틱의 메시지를 한 패킷에), 아주 작은 패킷을 자주 보내지 않게.', infra: '한도 초과 카운터 확인(AWS는 pps_allowance_exceeded, conntrack_allowance_exceeded 등)·경보, 더 큰 인스턴스, 연결 추적 한도는 추적이 생기지 않는 보안 그룹 구성으로 피하기.', ext: '클라우드 사업자에 인스턴스 종류별 초당 패킷 수·연결 추적 한도 문의.' },
      more: 'conntrack_allowance_exceeded는 연결 추적 테이블이 가득 차 새 연결을 버린 경우입니다. 테이블은 여유가 있는데 유휴 연결만 추적이 만료되어 끊긴다면 “클라우드 보안 그룹의 연결 추적 만료” 항목을 보세요.',
      sim: 'nic',
      sig: { k: 'ceiling', g: '초당 패킷 수, allowance 초과 카운터' },
      chk: {
        look: 'ethtool -S의 ENA 카운터 pps_allowance_exceeded·bw_in_allowance_exceeded·bw_out_allowance_exceeded·conntrack_allowance_exceeded를 짧은 간격으로 모아 초당 패킷 수와 함께 봄. CloudWatch 에이전트로 이 카운터를 올려 경보를 걸 수도 있음',
        yes: '손실이 난 시각에 allowance 초과 카운터가 늘고, 초당 패킷 수가 일정한 값에서 더 오르지 못함. 서버 CPU는 여유',
        no: '초과 카운터가 그대로면 이 원인이 아님. 한 코어의 %soft가 100%면 “NIC 인터럽트 단일 코어 집중”',
        by: 'ops',
      },
      ref: [
        { t: 'Monitor network performance for ENA settings on your EC2 instance', u: 'https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/monitoring-network-performance-ena.html', p: 'AWS', n: '인스턴스마다 대역폭·PPS·연결 추적 한도가 있고 넘치면 큐에 쌓았다가 버림, pps_allowance_exceeded·conntrack_allowance_exceeded 카운터' },
        { t: 'Amazon EC2 instance network bandwidth', u: 'https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-network-bandwidth.html', p: 'AWS', n: '16 vCPU 이하 인스턴스의 “최대 N Gbps”는 네트워크 I/O 크레딧으로 쓰는 버스트(보통 5~60분), 크레딧이 떨어지면 기준 대역폭으로 돌아감' },
      ] },
    { id: 'nic-saturate', t: 'NIC 대역폭 포화', en: 'NIC bandwidth saturation',
      s: '1Gbps·10Gbps 카드의 한계까지 쓰면 송신 대기열이 길어지고 결국 버려집니다.',
      c: ['브로드캐스트 증가로 전송량이 카드 한계에 도달', '송신 대기열이 길어지고 넘치면 폐기', '서버 전체 지연·손실(입력 지연·순간이동)'],
      sym: ['delay', 'teleport'], fx: ['lat', 'loss'], who: ['server'], when: ['event'],
      own: ['srv', 'sys'],
      act: { game: '전송량 줄이기(관심 영역, 압축, 변경분만).', infra: '카드 증설(더 빠른 NIC, 클라우드는 더 큰 인스턴스), NIC 사용률 경보.' },
      sig: { k: 'ceiling', g: 'NIC 송신량, 송신 폐기' },
      chk: {
        look: 'sar -n DEV 1의 txkB/s와 %ifutil(인터페이스 속도 대비 사용률)을 NIC 속도·인스턴스 대역폭과 비교하고, ip -s link의 TX dropped를 함께 봄',
        yes: '송신량이 NIC·인스턴스 대역폭 근처에서 평평해지고, 그때부터 송신 폐기와 서버 전체 지연이 늘어남',
        no: '대역폭에 여유가 있으면 이 원인이 아님. 작은 패킷이 많은데 손실이 있으면 “클라우드 PPS 한도 초과”',
        by: 'ops',
      },
      ref: [
        { t: 'Interface statistics', u: 'https://docs.kernel.org/networking/statistics.html', p: 'Linux kernel', n: 'tx_dropped: 자원이 모자라 송신 도중 버린 패킷 수' },
        { t: 'Amazon EC2 instance network bandwidth', u: 'https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-network-bandwidth.html', p: 'AWS', n: '인스턴스가 쓸 수 있는 대역폭은 vCPU 수(인스턴스 크기)에 따라 정해짐' },
        { t: 'sar(1) — Linux manual page', u: 'https://man7.org/linux/man-pages/man1/sar.1.html', p: 'sysstat', n: '-n DEV의 rxkB/s·txkB/s와 %ifutil(인터페이스 속도 대비 사용률)' },
      ] },
    { id: 'nic-noisy', t: '가상화 오버헤드·노이지 네이버', en: 'Noisy neighbors in virtualization',
      s: '같은 물리 서버의 다른 가상 머신이 네트워크·CPU를 많이 쓰면 내 서버의 처리가 불규칙하게 밀립니다.',
      c: ['같은 물리 서버의 다른 가상 머신이 자원을 많이 씀', '내 가상 머신의 패킷 처리가 불규칙하게 지연', '뚜렷한 원인 없이 가끔 지터(도착 간격의 흔들림)가 생겨 뚝뚝 끊김'],
      sym: ['stutter'], fx: ['jit'], who: ['server'], when: ['random'],
      own: ['sys', 'ext'],
      act: { infra: '전용 호스트, 성능 보장 인스턴스, 지터가 계속되는 인스턴스는 중지 후 다시 시작해 다른 호스트로 옮기기.', ext: '클라우드 사업자에 문제 호스트 신고.' },
      sig: { k: 'random', g: '같은 데이터센터 안 왕복 시간 지터, %steal' },
      chk: {
        look: '같은 데이터센터의 다른 서버로 계속 ping을 보내 왕복 시간의 지터를 기록하고, mpstat의 %steal과 함께 같은 구성의 다른 인스턴스와 비교',
        yes: '이 인스턴스만 왕복 시간 지터나 %steal이 불규칙하게 튀고, 같은 구성의 다른 인스턴스는 조용함. 중지 후 다시 시작해 다른 호스트로 옮기면 사라짐',
        no: '같은 구성의 인스턴스가 모두 똑같이 튀면 호스트 문제가 아님. 게임 서버 쪽 부하나 네트워크 구간을 봄',
        by: 'ops',
      },
      ref: [
        { t: 'How EC2 instance stop and start works', u: 'https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/how-ec2-instance-stop-start-works.html', p: 'AWS', n: '인스턴스를 중지했다 시작하면 대부분 새 호스트로 옮겨짐(전용 호스트 제외)' },
        { t: 'mpstat(1) — Linux manual page', u: 'https://man7.org/linux/man-pages/man1/mpstat.1.html', p: 'sysstat', n: '%steal: 하이퍼바이저가 다른 가상 CPU를 돌리는 동안 이 가상 CPU가 어쩔 수 없이 기다린 시간 비율' },
      ] },
    { id: 'nic-host-maintenance', t: '클라우드 호스트 점검·라이브 마이그레이션', en: 'Cloud host maintenance / live migration',
      s: '클라우드 사업자가 물리 서버(호스트)를 점검할 때 가상 머신을 다른 호스트로 옮기거나(라이브 마이그레이션) 잠시 멈춥니다. 그동안 서버 전체가 멈추고, 멈춘 시간이 길면 연결이 끊깁니다.',
      c: ['사업자가 호스트 점검이나 고장 예측으로 가상 머신을 다른 호스트로 옮기거나 잠시 일시 정지', '옮기는 동안 CPU·메모리·네트워크가 느려지고, 마지막에 가상 머신이 잠깐 완전히 멈춤(사업자와 방식에 따라 1초 미만에서 30초 안팎)', '서버의 모두가 동시에 멈췄다가 몰아치기·순간이동, 멈춤이 타임아웃보다 길면 대량 접속 끊김'],
      sym: ['freeze', 'burst', 'disconnect'], fx: ['stall', 'loss'], who: ['server'], when: ['random'],
      num: 'Google Compute Engine은 라이브 마이그레이션의 멈춤이 보통 1초보다 훨씬 짧다고 하고, 멈추는 동안 시스템 시계가 최대 5초 앞으로 뛸 수 있습니다. 메타데이터의 maintenance-event 값은 옮기기 60초 전에 바뀝니다(그 전에 이 값을 한 번 이상 조회해 둔 경우). Azure는 재부팅이 필요 없는 점검이면 거의 항상 10초 미만, 드물게(일반 크기는 18개월에 한 번 이하) 약 30초 멈추고, 라이브 마이그레이션은 보통 5초를 넘지 않습니다. Azure Scheduled Events는 이런 멈춤(Freeze)을 최소 15분 전에 알립니다.',
      more: 'AWS는 예약 이벤트로 알립니다. system-reboot는 재부팅하며 새 호스트로 옮긴다는 뜻이고, system-maintenance는 네트워크·전원 점검으로 잠시 영향을 받을 수 있다는 뜻입니다. 멈췄다 깨어나면 시계가 뛰어 “시스템 시계 점프 (NTP 스텝)”로 이어지기도 하고, 로드밸런서 헬스체크가 실패해 그 서버를 잠시 빼기도 합니다. 옮길 수 없는 인스턴스(Google Cloud의 베어메탈 인스턴스 등)는 점검 때 중지되거나 다시 시작됩니다.',
      own: ['sys', 'srv', 'ext'],
      act: { game: '서버: 수 초 멈춤을 견디는 타임아웃, 멈춘 뒤 따라잡는 틱 수에 상한 두기, 경과 시간은 단조 시계(monotonic clock)로 계산, 점검 알림을 받으면 진행 상황을 저장하고 유저를 다른 서버로 옮기는 절차.', infra: '점검 알림 구독과 경보(Google Cloud maintenance-event, AWS 예약 이벤트·AWS Health, Azure Scheduled Events), 알림을 받으면 유저가 적은 시간에 미리 서버 교체, 사업자가 허용하면 점검 시각 조정(Azure Maintenance Configuration, 종류에 따라 AWS 예약 이벤트), 점검 기록과 장애 기록 대조.', ext: '클라우드 사업자에 점검 일정과 영향 범위 확인, 같은 인스턴스에서 멈춤이 반복되면 신고.' },
      sig: { k: 'gap', g: '서버 송수신 패킷 수, 틱 간격' },
      chk: {
        look: '멈춘 시각을 사업자 기록과 대조함. Google Cloud는 감사 로그의 compute.instances.migrateOnHostMaintenance, AWS는 describe-instance-status·AWS Health의 예약 이벤트, Azure는 Scheduled Events와 Service Health 기록. 서버 안에서는 멈춘 동안 지표·로그가 비었는지, 직후 시계가 뛰었는지(시간 동기화 로그) 봄',
        yes: '서버 전체가 멈춘 시각이 사업자가 기록한 점검·마이그레이션 시각과 겹치고, 그 몇 초 동안 서버 안의 지표·로그가 모두 빔',
        no: '사업자 기록에 없고 짧은 멈춤이 자주 되풀이되면 “CPU 스틸 (가상 머신)”. 커널 로그에 NIC 재설정 기록이 있으면 “NIC 드라이버·펌웨어 문제”',
        by: 'ops',
      },
      ref: [
        { t: 'Live migration process during maintenance events', u: 'https://cloud.google.com/compute/docs/instances/live-migration-process', p: 'Google Cloud', n: '라이브 마이그레이션의 멈춤은 보통 1초보다 훨씬 짧음, 멈추는 동안 시스템 시계가 최대 5초 앞으로 뜀, 옮기는 동안 디스크·CPU·메모리·네트워크 성능이 잠시 떨어짐, 라이브 마이그레이션하지 않는 VM은 점검 때 종료(베어메탈 인스턴스는 지원 안 함)' },
        { t: 'Query metadata server for maintenance event notices', u: 'https://cloud.google.com/compute/docs/metadata/getting-live-migration-notice', p: 'Google Cloud', n: 'maintenance-event 메타데이터 값이 라이브 마이그레이션 60초 전에 바뀜(라이브 마이그레이션 설정이고 지난 점검 뒤 이 값을 한 번 이상 조회한 경우)' },
        { t: 'Monitor and plan for a host maintenance event', u: 'https://cloud.google.com/compute/docs/instances/monitor-plan-host-maintenance-event', p: 'Google Cloud', n: '점검 때 감사 로그에 compute.instances.migrateOnHostMaintenance 시스템 이벤트가 남음' },
        { t: 'Scheduled events for Amazon EC2 instances', u: 'https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/monitoring-instances-status-check_sched.html', p: 'AWS', n: '예약 이벤트 종류(system-reboot는 재부팅하며 새 호스트로 이동, system-maintenance는 네트워크·전원 점검으로 잠시 영향), 메일·AWS Health로 알림, describe-instance-status로 확인, 종류에 따라 시각 조정 가능' },
        { t: 'Maintenance and updates', u: 'https://learn.microsoft.com/en-us/azure/virtual-machines/maintenance-and-updates', p: 'Microsoft Azure', n: '재부팅 없는 점검은 거의 항상 10초 미만 멈춤, 드물게(일반 크기는 18개월에 한 번 이하) 약 30초, 라이브 마이그레이션은 보통 5초 이하, 멈춘 뒤 시계 자동 동기화, 긴 TCP 연결이 끊길 수 있고 로드밸런서 헬스체크가 약 10초 안에 비정상으로 판정, Maintenance Configuration으로 적용 시각 선택' },
        { t: 'Scheduled Events for Linux VMs in Azure', u: 'https://learn.microsoft.com/en-us/azure/virtual-machines/linux/scheduled-events', p: 'Microsoft Azure', n: 'Freeze(몇 초 멈춤, CPU·네트워크가 멈출 수 있음)는 최소 15분 전에 알림' },
      ] },
    { id: 'nic-reset', t: 'NIC 드라이버·펌웨어 문제', en: 'NIC hang / reset',
      s: '드라이버 버그나 기능 오동작으로 카드가 멈춰 재시작되는 동안 모든 송수신이 끊깁니다.',
      c: ['드라이버 버그, 오프로드 기능 오동작', 'NIC가 멈추고 재시작(수 초)', '그 서버의 모두가 함께 멈췄다가 순간이동하거나 접속 끊김'],
      sym: ['freeze', 'disconnect'], fx: ['loss'], who: ['server'], when: ['random', 'uptime'],
      own: ['sys'],
      act: { infra: '커널 로그의 “transmit queue … timed out”, “Link is Down” 기록 확인·경보, 드라이버·펌웨어 업데이트, 문제 기능(오프로드 등) 끄기.' },
      sig: { k: 'gap', g: '서버 송수신 패킷 수' },
      chk: {
        look: 'dmesg로 커널 로그에서 “NETDEV WATCHDOG … transmit queue N timed out”, 드라이버의 재설정, “Link is Down”·“Link is Up” 기록을 찾고, 그 시각의 서버 송수신 패킷 수를 봄',
        yes: '멈춘 시각에 커널 로그에 송신 큐 타임아웃이나 링크 다운·업 기록이 있고, 그 몇 초 동안 송수신 패킷 수가 0',
        no: '커널 로그가 깨끗하고 스위치 쪽 포트도 멀쩡하면 게임 서버 프로세스의 멈춤(“서버 GC 전체 멈춤”, “데드락”)이나 “네트워크 장비 장애 전환(페일오버)”',
        by: 'ops',
      },
      ref: [
        { t: 'net/sched/sch_generic.c (Linux v6.12)', u: 'https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/net/sched/sch_generic.c?h=v6.12', p: 'Linux kernel', n: '송신 큐가 멈추면 커널 워치독이 “NETDEV WATCHDOG … transmit queue N timed out”을 남기고 드라이버의 재설정 함수를 부름' },
        { t: 'drivers/net/ethernet/intel/ixgbe/ixgbe_main.c (Linux v6.12)', u: 'https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/net/ethernet/intel/ixgbe/ixgbe_main.c?h=v6.12', p: 'Linux kernel', n: 'ixgbe 드라이버가 송신 멈춤 때 어댑터를 재설정하고, 링크가 끊기면 “NIC Link is Down”을 기록' },
        { t: 'ethtool(8) — Linux manual page', u: 'https://man7.org/linux/man-pages/man8/ethtool.8.html', p: 'ethtool', n: 'ethtool -K로 오프로드 기능을 하나씩 끄는 옵션' },
      ] },
    { id: 'nic-offload', t: 'GRO/LRO 병합 대기 지연', en: 'GRO/LRO batching',
      s: '여러 패킷을 하나로 묶어 CPU 부담을 줄이는 기능입니다. 설정에 따라 작은 게임 패킷이 함께 묶을 다음 패킷을 잠깐 기다리기도 합니다.',
      c: ['NIC·커널이 도착한 패킷을 묶어서 처리', '하드웨어 병합(LRO)이나 병합 대기 시간 설정이 켜져 있으면 다음 패킷을 기다리며 잠깐 대기', '미세한 지연 증가(대개 수십 µs 이하)'],
      sym: ['delay'], fx: ['lat'], who: ['server'], when: ['always'],
      own: ['sys'],
      act: { infra: '게임 트래픽에 맞게 조정(LRO 끄기, 병합 대기 시간 설정 확인), 효과는 대개 작으니 다른 원인보다 뒤에 확인.' },
      sig: { k: 'high', g: '같은 데이터센터 안 왕복 시간' },
      chk: {
        look: 'ethtool -k로 lro·gro 상태를, 장치의 sysfs 설정 gro_flush_timeout 값을 확인하고, 바꾸기 전후 같은 데이터센터 안 작은 패킷의 왕복 시간을 비교',
        yes: 'LRO가 켜져 있거나 gro_flush_timeout이 0보다 크고, 끄거나 0으로 두면 작은 패킷의 왕복 시간이 줄어듦',
        no: '바꿔도 차이가 수 µs 안쪽이면 이 원인이 아님',
        by: 'ops',
      },
      ref: [
        { t: 'NAPI', u: 'https://docs.kernel.org/networking/napi.html', p: 'Linux kernel', n: 'gro_flush_timeout을 크게 잡으면 묶어 처리하는 대신 부하가 낮을 때 지연이 생김' },
        { t: 'Linux Base Driver for the Intel(R) Ethernet 10 Gigabit PCI Express Adapters (ixgbe)', u: 'https://docs.kernel.org/networking/device_drivers/ethernet/intel/ixgbe.html', p: 'Linux kernel', n: 'GRO는 수신 트래픽을 큰 덩어리로 합쳐 CPU를 아끼는 기능이고 LRO를 발전시킨 것' },
        { t: 'ethtool(8) — Linux manual page', u: 'https://man7.org/linux/man-pages/man8/ethtool.8.html', p: 'ethtool', n: 'ethtool -K의 gro·lro on|off 설정' },
      ] },
  ]);

  /* ---------------- 7. 서버 OS ---------------- */
  add('server-os', [
    { id: 'so-backlog', t: '접속 대기열(backlog) 넘침', en: 'Listen backlog / SYN queue overflow',
      s: '점검 직후 수만 명이 동시에 접속하면, 커널의 접속 대기열(backlog)이 넘쳐 접속 시도가 버려집니다.',
      c: ['점검 종료와 동시에 게임 서버가 accept로 접속을 처리하는 속도보다 빨리 몰림', '커널의 접속 대기열(backlog. 서버 코드가 listen에 준 값과 커널 상한 중 작은 쪽)이 가득', '접속 시도가 버려지고 재시도가 반복되어 접속 불가·무한 로딩'],
      sym: ['noconnect'], fx: ['loss'], who: ['server'], when: ['login'],
      num: '리눅스 커널 상한(somaxconn)은 5.4부터 기본 4,096(그 전 128)이지만, 서버 코드가 listen에 더 작은 값을 주면 그 값이 한도입니다. 리눅스는 대기열이 차면 접속 요청을 오류 없이 조용히 버립니다. 클라이언트 OS가 1초 뒤부터 몇 차례 다시 보내므로, 플레이어에게는 “연결 실패”보다 긴 로딩으로 보입니다. 윈도우 서버는 거절 응답을 돌려보내 클라이언트가 곧바로 “연결 실패”를 봅니다.',
      own: ['srv', 'sys', 'cli'],
      act: { game: '서버: 코드에서 주는 listen 값 늘리기, 접속을 받는 스레드가 다른 일로 멈추지 않게, 로그인 대기열 시스템. 클라이언트: 재시도 간격 늘리기(무작위로 분산).', infra: '커널 somaxconn 늘리기(서버 코드의 listen 값과 둘 다 올려야 효과), SYN 쿠키 켜 두기, 넘침 횟수 감시(nstat의 TcpExtListenOverflows).' },
      sim: 'rush',
      sig: { k: 'surge', g: '접속 대기열 넘침 수(ListenOverflows), 접속 시도 수' },
      chk: {
        look: 'nstat -az의 TcpExtListenOverflows·TcpExtListenDrops 증가량을 보고, ss -ltn으로 리슨 소켓의 Recv-Q(accept를 기다리는 접속 수)와 Send-Q(backlog 한도)를 비교',
        yes: '접속이 몰린 시각에 ListenOverflows가 늘고, 리슨 소켓의 Recv-Q가 Send-Q 값에 붙어 있음',
        no: 'ListenOverflows가 그대로면 이 원인이 아님. 연결은 맺어졌는데 로딩이 안 끝나면 “로그인 폭주와 N+1 쿼리”, 정확히 일정 인원에서 막히면 “파일 디스크립터 한도”',
        by: 'ops',
      },
      ref: [
        { t: 'listen(2) — Linux manual page', u: 'https://man7.org/linux/man-pages/man2/listen.2.html', p: 'Linux man-pages', n: 'listen의 backlog는 somaxconn을 넘으면 조용히 잘림, somaxconn 기본 4,096(5.4부터, 전에는 128), 대기열이 차면 요청을 무시해 클라이언트 재시도에 맡길 수 있음' },
        { t: 'IP Sysctl', u: 'https://docs.kernel.org/networking/ip-sysctl.html', p: 'Linux kernel', n: 'tcp_syn_retries: 접속 요청(SYN)을 첫 재전송 대기 1초로 여러 번 다시 보냄, tcp_abort_on_overflow 기본 꺼짐(넘쳐도 거절 응답 없음), tcp_syncookies 기본 켜짐' },
        { t: 'listen function (winsock2.h)', u: 'https://learn.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-listen', p: 'Microsoft', n: '윈도우는 대기열이 가득 차면 클라이언트가 WSAECONNREFUSED 오류를 받음' },
        { t: 'SNMP counter', u: 'https://docs.kernel.org/networking/snmp_counter.html', p: 'Linux kernel', n: 'TcpExtListenOverflows: accept 대기열이 가득 차 접속 요청(SYN)을 버린 횟수, 이때 TcpExtListenDrops도 함께 증가' },
        { t: 'net/ipv4/tcp_diag.c (Linux v6.12)', u: 'https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/net/ipv4/tcp_diag.c?h=v6.12', p: 'Linux kernel', n: 'ss의 Recv-Q·Send-Q 값: 리슨 소켓은 accept를 기다리는 접속 수와 backlog 한도, 연결된 소켓은 앱이 아직 안 읽은 바이트와 ACK를 받지 못한 송신 바이트' },
      ] },
    { id: 'so-fd', t: '파일 디스크립터 한도', en: 'File descriptor limit (ulimit)',
      s: '연결 하나마다 파일 디스크립터(fd, OS가 열린 파일·소켓에 붙이는 번호)가 필요한데, 한 프로세스가 열 수 있는 fd 수가 제한되어 있습니다.',
      c: ['동접이 프로세스의 파일 디스크립터 한도에 도달', '서버가 새 연결을 받지 못함(Too many open files). 로그·DB 연결 열기도 함께 실패', '정확히 일정 인원부터 아무도 못 들어오는 접속 불가·무한 로딩'],
      sym: ['noconnect'], fx: ['loss'], who: ['server'], when: ['login', 'event'],
      num: '리눅스는 서비스 설정을 따로 하지 않으면 한도가 1,024인 경우가 아직 많습니다. 게임 서버는 보통 수만~수십만으로 올립니다. 윈도우에는 이렇게 낮은 기본 한도가 없습니다.',
      own: ['sys', 'srv'],
      act: { game: '연결을 끝낼 때 소켓을 확실히 닫기(fd 누수 방지), accept가 EMFILE(fd 부족)로 실패하면 잠시 접속 받기를 멈추거나 미리 남겨 둔 예비 fd로 받아 바로 닫기(같은 접속 알림만 반복 처리하며 CPU를 낭비하지 않게).', infra: 'ulimit·서비스 설정(systemd의 LimitNOFILE) 확인, 한도 근접 경보.' },
      more: '받지 못한 접속은 커널 접속 대기열(backlog)에 그대로 남아 있어, 서버 코드에 따라 “새 접속 있음” 알림을 계속 받으며 CPU를 낭비하기도 합니다.',
      sim: 'rush',
      sig: { k: 'ceiling', g: '프로세스의 열린 fd 수, 동시 접속 수' },
      chk: {
        look: 'pidstat -v로 게임 서버 프로세스의 fd-nr(열린 파일 디스크립터 수)를, /proc/PID/limits로 열린 파일 수 한도를 보고, 서버 로그에서 accept 실패(EMFILE, Too many open files)를 찾음',
        yes: 'fd 수가 한도 값에서 평평해지고, 그 시각부터 accept가 EMFILE로 실패함',
        no: 'fd 수가 한도에 한참 못 미치면 이 원인이 아님. 접속 요청이 커널에서 버려지면 “접속 대기열(backlog) 넘침”, 연결 추적 쪽이면 “서버 conntrack 테이블 포화”',
        by: 'ops',
      },
      ref: [
        { t: 'systemd-system.conf(5) — Linux manual page', u: 'https://man7.org/linux/man-pages/man5/systemd-system.conf.5.html', p: 'systemd', n: '서비스의 DefaultLimitNOFILE 기본값은 1024:524288(소프트 한도 1,024)' },
        { t: 'accept(2) — Linux manual page', u: 'https://man7.org/linux/man-pages/man2/accept.2.html', p: 'Linux man-pages', n: '프로세스의 fd 한도에 닿으면 accept가 EMFILE로 실패' },
        { t: 'Maximum Number of Sockets Supported', u: 'https://learn.microsoft.com/en-us/windows/win32/winsock/maximum-number-of-sockets-supported-2', p: 'Microsoft', n: '윈도우 Winsock은 소켓 수를 사용 가능한 메모리로만 제한' },
        { t: 'pidstat(1) — Linux manual page', u: 'https://man7.org/linux/man-pages/man1/pidstat.1.html', p: 'sysstat', n: '-v의 fd-nr: 프로세스가 연 파일 디스크립터 수' },
        { t: 'proc_pid_limits(5) — Linux manual page', u: 'https://man7.org/linux/man-pages/man5/proc_pid_limits.5.html', p: 'Linux man-pages', n: '/proc/PID/limits에 프로세스별 자원 한도의 소프트·하드 값' },
      ] },
    { id: 'so-sockbuf', t: '커널 소켓 버퍼 부족', en: 'Small socket buffers',
      s: '송수신 버퍼가 작으면 버스트 트래픽이 몰릴 때 UDP로 받은 패킷은 버려지고, TCP 송신은 버퍼에 여유가 없어 막힙니다.',
      c: ['SO_SNDBUF·SO_RCVBUF가 기본값이거나 너무 작음', '버스트나 받는 스레드가 잠깐 멈춘 사이 UDP 수신 버퍼가 넘쳐 폐기, TCP는 송신 버퍼에 여유가 없어 대기', '순간이동(UDP 손실) 또는 몰아치기(TCP 대기)'],
      sym: ['teleport', 'burst'], fx: ['loss', 'stall'], who: ['server'], when: ['event'],
      num: '리눅스 UDP 수신 버퍼 기본값은 약 208KB입니다. 작은 패킷도 한 개가 커널 메모리를 실제 크기보다 훨씬 많이 차지해 수십~수백 개면 찹니다. 초당 10만 개를 받는 서버라면 받는 스레드가 몇 ms만 멈춰도 넘칩니다.',
      own: ['sys', 'srv'],
      act: { game: '트래픽에 맞춘 버퍼 크기(SO_SNDBUF·SO_RCVBUF)를 코드에서 설정, TCP는 크기를 직접 정하면 리눅스의 자동 크기 조절이 꺼지니 주의, 너무 크게 잡으면 오래된 데이터가 버퍼에 쌓여 지연이 늘어나니 적당히, 받는 스레드가 멈추지 않게.', infra: '커널 상한(rmem_max·wmem_max. 코드에서 정한 버퍼 크기도 이 값을 넘지 못함)과 기본값(rmem_default) 조정, 버퍼 넘침 카운터(RcvbufErrors) 감시.' },
      sim: 'sndbuf',
      sig: { k: 'random', g: 'UDP 수신 버퍼 넘침(UdpRcvbufErrors)' },
      chk: {
        look: 'nstat -az의 UdpRcvbufErrors 증가량과 ss -uamn의 skmem(rb는 수신 버퍼 크기, d는 소켓에 넣지 못하고 버린 패킷 수)을 보고, TCP는 ss -tm의 skmem에서 송신 대기 메모리(w)가 송신 버퍼 크기(tb)에 닿았는지 봄',
        yes: '버스트나 받는 스레드가 멈춘 시각에 UdpRcvbufErrors(또는 소켓의 d)가 늘고, rb가 기본값(약 208KB) 근처. TCP는 w가 tb에 붙은 채 send가 막힘',
        no: '카운터가 그대로인데 손실이 있으면 NIC 단계(“링 버퍼 부족”)나 네트워크 구간',
        by: 'ops',
      },
      ref: [
        { t: 'socket(7) — Linux manual page', u: 'https://man7.org/linux/man-pages/man7/socket.7.html', p: 'Linux man-pages', n: 'SO_RCVBUF·SO_SNDBUF 기본값은 rmem_default·wmem_default, 상한은 rmem_max·wmem_max, 설정값은 커널이 두 배로 잡음' },
        { t: 'include/net/sock.h (Linux v6.18)', u: 'https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/net/sock.h?h=v6.18', p: 'Linux kernel', n: '기본 소켓 버퍼를 sk_buff 오버헤드를 포함한 256바이트 패킷 256개분(SKB_TRUESIZE(256)×256)으로 정의, 작은 프레임도 sk_buff+MTU만큼 계산됨(약 208KB는 x86-64 기준 계산값)' },
        { t: 'IP Sysctl', u: 'https://docs.kernel.org/networking/ip-sysctl.html', p: 'Linux kernel', n: 'tcp_rmem·tcp_wmem: SO_RCVBUF·SO_SNDBUF를 직접 정하면 그 소켓의 자동 크기 조절이 꺼짐' },
        { t: 'net/ipv4/udp.c (Linux v6.12)', u: 'https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/net/ipv4/udp.c?h=v6.12', p: 'Linux kernel', n: 'UDP 수신 대기열이 소켓 버퍼 크기를 넘으면 곧바로 버리고 RcvbufErrors를 올림' },
        { t: 'net/ipv4/proc.c (Linux v6.12)', u: 'https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/net/ipv4/proc.c?h=v6.12', p: 'Linux kernel', n: 'nstat이 보여 주는 카운터 이름: Udp 그룹의 RcvbufErrors·SndbufErrors' },
        { t: 'ss(8) — Linux manual page', u: 'https://man7.org/linux/man-pages/man8/ss.8.html', p: 'iproute2', n: '-m의 skmem: rb 수신 버퍼 크기, tb 송신 버퍼 크기, w 송신 대기 메모리, d 소켓에 넣기 전 버린 패킷 수' },
      ] },
    { id: 'so-context', t: '스레드 과다와 컨텍스트 스위칭', en: 'Thread oversubscription, context switching',
      s: '코어보다 훨씬 많은 스레드를 돌리면 OS가 번갈아 실행시키는 데만 CPU를 씁니다.',
      c: ['연결마다 스레드를 만드는 등 스레드가 수백~수천 개', '컨텍스트 스위칭(실행 스레드 교체) 비용과 캐시 미스 증가', 'CPU는 바쁜데 처리량은 낮고 틱이 들쭉날쭉해 뚝뚝 끊김·슬로우모션'],
      sym: ['stutter', 'slowmo'], fx: ['stall', 'jit'], who: ['server'], when: ['event'],
      num: '컨텍스트 스위칭 한 번에 수 µs, 그 뒤 캐시 미스 비용까지 합치면 더 큽니다.',
      own: ['srv', 'sys'],
      act: { game: '코어 수에 맞춘 스레드, 비동기 I/O(epoll·IOCP).', infra: '컨텍스트 스위칭 횟수와 실행 대기 스레드 수(vmstat의 cs·r) 모니터링.' },
      sig: { k: 'load', g: '초당 컨텍스트 스위칭 수, 실행 대기 스레드 수' },
      chk: {
        look: 'vmstat 1의 cs(초당 컨텍스트 스위칭)·r(실행 중이거나 CPU를 기다리는 수)을 코어 수와 비교하고, pidstat -w -t로 게임 서버 스레드별 자발적(cswch/s)·비자발적(nvcswch/s) 컨텍스트 스위칭을 봄',
        yes: '동접이 늘 때 r이 코어 수보다 훨씬 크게 오르고 cs도 따라 치솟으며, 비자발적 컨텍스트 스위칭이 많은 스레드가 수백 개',
        no: 'r이 코어 수 이하로 머물면 이 원인이 아님. 자발적 스위칭만 많으면 스레드가 락·I/O를 기다리는 것(“락 경합”, “블로킹 I/O 구조”)',
        by: 'ops',
      },
      ref: [
        { t: 'Quantifying The Cost of Context Switch (ExpCS 2007)', u: 'https://www.usenix.org/legacy/events/expcs07/papers/2-li.pdf', p: 'ACM', n: '컨텍스트 스위칭 직접 비용 약 3.8µs, 캐시 영향까지 합친 간접 비용은 수 µs~1,000µs 이상(측정 환경 기준)' },
        { t: 'vmstat(8) — Linux manual page', u: 'https://man7.org/linux/man-pages/man8/vmstat.8.html', p: 'procps-ng', n: 'cs(초당 컨텍스트 스위칭 수)와 r(실행 중이거나 실행을 기다리는 프로세스 수) 항목' },
        { t: 'I/O Completion Ports', u: 'https://learn.microsoft.com/en-us/windows/win32/fileio/i-o-completion-ports', p: 'Microsoft', n: '미리 만든 스레드 풀과 IOCP로 많은 비동기 I/O를 처리하고, 동시에 도는 스레드 수를 CPU 동시성에 맞춤' },
        { t: 'pidstat(1) — Linux manual page', u: 'https://man7.org/linux/man-pages/man1/pidstat.1.html', p: 'sysstat', n: '-w의 cswch/s는 자원을 기다리며 스스로 멈춘 자발적 컨텍스트 스위칭, nvcswch/s는 타임 슬라이스를 다 써서 강제로 바뀐 비자발적 컨텍스트 스위칭, -t로 스레드별' },
      ] },
    { id: 'so-steal', t: 'CPU 스틸 (가상 머신)', en: 'CPU steal time',
      s: '물리 서버(하이퍼바이저)가 가상 머신의 CPU 시간을 잠시 다른 가상 머신에 넘기는 동안(CPU 스틸) 게임 서버가 멈춥니다.',
      c: ['같은 호스트의 다른 가상 머신이 CPU를 많이 씀', '내 가상 머신이 수 ms~수십 ms씩 실행 기회를 잃음', '원인 모를 틱 시간 급증으로 뚝뚝 끊김·멈춤'],
      sym: ['stutter', 'freeze'], fx: ['stall'], who: ['server'], when: ['random'],
      own: ['sys', 'ext'],
      act: { infra: 'steal 지표(top·vmstat의 st) 모니터링, 전용 코어·호스트, CPU 크레딧이 바닥나면 느려지는 버스트형 인스턴스 피하기, steal이 계속 높은 인스턴스는 중지 후 다시 시작해 다른 호스트로 옮기기.', ext: '클라우드 사업자에 steal이 계속 높은 호스트 신고.' },
      sig: { k: 'random', g: '%steal, 서버 틱 시간' },
      chk: {
        look: 'mpstat -P ALL 1의 %steal을 서버 틱 시간과 같은 시간축에 놓고 봄',
        yes: '틱이 튄 시각에 %steal이 함께 튀고, 중지 후 다시 시작해 다른 호스트로 옮기면 줄어듦',
        no: '%steal이 0에 가까운데 틱이 튀면 게임 서버 안쪽 원인(“서버 GC 전체 멈춤”, “락 경합”). 컨테이너면 “컨테이너 CPU 스로틀링 (CFS 쿼터)”',
        by: 'ops',
      },
      ref: [
        { t: 'proc_stat(5) — Linux manual page', u: 'https://man7.org/linux/man-pages/man5/proc_stat.5.html', p: 'Linux man-pages', n: 'steal: 가상화 환경에서 다른 운영체제가 실행되느라 빼앗긴 시간' },
        { t: 'Standard mode for burstable performance instances', u: 'https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/burstable-performance-instances-standard-mode.html', p: 'AWS', n: '버스트형 인스턴스는 크레딧을 써서 기준 성능을 넘고, 크레딧이 떨어지면 CPU 사용률이 기준 수준으로 낮아짐' },
        { t: 'How EC2 instance stop and start works', u: 'https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/how-ec2-instance-stop-start-works.html', p: 'AWS', n: '인스턴스를 중지했다 시작하면 대부분 새 호스트로 옮겨짐' },
        { t: 'mpstat(1) — Linux manual page', u: 'https://man7.org/linux/man-pages/man1/mpstat.1.html', p: 'sysstat', n: '%steal: 하이퍼바이저가 다른 가상 CPU를 돌리는 동안 이 가상 CPU가 어쩔 수 없이 기다린 시간 비율' },
      ] },
    { id: 'so-cpu-quota', t: '컨테이너 CPU 스로틀링 (CFS 쿼터)', en: 'Container CPU throttling (CFS quota)',
      s: '컨테이너에 CPU 한도를 걸면, 정해진 주기(보통 100ms) 안에 할당량을 다 쓴 순간 남은 시간 동안 강제로 멈춥니다(스로틀링).',
      c: ['쿠버네티스 등에서 게임 서버 컨테이너에 CPU 한도(limit)를 걸어 둠', '틱 계산이 몰린 순간 할당량을 다 써서 다음 주기까지 수십 ms 정지', '평균 CPU는 낮은데 틱이 주기적으로 튀어 뚝뚝 끊김·슬로우모션'],
      sym: ['stutter', 'slowmo'], fx: ['stall', 'jit'], who: ['server'], when: ['event', 'random'],
      num: '한도 2코어인 서버에서 스레드 8개가 동시에 일하면, 100ms 주기의 할당량을 25ms 만에 다 쓰고 75ms를 멈춥니다.',
      own: ['sys', 'srv'],
      act: { game: '워커 스레드 수를 CPU 한도에 맞추기(런타임이 호스트 전체 코어 수만큼 스레드를 만들지 않게).', infra: 'CPU 한도를 넉넉히 두거나 빼고 전용 코어 배정, 스로틀링된 횟수(nr_throttled) 감시.' },
      sig: { k: 'load', g: '스로틀링 횟수(nr_throttled), 서버 틱 시간' },
      chk: {
        look: '컨테이너 cgroup의 cpu.stat에서 nr_throttled·throttled_usec(cgroup v1은 nr_throttled·throttled_time) 증가량을 서버 틱 시간과 함께 봄',
        yes: '평균 CPU 사용률은 한도보다 낮은데 nr_throttled·throttled_usec가 계속 늘고, 틱이 튄 시각과 겹침',
        no: 'nr_throttled가 늘지 않으면 이 원인이 아님. 가상 머신 자체가 밀리면 “CPU 스틸 (가상 머신)”',
        by: 'ops',
      },
      ref: [
        { t: 'CFS Bandwidth Control', u: 'https://docs.kernel.org/scheduler/sched-bwc.html', p: 'Linux kernel', n: '주기마다 받은 할당량을 다 쓰면 다음 주기까지 스레드가 멈춤(스로틀링), 기본 주기 100ms, nr_throttled 통계' },
        { t: 'Control Group v2', u: 'https://docs.kernel.org/admin-guide/cgroup-v2.html', p: 'Linux kernel', n: 'cpu.max는 “할당량 주기” 형식이고 기본값은 “max 100000”(100ms 주기)' },
        { t: 'Resource Management for Pods and Containers', u: 'https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/', p: 'Kubernetes', n: '컨테이너의 CPU limit은 커널이 CPU 스로틀링으로 강제하는 하드 한도' },
      ] },
    { id: 'so-cstate', t: '서버 전원 관리(C-state·주파수 조절)로 지연 튐', en: 'CPU power management latency (C-states, frequency scaling)',
      s: '쉬는 CPU 코어는 전기를 아끼려고 깊은 절전 상태(C-state)로 들어가고 주파수도 낮춥니다. 패킷이나 타이머가 오면 깨어나고 주파수를 올리는 데 시간이 걸려, 작은 패킷 처리에 지연이 더해집니다.',
      c: ['OS의 주파수 조절 정책(governor)이나 BIOS 전원 설정이 깊은 C-state와 낮은 주파수를 허용', '쉬던 코어가 깊은 절전 상태에서 깨어날 때마다 최대 수백 µs 늦고, 주파수가 낮게 묶여 있으면 틱 계산 자체가 느려짐', '한산할 때 오히려 반응이 굼뜬 입력 지연, 주파수가 낮게 묶이면 사람이 몰릴 때 슬로우모션'],
      sym: ['delay', 'slowmo'], fx: ['lat', 'jit', 'stall'], who: ['server'], when: ['always', 'random'],
      num: '커널 intel_idle 드라이버의 표 기준으로 인텔 서버 CPU의 얕은 C1은 깨어나는 데 1~2µs, 가장 깊은 C6는 133µs(Skylake)~290µs(Sapphire Rapids)입니다. 한 번은 작지만 요청 하나가 서버 여러 대를 거치면 그만큼 쌓입니다. 커널은 예상 유휴 시간이 길수록 깊은 상태를 고르므로 패킷이 드문드문 오는 한산한 서버에서 더 자주 나타납니다. 범용 cpufreq의 powersave governor는 허용 범위의 가장 낮은 주파수로 고정합니다(intel_pstate의 같은 이름 알고리즘은 부하에 따라 조절).',
      more: '베어메탈 IDC 서버는 BIOS(펌웨어)의 전원 설정과 OS 설정을 함께 봅니다. 클라우드에서는 일부 인스턴스 종류만 OS가 C-state·주파수를 바꿀 수 있습니다(AWS 기준). Red Hat 계열의 tuned latency-performance 프로필은 governor를 performance로 두고 PM QoS로 얕은 C-state만 쓰게 합니다. 절전을 끄면 전력 소비가 늘어나니 지연에 민감한 서버에만 적용합니다.',
      own: ['sys'],
      act: { infra: 'BIOS 전원 설정을 성능 쪽으로, OS governor를 performance로(cpufreq의 scaling_governor), 지연에 민감한 서버는 깊은 C-state 제한(tuned latency-performance 프로필, PM QoS의 /dev/cpu_dma_latency, 커널 파라미터 intel_idle.max_cstate), 바꾼 뒤 같은 데이터센터 안 왕복 시간·틱 시간 지터와 전력 사용을 함께 비교.' },
      sig: { k: 'high', g: '같은 데이터센터 안 왕복 시간, 코어 주파수' },
      chk: {
        look: 'cpupower monitor로 코어별 C-state에 머문 비율과 실제 주파수를 보고, /sys/devices/system/cpu/cpu0/cpuidle/ 아래 state마다 name·latency(깨어나는 데 걸리는 µs)·usage, cpufreq의 scaling_governor, tuned-adm active로 현재 프로필을 확인',
        yes: '코어가 한산할 때 가장 깊은 C-state에 오래 머물거나 주파수가 최저 근처에 묶여 있고, performance governor·얕은 C-state로 바꾸면 작은 요청의 왕복 시간과 지터가 줄어듦',
        no: '바꿔도 차이가 수십 µs 안쪽이면 이 원인은 무시해도 됨. ms 단위로 튀면 “CPU 스틸 (가상 머신)”이나 다른 층',
        by: 'ops',
      },
      ref: [
        { t: 'CPU Idle Time Management', u: 'https://docs.kernel.org/admin-guide/pm/cpuidle.html', p: 'Linux kernel', n: '절전 상태마다 깨어나는 시간(exit latency)과 최소 머무름 시간(target residency)이 있고, 예상 유휴 시간에 맞춰 깊은 상태를 고름, sysfs의 state별 latency·usage·time, PM QoS(/dev/cpu_dma_latency)와 intel_idle.max_cstate로 깊은 상태 제한' },
        { t: 'drivers/idle/intel_idle.c (Linux v6.12)', u: 'https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/idle/intel_idle.c?h=v6.12', p: 'Linux kernel', n: '인텔 서버 CPU의 C-state별 깨어나는 시간: Skylake C1 2µs·C1E 10µs·C6 133µs, Ice Lake C6 170µs, Sapphire Rapids C1 1µs·C6 290µs' },
        { t: 'CPU Performance Scaling', u: 'https://docs.kernel.org/admin-guide/pm/cpufreq.html', p: 'Linux kernel', n: 'scaling_governor로 governor 확인·변경, performance는 허용 범위의 가장 높은 주파수, powersave는 가장 낮은 주파수를 요청' },
        { t: 'intel_pstate CPU Performance Scaling Driver', u: 'https://docs.kernel.org/admin-guide/pm/intel_pstate.html', p: 'Linux kernel', n: 'intel_pstate의 powersave 알고리즘은 범용 powersave governor와 다르게 부하에 따라 조절(schedutil·ondemand와 비슷)' },
        { t: 'Chapter 2. Getting started with TuneD', u: 'https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html/monitoring_and_managing_system_status_and_performance/getting-started-with-tuned_monitoring-and-managing-system-status-and-performance', p: 'Red Hat', n: 'latency-performance 프로필은 절전 기능을 끄고 governor를 performance로, PM QoS로 얕은 C-state만 쓰게 함, tuned-adm active로 현재 프로필 확인' },
        { t: 'tools/power/cpupower/man/cpupower-monitor.1 (Linux v6.12)', u: 'https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/tools/power/cpupower/man/cpupower-monitor.1?h=v6.12', p: 'Linux kernel', n: 'cpupower monitor: 코어별 주파수와 절전 상태 통계' },
        { t: 'Processor state control for Amazon EC2 Linux instances', u: 'https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/processor_state_control.html', p: 'AWS', n: '일부 인스턴스 종류만 OS가 C-state·P-state를 제어할 수 있고 지연을 줄이려고 바꿀 수 있음, Graviton은 고정 주파수라 OS가 제어하지 않음' },
      ] },
    { id: 'so-oom', t: 'OOM 킬러', en: 'Out-of-memory killer',
      s: '리눅스는 메모리가 바닥나면 메모리를 가장 많이 쓰는 프로세스를 골라 강제로 죽입니다. 대개 게임 서버입니다.',
      c: ['누수나 폭증으로 메모리 고갈, 또는 컨테이너 메모리 한도 도달', '커널이 게임 서버 프로세스를 강제 종료', '그 서버의 모두가 동시에 접속 끊김, 최근 진행 롤백 가능'],
      sym: ['disconnect', 'dropped'], fx: ['stall'], who: ['server'], when: ['uptime', 'event'],
      num: '커널 로그(dmesg)에 “Out of memory: Killed process”가 남고, 쿠버네티스에서는 OOMKilled로 보입니다. 윈도우에는 OOM 킬러가 없고, 메모리 할당이 실패하면서 서버가 오류로 죽는 경우가 많습니다.',
      own: ['srv', 'sys'],
      act: { game: '누수 수정, 메모리 사용 상한을 두고 가까워지면 저장 후 정상 종료하는 절차.', infra: '메모리 경보, 컨테이너 메모리 한도를 실제 사용량에 맞게 설정, 먼저 죽일 순서 조정(oom_score_adj).' },
      sim: 'leak',
      sig: { k: 'drop', g: '접속 수, 메모리 사용량' },
      chk: {
        look: 'dmesg의 “Out of memory: Killed process” 기록, 쿠버네티스면 파드 상태의 OOMKilled, cgroup v2면 memory.events의 oom_kill 증가를 접속이 끊긴 시각과 맞춰 봄',
        yes: '접속이 한꺼번에 끊긴 시각에 게임 서버 프로세스를 죽인 기록이 있고, 그 직전까지 메모리 사용량이 한도로 올라감',
        no: 'OOM 기록이 없는데 프로세스가 죽었으면 “서버 크래시”의 크래시 로그·코어 덤프를 봄',
        by: 'ops',
      },
      ref: [
        { t: 'mm/oom_kill.c (Linux v6.12)', u: 'https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/mm/oom_kill.c?h=v6.12', p: 'Linux kernel', n: '메모리를 가장 많이 쓰는 프로세스가 가장 높은 점수를 받도록 계산(oom_score_adj 반영), 종료할 때 “Out of memory: Killed process …” 기록' },
        { t: 'Assign Memory Resources to Containers and Pods', u: 'https://kubernetes.io/docs/tasks/configure-pod-container/assign-memory-resource/', p: 'Kubernetes', n: '컨테이너가 메모리 limit을 넘어 계속 쓰면 종료되고 상태가 OOMKilled로 표시됨' },
        { t: 'Pushing the Limits of Windows: Virtual Memory', u: 'https://learn.microsoft.com/en-us/archive/blogs/markrussinovich/pushing-the-limits-of-windows-virtual-memory', p: 'Microsoft', n: '윈도우는 커밋 한도에 닿으면 메모리를 확정하는 할당이 실패하고, 앱 오류나 시스템 장애로 이어질 수 있음' },
        { t: 'Control Group v2', u: 'https://docs.kernel.org/admin-guide/cgroup-v2.html', p: 'Linux kernel', n: 'memory.events의 oom_kill: 이 cgroup에서 OOM 킬러가 죽인 프로세스 수' },
      ] },
    { id: 'so-reclaim', t: '메모리 회수·컴팩션으로 인한 멈춤', en: 'Memory compaction / reclaim stalls (THP)',
      s: 'OS가 큰 페이지(huge page)를 만들려고 메모리를 컴팩션하거나 여유 메모리를 회수하는 동안 프로세스가 멈춥니다.',
      c: ['여유 메모리가 줄거나 큰 페이지 기능(THP)이 메모리 컴팩션 실행', '메모리를 요청한 스레드가 회수·컴팩션이 끝날 때까지 대기', '불규칙한 서버 멈춤(수 ms~수백 ms)'],
      sym: ['freeze', 'stutter'], fx: ['stall'], who: ['server'], when: ['uptime', 'random'],
      own: ['sys', 'srv'],
      act: { game: '실행 중 큰 메모리 할당 줄이기(시작할 때 미리 확보해 재사용).', infra: '큰 페이지(THP)는 필요한 곳에만 쓰게(madvise) 설정, 여유 메모리 기준 높이기(vm.min_free_kbytes 등).' },
      sig: { k: 'random', g: '서버 틱 시간, 메모리 PSI' },
      chk: {
        look: '/proc/pressure/memory의 some·full(메모리를 기다리며 멈춘 시간 비율)과 /proc/vmstat의 compact_stall 증가량을 서버 틱 시간과 함께 보고, /sys/kernel/mm/transparent_hugepage/defrag 설정을 확인',
        yes: '틱이 튄 시각에 메모리 PSI가 오르고 compact_stall이 늘어남. defrag가 always',
        no: 'PSI와 compact_stall이 그대로면 이 원인이 아님. 스왑 사용이 늘면 “스왑”',
        by: 'ops',
      },
      ref: [
        { t: 'Transparent Hugepage Support', u: 'https://docs.kernel.org/admin-guide/mm/transhuge.html', p: 'Linux kernel', n: 'defrag=always면 THP 할당에 실패할 때 그 자리에서 메모리 회수·컴팩션을 하며 멈춤, madvise는 요청한 영역만 그렇게 함' },
        { t: 'Documentation for /proc/sys/vm/', u: 'https://docs.kernel.org/admin-guide/sysctl/vm.html', p: 'Linux kernel', n: 'min_free_kbytes: 커널이 남겨 둘 최소 여유 메모리(워터마크) 기준' },
        { t: 'PSI - Pressure Stall Information', u: 'https://docs.kernel.org/accounting/psi.html', p: 'Linux kernel', n: '/proc/pressure/memory의 some(일부 작업이 메모리를 기다리며 멈춘 시간 비율)·full(모든 작업이 멈춘 시간 비율)' },
      ] },
    { id: 'so-timejump', t: '시스템 시계 점프 (NTP 스텝)', en: 'Wall-clock jump (NTP step)',
      s: '서버 시계가 한 번에 몇 초 앞뒤로 조정되면 시스템 시계에 의존하는 타이머가 한꺼번에 발동하거나 멈춥니다.',
      c: ['시간 동기화가 시계를 한 번에 크게 조정', '타이머가 몰아서 발동하거나 멈추고, 타임아웃이 잘못 판정됨', '버프·쿨타임 이상, 일제히 접속 끊김, 몰아치기'],
      sym: ['burst', 'disconnect', 'dropped'], fx: ['stall'], who: ['server'], when: ['random'],
      num: 'ntpd는 차이가 0.128초를 넘으면 한 번에 맞추고, 그보다 작으면 1초 차이를 없애는 데 30분 남짓 걸리는 속도로 서서히 맞춥니다. 요즘 많이 쓰는 chrony는 권장 설정(makestep)에서 켜진 직후 몇 번만 한 번에 맞추고, 그 뒤에는 서서히 맞춥니다. 가상 머신이 잠깐 멈췄다 깨어날 때도 시계가 뜁니다.',
      own: ['srv', 'sys'],
      act: { game: '경과 시간·타임아웃·쿨타임은 뛰거나 되돌아가지 않는 단조 시계(monotonic clock)로 계산, wall clock은 표시·기록용으로만.', infra: '시계는 서서히 조정(chrony의 makestep은 켜진 직후에만), 시간 동기화 상태(시계 차이) 모니터링.' },
      sig: { k: 'random', g: '타이머 발동 수·끊김 수, 시계 조정 기록' },
      chk: {
        look: '시간 동기화 서비스의 로그에서 시계를 한 번에 크게 조정한 기록을 찾아 이상이 난 시각과 맞춰 봄. chrony는 logchange에 정한 값(기본 1초)보다 크게 조정하면 syslog에 남김',
        yes: '버프·쿨타임 이상, 일제히 접속 끊김, 몰아치기가 난 시각에 시계 조정 기록이 있고, 조정 폭이 이상의 크기와 비슷함',
        no: '시계 조정 기록이 없으면 이 원인이 아님. 가상 머신이면 멈췄다 깨어난 경우(“클라우드 호스트 점검·라이브 마이그레이션”)도 봄',
        by: 'ops',
      },
      ref: [
        { t: 'ntpd - Network Time Protocol (NTP) daemon', u: 'https://www.ntp.org/documentation/4.2.8-series/ntpd/', p: 'Network Time Foundation', n: '차이가 스텝 임계값 128ms를 넘으면 한 번에 맞추고 작으면 서서히 맞춤, 초당 0.5ms씩이라 1초를 맞추는 데 2,000초(약 33분) 걸림' },
        { t: 'chrony – Frequently Asked Questions', u: 'https://chrony-project.org/faq.html', p: 'chrony', n: 'makestep 1 3처럼 시작 직후 몇 번만 스텝을 허용하는 것이 권장, 멈췄다 재개한 가상 머신은 시각이 틀어진 채 깨어날 수 있음' },
        { t: 'clock_gettime(2) — Linux manual page', u: 'https://man7.org/linux/man-pages/man2/clock_gettime.2.html', p: 'Linux man-pages', n: 'CLOCK_MONOTONIC은 시스템 시계의 불연속 점프에 영향받지 않고 뒤로 가지 않음' },
        { t: 'chrony.conf(5)', u: 'https://chrony-project.org/doc/4.6/chrony.conf.html', p: 'chrony', n: 'logchange: 이 값(기본 1초)보다 크게 시계를 조정하면 syslog에 기록' },
      ] },
    { id: 'so-cron', t: '예약 작업', en: 'Cron jobs (log rotation, backup, scans)',
      s: '매일 같은 시각에 도는 로그 압축·백업·보안 검사가 CPU와 디스크를 차지합니다.',
      c: ['정해진 시각에 OS 작업이 실행', 'CPU·디스크를 게임 서버와 나눠 씀', '매일 새벽 4시처럼 정해진 시각에 뚝뚝 끊김·슬로우모션'],
      sym: ['stutter', 'slowmo'], fx: ['stall'], who: ['server'], when: ['periodic'],
      own: ['sys'],
      act: { infra: '작업 시각 분산, 우선순위 낮추기(nice, ionice), 게임 서버와 분리(별도 서버에서 실행).' },
      sig: { k: 'periodic', g: 'CPU 사용률, 디스크 대기열, 서버 틱 시간' },
      chk: {
        look: 'crontab과 systemctl list-timers로 예약 작업의 실행 시각을 모으고, 틱이 튄 시각에 pidstat -u -d로 어떤 프로세스가 CPU·디스크를 쓰는지 봄',
        yes: '틱이 매일(또는 매시) 같은 시각에 튀고, 그 시각에 예약 작업 프로세스가 CPU·디스크를 차지함',
        no: '튀는 시각이 매일 같은 시각과 맞지 않으면 이 원인이 아님. 몇 초·몇 분 간격으로 튀면 “서버 GC 전체 멈춤”, “타이머 동시 발동 몰림”',
        by: 'ops',
      },
      ref: [
        { t: 'ionice(1) — Linux manual page', u: 'https://man7.org/linux/man-pages/man1/ionice.1.html', p: 'util-linux', n: 'idle 클래스 작업은 다른 프로그램이 디스크를 쓰지 않을 때만 I/O를 받음' },
        { t: 'systemd.timer(5) — Linux manual page', u: 'https://man7.org/linux/man-pages/man5/systemd.timer.5.html', p: 'systemd', n: 'RandomizedDelaySec로 예약 작업 시각을 무작위로 늦춰 부하 몰림을 줄임' },
        { t: 'systemctl(1) — Linux manual page', u: 'https://man7.org/linux/man-pages/man1/systemctl.1.html', p: 'systemd', n: 'list-timers: 타이머 유닛을 다음 실행 시각 순으로 보여 줌' },
        { t: 'pidstat(1) — Linux manual page', u: 'https://man7.org/linux/man-pages/man1/pidstat.1.html', p: 'sysstat', n: '-u는 CPU, -d는 디스크 I/O를 프로세스별로 보여 줌' },
      ] },
    { id: 'so-os-update', t: 'OS·커널·드라이버·펌웨어 업데이트 뒤 성능 변화', en: 'Performance regression after OS / kernel / driver / firmware update',
      s: '게임 코드는 그대로인데 서버 OS·커널·드라이버·펌웨어를 업데이트한 뒤부터 느려지는 경우입니다. 업데이트로 기본값, 스케줄러, CPU 취약점 완화(mitigations), 드라이버 동작이 바뀌기도 합니다.',
      c: ['정기 보안 패치나 새 서버 이미지로 커널·드라이버·펌웨어가 바뀜', '기본값·스케줄러가 바뀌거나 새 취약점 완화가 켜져, 같은 일에 CPU 시간이 더 들고 스레드가 CPU를 배정받는 순서가 달라짐', '잘되던 서버가 업데이트한 날부터 늘 조금씩 느려져 입력 지연, 사람이 몰리면 뚝뚝 끊김·슬로우모션'],
      sym: ['delay', 'stutter', 'slowmo'], fx: ['lat', 'stall', 'jit'], who: ['server'], when: ['always', 'event'],
      num: '커널 버전이 바뀌면 기본 동작도 바뀝니다. 예를 들어 리눅스는 6.6부터 스케줄러를 CFS에서 EEVDF로 옮겨 가기 시작했고, 접속 대기열 상한(somaxconn) 기본값도 5.4부터 128에서 4,096으로 바뀌었습니다. CPU 취약점 완화는 컨텍스트 스위칭이나 가상 머신 전환 때 CPU 내부 버퍼를 비우는 등 일을 더하고, 일부 완화는 SMT(코어 하나를 스레드 두 개처럼 쓰는 기능)를 꺼야 해서 작업에 따라 성능에 큰 영향을 줍니다. 커널 파라미터 mitigations=off는 이 완화를 모두 꺼 성능을 되찾지만 취약점에 노출됩니다.',
      more: '완화 상태는 /sys/devices/system/cpu/vulnerabilities/ 아래 파일에서 확인합니다. 기본값(mitigations=auto)은 SMT를 켜 둔 채 완화하지만, auto,nosmt로 두면 필요할 때 SMT를 꺼서 업그레이드 뒤 논리 코어 수가 줄 수 있습니다. 게임 패치와 같은 날 OS를 업데이트하면 원인을 가리기 어려우니 따로 배포합니다.',
      own: ['sys'],
      act: { infra: '업데이트는 일부 서버에 먼저 적용하고 틱 시간·지연·CPU 사용률을 이전 버전과 비교한 뒤 넓히기, 게임 패치와 다른 날 배포, 업데이트 전후 커널·드라이버·펌웨어 버전과 주요 sysctl 값 기록, 문제가 생기면 이전 커널로 부팅해 확인, 완화를 끄는 설정(mitigations=off)은 보안 위험을 따져 결정.' },
      sig: { k: 'step', g: '서버 틱 시간, CPU 사용률, 같은 부하의 지연' },
      chk: {
        look: '패키지 관리자의 업데이트 기록과 재부팅 시각, uname -r로 본 커널 버전을 지연이 오른 시각과 맞춰 봄. 업데이트한 서버와 안 한 서버를 같은 부하에서 mpstat·pidstat로 비교하고, /sys/devices/system/cpu/vulnerabilities/의 완화 상태도 비교',
        yes: '지연·CPU 사용률이 업데이트 뒤 재부팅한 시각부터 한 단계 올라 그대로 머물고, 같은 부하에서 업데이트한 서버만 높음. 이전 커널·드라이버로 부팅하면 돌아옴',
        no: '같은 시각에 게임 서버 배포가 있었으면 “배포·재시작”부터 분리해서 봄. 업데이트한 서버와 안 한 서버가 똑같이 느리면 이 원인이 아님',
        by: 'ops',
      },
      ref: [
        { t: 'The kernel’s command-line parameters', u: 'https://docs.kernel.org/admin-guide/kernel-parameters.html', p: 'Linux kernel', n: 'mitigations=: off는 CPU 취약점 완화를 모두 꺼 성능을 높이지만 취약점에 노출, 기본 auto는 SMT를 켠 채 완화, auto,nosmt는 필요하면 SMT를 끔' },
        { t: 'MDS - Microarchitectural Data Sampling', u: 'https://docs.kernel.org/admin-guide/hw-vuln/mds.html', p: 'Linux kernel', n: '/sys/devices/system/cpu/vulnerabilities/ 아래 파일로 취약점·완화 상태 확인, 완전히 막으려면 SMT를 꺼야 하는 CPU가 많고 SMT를 끄면 작업에 따라 성능 영향이 큼' },
        { t: 'Spectre Side Channels', u: 'https://docs.kernel.org/admin-guide/hw-vuln/spectre.html', p: 'Linux kernel', n: '완화를 위해 컨텍스트 스위칭·가상 머신 전환 때 분기 예측 버퍼를 비우고, 강한 완화는 모든 프로그램에 오버헤드를 더함' },
        { t: 'EEVDF Scheduler', u: 'https://docs.kernel.org/scheduler/sched-eevdf.html', p: 'Linux kernel', n: '리눅스는 6.6부터 CFS에서 EEVDF 스케줄러로 옮겨 가기 시작' },
        { t: 'listen(2) — Linux manual page', u: 'https://man7.org/linux/man-pages/man2/listen.2.html', p: 'Linux man-pages', n: 'somaxconn 기본값이 리눅스 5.4부터 128에서 4,096으로 바뀜' },
      ] },
    { id: 'so-conntrack', t: '서버 conntrack 테이블 포화', en: 'conntrack table full',
      s: '리눅스 방화벽이 모든 연결을 기록하는 연결 추적(conntrack) 테이블이 한도에 닿으면 새 패킷을 버립니다.',
      c: ['접속 폭주, 짧은 연결 반복으로 연결 기록 증가', '테이블이 가득 차 새 연결과 일부 패킷 폐기', '접속 불가, 원인 모를 손실로 순간이동'],
      sym: ['noconnect', 'teleport'], fx: ['loss'], who: ['server'], when: ['login', 'event'],
      num: '기본 한도는 서버 메모리에 따라 약 6만~26만 개입니다. 넘치면 커널 로그에 “nf_conntrack: table full, dropping packet”이 찍힙니다.',
      own: ['sys', 'srv', 'cli'],
      act: { game: '서버: 짧은 연결 줄이기(서버 간 호출은 연결 재사용). 클라이언트: 접속이 실패하거나 끊기면 재시도 간격을 늘려 가며 무작위로 분산.', infra: '테이블 크기(nf_conntrack_max) 늘리기, 게임 포트는 추적 제외(raw 테이블의 NOTRACK), 사용량 경보.' },
      sig: { k: 'ceiling', g: 'conntrack 항목 수(nf_conntrack_count)' },
      chk: {
        look: 'sysctl의 net.netfilter.nf_conntrack_count(현재 항목 수)를 nf_conntrack_max와 같은 그래프에 놓고, dmesg에서 “nf_conntrack: table full, dropping packet”을 찾음',
        yes: 'nf_conntrack_count가 max에서 평평해지고, 그 시각부터 커널 로그에 table full이 찍힘',
        no: '항목 수가 max에 한참 못 미치면 이 원인이 아님. AWS 인스턴스 자체의 연결 추적 한도는 “클라우드 PPS 한도 초과”의 conntrack_allowance_exceeded로 봄',
        by: 'ops',
      },
      ref: [
        { t: 'Netfilter Conntrack Sysfs variables', u: 'https://docs.kernel.org/networking/nf_conntrack-sysctl.html', p: 'Linux kernel', n: 'nf_conntrack_max 기본값은 해시 버킷 수(nf_conntrack_buckets)와 같고, 버킷 수는 메모리 크기로 정해짐' },
        { t: 'net/netfilter/nf_conntrack_core.c (Linux v6.12)', u: 'https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/net/netfilter/nf_conntrack_core.c?h=v6.12', p: 'Linux kernel', n: '기본 크기는 메모리 1GB 초과면 65,536, 4GB 초과(64비트)면 262,144, 가득 차면 “nf_conntrack: table full, dropping packet”을 남기고 버림' },
        { t: 'iptables-extensions(8) — Linux manual page', u: 'https://man7.org/linux/man-pages/man8/iptables-extensions.8.html', p: 'netfilter', n: 'raw 테이블의 CT --notrack으로 연결 추적 제외' },
      ] },
    { id: 'so-ports', t: '서버 간 연결의 임시 포트 고갈', en: 'Ephemeral port exhaustion (TIME_WAIT)',
      s: '게임 서버가 DB나 다른 서버에 연결을 짧게 자주 맺고 끊으면, 끊긴 연결이 한동안 포트를 점유해 새 연결을 못 엽니다.',
      c: ['요청마다 새 연결을 열고 닫음', '먼저 닫은 쪽이 약 60초(리눅스) 동안 포트를 점유해(TIME_WAIT) 쓸 포트가 바닥', '내부 요청 실패로 저장 실패·기능 오류'],
      sym: ['dropped', 'noconnect'], fx: ['loss'], who: ['server', 'feature'], when: ['event'],
      num: '리눅스 기본 포트 범위(32768~60999)는 약 2만 8천 개. 같은 상대 주소로 1초에 470번 넘게 새로 연결하면 바닥납니다. 윈도우는 기본 포트가 약 1만 6천 개(49152~65535)이고 TIME_WAIT도 더 길어 더 빨리 바닥납니다.',
      own: ['srv', 'sys'],
      act: { game: '연결 재사용(커넥션 풀), 요청마다 연결을 새로 열고 닫지 않게.', infra: '포트 범위 확장(ip_local_port_range), 나가는 연결의 TIME_WAIT 재사용(리눅스 tcp_tw_reuse) 검토, TIME_WAIT 수 감시.' },
      more: '리눅스의 TIME_WAIT 60초는 커널에 고정된 값입니다. 이름이 비슷한 tcp_fin_timeout을 줄여도 TIME_WAIT는 짧아지지 않습니다.',
      sig: { k: 'ceiling', g: 'TIME_WAIT 소켓 수, 내부 연결 실패 수' },
      chk: {
        look: 'ss -tan state time-wait로 TIME_WAIT 소켓을 상대 주소별로 세고, 게임 서버 로그에서 connect 실패(EADDRNOTAVAIL)를 찾음',
        yes: '같은 상대(DB 등)로 가는 TIME_WAIT가 임시 포트 범위(기본 약 2만 8천 개) 근처에서 평평해지고, connect가 EADDRNOTAVAIL로 실패함',
        no: 'TIME_WAIT가 적은데 외부로 나가는 연결만 실패하면 “클라우드 NAT 게이트웨이 연결·포트 한도”',
        by: 'ops',
      },
      ref: [
        { t: 'IP Sysctl', u: 'https://docs.kernel.org/networking/ip-sysctl.html', p: 'Linux kernel', n: 'ip_local_port_range 기본 32768~60999, tcp_tw_reuse, tcp_fin_timeout은 FIN_WAIT_2 상태 유지 시간' },
        { t: 'include/net/tcp.h (Linux v6.12)', u: 'https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/net/tcp.h?h=v6.12', p: 'Linux kernel', n: 'TCP_TIMEWAIT_LEN(60*HZ): TIME_WAIT 약 60초는 커널 상수' },
        { t: 'TCP/IP port exhaustion troubleshooting', u: 'https://learn.microsoft.com/en-us/troubleshoot/windows-client/networking/tcp-ip-port-exhaustion-troubleshooting', p: 'Microsoft', n: '윈도우 동적 포트 기본 49152~65535, 닫힌 연결은 기본 4분 동안 TIME_WAIT로 포트를 잡고 있음' },
        { t: 'ss(8) — Linux manual page', u: 'https://man7.org/linux/man-pages/man8/ss.8.html', p: 'iproute2', n: '상태 필터 state time-wait로 TIME_WAIT 소켓만 골라 봄' },
        { t: 'connect(2) — Linux manual page', u: 'https://man7.org/linux/man-pages/man2/connect.2.html', p: 'Linux man-pages', n: 'EADDRNOTAVAIL: 임시 포트 범위의 포트가 모두 쓰이는 중이라 연결을 열지 못함' },
      ] },
  ]);

  /* ---------------- 8. 소켓과 프로토콜 ---------------- */
  add('socket', [
    { id: 'sk-hol', t: 'TCP HOL 블로킹', en: 'Head-of-line blocking',
      s: 'TCP는 순서를 지키려고, 잃어버린 패킷 하나를 다시 받을 때까지 뒤에 도착한 패킷을 게임에 넘기지 않습니다.',
      c: ['패킷 하나가 사라짐', '뒤 패킷들은 도착했지만 수신 버퍼에서 대기', '멈췄다가 한꺼번에 풀리며 몰아치기'],
      sym: ['freeze', 'burst'], fx: ['loss', 'stall'], who: ['me'], when: ['random'],
      num: '패킷 하나를 잃으면 최소 왕복 시간 + α, 재전송까지 잃으면 수백 ms~수 초 멈춥니다.',
      own: ['srv', 'cli'],
      act: { game: '서버: 실시간 위치는 UDP, 꼭 필요한 것만 신뢰성 전송, 스트림 여러 개로 나누기. 클라이언트: 서버와 같은 방식(UDP, 채널 분리)으로 네트워크 처리 변경.' },
      sim: 'hol',
      sig: { k: 'gap', g: '연결별 수신량, 재전송 수' },
      chk: {
        look: '서버 쪽 패킷 캡처(tcpdump·Wireshark)로 그 유저 연결에서 재전송 패킷과 그 앞뒤의 공백을 보고, 서버 전체는 nstat -az의 TcpRetransSegs 증가량을 봄',
        yes: '멈춘 구간이 패킷 하나의 재전송으로 시작하고, 재전송 패킷이 도착한 직후 밀린 데이터가 한꺼번에 처리됨(수신량이 0이다가 몰림)',
        no: 'UDP로 통신하는 게임이면 해당 없음. 재전송이 없는데 멈추면 서버 틱 쪽(“틱 예산 초과”)을 봄',
        by: 'ops',
      },
      ref: [
        { t: 'RFC 9293: Transmission Control Protocol (TCP)', u: 'https://www.rfc-editor.org/rfc/rfc9293', p: 'IETF', n: 'TCP는 신뢰성 있는, 순서를 지키는 바이트 스트림 서비스' },
        { t: 'RFC 5681: TCP Congestion Control', u: 'https://www.rfc-editor.org/rfc/rfc5681', p: 'IETF', n: '중복 ACK 3개로 손실을 감지해 빠른 재전송, 그렇지 않으면 재전송 타이머를 기다림' },
        { t: 'RFC 6298: Computing TCP\'s Retransmission Timer', u: 'https://www.rfc-editor.org/rfc/rfc6298', p: 'IETF', n: '재전송 타이머가 만료될 때마다 두 배로 늘리는 백오프' },
        { t: 'net/ipv4/proc.c (Linux v6.12)', u: 'https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/net/ipv4/proc.c?h=v6.12', p: 'Linux kernel', n: 'nstat이 보여 주는 카운터 이름: Tcp 그룹의 RetransSegs(재전송한 세그먼트 수)' },
      ] },
    { id: 'sk-rto', t: 'TCP RTO와 지수 백오프', en: 'RTO and exponential backoff',
      s: '재전송이 또 실패할 때마다 기다리는 시간이 두 배로 늘어, 짧은 회선 끊김이 긴 멈춤이 됩니다.',
      c: ['회선이 잠깐 끊겨 재전송도 연달아 실패', '다음 시도까지 0.3 → 0.6 → 1.2 → 2.4초처럼 두 배씩 늘어남(핑 100ms 기준)', '회선은 1초 끊겼는데 게임은 2초 넘게 멈춤. 더 길게 끊기면 결국 접속 끊김'],
      sym: ['freeze', 'disconnect'], fx: ['loss', 'stall'], who: ['me'], when: ['random', 'moving'],
      num: '리눅스 RTO(재전송 대기 시간)는 “핑 + 200ms”가 최소이고, 연결을 맺을 때는 1초부터 시작합니다. 기본 설정(tcp_retries2=15)이면 재전송이 계속 실패해도 약 15분 뒤에야 연결을 포기합니다.',
      own: ['srv', 'cli'],
      act: { game: '서버: 하트비트에 응답하고, 일정 시간 못 받으면 연결을 먼저 정리(TCP_USER_TIMEOUT으로 포기 시점 줄이기), 세션 토큰으로 이어 받기, 신뢰성 UDP. 클라이언트: 짧은 간격으로 하트비트를 보내고 응답이 끊기면 TCP 재전송을 기다리지 말고 빨리 재접속.' },
      sim: 'hol',
      sig: { k: 'gap', g: '연결별 RTO·backoff, RTO 만료 수' },
      chk: {
        look: '멈춘 연결을 ss -ti로 보고 rto(재전송 대기 ms)와 backoff(연속 만료 횟수)를, 서버 전체는 nstat -az의 TcpExtTCPTimeouts(재전송 타이머 만료 횟수) 증가량을 봄',
        yes: '멈춘 연결의 backoff가 1 이상이고 rto가 초 단위로 커져 있으며, 그 시각 TCPTimeouts가 늘어남',
        no: '재전송이 빠른 재전송으로 끝나고 RTO 만료가 없으면 멈춤이 짧음. 그때는 “TCP HOL 블로킹”',
        by: 'ops',
      },
      ref: [
        { t: 'RFC 6298: Computing TCP\'s Retransmission Timer', u: 'https://www.rfc-editor.org/rfc/rfc6298', p: 'IETF', n: '첫 RTO 1초, 타이머가 만료될 때마다 RTO를 두 배로(지수 백오프)' },
        { t: 'net/ipv4/tcp_input.c (Linux v6.12)', u: 'https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/net/ipv4/tcp_input.c?h=v6.12', p: 'Linux kernel', n: '리눅스 RTO = 평활 RTT + RTT 변동값이고 변동값의 하한이 tcp_rto_min(200ms)이라 RTO는 RTT+200ms 이상' },
        { t: 'IP Sysctl', u: 'https://docs.kernel.org/networking/ip-sysctl.html', p: 'Linux kernel', n: 'tcp_rto_min_us 기본 200ms, 접속 요청의 첫 RTO 1초, tcp_retries2=15면 포기까지 최소 924.6초(약 15분)' },
        { t: 'ss(8) — Linux manual page', u: 'https://man7.org/linux/man-pages/man8/ss.8.html', p: 'iproute2', n: '-i의 rto(재전송 타이머, ms)와 backoff(지수 백오프 횟수)' },
        { t: 'net/ipv4/proc.c (Linux v6.12)', u: 'https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/net/ipv4/proc.c?h=v6.12', p: 'Linux kernel', n: 'nstat이 보여 주는 카운터 이름: TcpExt 그룹의 TCPTimeouts' },
        { t: 'net/ipv4/tcp_timer.c (Linux v6.12)', u: 'https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/net/ipv4/tcp_timer.c?h=v6.12', p: 'Linux kernel', n: '재전송 타이머가 만료될 때마다 TCPTimeouts를 올리고, backoff를 하나 늘리며 RTO를 두 배로(최대값까지) 늘림' },
      ] },
    { id: 'sk-nagle', t: 'Nagle 알고리즘 + 지연 ACK', en: 'Nagle + delayed ACK (TCP_NODELAY off)',
      s: '작은 패킷을 모아 보내는 Nagle 알고리즘과 ACK를 늦게 보내는 지연 ACK가 맞물려, 메시지를 나눠 쓸 때마다 40~200ms씩 지연됩니다.',
      c: ['TCP_NODELAY를 켜지 않은 채 작은 메시지를 나눠 씀', '보내는 쪽은 ACK를 기다리고, 받는 쪽은 ACK를 늦게 보냄', '회선 핑은 낮은데 모든 행동이 일정하게 굼뜬 입력 지연'],
      sym: ['delay'], fx: ['lat'], who: ['server', 'me'], when: ['always', 'action'],
      num: '지연 ACK는 리눅스가 보통 40ms(상황에 따라 최대 200ms)입니다. 윈도우는 예전 버전이 200ms였고 요즘 버전은 40ms입니다(윈도우 서버 2019 기본 템플릿 40ms). 지연 ACK는 받는 쪽 OS가 정하므로, 서버가 Nagle을 켠 채 메시지를 나눠 보내면 받는 PC에 따라 40~200ms씩 지연될 수 있습니다.',
      own: ['srv', 'cli'],
      act: { game: '서버: TCP_NODELAY 켜기, 한 틱 동안의 메시지를 모아 한 번에 쓰기, 받는 쪽 지연 ACK를 끄는 방법(리눅스 TCP_QUICKACK은 잠깐만 유지, 윈도우는 PC마다 레지스트리 수정)은 게임이 확실히 통제할 수 없으니 기대지 않기. 클라이언트: TCP_NODELAY 켜기, 한 프레임 동안의 메시지를 모아 한 번에 쓰기.' },
      sim: 'nagle',
      sig: { k: 'high', g: '행동 응답 시간(게임 안 RTT)' },
      chk: {
        look: '서버 쪽 패킷 캡처(tcpdump·Wireshark)에서 요청·응답 사이의 간격을 보고, 서버·클라이언트 코드가 TCP_NODELAY를 켜는지 확인',
        yes: '회선 핑은 낮은데 작은 패킷 사이에 40ms(윈도우 예전 버전은 200ms) 안팎의 공백이 반복되고, 그 공백은 상대의 ACK가 온 직후 끝남. TCP_NODELAY를 켜면 사라짐',
        no: '응답 간격이 회선 핑과 비슷하면 이 원인이 아님. 게임 서버가 응답을 늦게 만들면 서버 처리 쪽(“메시지 큐 적체”)',
        by: 'ops',
      },
      ref: [
        { t: 'RFC 9293: Transmission Control Protocol (TCP)', u: 'https://www.rfc-editor.org/rfc/rfc9293', p: 'IETF', n: 'Nagle은 ACK를 못 받은 데이터가 있으면 작은 데이터를 모아 둠, 연결마다 끌 수 있어야 함, 지연 ACK는 0.5초 미만, 둘이 맞물리는 문제' },
        { t: 'include/net/tcp.h (Linux v6.12)', u: 'https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/net/tcp.h?h=v6.12', p: 'Linux kernel', n: '리눅스 지연 ACK 최소 TCP_DELACK_MIN(HZ/25 = 40ms), 최대 TCP_DELACK_MAX(HZ/5 = 200ms)' },
        { t: 'TCP improvements in the Windows network stack (IETF 98 TCPM)', u: 'https://datatracker.ietf.org/meeting/98/materials/slides-98-tcpm-tcp-improvements-in-windows-01', p: 'Microsoft', n: '윈도우 기본 지연 ACK 타임아웃을 40ms로 바꿈(2017년 발표)' },
        { t: 'TCP Templates for Windows Server 2019 – How to tune your Windows Server Transports (Advanced users only 😉)', u: 'https://techcommunity.microsoft.com/blog/networkingblog/tcp-templates-for-windows-server-2019-8211-how-to-tune-your-windows-server-trans/339795', p: 'Microsoft', n: '서버 2019 템플릿 DelayedAckTimeout 40ms, MaxSynRetransmissions 2, InitialRto 3000ms' },
        { t: 'Design issues - Sending small data segments over TCP with Winsock', u: 'https://learn.microsoft.com/en-us/previous-versions/troubleshoot/windows/win32/data-segment-tcp-winsock', p: 'Microsoft', n: '예전 윈도우 TCP는 데이터를 받으면 200ms 지연 ACK 타이머를 걸고, Nagle은 기본으로 켜져 있어 작은 패킷이 ACK를 기다림, TCP_NODELAY로 해결' },
      ] },
    { id: 'sk-block-send', t: '느린 클라이언트로 인한 블로킹 전송', en: 'Blocking send on a full socket',
      s: '회선이 느린 한 명의 송신 버퍼가 가득 찼는데 블로킹 방식(버퍼에 여유가 생길 때까지 호출이 반환되지 않는 전송)으로 보내면, 서버 스레드가 그 한 명을 기다립니다.',
      c: ['느린 클라이언트의 송신 버퍼가 가득', '블로킹 전송이라 서버 스레드가 버퍼에 여유가 생길 때까지 대기', '그 스레드가 맡은 모두가 멈춤·슬로우모션'],
      sym: ['freeze', 'slowmo'], fx: ['stall'], who: ['zone', 'server'], when: ['random', 'event'],
      own: ['srv'],
      act: { game: '논블로킹 전송, 클라이언트별 송신 대기열 상한, 오래된 업데이트 버리기.' },
      sim: 'sndbuf',
      sig: { k: 'random', g: '서버 틱 시간, 연결별 Send-Q' },
      chk: {
        look: 'ss -tn으로 연결별 Send-Q(ACK를 받지 못했거나 아직 못 보낸 바이트)가 송신 버퍼만큼 찬 연결을 찾고, 틱이 튄 순간 게임 서버의 스레드 덤프(스택)에서 send 호출에 멈춘 스레드가 있는지 봄',
        yes: 'Send-Q가 가득 찬 느린 연결이 있을 때 그 연결을 맡은 스레드가 send에서 멈춰 있고, 같은 스레드가 맡은 사람들만 함께 멈춤',
        no: '멈춘 스레드가 send 밖(락, DB 호출)에서 기다리면 “락 경합”, “게임 스레드의 동기 호출”',
        by: 'ops',
      },
      ref: [
        { t: 'send(2) — Linux manual page', u: 'https://man7.org/linux/man-pages/man2/send.2.html', p: 'Linux man-pages', n: '송신 버퍼에 자리가 없으면 send()가 블록되고, 논블로킹 모드면 EAGAIN으로 바로 돌아옴' },
        { t: 'send function (winsock2.h)', u: 'https://learn.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-send', p: 'Microsoft', n: 'Winsock도 버퍼 공간이 없으면 논블로킹 모드가 아닌 한 send가 블록' },
        { t: 'net/ipv4/tcp_diag.c (Linux v6.12)', u: 'https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/net/ipv4/tcp_diag.c?h=v6.12', p: 'Linux kernel', n: 'ss의 Recv-Q·Send-Q 값: 리슨 소켓은 accept를 기다리는 접속 수와 backlog 한도, 연결된 소켓은 앱이 아직 안 읽은 바이트와 ACK를 받지 못한 송신 바이트' },
      ] },
    { id: 'sk-slow-client', t: '느린 클라이언트(slow consumer) 처리 정책', en: 'Slow-consumer policy',
      s: '보낼 게 계속 쌓이는 클라이언트에게 서버가 오래된 업데이트를 버리거나 연결을 끊습니다.',
      c: ['클라이언트의 회선이 서버가 보내는 양을 못 따라감', '서버가 오래된 업데이트를 버리거나 한도 초과 시 연결 해제', '그 사람만 순간이동 또는 접속 끊김'],
      sym: ['teleport', 'disconnect'], fx: ['loss'], who: ['me'], when: ['event'],
      num: '송신 버퍼가 256KB면 30KB/s 회선에서는 8초 넘게 밀린 데이터가 쌓입니다. 리눅스는 이 버퍼를 자동으로 수 MB까지 키우기도 합니다.',
      own: ['srv'],
      act: { game: '보내는 양 줄이기(거리별 갱신 빈도), 품질 낮춰 계속 보내기, 커널에 쌓아 두는 양 줄이기(리눅스 TCP_NOTSENT_LOWAT).' },
      sim: 'sndbuf',
      sig: { k: 'outlier', g: '연결별 Send-Q, 클라이언트별 버린 업데이트 수' },
      chk: {
        look: '게임 서버가 남기는 클라이언트별 송신 대기열 길이·버린 업데이트 수·끊김 사유를 보고, 서버에서 ss -tni로 그 연결의 Send-Q와 cwnd를 함께 확인',
        yes: '튀거나 끊긴 사람의 연결만 Send-Q가 계속 차 있고, 게임 로그에 그 사람의 업데이트 폐기나 송신 대기열 초과로 인한 끊김이 기록됨',
        no: 'Send-Q가 비어 있는데 순간이동하면 서버 송신 쪽 문제가 아님. 그 사람의 회선 손실(“무선 구간 손실”)이나 화면 보간 쪽',
        by: 'code',
      },
      ref: [
        { t: 'IP Sysctl', u: 'https://docs.kernel.org/networking/ip-sysctl.html', p: 'Linux kernel', n: 'tcp_wmem: 자동 조절되는 송신 버퍼 최대치 기본 64KB~4MB(메모리에 따라), tcp_notsent_lowat·TCP_NOTSENT_LOWAT로 아직 안 보낸 데이터 양 제한' },
        { t: 'net/ipv4/tcp_diag.c (Linux v6.12)', u: 'https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/net/ipv4/tcp_diag.c?h=v6.12', p: 'Linux kernel', n: 'ss의 Recv-Q·Send-Q 값: 리슨 소켓은 accept를 기다리는 접속 수와 backlog 한도, 연결된 소켓은 앱이 아직 안 읽은 바이트와 ACK를 받지 못한 송신 바이트' },
      ] },
    { id: 'sk-keepalive', t: 'keepalive 기본값 2시간', en: 'TCP keepalive defaults',
      s: '상대가 종료 신호 없이 사라지면 TCP는 한참 뒤에야 감지합니다. keepalive(유휴 연결이 살아 있는지 확인하는 TCP 기능)는 기본으로 꺼져 있고, 켜도 2시간 동안 유휴 상태여야 확인을 시작합니다.',
      c: ['클라이언트가 전원 꺼짐·회선 끊김으로 종료 신호 없이 사라짐', '서버는 연결이 살아 있다고 간주(keepalive 기본 7,200초. 보내던 데이터가 있으면 재전송 포기까지 약 15분)', '유령 캐릭터가 남고, 재접속하면 “이미 접속 중” 오류'],
      sym: ['noconnect', 'invisible'], fx: ['loss'], who: ['me'], when: ['idle', 'login'],
      num: '리눅스 기본값은 7,200초 유휴 상태면 확인을 시작해 75초 간격으로 프로브를 9번 보내고, 끝까지 응답이 없으면 연결을 끊습니다. 합치면 약 2시간 11분입니다. 윈도우도 기본으로 2시간 유휴 상태여야 확인을 시작합니다.',
      own: ['srv', 'cli', 'sys'],
      act: { game: '서버: 하트비트에 응답하고, 일정 시간 못 받으면 연결을 먼저 정리(TCP_KEEPIDLE·TCP_USER_TIMEOUT 조정), 재접속하면 세션 토큰으로 기존 세션을 교체해 이어 받기. 클라이언트: 게임 수준 하트비트를 수 초~수십 초 간격(가장 짧은 유휴 타임아웃의 절반 이하)으로 보내기, 끊기면 자동 재접속.', infra: '코드가 따로 정하지 않는 소켓을 위해 커널 기본값(tcp_keepalive_time 등) 낮추기(SO_KEEPALIVE를 켠 소켓에만 적용).' },
      sim: 'timeouts',
      sig: { k: 'outlier', g: '연결별 마지막 수신 뒤 경과 시간' },
      chk: {
        look: 'ss -tnoi로 연결별 lastrcv(마지막 수신 뒤 경과 ms)와 keepalive 타이머(timer:(keepalive,…))를 보고, 게임 서버의 “이미 접속 중” 거절 기록과 맞춰 봄',
        yes: 'lastrcv가 수 분~수 시간인 ESTABLISHED 연결이 남아 있고, 그 계정의 재접속이 “이미 접속 중”으로 거절됨',
        no: '오래 조용한 연결이 없는데 “이미 접속 중”이 나오면 게임 서버의 세션 정리 코드 쪽',
        by: 'ops',
      },
      ref: [
        { t: 'tcp(7) — Linux manual page', u: 'https://man7.org/linux/man-pages/man7/tcp.7.html', p: 'Linux man-pages', n: '7,200초 유휴 뒤 75초 간격 프로브 9번(약 11분 추가), SO_KEEPALIVE를 켠 소켓에만 적용, TCP_KEEPIDLE·TCP_USER_TIMEOUT' },
        { t: 'RFC 9293: Transmission Control Protocol (TCP)', u: 'https://www.rfc-editor.org/rfc/rfc9293', p: 'IETF', n: 'keepalive는 기본으로 꺼져 있어야 하고, 유휴 간격 기본값은 2시간 이상' },
        { t: 'SO_KEEPALIVE socket option', u: 'https://learn.microsoft.com/en-us/windows/win32/winsock/so-keepalive', p: 'Microsoft', n: '윈도우 TCP keepalive 기본 타임아웃 2시간' },
        { t: 'ss(8) — Linux manual page', u: 'https://man7.org/linux/man-pages/man8/ss.8.html', p: 'iproute2', n: '-i의 lastrcv(마지막 수신 뒤 경과 ms), -o의 timer:(keepalive,…)' },
      ] },
    { id: 'sk-fragment', t: 'UDP 패킷의 IP 단편화', en: 'IP fragmentation of large UDP',
      s: 'MTU(한 번에 보낼 수 있는 크기)를 넘는 UDP 패킷은 IP 계층에서 단편화되고, 프래그먼트 하나만 잃어도 전체가 버려집니다.',
      c: ['사람 많은 곳의 스냅샷이 1,500바이트를 넘음', '여러 프래그먼트로 나뉘어 전송, 하나라도 잃으면 전체 폐기', '큰 패킷일수록 손실률이 몇 배. 붐비는 곳에서만 순간이동'],
      sym: ['teleport'], fx: ['loss'], who: ['zone', 'region'], when: ['event'],
      num: '손실 2%인 회선에서 프래그먼트 4개로 나뉜 패킷은 약 8%가 사라집니다. 단편화된 패킷을 아예 버리는 방화벽·통신사도 있어, 그 사용자는 큰 패킷을 하나도 받지 못합니다.',
      own: ['srv'],
      act: { game: '패킷을 1,200바이트 이하로 직접 나누기, 변경분만 보내기.' },
      sig: { k: 'load', g: 'IP 단편화 수(IpFragCreates), 스냅샷 크기' },
      chk: {
        look: '서버에서 nstat -az의 IpFragCreates(보내면서 만든 프래그먼트 수) 증가량을 보고, 받는 쪽은 IpReasmFails(재조립 실패 수)를 봄. 게임 서버 로그나 패킷 캡처로 UDP 패킷 크기 분포를 확인',
        yes: '사람이 몰리는 곳에서 IpFragCreates가 늘고, 1,500바이트를 넘는 UDP 패킷이 있으며, 그때 순간이동 제보가 늘어남',
        no: 'IpFragCreates가 늘지 않으면 서버가 보내는 쪽에서는 단편화가 일어나지 않음',
        by: 'ops',
      },
      ref: [
        { t: 'RFC 8085: UDP Usage Guidelines', u: 'https://www.rfc-editor.org/rfc/rfc8085', p: 'IETF', n: '프래그먼트 하나를 잃으면 재조립이 안 돼 패킷 전체를 잃음, UDP 앱은 IP 단편화를 피해야 함' },
        { t: 'RFC 8900: IP Fragmentation Considered Fragile', u: 'https://www.rfc-editor.org/rfc/rfc8900', p: 'IETF', n: '방화벽·일부 네트워크가 IP 프래그먼트를 버리는 사례' },
        { t: 'net/ipv4/proc.c (Linux v6.12)', u: 'https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/net/ipv4/proc.c?h=v6.12', p: 'Linux kernel', n: 'nstat이 보여 주는 카운터 이름: Ip 그룹의 FragCreates(만든 프래그먼트 수)·ReasmFails(재조립 실패 수)' },
      ] },
    { id: 'sk-reliable-udp', t: '신뢰성 UDP 재전송 설정', en: 'Reliable-UDP tuning (KCP, ENet…)',
      s: 'UDP 위에 직접 만든 재전송 규칙이 너무 보수적이면 복구가 늦고, 너무 공격적이면 회선을 더 막습니다.',
      c: ['재전송 간격·횟수·윈도우 크기 설정이 회선과 맞지 않음', '늦은 복구, 또는 중복 전송으로 혼잡 악화', '스킬 씹힘, 몰아치기, 혼잡 시 더 심한 렉'],
      sym: ['dropped', 'burst'], fx: ['loss', 'lat'], who: ['me'], when: ['random'],
      own: ['srv', 'cli'],
      act: { game: '서버: 측정한 왕복 시간 기반 재전송, 중요도별 채널 분리. 클라이언트: 서버와 같은 재전송·채널 설정 적용.' },
      sig: { k: 'random', g: '신뢰성 UDP 재전송 비율, 게임 안 RTT' },
      chk: {
        look: '쓰는 라이브러리가 연결마다 가진 통계(재전송 수, 추정 왕복 시간, 재전송 대기 시간)를 서버·클라이언트에서 남기고, 같은 유저의 실제 회선 손실률(mtr로 잰 값)과 비교',
        yes: '재전송 비율이 실제 회선 손실률보다 몇 배 높으면 너무 공격적인 설정, 재전송 대기 시간이 측정 왕복 시간의 몇 배면 너무 보수적인 설정',
        no: '재전송 비율이 회선 손실률과 비슷하고 대기 시간이 왕복 시간에 맞으면 설정 문제가 아님. 회선 손실 자체를 봄',
        by: 'code',
      },
      ref: [
        { t: 'RFC 8085: UDP Usage Guidelines', u: 'https://www.rfc-editor.org/rfc/rfc8085', p: 'IETF', n: '재전송은 혼잡을 키울 수 있어 혼잡 제어 대상, 왕복 시간은 여러 측정의 평균(EWMA)으로 추정, 초기 1초, 타이머 만료 시 전송률 낮추기' },
      ] },
    { id: 'sk-slowstart', t: '유휴 후 슬로 스타트', en: 'Slow start after idle',
      s: 'TCP는 한동안 유휴 상태면 혼잡 윈도우(한 번에 보낼 수 있는 양)를 다시 줄여, 갑자기 큰 데이터를 보낼 때 여러 번에 나눠 보냅니다.',
      c: ['유휴 상태이던 연결로 마을 입장 등 큰 데이터를 보냄', '혼잡 윈도우가 줄어 있어 여러 왕복에 나눠 전송', '입장 직후 주변 캐릭터와 NPC가 왕복 몇 번만큼 늦게 나타남(먼 서버일수록 눈에 띔)'],
      sym: ['delay', 'invisible'], fx: ['lat'], who: ['me'], when: ['moving', 'idle'],
      num: 'RTO보다 오래 유휴 상태면 혼잡 윈도우가 줄기 시작해, 오래 유휴 상태였다면 약 14KB(패킷 10개)까지 내려갑니다. 그러면 100KB는 한 번에 못 보내고 왕복 3번에 나눠 보냅니다.',
      own: ['sys', 'srv'],
      act: { game: '입장 데이터 줄이기(꼭 필요한 것부터 먼저 보내기).', infra: 'tcp_slow_start_after_idle 끄기(리눅스, 서버 전체 설정).' },
      sig: { k: 'outlier', g: '입장 직후 전송 시간(RTT가 긴 유저)' },
      chk: {
        look: 'sysctl net.ipv4.tcp_slow_start_after_idle 값을 확인하고, 유휴 뒤 지역에 입장하는 순간 그 연결의 ss -ti에서 cwnd(혼잡 윈도우)가 작아졌는지 봄',
        yes: '설정이 1(기본)이고, 유휴 뒤 입장 순간 cwnd가 10 안팎으로 줄어 전송이 왕복 여러 번에 나뉨. RTT가 긴 유저일수록 늦게 나타나고, 0으로 바꾸면 사라짐',
        no: 'cwnd가 크게 유지되는데도 늦게 나타나면 서버 쪽 입장 처리(“밀집 지역 진입 시 스폰 폭주”)',
        by: 'ops',
      },
      ref: [
        { t: 'IP Sysctl', u: 'https://docs.kernel.org/networking/ip-sysctl.html', p: 'Linux kernel', n: 'tcp_slow_start_after_idle 기본 켜짐, RTO 동안 유휴면 혼잡 윈도우를 줄임(RFC 2861 방식)' },
        { t: 'RFC 5681: TCP Congestion Control', u: 'https://www.rfc-editor.org/rfc/rfc5681', p: 'IETF', n: 'RTO보다 오래 데이터를 보내지 않았으면 혼잡 윈도우를 재시작 윈도우 min(IW, cwnd) 이하로 줄이고 슬로 스타트' },
        { t: 'RFC 6928: Increasing TCP\'s Initial Window', u: 'https://www.rfc-editor.org/rfc/rfc6928', p: 'IETF', n: '초기 윈도우 10세그먼트, 최대 14,600바이트' },
        { t: 'ss(8) — Linux manual page', u: 'https://man7.org/linux/man-pages/man8/ss.8.html', p: 'iproute2', n: '-i의 cwnd(혼잡 윈도우)·ssthresh(슬로 스타트 임계값)' },
      ] },
    { id: 'sk-congestion', t: '혼잡 제어로 전송량 급감', en: 'Congestion control backoff',
      s: 'TCP는 손실을 혼잡 신호로 보고 전송 속도를 30~50% 줄입니다. 와이파이 손실에도 똑같이 반응합니다.',
      c: ['보낼 양이 많을 때 와이파이나 회선에서 약간의 손실 발생', 'TCP가 전송 속도를 크게 줄이고 천천히 회복(리눅스·윈도우 기본인 CUBIC은 30% 줄임)', '사람 많은 곳에서 업데이트가 밀려 몰아치기·입력 지연'],
      sym: ['burst', 'delay'], fx: ['lat', 'stall'], who: ['me'], when: ['event'],
      own: ['sys', 'srv'],
      act: { game: '보내는 양 줄이기(관심 영역, 변경분만), 한꺼번에 몰아 보내지 않게 나눠 보내기.', infra: 'BBR 같은 혼잡 제어로 바꾸기(tcp_congestion_control).' },
      sig: { k: 'sawtooth', g: '연결별 혼잡 윈도우(cwnd)·전송률' },
      chk: {
        look: '업데이트가 밀린 유저 연결을 ss -ti로 여러 번 떠서 cwnd·ssthresh 변화와 혼잡 제어 이름(cubic·bbr)을 보고, Send-Q가 쌓이는지 함께 봄',
        yes: '손실 뒤 cwnd가 크게 줄었다가 천천히 오르기를 반복하고, 줄어든 동안 Send-Q가 쌓여 몰아치기·입력 지연 제보 시각과 겹침',
        no: 'cwnd가 넉넉한데도 밀리면 받는 쪽 윈도우(“제로 윈도우 (재전송처럼 보이는 멈춤)”)나 서버 송신 쪽',
        by: 'ops',
      },
      ref: [
        { t: 'RFC 9438: CUBIC for Fast and Long-Distance Networks', u: 'https://www.rfc-editor.org/rfc/rfc9438', p: 'IETF', n: 'CUBIC은 손실 때 윈도우를 0.7배(30% 감소), Reno는 0.5배, CUBIC이 리눅스·윈도우·애플 기본' },
        { t: 'TCP BBR congestion control comes to GCP – your Internet just got faster', u: 'https://cloud.google.com/blog/products/networking/tcp-bbr-congestion-control-comes-to-gcp-your-internet-just-got-faster', p: 'Google Cloud', n: '손실 기반 혼잡 제어는 혼잡 때문이 아닌 손실에도 전송률을 크게 줄임, BBR은 전달률과 RTT로 판단' },
        { t: 'IP Sysctl', u: 'https://docs.kernel.org/networking/ip-sysctl.html', p: 'Linux kernel', n: 'tcp_congestion_control로 새 연결의 혼잡 제어 알고리즘 선택' },
        { t: 'ss(8) — Linux manual page', u: 'https://man7.org/linux/man-pages/man8/ss.8.html', p: 'iproute2', n: '-i의 cwnd·ssthresh와 혼잡 제어 알고리즘 이름' },
        { t: 'net/ipv4/tcp_diag.c (Linux v6.12)', u: 'https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/net/ipv4/tcp_diag.c?h=v6.12', p: 'Linux kernel', n: 'ss의 Recv-Q·Send-Q 값: 리슨 소켓은 accept를 기다리는 접속 수와 backlog 한도, 연결된 소켓은 앱이 아직 안 읽은 바이트와 ACK를 받지 못한 송신 바이트' },
      ] },
    { id: 'sk-linger', t: 'RST 강제 종료로 마지막 데이터 유실', en: 'SO_LINGER, abrupt RST',
      s: '서버가 연결을 급히 끊으면 마지막으로 보낸 안내나 저장 완료 신호가 사라집니다.',
      c: ['서버가 연결을 강제 종료(RST)로 닫음. SO_LINGER를 0초로 두거나, 받은 데이터를 다 읽지 않고 닫으면 생김', '아직 전송 중이던 킥 사유·마지막 데이터가 버려짐', '이유 없는 “알 수 없는 오류로 연결 종료”'],
      sym: ['disconnect'], fx: ['loss'], who: ['me'], when: ['random'],
      own: ['srv'],
      act: { game: '사유를 보낸 뒤 송신 방향만 먼저 닫고(shutdown), 상대가 닫을 때까지 받은 데이터를 끝까지 읽은 다음 닫기, SO_LINGER 0초 피하기.' },
      sig: { k: 'random', g: 'RST로 끝난 연결 수' },
      chk: {
        look: 'nstat -az의 TcpExtTCPAbortOnData(보낼 데이터가 남은 채 RST로 닫음, SO_LINGER 0초)·TcpExtTCPAbortOnClose(안 읽은 데이터가 남은 채 닫음) 증가량을 보고, 끊김 순간 서버 쪽 패킷 캡처에서 FIN 대신 RST가 나가는지 봄',
        yes: '“알 수 없는 오류로 연결 종료” 제보 시각에 서버가 RST를 보내고, AbortOnData·AbortOnClose가 늘어남',
        no: '서버가 FIN으로 정상 종료했는데 사유가 안 보이면 클라이언트의 종료 처리 쪽',
        by: 'ops',
      },
      ref: [
        { t: 'closesocket function (winsock.h)', u: 'https://learn.microsoft.com/en-us/windows/win32/api/winsock/nf-winsock-closesocket', p: 'Microsoft', n: 'SO_LINGER를 켜고 시간을 0으로 두면 연결을 즉시 리셋하는 강제 종료가 되고 보내지 못한 데이터는 사라짐' },
        { t: 'RFC 9293: Transmission Control Protocol (TCP)', u: 'https://www.rfc-editor.org/rfc/rfc9293', p: 'IETF', n: '받은 데이터가 남은 채 닫으면 데이터 유실을 알리려 RST를 보냄' },
        { t: 'Graceful Shutdown, Linger Options, and Socket Closure', u: 'https://learn.microsoft.com/en-us/windows/win32/winsock/graceful-shutdown-linger-options-and-socket-closure-2', p: 'Microsoft', n: 'shutdown으로 송신만 먼저 닫고, 상대의 종료 알림을 받은 뒤 소켓을 닫는 순서' },
        { t: 'SNMP counter', u: 'https://docs.kernel.org/networking/snmp_counter.html', p: 'Linux kernel', n: 'TcpExtTCPAbortOnData: SO_LINGER 0초 등으로 보낼 데이터가 남은 채 RST로 닫음, TcpExtTCPAbortOnClose: 안 읽은 데이터가 남은 채 닫아 RST를 보냄' },
      ] },
    { id: 'sk-blocking-io', t: '블로킹 I/O 구조', en: 'Blocking I/O model',
      s: '소켓 하나를 기다리는 동안 스레드가 다른 일을 못 하는 구조는 사람이 늘수록 전체가 느려집니다.',
      c: ['연결마다 읽기·쓰기를 기다리는 방식', '한 연결의 지연이 같은 스레드의 다른 연결로 번짐', '동접이 늘수록 전체가 슬로우모션·입력 지연'],
      sym: ['slowmo', 'delay'], fx: ['stall'], who: ['server'], when: ['event', 'peak'],
      own: ['srv'],
      act: { game: 'epoll·IOCP·io_uring 기반 비동기 I/O로 전환.' },
      sig: { k: 'load', g: '응답 시간, 스레드 수' },
      chk: {
        look: 'pidstat -w -t로 게임 서버 스레드 수와 스레드별 자발적 컨텍스트 스위칭(cswch/s, 자원을 기다리며 멈춘 횟수)을 보고, 동접에 따른 응답 시간과 비교',
        yes: '동접이 늘수록 응답 시간이 가파르게 오르고, 연결 수만큼 늘어난 스레드 대부분이 자발적 스위칭만 많고 CPU는 거의 쓰지 않음(소켓 대기)',
        no: '스레드가 대기 없이 CPU를 계속 쓰고 있으면 계산 과부하(“틱 예산 초과”)',
        by: 'ops',
      },
      ref: [
        { t: 'epoll(7) — Linux manual page', u: 'https://man7.org/linux/man-pages/man7/epoll.7.html', p: 'Linux man-pages', n: '많은 fd를 한 번에 감시하도록 확장되는 I/O 이벤트 알림' },
        { t: 'I/O Completion Ports', u: 'https://learn.microsoft.com/en-us/windows/win32/fileio/i-o-completion-ports', p: 'Microsoft', n: '많은 비동기 I/O를 미리 만든 스레드 풀로 처리하는 윈도우 방식' },
        { t: 'pidstat(1) — Linux manual page', u: 'https://man7.org/linux/man-pages/man1/pidstat.1.html', p: 'sysstat', n: '-w의 cswch/s: 자원을 기다리며 스스로 멈춘 자발적 컨텍스트 스위칭, -t로 스레드별' },
      ] },
    { id: 'sk-reuseport', t: 'SO_REUSEPORT 분배 쏠림', en: 'SO_REUSEPORT imbalance, stuck worker',
      s: '같은 포트를 여러 프로세스가 나눠 받으면, 커널은 접속마다 주소 해시로 담당 프로세스를 정해 두고 바꾸지 않습니다. 담당 프로세스 하나가 멈추면 거기에 배정된 사람만 기다립니다.',
      c: ['게이트웨이·로그인 서버가 SO_REUSEPORT로 프로세스 여러 개를 띄움', '한 프로세스가 GC·과부하로 멈춰도 거기에 배정된 새 접속과 UDP 패킷은 다른 프로세스로 넘어가지 않음', '일부 사람만 접속 불가·멈춤. 프로세스 수가 바뀌는 재시작 때는 일부 UDP 세션이 끊김'],
      sym: ['noconnect', 'freeze', 'disconnect'], fx: ['stall', 'loss'], who: ['me', 'server'], when: ['login', 'random'],
      own: ['srv', 'sys'],
      act: { game: '받는 스레드는 절대 멈추지 않게, 재시작 때 세션을 넘겨받는 절차 구현.', infra: '프로세스별 접속 대기열 감시(ss의 Recv-Q), 배포 때 프로세스 수를 바꾸면 세션 넘겨받기 절차를 따르게.' },
      sig: { k: 'outlier', g: '리슨 소켓별 접속 대기열(Recv-Q)' },
      chk: {
        look: 'ss -ltnp로 같은 포트의 리슨 소켓마다 Recv-Q(accept를 기다리는 접속 수)와 담당 프로세스를 보고, 프로세스별 처리량을 비교',
        yes: '같은 포트의 여러 소켓 중 하나만 Recv-Q가 계속 쌓이고, 그 프로세스가 멈춰 있거나 처리량이 0에 가까움',
        no: '모든 소켓의 Recv-Q가 고르게 쌓이면 전체 과부하(“접속 대기열(backlog) 넘침”)',
        by: 'ops',
      },
      ref: [
        { t: 'socket(7) — Linux manual page', u: 'https://man7.org/linux/man-pages/man7/socket.7.html', p: 'Linux man-pages', n: 'SO_REUSEPORT로 여러 소켓이 같은 주소에 bind해 TCP 접속과 UDP 패킷을 나눠 받음' },
        { t: 'net/core/sock_reuseport.c (Linux v6.12)', u: 'https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/net/core/sock_reuseport.c?h=v6.12', p: 'Linux kernel', n: 'BPF 프로그램이 없으면 패킷 해시 값을 그룹의 소켓 수에 맞춰 나눠 담당 소켓을 고름' },
        { t: 'Why does one NGINX worker take all the load?', u: 'https://blog.cloudflare.com/the-sad-state-of-linux-socket-balancing/', p: 'Cloudflare', n: 'SO_REUSEPORT는 간단한 해시로 워커마다 큐를 나누므로, 워커 하나가 막히면 그 큐에 쌓인 접속이 모두 멈춤' },
        { t: 'net/ipv4/tcp_diag.c (Linux v6.12)', u: 'https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/net/ipv4/tcp_diag.c?h=v6.12', p: 'Linux kernel', n: 'ss의 Recv-Q·Send-Q 값: 리슨 소켓은 accept를 기다리는 접속 수와 backlog 한도, 연결된 소켓은 앱이 아직 안 읽은 바이트와 ACK를 받지 못한 송신 바이트' },
      ] },
    { id: 'sk-udp-connreset', t: '윈도우 UDP 소켓의 WSAECONNRESET 오류', en: 'WSAECONNRESET on a Windows UDP socket',
      s: '윈도우 서버가 이미 떠난 클라이언트에게 UDP를 보내면 “포트 없음”(ICMP) 알림이 돌아옵니다. 그 알림 때문에 다음 수신 호출이 오류로 끝나는데, 서버 코드가 이 오류를 소켓 자체의 고장으로 처리하면 그 소켓을 쓰는 모두가 영향을 받습니다.',
      c: ['막 나간 클라이언트의 주소로 계속 UDP를 보내 “포트 없음”(ICMP) 알림이 돌아옴', '윈도우가 그다음 수신 호출을 WSAECONNRESET(10054) 오류로 끝내고, 서버 코드가 수신을 멈추거나 소켓을 닫음', '그 소켓을 쓰던 모든 사람이 한꺼번에 멈춤·접속 끊김'],
      sym: ['disconnect', 'freeze'], fx: ['loss', 'stall'], who: ['server'], when: ['random', 'login'],
      own: ['srv'],
      act: { game: 'WSAIoctl로 SIO_UDP_CONNRESET을 꺼서 이 알림을 받지 않기, 수신 오류가 나도 로그만 남기고 수신을 계속하기.' },
      sig: { k: 'drop', g: '접속 수, 수신 오류 로그' },
      chk: {
        look: '게임 서버 로그에서 UDP 수신 오류 코드(WSAECONNRESET, 10054)와 수신 루프가 멈추거나 소켓을 닫은 기록을 찾고, 서버 쪽 패킷 캡처로 직전에 ICMP Port Unreachable이 도착했는지 봄',
        yes: '접속이 한꺼번에 끊기기 직전에 WSAECONNRESET 수신 오류가 기록되고, 그 전에 막 나간 클라이언트 주소에서 ICMP Port Unreachable이 옴',
        no: '리눅스 서버이거나 코드가 SIO_UDP_CONNRESET을 끈 경우면 해당 없음',
        by: 'code',
      },
      ref: [
        { t: 'Winsock IOCTLs', u: 'https://learn.microsoft.com/en-us/windows/win32/winsock/winsock-ioctls', p: 'Microsoft', n: 'SIO_UDP_CONNRESET으로 UDP “포트 없음”(PORT_UNREACHABLE) 알림 보고를 켜고 끔' },
        { t: 'recvfrom function (winsock.h)', u: 'https://learn.microsoft.com/en-us/windows/win32/api/winsock/nf-winsock-recvfrom', p: 'Microsoft', n: 'UDP 소켓의 WSAECONNRESET은 이전 전송이 ICMP Port Unreachable을 받았다는 뜻' },
        { t: 'Windows Sockets Error Codes', u: 'https://learn.microsoft.com/en-us/windows/win32/winsock/windows-sockets-error-codes-2', p: 'Microsoft', n: 'WSAECONNRESET 오류 번호 10054' },
      ] },
  ]);
})();
