/* 원인 항목 1: 내 쪽(클라이언트 게임, 클라이언트 OS, 집 네트워크) + 인터넷 회선
   필드: id, t(이름), en(영문), s(한 줄), c[왜, 그러면, 화면에서는], sym(증상), fx(요인),
         who(누가), when(언제), num(수치 감각), own(해결 담당), act(팀별 할 일), more(자세히), sim(관련 실험)
   who: me 나만 · home 같은 집 · region 특정 지역·통신사 · zone 특정 장소·채널 · server 서버 전체 · feature 특정 기능
   when: always 항상 · peak 저녁 피크 · event 몰릴 때 · login 접속·점검 직후 · idle 가만히 있다가 · random 가끔 · periodic 일정 주기 · uptime 켜 둔 지 오래 · moving 이동·지역 전환 · action 특정 행동 */
(function () {
  const add = (layer, list) => list.forEach(c => DATA.causes.push(Object.assign({ layer }, c)));

  /* ---------------- 1. 클라이언트 게임 프로세스 ---------------- */
  add('client-game', [
    { id: 'cg-hitch', t: '프레임 타임 스파이크', en: 'Frame hitch',
      s: '한 프레임 계산이 평소보다 몇 배 오래 걸려 화면이 잠깐 멈춥니다.',
      c: ['스킬 이펙트 폭증, 대량 스폰, UI 전체 갱신이 한 프레임에 몰림', '16.7ms 안에 못 끝내고 50~300ms가 걸림', '화면이 멈칫했다가 다음 프레임에 모두가 한 번에 이동'],
      sym: ['stutter', 'freeze'], fx: ['stall'], who: ['me'], when: ['event', 'action', 'random'],
      num: '60FPS의 한 프레임은 16.7ms. 50ms를 넘는 프레임 하나만 있어도 “끊겼다”고 느끼기 쉽습니다.',
      own: ['cli'],
      act: { game: '무거운 일을 여러 프레임에 나누기, 프로파일러로 튀는 프레임 찾기, 이펙트 개수 상한.' },
      sim: 'frames',
      ref: [
        { t: 'Slow rendering', u: 'https://developer.android.com/topic/performance/vitals/render', p: 'Android (Google)', n: '60FPS를 내려면 한 프레임을 16ms 안에 그려야 하고, 늦으면 프레임을 건너뛰어 끊김(jank)으로 보임' },
        { t: 'Slow Sessions (games only)', u: 'https://developer.android.com/topic/performance/issues/slow-session', p: 'Android (Google)', n: '안드로이드 vitals는 게임 프레임이 50ms(20FPS)·34ms(30FPS)를 넘으면 느린 프레임으로 봄' },
      ] },
    { id: 'cg-gc', t: '클라이언트 가비지 컬렉션', en: 'Client GC (Unity C#, Unreal, Lua)',
      s: '쓰고 버린 메모리(가비지)를 회수하는 동안 게임 전체가 멈춥니다. 규칙적인 간격으로 뚝뚝 끊기는 것이 특징입니다.',
      c: ['매 프레임 임시 문자열·배열·리스트를 만들고 버림', '가비지가 쌓이면 GC가 메인 스레드를 멈추고 회수', '몇 초~몇십 초마다 규칙적으로 뚝뚝 끊김'],
      sym: ['stutter', 'freeze'], fx: ['stall'], who: ['me'], when: ['periodic', 'event'],
      num: '보통 한 번에 수 ms~100ms, 저사양 폰이나 메모리를 많이 쓰는 게임은 그 이상(실험은 약 150~170ms). 유니티의 GC는 돌 때마다 힙 전체를 검사해서, 게임이 쓰고 있는 메모리가 많을수록 길어집니다.',
      own: ['cli'],
      act: { game: '할당 줄이기(문자열 합치기·LINQ·람다 캡처 피하기), 오브젝트 풀, 점진적 GC 켜 두기(유니티 2020 이후 기본값), 로딩 화면처럼 멈춰도 괜찮은 때에 미리 GC 돌리기.' },
      more: '유니티처럼 C#을 쓰는 클라이언트에서 흔합니다. 전투 로그 문자열, 데미지 숫자, UI 텍스트를 매 프레임 새로 만드는 코드가 주범입니다. 사람 많은 곳에서만 끊긴다면 인원에 비례해 가비지가 늘어나는 코드가 있다는 뜻입니다. 점진적 GC는 한 프레임에 조금씩(유니티 기본 3ms) 나눠 수집하지만, 수집하는 속도보다 가비지를 빨리 만들면 결국 한 번에 멈춥니다. 언리얼 엔진에도 안 쓰는 게임 오브젝트를 정리하는 자체 GC가 있고, 엔진 버전·설정에 따라 다르지만 기본 설정으로 약 1분마다 돌아 1분 간격의 멈칫을 만들기도 합니다. 게임 규칙을 Lua 같은 스크립트로 짠 클라이언트는 그 스크립트의 GC도 따로 돕니다.',
      sim: 'frames',
      ref: [
        { t: 'Garbage collection modes', u: 'https://docs.unity3d.com/Manual/performance-incremental-garbage-collection.html', p: 'Unity', n: '점진적 GC가 기본값이고 여러 프레임에 나눠 수집, 끄면 힙 전체를 검사하는 동안 메인 스레드가 멈추며 수백 ms까지 갈 수 있음' },
        { t: 'Scripting.GarbageCollector.CollectIncremental', u: 'https://docs.unity3d.com/ScriptReference/Scripting.GarbageCollector.CollectIncremental.html', p: 'Unity', n: '점진적 GC가 한 번에 쓰는 시간(타임 슬라이스)의 기본 목표는 3ms(incrementalTimeSliceNanoseconds)' },
        { t: 'Garbage Collection Settings in the Unreal Engine Project Settings', u: 'https://dev.epicgames.com/documentation/en-us/unreal-engine/garbage-collection-settings-in-the-unreal-engine-project-settings', p: 'Epic Games', n: '언리얼 GC가 정해진 간격(Time Between Purging Pending Kill Objects, 초 단위)으로 돈다는 설정. 기본값 숫자는 이 문서에 없음' },
      ] },
    { id: 'cg-sync-load', t: '메인 스레드 동기 로딩·셰이더 컴파일', en: 'Synchronous asset load, shader compile',
      s: '처음 보는 지역·몬스터·이펙트를 그리기 직전에 파일을 읽고 셰이더를 만드느라 멈춥니다.',
      c: ['새 지역 진입, 처음 보는 스킬·장비·몬스터 등장', '메인 스레드가 파일 읽기와 셰이더 컴파일을 기다림', '처음 한 번만 0.1~1초 멈춤, 두 번째부터는 괜찮음'],
      sym: ['freeze', 'stutter'], fx: ['stall'], who: ['me'], when: ['moving', 'action'],
      num: '셰이더 하나 컴파일에 수십 ms, 길면 100ms 이상. 텍스처 로딩은 저장장치 속도에 따라 수십~수백 ms.',
      own: ['cli'],
      act: { game: '비동기 로딩, 미리 불러두기(프리워밍), 셰이더를 로딩 화면이나 첫 실행 때 미리 컴파일, 로딩 화면 활용.' },
      more: 'PC에서 한 번 만든 셰이더는 그래픽 드라이버가 셰이더 캐시에 저장해 두었다가 다시 씁니다. 그래서 그래픽 드라이버를 업데이트하거나 게임 패치가 나온 직후에는 이 캐시가 무효화되어, 괜찮던 사람도 한동안 다시 끊깁니다. “패치 후 처음 가는 곳마다 멈칫”이라는 제보가 전형입니다.',
      sim: 'frames',
      ref: [
        { t: 'Shader loading', u: 'https://docs.unity3d.com/Manual/shader-loading.html', p: 'Unity', n: '셰이더 변형을 처음 쓸 때 그래픽 드라이버가 GPU용으로 만드느라 눈에 띄게 멈출 수 있고, 한 번 만든 것은 캐시해 다시 멈추지 않음' },
        { t: 'Optimizing Rendering With PSO Caches in Unreal Engine', u: 'https://dev.epicgames.com/documentation/en-us/unreal-engine/optimizing-rendering-with-pso-caches-in-unreal-engine', p: 'Epic Games', n: '파이프라인 상태(PSO)를 필요한 순간에 만들면 100ms 이상 걸릴 수 있어 미리 만들어 둬야 함' },
        { t: 'Direct3D 12 Return Codes', u: 'https://learn.microsoft.com/en-us/windows/win32/direct3d12/d3d12-graphics-reference-returnvalues', p: 'Microsoft', n: 'D3D12_ERROR_DRIVER_VERSION_MISMATCH: 다른 드라이버 버전에서 만든 PSO 캐시는 다시 쓸 수 없음(드라이버 업데이트 후 재컴파일)' },
      ] },
    { id: 'cg-crowd', t: '대규모 인원 렌더링 부하', en: 'Render/animation cost of crowds',
      s: '공성전·월드 보스처럼 수백 명이 한 화면에 들어오면 그리는 비용 자체가 감당이 안 됩니다.',
      c: ['한 화면에 수백 명과 이펙트가 겹침', '애니메이션·그림자·이름표·이펙트 비용이 인원에 비례해 증가', 'FPS가 60 → 15로 떨어져 모든 움직임이 뚝뚝 끊기고 입력도 늦음'],
      sym: ['stutter', 'delay'], fx: ['stall'], who: ['zone', 'me'], when: ['event'],
      num: '캐릭터 1명당 0.02~0.1ms라도 300명이면 6~30ms. 이것만으로 프레임 예산을 넘습니다.',
      own: ['cli'],
      act: { game: '거리별 간소화(LOD), 표시 인원 상한, 이펙트 간소화 옵션, 애니메이션 갱신 주기 낮추기.' },
      sim: 'frames',
      ref: [
        { t: 'Introduction to level of detail', u: 'https://docs.unity3d.com/Manual/LevelOfDetail.html', p: 'Unity', n: 'LOD가 없으면 화면에 작게 보이는 물체도 같은 복잡도로 그림, LOD로 그리기 부담을 줄임' },
        { t: 'Animation Budget Allocator in Unreal Engine', u: 'https://dev.epicgames.com/documentation/en-us/unreal-engine/animation-budget-allocator-in-unreal-engine', p: 'Epic Games', n: '스켈레탈 메시의 애니메이션 갱신(틱)을 동적으로 줄여 애니메이션에 쓰는 시간을 예산 안으로 제한' },
      ] },
    { id: 'cg-net-mainthread', t: '메인 스레드 패킷 처리 병목', en: 'Network processing on the main thread',
      s: '받은 패킷을 프레임마다 정해진 만큼만 처리하면, 몰려온 패킷이 다음 프레임으로 계속 밀립니다.',
      c: ['사람 많은 곳에서 초당 수천 개의 업데이트가 도착', '메인 스레드가 프레임당 처리량 제한에 걸려 다 못 읽음', '다른 사람 움직임이 점점 늦게, 몰아서 반영'],
      sym: ['burst', 'delay'], fx: ['stall', 'lat'], who: ['zone', 'me'], when: ['event'],
      num: '처리 못 한 패킷이 쌓이면 1초 분량이 밀리는 데 몇 초면 충분합니다.',
      own: ['cli', 'srv'],
      act: { game: '클라이언트: 수신·해석은 별도 스레드, 같은 대상의 오래된 위치 업데이트는 합쳐서 최신만 적용. 서버: 사람 많은 곳에서는 먼 캐릭터의 업데이트를 덜 자주 보내 전송량 줄이기.' },
      ref: [
        { t: 'Actor Priority in Unreal Engine', u: 'https://dev.epicgames.com/documentation/en-us/unreal-engine/actor-priority-in-unreal-engine', p: 'Epic Games', n: '대역폭이 모자라면 모든 액터를 매번 복제하지 않고, 보는 사람과의 거리·마지막 복제 후 시간으로 우선순위를 매김' },
        { t: 'Replication Graph in Unreal Engine', u: 'https://dev.epicgames.com/documentation/en-us/unreal-engine/replication-graph-in-unreal-engine', p: 'Epic Games', n: '접속자·복제 대상이 많은 게임(MMORPG 등)은 위치별로 묶어 필요한 대상만 보내야 서버 CPU 병목을 피함' },
      ] },
    { id: 'cg-no-buffer', t: '보간 버퍼가 없거나 짧음', en: 'Missing/short interpolation buffer',
      s: '서버 패킷을 받자마자 그리면 지터(도착 간격의 흔들림)가 그대로 화면에 드러납니다.',
      c: ['받은 위치를 바로 그리거나 버퍼가 지터보다 짧음', '늦게 온 패킷만큼 멈추고 몰려온 패킷만큼 튐', '다른 캐릭터가 멈칫멈칫 움직임'],
      sym: ['stutter'], fx: ['jit'], who: ['me'], when: ['always'],
      num: '보통 서버가 패킷을 보내는 간격의 2배 정도(1초에 20번 받으면 100ms)를 버퍼로 둡니다.',
      own: ['cli', 'srv'],
      act: { game: '클라이언트: 보간 버퍼 두기, 회선 상태에 따라 버퍼 길이를 자동 조절. 서버: 버퍼만큼 과거 모습을 보고 쏴도 판정이 맞도록 지연 보상(되감기 판정) 적용.' },
      more: '버퍼를 늘리면 매끄러워지지만 그만큼 상대를 과거 모습으로 봅니다. 그래서 공격 판정은 서버가 “그 사람이 보던 과거”로 되감아 확인하는 지연 보상을 함께 씁니다.',
      sim: 'lab',
      ref: [
        { t: 'Interpolation and extrapolation (Netcode for Entities 6.5)', u: 'https://docs.unity3d.com/Packages/com.unity.netcode@6.5/manual/interpolation.html', p: 'Unity', n: '늦게 온 패킷을 기다리려고 일부러 늦춰 그리는 버퍼 보간, 버퍼가 클수록 정확하지만 그만큼 지연이 늘어남' },
        { t: 'Struct ClientTickRate (Netcode for Entities 6.5)', u: 'https://docs.unity3d.com/Packages/com.unity.netcode@6.5/api/Unity.NetCode.ClientTickRate.html', p: 'Unity', n: '보간 버퍼 기본값 InterpolationTimeNetTicks = 2(서버 전송 2번 분량)' },
        { t: 'Physics (Netcode for Entities 6.5)', u: 'https://docs.unity3d.com/Packages/com.unity.netcode@6.5/manual/physics.html', p: 'Unity', n: '지연 보상: 서버가 클라이언트가 그 틱에 보던 충돌 세계를 찾아 명중 여부를 판정' },
      ] },
    { id: 'cg-extrap', t: '과도한 외삽(데드 레커닝)', en: 'Over-extrapolation / dead reckoning',
      s: '패킷이 오지 않는 동안 마지막 속도로 계속 움직여 보여 주다가, 틀린 걸 알고 되돌립니다.',
      c: ['패킷 수신이 끊겨 마지막 방향·속도로 계속 이동시킴', '실제로는 상대가 멈추거나 방향을 바꿨음', '상대 캐릭터가 한참 가다가 진짜 위치로 휙 옮겨지거나 벽을 뚫고 지나감. 패킷 도착 간격이 들쭉날쭉하면 앞서 나갔다 당겨지기를 반복해 떨리듯 움직임'],
      sym: ['teleport', 'stutter'], fx: ['loss', 'jit'], who: ['me'], when: ['random'],
      num: '속도 6m/s라면 300ms만 틀려도 1.8m 어긋납니다.',
      own: ['cli'],
      act: { game: '외삽 시간 상한(예: 200~250ms), 틀렸을 때 부드럽게 수렴.' },
      sim: 'lab',
      ref: [
        { t: 'Interpolation and extrapolation (Netcode for Entities 6.5)', u: 'https://docs.unity3d.com/Packages/com.unity.netcode@6.5/manual/interpolation.html', p: 'Unity', n: '다음 스냅샷이 제때 안 오면 같은 방향·속도로 계속 움직이는 외삽은 자주 틀리므로 상한을 둠(유니티 기본 20틱, 60Hz에서 약 1/3초)' },
        { t: 'Peeking into VALORANT\'s Netcode', u: 'https://technology.riotgames.com/news/peeking-valorants-netcode', p: 'Riot Games', n: '늦거나 빠진 데이터를 추측으로 메우다 틀리면 서버와 어긋나 캐릭터가 튀거나 미끄러지듯 보정됨' },
      ] },
    { id: 'cg-predict', t: '클라이언트 예측 불일치', en: 'Prediction mismatch / reconciliation',
      s: '내 클라이언트가 먼저 움직여 보여 줬는데, 서버가 다르게 계산하면 내 캐릭터가 끌려갑니다.',
      c: ['클라이언트가 서버 확인 전에 먼저 움직임(예측)', '서버는 충돌·이동 속도·버프를 다르게 계산하거나 명령을 못 받음', '확인이 올 때 내 캐릭터가 뒤로 끌려감'],
      sym: ['rubber'], fx: ['loss', 'lat'], who: ['me'], when: ['moving', 'random'],
      num: '끌려가는 거리는 “어긋난 시간 × 이동 속도”. 명령 몇 개만 사라져도 1~3m.',
      own: ['cli', 'srv'],
      act: { game: '클라이언트: 서버와 같은 이동 코드 사용, 입력 중복 전송, 보정은 부드럽게. 서버: 클라이언트와 같은 이동 코드 사용, 중복으로 온 입력은 입력 번호로 걸러 한 번만 처리.' },
      sim: 'lab',
      ref: [
        { t: 'Introduction to prediction (Netcode for Entities 6.5)', u: 'https://docs.unity3d.com/Packages/com.unity.netcode@6.5/manual/intro-to-prediction.html', p: 'Unity', n: '클라이언트와 서버가 같은 시뮬레이션 코드로 예측, 서버 상태와 다르면(예측 실패) 되돌려 다시 계산하며 보정이 보임' },
        { t: 'Use the command stream to handle user inputs (Netcode for Entities 6.5)', u: 'https://docs.unity3d.com/Packages/com.unity.netcode@6.5/manual/command-stream.html', p: 'Unity', n: '패킷 손실에 대비해 최신 입력과 함께 이전 몇 틱의 입력을 중복으로 보냄' },
        { t: 'Understanding Networked Movement in the Character Movement Component for Unreal Engine', u: 'https://dev.epicgames.com/documentation/en-us/unreal-engine/understanding-networked-movement-in-the-character-movement-component-for-unreal-engine', p: 'Epic Games', n: '클라이언트가 먼저 움직이고 서버가 같은 이동을 재현, 위치가 다르면 ClientAdjustPosition으로 보정하고 저장한 이동을 다시 적용' },
      ] },
    { id: 'cg-fixed-step', t: '고정 타임스텝 따라잡기 폭주', en: 'Fixed-timestep catch-up / spiral of death',
      s: '한 번 멈춘 뒤 밀린 계산을 몰아서 하다가, 그 계산 때문에 또 밀립니다.',
      c: ['게임 시뮬레이션을 고정 간격으로 돌리는데 한 번 멈춤', '밀린 스텝을 한 프레임에 몰아서 계산', '긴 프레임이 줄줄이 이어지며 튀거나, 상한에 걸려 세계가 느려짐'],
      sym: ['stutter', 'burst', 'slowmo'], fx: ['stall'], who: ['me'], when: ['random', 'event'],
      own: ['cli'],
      act: { game: '프레임당 따라잡기 상한, 남는 시간은 보간으로 처리.' },
      more: '유니티의 물리 계산(FixedUpdate)이 대표적인 고정 스텝입니다(기본 0.02초, 1초에 50번). Time 설정의 Maximum Allowed Timestep(한 프레임에 따라잡을 최대 시간, 기본 약 0.33초)이 따라잡기 상한입니다. 한 프레임이 이보다 길면 넘친 시간은 버려져, 그만큼 게임 시계가 실제보다 늦어집니다.',
      sim: 'frames',
      ref: [
        { t: 'Set fixed timestep to optimize physics simulation frequency', u: 'https://docs.unity3d.com/Manual/physics-optimization-cpu-frequency.html', p: 'Unity', n: 'Fixed Timestep 기본값 0.02초(1초에 50번), 프레임이 길면 한 프레임에 물리 스텝을 여러 번 돌려 부담이 커짐' },
        { t: 'Handling variation in time', u: 'https://docs.unity3d.com/Manual/time-handling-variations.html', p: 'Unity', n: 'Maximum Allowed Timestep 기본값 1/3초(0.3333333), 1초가 멈춰도 게임 시간은 0.333초만 흐름, 따라잡기 스텝이 또 느려지는 악순환을 막는 상한' },
      ] },
    { id: 'cg-clock', t: '시계 동기화 오차', en: 'Clock sync error',
      s: '클라이언트가 추정한 서버 시각이 틀리면 보간 시점과 쿨타임 판정이 어긋납니다.',
      c: ['접속할 때 한 번만 서버 시간을 맞추고, 핑이 변해도 그대로 둠', '보간할 시점·쿨타임 끝나는 시각이 서버와 어긋남', '상대가 가끔 멈칫, 쿨타임이 끝났는데 스킬이 거절됨'],
      sym: ['stutter', 'dropped'], fx: ['lat'], who: ['me'], when: ['uptime', 'random'],
      own: ['cli'],
      act: { game: '주기적으로 시간 동기화(왕복 시간 측정 후 보정), 급하게 바꾸지 말고 서서히 맞추기, 경과 시간은 PC 시각 대신 단조 시계(monotonic clock)로 재기.' },
      more: '경과 시간을 PC의 날짜·시각(wall clock)으로 재면, 윈도우가 인터넷 시간에 맞춰 시계를 고치거나 사용자가 시계를 바꾸는 순간 게임 시각이 튑니다. 경과 시간은 되돌아가지 않는 단조 시계(monotonic clock. Stopwatch 등)로 재야 합니다.',
      ref: [
        { t: 'RFC 5905: Network Time Protocol Version 4: Protocol and Algorithms Specification', u: 'https://www.rfc-editor.org/rfc/rfc5905', p: 'IETF', n: '요청·응답의 네 시각으로 왕복 지연과 시계 오차를 계산하는 방식' },
        { t: 'Acquiring high-resolution time stamps', u: 'https://learn.microsoft.com/en-us/windows/win32/sysinfo/acquiring-high-resolution-time-stamps', p: 'Microsoft', n: 'QueryPerformanceCounter(Stopwatch가 사용)는 외부 시각과 동기화되지 않는 경과 시간용 시계, UTC 시각이 필요할 때만 시스템 시각 사용' },
        { t: 'Time synchronization (Netcode for Entities 6.5)', u: 'https://docs.unity3d.com/Packages/com.unity.netcode@6.5/manual/time-synchronization.html', p: 'Unity', n: '왕복 시간으로 서버 시각을 추정하고, 시각을 크게 바꾸지 않고 진행 속도를 조금씩 조정해 맞춤' },
      ] },
    { id: 'cg-float-time', t: 'float 시간 정밀도 손실', en: 'Float time precision loss on long sessions',
      s: '게임 시각을 정밀도가 낮은 소수 형식(float)으로 들고 있으면, 켜 둔 시간이 길수록 시간 해상도(구별할 수 있는 가장 작은 시간 차이)가 떨어져 움직임과 이펙트가 떨립니다.',
      c: ['게임을 켠 뒤 흐른 시간을 float로 쌓거나 그대로 셰이더에 넘김', '켜 둔 시간이 길수록 float가 나타낼 수 있는 가장 작은 차이가 커짐', '며칠 켜 둔 클라이언트만 캐릭터·애니메이션·흐르는 이펙트가 덜덜 떨리고, 다시 켜면 멀쩡함'],
      sym: ['stutter'], fx: ['jit'], who: ['me'], when: ['uptime'],
      num: '32비트 float는 유효 숫자가 7자리 남짓이라, 켜 둔 지 하루(약 86,400초)면 시간 해상도가 약 8ms, 일주일이면 약 60ms가 됩니다. 60FPS의 한 프레임(16.7ms)에 맞먹거나 더 큽니다.',
      own: ['cli'],
      act: { game: '흐른 시간은 double(64비트)이나 정수로 보관, 셰이더에 넘기는 시간은 일정 주기로 되감기, 며칠짜리 장시간 자동 테스트.' },
      more: '자동 사냥을 켜 두고 며칠씩 끄지 않는 모바일 MMO에서 특히 나옵니다. 유니티의 Time.time도 float라서, 유니티는 double로 된 Time.timeAsDouble을 따로 두고 이쪽을 권합니다.',
      ref: [
        { t: 'Time.timeAsDouble', u: 'https://docs.unity3d.com/ScriptReference/Time-timeAsDouble.html', p: 'Unity', n: 'Time.time의 double 버전, 오래 켜 둘수록 float보다 정밀해 대부분 이쪽을 권장' },
        { t: 'Floating-point numeric types (C# reference)', u: 'https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/floating-point-numeric-types', p: 'Microsoft', n: 'float 정밀도 약 6~9자리, double 약 15~17자리' },
      ] },
    { id: 'cg-vsync', t: 'V-Sync와 렌더 대기열', en: 'V-Sync, render queue',
      s: 'GPU가 그린 프레임을 몇 장 대기열에 쌓아 두었다가 모니터 주기에 맞춰 내보내는 동안 입력이 늦어집니다.',
      c: ['그래픽 드라이버가 프레임을 1~3장 미리 대기열에 쌓음', '입력이 화면에 반영되기까지 그만큼 더 걸림', '핑은 낮은데 조작이 묵직하고 굼뜸'],
      sym: ['delay', 'stutter'], fx: ['lat'], who: ['me'], when: ['always'],
      num: '60Hz에서 한 장당 16.7ms. CPU가 GPU나 화면 주기보다 빨라 대기열 세 장(DirectX 11 기본값)이 꽉 차면 50ms가 더해집니다. 이중 버퍼 V-Sync에서는 17ms 걸린 프레임이 다음 화면 갱신 시점(33.3ms)까지 기다리고, 그동안 이전 프레임이 한 번 더 보입니다.',
      own: ['cli', 'ext'],
      act: { game: '저지연 모드 지원, 프레임 대기열 줄이기, 주사율보다 조금 낮게 거는 프레임 상한 옵션 제공, 폰은 프레임 페이싱 기능 켜기.', ext: '유저에게 가변 주사율 모니터와 함께 주사율보다 조금 낮은 프레임 상한 걸기, 그래픽 드라이버의 저지연 모드 켜기 안내.' },
      more: 'V-Sync(수직 동기화)는 모니터가 화면을 바꾸는 순간에만 새 프레임을 내보내는 설정입니다. 화면 찢어짐은 사라지지만, 그 순간을 기다리는 만큼 입력이 늦고 FPS가 60 아래로 내려가면 60과 30 사이를 오가며 뚝뚝 끊깁니다. 가변 주사율 모니터는 모니터가 프레임이 준비되는 때에 맞춰 화면을 바꿔 이 기다림을 줄입니다. 폰에서도 같은 일이 생깁니다. 30FPS 게임이 60Hz 화면에 프레임을 고르게 맞춰 내보내지 못하면, 평균은 30FPS인데 한 장이 49·16·33ms처럼 들쭉날쭉 머물러 뚝뚝 끊깁니다(안드로이드 개발 문서의 예). 안드로이드의 프레임 페이싱(프레임 출력 간격 고르기) 라이브러리나 엔진의 같은 옵션으로 줄입니다.',
      sim: 'frames',
      ref: [
        { t: 'IDXGIDevice1::SetMaximumFrameLatency', u: 'https://learn.microsoft.com/en-us/windows/win32/api/dxgi/nf-dxgi-idxgidevice1-setmaximumframelatency', p: 'Microsoft', n: '드라이버가 대기열에 쌓을 수 있는 프레임 수 기본값 3(1~16)' },
        { t: 'Reduce latency with DXGI 1.3 swap chains', u: 'https://learn.microsoft.com/en-us/windows/uwp/gaming/reduce-latency-with-dxgi-1-3-swap-chains', p: 'Microsoft', n: 'Present가 대기열이 빌 때까지 막혀 그린 뒤 표시까지 거의 한 프레임을 더 기다리게 됨, 대기 가능한 스왑 체인으로 줄임' },
        { t: 'Frame Pacing library', u: 'https://developer.android.com/games/sdk/frame-pacing', p: 'Android (Google)', n: '60Hz 화면에서 새 프레임이 없으면 이전 프레임을 다시 보여 줌, 30FPS 게임의 프레임 시간이 49·16·33ms처럼 들쭉날쭉해지는 예' },
      ] },
    { id: 'cg-leak', t: '클라이언트 메모리 누수', en: 'Client memory leak',
      s: '오래 켜 둘수록 메모리가 늘어 점점 느려지다가 결국 게임이 강제로 꺼집니다.',
      c: ['지역을 오갈 때 텍스처·UI·이펙트가 해제되지 않음', 'GC가 잦아지고 OS 메모리가 부족해 스왑 발생', '몇 시간 플레이 뒤 점점 뚝뚝 끊기다가 강제 종료(플레이어에게는 접속 끊김처럼 보임)'],
      sym: ['stutter', 'disconnect'], fx: ['stall'], who: ['me'], when: ['uptime'],
      own: ['cli'],
      act: { game: '지역 전환 때 메모리 사용량 측정, 해제되지 않는 텍스처·UI·이펙트 찾아 고치기, 장시간 자동 테스트(소크 테스트).' },
      more: '폰은 주로 메모리를 압축해 버팁니다. 그래도 메모리가 모자라면 OS가 게임을 바로 꺼 버립니다(튕김). 램이 작은 기기일수록 먼저 꺼집니다.',
      ref: [
        { t: 'Memory allocation among processes', u: 'https://developer.android.com/topic/performance/memory-management', p: 'Android (Google)', n: '안드로이드는 메모리를 zRAM에 압축해 버티고, 모자라면 저메모리 킬러가 프로세스를 종료, 앞에 띄운 앱이 종료되면 크래시처럼 보임' },
        { t: 'Identifying high-memory use with jetsam event reports', u: 'https://developer.apple.com/documentation/xcode/identifying-high-memory-use-with-jetsam-event-reports', p: 'Apple', n: 'iOS는 메모리 압박이 풀리지 않으면 앱을 강제 종료(jetsam)하고, 앱마다 메모리 한도를 넘으면 종료 대상이 됨' },
      ] },
    { id: 'cg-crash', t: '클라이언트 크래시', en: 'Client crash',
      s: '처리하지 못한 오류로 게임이 꺼집니다. 플레이어에게는 접속 끊김처럼 보이지만 서버는 정상입니다.',
      c: ['널 참조, 메모리 부족, 그래픽 드라이버 오류', '게임 프로세스가 강제 종료', '“튕겼다”는 제보. 같은 시각 다른 사람은 멀쩡'],
      sym: ['disconnect'], fx: ['stall'], who: ['me'], when: ['action', 'random'],
      own: ['cli', 'ext'],
      act: { game: '크래시 리포트 수집, 기기·드라이버별 통계, 많이 몰리는 오류부터 수정.', ext: '특정 그래픽 드라이버 버전에서 몰리면 유저에게 드라이버 업데이트 안내.' },
      ref: [
        { t: 'Crashes', u: 'https://developer.android.com/topic/performance/vitals/crash', p: 'Android (Google)', n: '처리하지 않은 예외나 시그널(SIGSEGV 등)로 앱이 예기치 않게 종료되는 것이 크래시, Play Console의 Android vitals로 집계' },
        { t: 'WDDM Support for Timeout Detection and Recovery (TDR)', u: 'https://learn.microsoft.com/en-us/windows-hardware/drivers/display/timeout-detection-and-recovery', p: 'Microsoft', n: 'GPU가 기본 2초 안에 작업을 못 끝내면 윈도우가 그래픽 드라이버와 GPU를 재설정' },
      ] },
    { id: 'cg-anticheat', t: '게임 보안 모듈(안티치트) 검사', en: 'Anti-cheat scan and heartbeat',
      s: '해킹을 막으려고 게임과 함께 도는 보안 모듈이 주기적으로 검사를 합니다. 검사가 무겁거나 보안 서버와 주고받는 하트비트(주기적인 생존 확인 신호)가 늦으면 뚝뚝 끊기거나 접속이 끊깁니다.',
      c: ['보안 모듈이 주기적으로 게임 메모리·실행 중인 프로그램·드라이버를 검사', '검사하는 동안 게임 스레드가 멈추거나, 하트비트가 제때 못 감', '일정한 간격으로 멈칫, 심하면 보안 오류 안내와 함께 접속 끊김'],
      sym: ['stutter', 'freeze', 'disconnect'], fx: ['stall'], who: ['me'], when: ['periodic', 'login', 'random'],
      num: '가벼운 검사는 보통 1ms도 안 걸리지만, 게임 스레드에서 도는 무거운 검사는 구현에 따라 한 번에 수십~수백 ms를 차지하기도 합니다.',
      own: ['cli', 'srv'],
      act: { game: '클라이언트: 무거운 검사는 게임 스레드 밖에서 조금씩 나눠 돌리기, 보안 모듈 버전별 끊김·튕김 통계 비교(업데이트 직후 몰리면 보안 모듈 업체에 전달). 서버: 하트비트가 한두 번 늦는 것은 허용하기.' },
      more: '보안 모듈은 OS 깊숙이 드라이버로 들어가 있어 백신·오버레이·다른 게임의 보안 모듈과 충돌하기도 합니다. 보안 모듈 업데이트 직후 특정 사양에서만 끊김·튕김 제보가 몰리면 먼저 의심합니다.',
      ref: [
        { t: 'Using the Anti-Cheat Interfaces', u: 'https://dev.epicgames.com/docs/epic-online-services/trust-and-safety/anti-cheat-interfaces/using-anti-cheat', p: 'Epic Games', n: '서버가 정해진 시간(RegisterTimeout) 안에 클라이언트의 안티치트 메시지를 못 받으면 인증 시간 초과로 내보냄(로딩으로 멈춘 클라이언트가 흔한 원인), 최근 모듈 업데이트가 문제면 이전 모듈로 되돌림' },
      ] },
  ]);

  /* ---------------- 2. 클라이언트 OS·기기 ---------------- */
  add('client-os', [
    { id: 'co-background', t: '백그라운드 프로세스의 CPU 점유', en: 'Background CPU contention',
      s: '백신 검사, 윈도우 업데이트, 방송 프로그램, 브라우저 영상이 코어를 차지하면 게임 스레드가 CPU를 배정받지 못하고 기다립니다.',
      c: ['다른 프로그램이 CPU 코어를 오래 차지', '게임 스레드가 스케줄링 대기', '프레임이 늦고 받은 패킷 처리도 늦어짐'],
      sym: ['stutter', 'burst'], fx: ['stall'], who: ['me'], when: ['random', 'periodic'],
      num: '윈도우는 보통 한 번에 수 ms~수십 ms씩 코어를 넘겨줍니다. 스케줄링에서 한 번만 밀려도 한 프레임이 사라집니다.',
      own: ['ext', 'cli'],
      act: { game: '게임 스레드 우선순위 조정, 끊김 로그에 PC 전체 CPU 사용률을 함께 남겨 다른 프로그램 탓인지 구분.', ext: '유저에게 윈도우 게임 모드 켜기, 게임 중 불필요한 프로그램(백신 검사·윈도우 업데이트·방송 프로그램·브라우저 영상) 종료 안내.' },
      more: '윈도우는 앞에 띄운 창(포그라운드)의 프로그램에 우선순위를 조금 더 주지만, 코어보다 바쁜 일이 많으면 게임도 기다립니다. 백신은 CPU를 쓰는 것보다 “실시간 감시”로 더 자주 끼어듭니다. 게임이 파일을 열 때마다 검사해서, 에셋을 읽는 순간의 멈춤이 길어집니다.',
      sim: 'cpu',
      ref: [
        { t: 'Multitasking', u: 'https://learn.microsoft.com/en-us/windows/win32/procthread/multitasking', p: 'Microsoft', n: '윈도우는 스레드마다 타임 슬라이스를 주고 다 쓰면 다음 스레드로 넘김, 타임 슬라이스는 약 20ms(OS·CPU에 따라 다름)' },
        { t: 'Priority Boosts', u: 'https://learn.microsoft.com/en-us/windows/win32/procthread/priority-boosts', p: 'Microsoft', n: '앞에 띄운 창(포그라운드)의 프로세스는 우선순위를 백그라운드 프로세스 이상으로 올려 줌' },
        { t: 'About regular quick and full scans with Microsoft Defender Antivirus', u: 'https://learn.microsoft.com/en-us/defender-endpoint/schedule-antivirus-scans', p: 'Microsoft', n: '실시간 보호는 파일을 열고 닫을 때마다, 폴더를 열 때마다 검사' },
      ] },
    { id: 'co-power', t: '절전 모드·발열 스로틀링', en: 'Power saving, thermal throttling',
      s: '노트북 배터리 모드, 폰 절전 모드, 기기 발열 때문에 CPU·GPU 속도가 떨어집니다. 발열은 처음엔 괜찮다가 한참 뒤부터 느려지는 게 특징입니다.',
      c: ['배터리·절전 모드이거나 기기가 뜨거워짐', 'CPU·GPU 클럭을 기기에 따라 30~50% 낮춤', '절전 모드는 켜자마자, 발열은 몇 분~20분쯤 플레이한 뒤부터 FPS가 떨어지고 뚝뚝 끊김'],
      sym: ['stutter', 'delay'], fx: ['stall'], who: ['me'], when: ['uptime', 'always'],
      own: ['ext', 'cli'],
      act: { game: '그래픽 옵션 자동 조절, 프레임 상한으로 발열 관리, OS가 알려 주는 발열 단계(iOS의 thermalState, 안드로이드의 발열 상태 API)를 보고 미리 옵션 낮추기, 그래픽 칩이 두 개인 노트북에서 외장 그래픽을 쓰도록 실행 파일에 표시(NvOptimusEnablement·AmdPowerXpressRequestHighPerformance 내보내기).', ext: '유저에게 절전 모드 끄기, 노트북은 전원 연결 권장 안내, “좋은 노트북인데 FPS가 낮다”는 제보면 게임이 어느 그래픽 칩에서 도는지 확인하고 윈도우 그래픽 설정에서 게임을 고성능 GPU로 지정하도록 안내.' },
      more: '그래픽 칩이 두 개인 노트북은 전기를 아끼려고 게임을 느린 내장 그래픽으로 돌리기도 합니다. “좋은 노트북인데 FPS가 낮다”는 제보라면 게임이 어느 그래픽 칩에서 도는지 먼저 확인합니다.',
      sim: 'cpu',
      ref: [
        { t: 'Thermal API', u: 'https://developer.android.com/games/optimize/adpf/thermal', p: 'Android (Google)', n: '기기는 높은 성능을 제한된 시간만 유지하고 그 뒤 발열로 스로틀링됨, 발열 상태를 보고 미리 부하를 낮추도록 권장' },
        { t: 'thermalState', u: 'https://developer.apple.com/documentation/foundation/processinfo/thermalstate-swift.property', p: 'Apple', n: 'iOS가 알려 주는 현재 발열 단계, 단계가 높아지면 앱이 자원 사용을 줄여야 함' },
        { t: 'Selecting the Best Graphics Device to Run a 3D Intensive Application', u: 'https://gpuopen.com/learn/amdpowerxpressrequesthighperformance/', p: 'AMD', n: '그래픽 칩이 두 개인 노트북에서 내장 그래픽으로 돌면 60FPS 게임이 30FPS가 되기도 함, AmdPowerXpressRequestHighPerformance 내보내기로 외장 그래픽 선택' },
      ] },
    { id: 'co-timer', t: '타이머 해상도', en: 'Timer resolution (Windows 15.6ms)',
      s: '윈도우의 기본 타이머는 15.6ms 단위라 “1ms만 쉬기”가 실제로는 다음 타이머 주기까지, 길게는 15.6ms로 늘어납니다.',
      c: ['프레임 제한·패킷 전송을 Sleep(잠깐 대기) 방식으로 구현', 'OS가 15.6ms 단위로만 깨워 줌', '프레임 간격과 입력 전송 간격이 들쭉날쭉'],
      sym: ['stutter'], fx: ['jit'], who: ['me'], when: ['always'],
      num: '15.6ms 단위로는 16.7ms 간격을 맞출 수 없어, 프레임 간격이 15.6ms와 31.2ms 사이를 오갑니다.',
      own: ['cli'],
      act: { game: '고해상도 타이머 사용, 대기 대신 이벤트·V-Sync 기반 페이싱.' },
      more: '예전 윈도우는 한 프로그램이 타이머를 1ms로 바꾸면 모든 프로그램에 적용됐습니다. 그래서 “브라우저를 켜 두면 게임이 부드러워진다”는 말도 있었습니다. 윈도우 10 2004 버전부터는 요청한 프로그램에만 적용되고, 윈도우 11은 최소화되거나 완전히 가려져 소리도 내지 않는 창의 요청을 적용하지 않을 수 있습니다.',
      sim: 'cpu',
      ref: [
        { t: '_WDF_TIMER_CONFIG (wdftimer.h)', u: 'https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdftimer/ns-wdftimer-_wdf_timer_config', p: 'Microsoft', n: '일반 타이머의 정확도는 시스템 클록 틱 간격인 기본 15.6ms, 고해상도 타이머는 1ms' },
        { t: 'timeBeginPeriod function (timeapi.h)', u: 'https://learn.microsoft.com/en-us/windows/win32/api/timeapi/nf-timeapi-timebeginperiod', p: 'Microsoft', n: '윈도우 10 2004 이전에는 전역 설정, 이후에는 요청한 프로세스에만 적용, 윈도우 11은 가려지거나 최소화된 창의 프로세스에 높은 해상도를 보장하지 않음' },
        { t: 'CreateWaitableTimerExW function (synchapi.h)', u: 'https://learn.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-createwaitabletimerexw', p: 'Microsoft', n: '고해상도 대기 타이머 플래그 CREATE_WAITABLE_TIMER_HIGH_RESOLUTION' },
      ] },
    { id: 'co-mobile-bg', t: '모바일 앱 백그라운드 전환', en: 'App suspended in background',
      s: '알림을 보려고 앱을 잠깐 내리면 OS가 몇 초 뒤 앱을 일시 정지(suspend)하고, 그동안 서버는 나를 끊습니다.',
      c: ['메시지 확인·전화로 게임을 내림', '게임 엔진이 게임 진행을 멈추고, OS도 곧 앱과 네트워크를 정지시킴', '돌아오면 이미 접속 끊김, 재접속'],
      sym: ['disconnect'], fx: ['stall', 'loss'], who: ['me'], when: ['idle', 'action'],
      num: '게임 엔진은 보통 내리는 순간 멈춥니다. iOS는 몇 초, 추가 시간을 받아도 대개 수십 초 안에 앱을 일시 정지하고, 안드로이드 14 이상은 화면에서 내려간 앱을 10초쯤 뒤 동결(freeze)합니다.',
      own: ['cli', 'srv'],
      act: { game: '클라이언트: 돌아오면 끊긴 연결을 기다리지 말고 세션 토큰으로 바로 자동 재접속(재로그인 없이 이어 붙이기), 최신 상태를 한 번에 받아 맞추기. 서버: 하트비트가 끊기면 연결은 정리하되 캐릭터 세션은 짧은 유예 시간 동안 유지(바로 내보내지 않기), 그 안에 재접속하면 세션 토큰으로 이어 받기.' },
      more: '폰은 메모리가 모자라면 내려 둔 게임을 아예 종료하기도 합니다. 카메라나 결제·인증 앱을 다녀오면 게임이 처음부터 다시 켜지는 이유입니다. 저사양 기기일수록 흔합니다.',
      sim: 'timeouts',
      ref: [
        { t: 'Extending your app’s background execution time', u: 'https://developer.apple.com/documentation/uikit/extending-your-app-s-background-execution-time', p: 'Apple', n: '백그라운드로 가면 applicationDidEnterBackground에 5초가 주어지고 곧 일시 정지, 더 필요하면 beginBackgroundTask로 시간을 요청(남은 시간은 backgroundTimeRemaining)' },
        { t: 'Cached apps freezer', u: 'https://source.android.com/docs/core/perf/cached-apps-freezer', p: 'Android (Google)', n: '안드로이드 14 이상은 캐시 상태가 된 앱 프로세스를 10초 뒤 동결, 동결되면 모든 스레드가 멈춤' },
        { t: 'Application.runInBackground', u: 'https://docs.unity3d.com/ScriptReference/Application-runInBackground.html', p: 'Unity', n: '기본값 false로 백그라운드에서 멈춤, 안드로이드는 백그라운드면 설정과 관계없이 멈추고 iOS는 이 설정을 무시' },
      ] },
    { id: 'co-netswitch', t: '와이파이 ↔ LTE·5G 전환', en: 'Network switch changes IP',
      s: '집 밖으로 나가며 와이파이가 끊기고 LTE·5G로 바뀌면 내 IP 주소가 바뀌어 기존 연결이 무효가 됩니다.',
      c: ['와이파이 신호가 약해져 모바일망으로 전환', '내 IP 주소가 바뀌어 옛 주소로 맺은 연결로는 더 주고받을 수 없음', '잠깐 멈춘 뒤 접속 끊김 또는 재접속'],
      sym: ['freeze', 'disconnect'], fx: ['loss'], who: ['me'], when: ['moving'],
      own: ['srv', 'cli', 'net'],
      act: { game: '서버: 세션 토큰으로 주소가 바뀌어도 같은 플레이어로 이어 받고 옛 주소의 연결은 바로 정리, 주소가 바뀌어도 이어지는 프로토콜(QUIC의 연결 마이그레이션 등) 검토. 클라이언트: 네트워크 전환을 감지하면 하트비트 타임아웃을 기다리지 말고 세션 토큰으로 바로 재접속.', infra: 'QUIC 연결 마이그레이션을 쓰면 로드밸런서가 주소·포트 대신 연결 ID로 서버를 고르도록 설정(주소·포트로 고르면 주소가 바뀐 패킷이 다른 서버로 감).' },
      ref: [
        { t: 'Read network state', u: 'https://developer.android.com/training/basics/network-ops/reading-network-state', p: 'Android (Google)', n: '기본 네트워크가 바뀌면 새 연결은 새 네트워크로 가고 이전 네트워크의 연결은 결국 강제로 끊김, registerDefaultNetworkCallback으로 전환 감지' },
        { t: 'RFC 9000: QUIC: A UDP-Based Multiplexed and Secure Transport', u: 'https://www.rfc-editor.org/rfc/rfc9000', p: 'IETF', n: '연결 ID로 IP 주소·포트가 바뀌어도 연결 유지(9장), 주소·포트로만 분산하는 로드밸런서는 주소가 바뀐 패킷을 다른 서버로 보낼 수 있음(5.2.3절)' },
        { t: 'RFC 9293: Transmission Control Protocol (TCP)', u: 'https://www.rfc-editor.org/rfc/rfc9293', p: 'IETF', n: 'TCP 연결은 양 끝의 소켓(주소·포트) 쌍으로 식별됨' },
      ] },
    { id: 'co-security', t: '보안 프로그램의 패킷 검사', en: 'Antivirus / firewall inspection',
      s: '백신·방화벽이 모든 패킷을 검사하면 지연이 늘고, 과하면 게임을 공격으로 오인해 막습니다.',
      c: ['보안 프로그램이 송수신 패킷을 하나하나 검사', '패킷마다 지연이 붙고 검사가 밀리면 버려짐', '핑이 불규칙하게 튀거나 접속이 막힘'],
      sym: ['stutter', 'noconnect'], fx: ['jit', 'loss'], who: ['me'], when: ['always', 'login'],
      num: '정상일 때 패킷 검사에 드는 시간은 보통 1ms도 안 됩니다. 문제는 검사 모듈이 밀리거나 버그가 있을 때, 게임 통신을 공격으로 오인할 때입니다.',
      own: ['ext', 'cli'],
      act: { game: '보안 프로그램 호환성 목록 관리, 설치할 때 윈도우 방화벽에 게임 예외 등록.', ext: '유저에게 보안 프로그램에서 게임을 예외로 등록하도록 안내, 게임을 공격으로 오인하면 보안 프로그램 업체에 오탐 수정 요청.' },
      ref: [
        { t: 'About Windows Filtering Platform', u: 'https://learn.microsoft.com/en-us/windows/win32/fwp/about-windows-filtering-platform', p: 'Microsoft', n: '윈도우 네트워크 스택의 후크와 필터 엔진으로 패킷을 허용·차단하는 구조, 외부 보안 업체가 자기 필터 모듈(콜아웃)을 끼워 넣을 수 있음' },
        { t: 'Windows Firewall Rules', u: 'https://learn.microsoft.com/en-us/windows/security/operating-system-security/network-security/windows-firewall/rules', p: 'Microsoft', n: '기본은 들어오는 연결 차단이라 앱에 예외 규칙이 필요하고, 흔히 앱 설치 프로그램이 규칙을 만듦' },
        { t: 'Address false positives/negatives in Microsoft Defender for Endpoint', u: 'https://learn.microsoft.com/en-us/defender-endpoint/defender-endpoint-false-positives-negatives', p: 'Microsoft', n: '정상 프로그램을 위협으로 오인(오탐)했을 때 예외 설정과 마이크로소프트에 분석 제출하는 절차' },
      ] },
    { id: 'co-rcvbuf', t: '수신 버퍼 넘침', en: 'Socket receive buffer overflow',
      s: '게임이 바빠서 소켓(OS가 제공하는 네트워크 송수신 인터페이스)에서 패킷을 늦게 꺼내면 OS 버퍼가 넘칩니다.',
      c: ['프레임이 밀려 게임이 소켓을 늦게 읽음', 'OS 수신 버퍼가 가득 차 UDP는 버리고 TCP는 수신 윈도우를 줄여 송신을 멈추게 함', '순간이동(UDP) 또는 몰아치기(TCP)'],
      sym: ['teleport', 'burst'], fx: ['loss', 'stall'], who: ['me'], when: ['event'],
      num: '기본 수신 버퍼는 OS·설정에 따라 수십~수백 KB. 사람 많은 곳의 업데이트는 1초에 수백 KB가 되기도 합니다.',
      own: ['cli'],
      act: { game: '수신 전용 스레드, 버퍼 크기 조정(SO_RCVBUF).' },
      ref: [
        { t: 'socket(7) — Linux manual page', u: 'https://man7.org/linux/man-pages/man7/socket.7.html', p: 'Linux man-pages', n: 'SO_RCVBUF는 소켓 수신 버퍼 최대 크기, 기본값은 rmem_default, 최대값은 rmem_max로 정해짐(안드로이드도 리눅스 커널)' },
        { t: 'SOL_SOCKET Socket Options (Winsock2.h)', u: 'https://learn.microsoft.com/en-us/windows/win32/winsock/sol-socket-socket-options', p: 'Microsoft', n: '윈도우 SO_RCVBUF: 소켓마다 수신용으로 잡아 두는 버퍼 공간' },
        { t: 'RFC 9293: Transmission Control Protocol (TCP)', u: 'https://www.rfc-editor.org/rfc/rfc9293', p: 'IETF', n: 'TCP 윈도우 필드는 수신 측이 더 받을 수 있는 바이트 수, 0이면 송신 측은 제로 윈도우 프로브만 보내며 기다림' },
      ] },
    { id: 'co-swap', t: '클라이언트 메모리 부족·스왑', en: 'Paging / swap on client',
      s: '브라우저 탭 수십 개와 게임을 함께 켜 두면 OS가 게임 메모리 일부를 디스크로 내보냅니다.',
      c: ['전체 램이 부족해짐', 'OS가 당장 안 쓰는 게임 메모리를 디스크로 옮김', '그 부분을 다시 쓰는 순간 저장장치에 따라 수십~수백 ms 멈춤'],
      sym: ['freeze', 'stutter'], fx: ['stall'], who: ['me'], when: ['moving', 'random'],
      own: ['ext', 'cli'],
      act: { game: '메모리 사용량 줄이기, 남은 메모리가 적으면 경고 표시.', ext: '유저에게 최소 사양 안내, 게임 중 다른 프로그램(브라우저 탭 등) 종료 안내.' },
      sim: 'ladder',
      ref: [
        { t: 'Introduction to the page file', u: 'https://learn.microsoft.com/en-us/troubleshoot/windows-client/performance/introduction-to-the-page-file', p: 'Microsoft', n: '페이지 파일은 디스크에 있는 파일로, 자주 안 쓰는 수정된 메모리 페이지를 램에서 내보내는 데 씀' },
        { t: 'Working Set', u: 'https://learn.microsoft.com/en-us/windows/win32/memory/working-set', p: 'Microsoft', n: '램에 없는 페이지를 건드리면 페이지 폴트, 하드 폴트는 페이지 파일 등 디스크에서 읽어 와야 해결됨' },
      ] },
    { id: 'co-vram', t: '그래픽 메모리(VRAM) 부족', en: 'VRAM over-commit',
      s: '그래픽 옵션이 요구하는 메모리가 그래픽카드 메모리보다 크면, OS가 텍스처를 PC 메모리로 내보냈다가 다시 가져오느라 뚝뚝 끊깁니다.',
      c: ['높은 텍스처 옵션, 사람 많은 곳의 온갖 장비·이펙트로 그래픽카드 메모리가 가득 참', 'OS가 당장 안 쓰는 텍스처를 PC 메모리로 옮겼다가, 필요할 때 느린 PCIe 버스로 다시 가져옴', '새 장면이나 새 캐릭터가 보일 때마다 멈칫, 텍스처가 한동안 흐릿함'],
      sym: ['stutter', 'freeze'], fx: ['stall'], who: ['me'], when: ['event', 'moving'],
      num: '그래픽카드 메모리는 1초에 수백 GB를 읽지만, PC 메모리와 오가는 PCIe 버스는 세대에 따라 1초에 16~64GB 안팎이라 열 배 넘게 느립니다.',
      own: ['cli', 'ext'],
      act: { game: '그래픽카드 메모리 크기에 맞춘 옵션 기본값, 메모리 예산을 넘으면 텍스처 품질 자동 낮추기, 사람 많은 곳은 캐릭터 텍스처 간소화.', ext: '유저에게 텍스처 옵션 낮추기 안내, 클라이언트를 두 개 띄우면 옵션을 더 낮추도록 안내.' },
      more: '윈도우 작업 관리자의 GPU 항목에서 “전용 GPU 메모리”가 꽉 차고 “공유 GPU 메모리”가 늘어나면 이 상태입니다. 같은 PC에 클라이언트를 두 개 띄우면 더 빨리 찹니다(“메모리·VRAM 부족으로 스트리밍 실패” 항목).',
      ref: [
        { t: 'Residency', u: 'https://learn.microsoft.com/en-us/windows/win32/direct3d12/residency', p: 'Microsoft', n: '프로세스가 쓸 수 있는 그래픽 메모리 예산이 있고, 넘치면 커널이 외장 GPU의 힙 일부를 PC 메모리로 옮김(최후의 수단이라 예산 관리 권장)' },
        { t: 'GPUs in the task manager', u: 'https://devblogs.microsoft.com/directx/gpus-in-the-task-manager/', p: 'Microsoft', n: '작업 관리자의 전용 GPU 메모리는 그래픽카드의 VRAM, 공유 GPU 메모리는 GPU와 CPU가 함께 쓰는 PC 메모리' },
        { t: 'CUDA C++ Best Practices Guide', u: 'https://docs.nvidia.com/cuda/cuda-c-best-practices-guide/index.html', p: 'NVIDIA', n: '그래픽 메모리 대역폭(V100 898GB/s)이 PCIe x16 3세대(16GB/s)보다 훨씬 커서 PC 메모리와 오가는 전송을 줄이라고 권장' },
      ] },
    { id: 'co-wifi-scan', t: '와이파이 백그라운드 스캔', en: 'Periodic Wi-Fi background scan',
      s: 'OS가 주변 와이파이를 찾으려고 주기적으로 채널을 옮겨 다니는 동안 통신이 잠깐 멈춥니다.',
      c: ['OS·드라이버가 일정 주기로 주변 와이파이를 검색', '검색하는 동안 송수신이 잠깐 멈춤', '정확히 일정한 간격(예: 60초마다)으로 핑이 튐'],
      sym: ['stutter', 'teleport'], fx: ['jit'], who: ['me'], when: ['periodic'],
      num: '보통 한 번에 수십~수백 ms. 너무 규칙적이면 이 원인을 먼저 의심합니다.',
      own: ['ext', 'cli'],
      act: { game: '게임 중 무선 검색을 줄이는 모드 요청(안드로이드는 저지연 와이파이 모드 WIFI_MODE_FULL_LOW_LATENCY, 윈도우는 WlanSetInterface의 미디어 스트리밍 모드. 기기·드라이버에 따라 효과가 없기도 함).', ext: '유저에게 유선 연결, 위치 서비스·와이파이 자동 검색 설정 조정, 무선 드라이버 업데이트 안내.' },
      ref: [
        { t: 'WDI low latency connection quality', u: 'https://learn.microsoft.com/en-us/windows-hardware/drivers/network/wdi-low-latency-connection-quality', p: 'Microsoft', n: '검색·로밍은 무선 칩을 연결된 채널 밖으로 옮기므로, 저지연 모드에서는 채널을 벗어나는 시간과 검색을 제한' },
        { t: 'WlanSetInterface function (wlanapi.h)', u: 'https://learn.microsoft.com/en-us/windows/win32/api/wlanapi/nf-wlanapi-wlansetinterface', p: 'Microsoft', n: '윈도우에서 백그라운드 검색(wlan_intf_opcode_background_scan_enabled)과 미디어 스트리밍 모드를 켜고 끄는 API' },
        { t: 'Wi-Fi low-latency mode', u: 'https://source.android.com/docs/core/connect/wifi-low-latency', p: 'Android (Google)', n: '저지연 모드에서는 와이파이 절전을 끄고, 검색·로밍 설정 최적화는 기기 제조사 구현에 따라 다름' },
      ] },
    { id: 'co-driver', t: 'NIC 절전·드라이버 문제', en: 'NIC power saving, driver bugs',
      s: '랜카드·와이파이 칩이 패킷 사이에 절전 상태로 들어가면 다시 활성화되는 데 시간이 걸립니다.',
      c: ['네트워크 장치 절전 기능이 켜져 있거나 드라이버가 오래됨', '절전 해제(wake-up) 지연, 가끔 장치 재시작', '불규칙한 지연, 드물게 수 초 멈춤'],
      sym: ['stutter', 'freeze'], fx: ['jit', 'loss'], who: ['me'], when: ['idle', 'random'],
      own: ['ext', 'cli'],
      act: { game: '안드로이드 클라이언트는 게임 중 저지연 와이파이 모드(WIFI_MODE_FULL_LOW_LATENCY)를 요청해 와이파이 절전 끄기.', ext: '유저에게 네트워크 드라이버 업데이트, 장치 관리자에서 네트워크 장치 절전 해제 안내, 화면 전체가 멈칫하고 소리가 지직거리면 LatencyMon으로 원인 드라이버를 찾도록 안내.' },
      more: '드라이버가 인터럽트를 처리하느라 CPU를 오래 점유하면(윈도우에서는 DPC 지연이라고 부릅니다) 그동안 게임 스레드도 코어를 못 씁니다. 이때는 CPU 사용률이 낮은데도 화면 전체가 멈칫하고 소리도 지직거립니다. LatencyMon 같은 도구로 어느 드라이버인지 찾을 수 있고, 와이파이·랜 드라이버가 흔한 원인입니다.',
      ref: [
        { t: 'Introduction to NDIS Selective Suspend', u: 'https://learn.microsoft.com/en-us/windows-hardware/drivers/network/ndis-selective-suspend', p: 'Microsoft', n: '윈도우는 쉬고 있는 네트워크 어댑터를 저전력 상태로 보낼 수 있음(선택적 절전)' },
        { t: 'Guidelines for Writing DPC Routines', u: 'https://learn.microsoft.com/en-us/windows-hardware/drivers/kernel/guidelines-for-writing-dpc-routines', p: 'Microsoft', n: 'DPC가 도는 동안 그 코어의 모든 스레드가 멈추므로 한 번에 100µs를 넘기지 않도록 권고' },
        { t: 'Wi-Fi low-latency mode', u: 'https://source.android.com/docs/core/connect/wifi-low-latency', p: 'Android (Google)', n: '안드로이드 저지연 와이파이 모드는 프레임워크가 와이파이 절전을 명시적으로 끔' },
      ] },
    { id: 'co-other-apps', t: '같은 기기의 다른 앱이 대역폭 점유', en: 'Other apps saturating the link',
      s: '클라우드 동기화, 대용량 다운로드, 게임 패치가 같은 PC에서 돌면 게임 패킷이 대기열에서 기다립니다.',
      c: ['다른 앱이 업로드·다운로드를 최대로 사용', 'PC와 공유기의 대기열에 게임 패킷이 쌓임', '핑 폭등, 입력 지연, 몰아치기'],
      sym: ['delay', 'burst'], fx: ['lat', 'jit'], who: ['me', 'home'], when: ['random'],
      own: ['ext', 'cli'],
      act: { game: '우리 런처·패처는 게임 중 백그라운드 다운로드를 멈추거나 속도 제한.', ext: '유저에게 다운로드 속도 제한, 게임 중 자동 업데이트 끄기 안내.' },
      sim: 'bloat',
      ref: [
        { t: 'Introduction', u: 'https://www.bufferbloat.net/projects/bloat/wiki/Introduction/', p: 'Bufferbloat.net', n: '공유기 등 네트워크 장비가 데이터를 너무 많이 쌓아 두면 지연이 크게 튐(버퍼블로트)' },
        { t: 'Delivery Optimization reference', u: 'https://learn.microsoft.com/en-us/windows/deployment/do/waas-delivery-optimization-reference', p: 'Microsoft', n: '윈도우 업데이트 다운로드(배달 최적화)는 기본값이 사용 가능한 대역폭에 맞춰 동적으로 조절되고, 백그라운드·포그라운드 다운로드 대역폭 상한을 설정할 수 있음' },
      ] },
    { id: 'co-unfocused', t: '창 최소화·비활성 시 처리 제한', en: 'Minimized / unfocused window throttling',
      s: '다른 창을 보거나 게임을 최소화하면 게임과 윈도우가 전기를 아끼려고 게임을 느리게 돌립니다. 돌아오면 밀린 패킷이 몰려오거나, 이미 접속이 끊겨 있습니다.',
      c: ['Alt+Tab으로 다른 창을 보거나 게임을 최소화', '게임이 보이지 않는 동안 FPS를 크게 낮추거나 멈추고, 윈도우도 보이지 않는 프로그램의 우선순위를 낮춤', '돌아오는 순간 몰아치기, 오래 내려 두었다면 접속 끊김'],
      sym: ['burst', 'stutter', 'disconnect'], fx: ['stall'], who: ['me'], when: ['action', 'idle'],
      num: '창이 안 보일 때 FPS를 5~10으로 낮추면 프레임 하나가 100~200ms. 패킷을 프레임마다 처리하는 게임은 그만큼 패킷을 늦게 읽습니다.',
      own: ['cli'],
      act: { game: '창이 안 보여도 패킷 수신과 하트비트는 별도 스레드에서 계속, 엔진의 “백그라운드에서 실행” 설정 확인, 복귀할 때 최신 상태로 한 번에 맞추기.' },
      more: '윈도우 11은 최소화되거나 완전히 가려져 소리도 내지 않는 창의 프로그램에 1ms 타이머를 보장하지 않습니다. 배터리로 도는 노트북에서는 그런 프로그램을 전기를 가장 적게 쓰는 속도로 낮추고, 코어 종류가 섞인 CPU라면 느린 효율 코어로 돌리기도 합니다. 같은 PC의 두 클라이언트 중 백그라운드 쪽만 이상하다면 “백그라운드 창의 처리 제한” 항목을 함께 보세요.',
      ref: [
        { t: 'Quality of Service', u: 'https://learn.microsoft.com/en-us/windows/win32/procthread/quality-of-service', p: 'Microsoft', n: '보이지도 들리지도 않는 창의 프로그램은 Low QoS, 배터리일 때 가장 효율적인 CPU 속도와 효율 코어로 스케줄링' },
        { t: 'timeBeginPeriod function (timeapi.h)', u: 'https://learn.microsoft.com/en-us/windows/win32/api/timeapi/nf-timeapi-timebeginperiod', p: 'Microsoft', n: '윈도우 11은 가려지거나 최소화된 창의 프로세스에 기본보다 높은 타이머 해상도를 보장하지 않음' },
        { t: 'Application.runInBackground', u: 'https://docs.unity3d.com/ScriptReference/Application-runInBackground.html', p: 'Unity', n: '유니티 기본값은 false라 창이 백그라운드로 가면 게임 루프가 멈춤' },
      ] },
    { id: 'co-overlay', t: '오버레이 프로그램 간섭', en: 'Overlays and screen hooks',
      s: '메신저·런처·녹화·FPS 표시 프로그램이 게임 화면 위에 자기 UI를 덧그리려고 게임의 렌더링 과정에 끼어듭니다(후킹). 프레임마다 작업이 늘고, 가끔 게임과 부딪혀 멈칫하거나 게임이 강제로 꺼집니다.',
      c: ['메신저·게임 런처·그래픽카드 도구·녹화 프로그램의 오버레이가 켜져 있음', '프레임을 화면에 내보낼 때마다 오버레이가 끼어들어 자기 UI를 덧그림', '프레임이 조금씩 늦고, 알림이 뜨는 순간 멈칫하거나 그래픽 오류·강제 종료(플레이어에게는 접속 끊김처럼 보임)'],
      sym: ['stutter', 'freeze', 'disconnect'], fx: ['stall'], who: ['me'], when: ['always', 'random'],
      own: ['ext', 'cli'],
      act: { game: '크래시·끊김 리포트에 실행 중인 오버레이 목록을 함께 모으기.', ext: '제보가 오면 유저에게 오버레이를 모두 끄고 다시 시험하도록 안내.' },
      more: '특정 사람만 뚝뚝 끊기거나 게임이 꺼지고 사양으로는 설명이 안 될 때, 오버레이와 게임 보안 모듈의 충돌을 먼저 의심합니다.',
      ref: [
        { t: 'Steam Overlay (Steamworks Documentation)', u: 'https://partner.steamgames.com/doc/features/overlay', p: 'Valve', n: '스팀 오버레이는 스팀으로 실행한 게임에 자동으로 후킹해 끼어들고, 그 방식 때문에 게임의 렌더링 API 사용상 메모리 오류를 드러내 크래시가 나기도 함' },
      ] },
  ]);

  /* ---------------- 3. 집 네트워크 ---------------- */
  add('home', [
    { id: 'hn-wifi', t: '와이파이 간섭·신호 약화', en: 'Wi-Fi interference, weak signal',
      s: '신호가 약하거나 간섭이 생기면 무선 구간에서 몇 번씩 다시 보내느라 도착이 들쭉날쭉해집니다.',
      c: ['벽·거리·전자레인지·블루투스·이웃 공유기로 전파 품질 저하', '무선 구간에서 전송 실패 → 몇 번씩 재전송', '패킷 도착이 들쭉날쭉(지터)해 캐릭터가 멈칫멈칫, 심하면 손실로 순간이동'],
      sym: ['stutter', 'teleport', 'rubber'], fx: ['jit', 'loss'], who: ['me', 'home'], when: ['random', 'always'],
      num: '재전송 한 번에 1~4ms쯤 더 걸립니다. 신호가 약하면 느린 속도로 여러 번 다시 보내고 채널이 빌 때까지 대기도 해서, 50~200ms씩 튀기도 합니다. 평균 핑은 멀쩡해 보이는 게 함정입니다.',
      own: ['ext', 'cli'],
      act: { game: '회선 상태에 따라 보간 버퍼 길이 자동 조절, 지터·손실이 크면 화면에 네트워크 상태 표시.', ext: '유저에게 유선 연결, 5GHz·6GHz 사용, 공유기 위치 옮기기 안내.' },
      sim: 'bloat',
      ref: [
        { t: 'Resolve Wi-Fi and Bluetooth issues caused by wireless interference', u: 'https://support.apple.com/en-us/102319', p: 'Apple', n: '전자레인지·무선 전화기 같은 간섭원, 와이파이와 블루투스가 같은 2.4GHz 대역을 씀, 5GHz로 옮기기와 간섭이 적은 채널 고르기 권장' },
        { t: 'RFC 8325: Mapping Diffserv to IEEE 802.11', u: 'https://www.rfc-editor.org/rfc/rfc8325', p: 'IETF', n: '802.11의 CSMA/CA: 채널이 비어 있을 때만 보내고, 바쁘면 빌 때까지 미룬 뒤 무작위 백오프만큼 더 기다림' },
        { t: 'Ending the Anomaly: Achieving Low Latency and Airtime Fairness in WiFi (USENIX ATC 2017)', u: 'https://www.usenix.org/system/files/conference/atc17/atc17-hoiland-jorgensen.pdf', p: 'USENIX', n: '부하가 걸린 와이파이의 기본 대기열은 수백 ms 지연, 느린 속도로 붙은(신호 약한) 기기는 FQ-CoDel을 써도 중앙값 200ms 넘음' },
      ] },
    { id: 'hn-channel', t: '와이파이 채널 혼잡', en: 'Crowded Wi-Fi channel',
      s: '아파트처럼 공유기가 수십 개 있는 곳은 같은 채널을 나눠 쓰느라 전송 기회를 기다립니다.',
      c: ['수십 개 공유기가 같은 2.4GHz 채널을 사용', '전송하려면 다른 기기의 전송이 끝나 채널이 빌 때까지 대기', '사람들이 집에 오는 저녁 시간에 지터(도착 간격의 흔들림)가 늘어 뚝뚝 끊김'],
      sym: ['stutter', 'delay'], fx: ['jit', 'lat'], who: ['home'], when: ['peak'],
      own: ['ext', 'cli'],
      act: { game: '지터가 늘면 보간 버퍼 길이를 자동으로 늘리기.', ext: '유저에게 5GHz·6GHz, 덜 붐비는 채널, 유선 연결 안내.' },
      ref: [
        { t: 'Recommended settings for Wi-Fi routers and access points', u: 'https://support.apple.com/en-us/102766', p: 'Apple', n: '같은 채널을 쓰는 다른 공유기·기기가 간섭원, 2.4GHz는 20MHz 폭 권장, 5GHz·6GHz는 간섭 걱정이 덜함' },
        { t: 'RFC 8325: Mapping Diffserv to IEEE 802.11', u: 'https://www.rfc-editor.org/rfc/rfc8325', p: 'IETF', n: '802.11은 채널이 바쁘면 빌 때까지 전송을 미루고 무작위 백오프 뒤에 보냄(CSMA/CA)' },
      ] },
    { id: 'hn-bufferbloat', t: '버퍼블로트 (공유기 대기열)', en: 'Bufferbloat',
      s: '가족 누군가 영상을 올리거나 큰 파일을 받으면 공유기 대기열에 수백 ms 분량의 패킷이 쌓이고, 게임 패킷도 그 뒤에서 기다립니다.',
      c: ['가족의 영상 업로드·클라우드 백업, 내 방송 송출, 대용량 다운로드로 회선이 꽉 참', '공유기나 모뎀이 넘치는 패킷을 큰 대기열에 쌓아 둠', '게임 패킷도 대기열 뒤에서 기다려 핑이 수백 ms로 폭등'],
      sym: ['delay', 'burst', 'teleport'], fx: ['lat', 'jit'], who: ['home', 'me'], when: ['random', 'peak'],
      num: '업로드 10Mbps 회선에 1MB 버퍼면 대기열이 800ms 분량까지 길어집니다.',
      own: ['ext', 'cli'],
      act: { game: '핑이 갑자기 수백 ms로 오르면 화면에 네트워크 상태 표시(같은 회선의 대용량 전송 가능성 안내).', ext: '유저에게 SQM(fq_codel, CAKE)이나 QoS가 있는 공유기 사용, SQM 속도는 회선 속도의 90~95%로 맞추기(그래야 대기열이 공유기 안에 생겨 효과가 남), 업로드 속도 제한 안내.' },
      more: '업로드 쪽이 특히 잘 막힙니다. 케이블·모바일 회선은 업로드가 다운로드보다 훨씬 좁은 경우가 많기 때문입니다. 광랜이 넉넉한 집에서는 와이파이 구간이 병목이 되어, 공유기의 무선 대기열에서 같은 일이 생깁니다. 게임 패킷은 작아서 대역폭은 거의 안 쓰지만, 대기열에서 기다려야 한다는 점은 똑같습니다. 업로드 방향만 막히면 내 입력만 늦고 남의 움직임은 멀쩡합니다. 폰에서는 같은 폰의 사진 백업·앱 업데이트가 폰 모뎀과 기지국의 대기열을 채워 같은 일이 생깁니다.',
      sim: 'bloat',
      ref: [
        { t: 'Setting up SQM for CeroWrt 3.10', u: 'https://www.bufferbloat.net/projects/cerowrt/wiki/Setting_up_SQM_for_CeroWrt_310/', p: 'Bufferbloat.net', n: 'SQM 속도를 실측 속도의 95%(광고 속도 기준이면 85%)로 낮춰 병목을 통신사 장비에서 공유기 안으로 가져와야 효과가 남' },
        { t: 'SQM (Smart Queue Management)', u: 'https://openwrt.org/docs/guide-user/network/traffic-shaping/sqm', p: 'OpenWrt', n: '다운로드·업로드 속도를 실측의 90%로 입력, 대기열 방식은 cake 권장(CPU가 약하면 fq_codel)' },
        { t: 'Ending the Anomaly: Achieving Low Latency and Airtime Fairness in WiFi (USENIX ATC 2017)', u: 'https://www.usenix.org/system/files/conference/atc17/atc17-hoiland-jorgensen.pdf', p: 'USENIX', n: '와이파이 구간이 꽉 차면 공유기 무선 대기열에서 수백 ms 지연이 생김, 무선 대기열을 고치면 부하 중 지연이 약 10분의 1로 줄어듦' },
      ] },
    { id: 'hn-nat', t: 'NAT 매핑 만료', en: 'NAT mapping timeout',
      s: '공유기는 한동안 패킷이 오가지 않은 유휴 연결을 NAT 테이블에서 지웁니다. 가만히 있다가 움직이는 순간 접속이 끊기는 흔한 원인입니다.',
      c: ['공유기가 “안쪽 기기 ↔ 바깥 서버” 연결을 NAT 테이블(주소 변환표)에 기록', '패킷이 한동안 없으면 테이블에서 삭제(UDP는 흔히 30~120초)', '서버 패킷이 집 안으로 못 들어와 접속 끊김'],
      sym: ['disconnect'], fx: ['loss'], who: ['me', 'home'], when: ['idle'],
      own: ['cli', 'srv'],
      act: { game: '클라이언트: 가장 짧은 유휴 타임아웃의 절반 이하 간격으로 하트비트 보내기(UDP 매핑은 집 안에서 나가는 패킷으로만 확실히 갱신되므로 클라이언트가 보냄), 끊기면 자동 재접속. 서버: 하트비트에 응답하고, 일정 시간 못 받으면 연결을 먼저 정리, 매핑이 지워져 바깥 주소·포트가 바뀌어도 세션 토큰(접속할 때 받은 확인 번호)으로 같은 플레이어임을 확인해 이어 받기.' },
      sim: 'timeouts',
      ref: [
        { t: 'RFC 4787: Network Address Translation (NAT) Behavioral Requirements for Unicast UDP', u: 'https://www.rfc-editor.org/rfc/rfc4787', p: 'IETF', n: 'UDP 매핑 타이머는 2분 전에 끝나면 안 되고 기본 5분 이상 권장, 안에서 나가는 패킷으로 갱신은 필수·바깥에서 들어오는 패킷으로 갱신은 선택' },
        { t: 'An Experimental Study of Home Gateway Characteristics (IMC 2010)', u: 'https://conferences.sigcomm.org/imc/2010/papers/p260.pdf', p: 'ACM', n: '가정용 공유기 34종 측정: UDP 매핑 유지 30~691초·중앙값 90초로 절반 넘게 2분 미만, TCP는 중앙값 약 60분' },
        { t: 'RFC 9308: Applicability of the QUIC Transport Protocol', u: 'https://www.rfc-editor.org/rfc/rfc9308', p: 'IETF', n: '경로에 NAT가 있는 인터넷에서는 약 30초 간격의 keep-alive가 적당, 그보다 잦으면 트래픽·전력 낭비' },
      ] },
    { id: 'hn-router', t: '공유기 성능 부족·과열', en: 'Router CPU / session table exhaustion',
      s: '값싼 공유기에 기기 수십 대, 연결 수천 개가 몰리면 공유기 자체가 처리를 못 합니다.',
      c: ['기기 수십 대, P2P·토렌트가 연결 수천 개를 엶', '공유기 CPU와 세션 테이블이 포화', '패킷 처리 지연·손실, 새 연결 실패'],
      sym: ['stutter', 'noconnect', 'disconnect'], fx: ['loss', 'jit'], who: ['home'], when: ['uptime', 'random'],
      own: ['ext'],
      act: { ext: '유저에게 공유기 재부팅(임시), 공유기 교체, 연결을 많이 여는 프로그램(P2P·토렌트) 정리 안내.' },
      ref: [
        { t: 'An Experimental Study of Home Gateway Characteristics (IMC 2010)', u: 'https://conferences.sigcomm.org/imc/2010/papers/p260.pdf', p: 'ACM', n: '가정용 공유기가 한 서버 포트로 허용하는 TCP 연결 수는 16~약 1,024개(중앙값 135), 저가 장비는 처리량이 수 Mbps 수준에 그치기도 함' },
        { t: 'Netfilter Conntrack Sysfs variables', u: 'https://docs.kernel.org/networking/nf_conntrack-sysctl.html', p: 'Linux kernel', n: '리눅스 연결 추적 표의 최대 항목 수(nf_conntrack_max)와 상태별 유지 시간 기본값' },
      ] },
    { id: 'hn-handover', t: '기지국 핸드오버 (이동 중)', en: 'Cellular handover',
      s: '버스·지하철로 이동하면 기지국이 바뀌는 동안 통신이 끊깁니다.',
      c: ['이동하며 접속하는 기지국이 바뀜', '보통은 수십 ms 공백이지만, 신호가 나빠 전환에 실패하면 수백 ms~수 초 끊기기도 함', '멈췄다가 순간이동, 길면 접속 끊김'],
      sym: ['freeze', 'teleport', 'disconnect'], fx: ['loss'], who: ['me'], when: ['moving'],
      own: ['ext', 'cli', 'srv'],
      act: { game: '클라이언트: 짧은 끊김을 견디는 타임아웃, 빠른 재접속. 서버: 몇 초 끊겨도 바로 내보내지 않는 타임아웃, 재접속하면 같은 세션으로 이어 주기.', ext: '이동 중(버스·지하철) 끊김은 기지국 전환 때문임을 유저에게 안내.' },
      ref: [
        { t: 'Report ITU-R M.2134: Requirements related to technical performance for IMT-Advanced radio interface(s)', u: 'https://www.itu.int/pub/R-REP-M.2134-2008', p: 'ITU', n: '핸드오버 중 데이터를 못 주고받는 시간의 요구치: 같은 주파수 27.5ms, 다른 주파수 40~60ms' },
        { t: 'Understanding Operational 5G: A First Measurement Study on Its Coverage, Performance and Energy Consumption (SIGCOMM 2020)', u: 'https://xyzhang.ucsd.edu/papers/DXu_SIGCOMM20_5Gmeasure.pdf', p: 'ACM', n: '상용망 실측 핸드오버 지연: 4G↔4G 평균 30ms, 5G(NSA) 셀 사이 평균 108ms' },
      ] },
    { id: 'hn-rrc', t: 'RRC 상태 전환 지연 (모바일 무선 절전)', en: 'Radio state promotion (RRC)',
      s: '폰은 한동안 통신이 없으면 무선 연결을 저전력 상태로 내리고, 다음 패킷 때 다시 올리느라 늦어집니다.',
      c: ['잠시 통신이 없으면 폰이 무선 연결을 절전 상태로 전환', '다음 패킷을 보내려면 연결을 다시 올려야 함', '가만히 있다 한 첫 행동만 유독 늦음'],
      sym: ['delay'], fx: ['lat'], who: ['me'], when: ['idle'],
      num: 'LTE는 보통 10초 안팎 통신이 없으면 절전으로 내려가고, 다시 올리는 데 수십~수백 ms가 걸립니다(실측 예: 약 0.3~0.6초). 3G는 1초 이상.',
      own: ['cli'],
      act: { game: '가벼운 주기 전송으로 활성 유지(배터리와 맞바꿈).' },
      ref: [
        { t: 'An In-depth Study of LTE: Effect of Network Protocol and Application Behavior on Performance (SIGCOMM 2013)', u: 'https://conferences.sigcomm.org/sigcomm/2013/papers/sigcomm/p363.pdf', p: 'ACM', n: '측정한 LTE망의 절전 전환 타이머(tail) 10초, 절전에서 다시 올리는 지연 중앙값 435ms(25~75%: 319~558ms), 3G는 약 1.5~2초' },
        { t: 'Optimize network access', u: 'https://developer.android.com/develop/connectivity/network-ops/network-access-optimization', p: 'Android (Google)', n: '무선 상태 전환 지연과 tail 시간은 무선 기술(3G·LTE·5G)과 통신사 설정에 따라 다름, 3G 예: 저전력→최대 전력 약 1.5초, 대기→최대 전력 2초 이상' },
        { t: 'Report ITU-R M.2134: Requirements related to technical performance for IMT-Advanced radio interface(s)', u: 'https://www.itu.int/pub/R-REP-M.2134-2008', p: 'ITU', n: '대기 상태에서 활성 상태로 올라가는 제어 평면 지연 요구치 100ms 미만(호출·유선 구간 제외)' },
      ] },
    { id: 'hn-weak-cell', t: '모바일 신호 약함·음영 지역', en: 'Weak cellular signal',
      s: '엘리베이터·지하·건물 안쪽에서는 재전송이 늘고 속도가 떨어지며 결국 접속이 끊깁니다.',
      c: ['신호가 약한 곳으로 이동', '무선 재전송 증가, 속도 저하, 순간 단절', '지터·손실로 뚝뚝 끊김·순간이동, 결국 접속 끊김'],
      sym: ['stutter', 'teleport', 'disconnect'], fx: ['jit', 'loss'], who: ['me'], when: ['moving'],
      own: ['ext', 'cli'],
      act: { game: '재접속 흐름 다듬기, 네트워크 품질 표시.', ext: '신호가 약한 곳(엘리베이터·지하·건물 안쪽)에서 생기는 문제임을 유저에게 안내.' },
      ref: [
        { t: 'An In-depth Study of LTE: Effect of Network Protocol and Application Behavior on Performance (SIGCOMM 2013)', u: 'https://conferences.sigcomm.org/sigcomm/2013/papers/sigcomm/p363.pdf', p: 'ACM', n: 'LTE는 무선 구간 손실을 물리·MAC 계층 재전송으로 감춤, 가용 대역폭은 신호 세기 등에 따라 초 단위로 크게 변함' },
      ] },
    { id: 'hn-5g-flip', t: '5G↔LTE 잦은 전환 (5G 경계 지역)', en: '5G NSA / LTE switching',
      s: '5G 신호가 약한 건물 안이나 5G 경계 지역에서는 폰이 5G와 LTE를 자주 오가고, 바뀔 때마다 핑이 튀거나 통신이 잠깐 끊깁니다.',
      c: ['5G 신호가 들쭉날쭉한 곳(건물 안, 5G 경계)에 있음', '폰이 5G와 LTE 사이를 수시로 전환하며 그때마다 짧은 공백이 생김', '가만히 있어도 규칙 없이 핑이 튀고, 가끔 멈춤·순간이동'],
      sym: ['stutter', 'teleport', 'freeze'], fx: ['jit', 'loss'], who: ['me'], when: ['random', 'moving'],
      num: '전환 한 번에 수십~수백 ms. 국내 5G는 대부분 LTE와 함께 묶어 쓰는 방식(NSA)이라 5G 쪽만 붙었다 떨어졌다 하기 쉽습니다.',
      own: ['ext', 'cli'],
      act: { game: '지터가 늘면 보간 버퍼 길이를 자동으로 늘리기, 끊김 로그에 망 종류(5G·LTE) 변화를 함께 남겨 원인 구분.', ext: '유저에게 설정에서 LTE 우선 모드로 바꿔 비교해 보도록 안내, 와이파이 사용 권장.' },
      ref: [
        { t: 'Understanding Operational 5G: A First Measurement Study on Its Coverage, Performance and Energy Consumption (SIGCOMM 2020)', u: 'https://xyzhang.ucsd.edu/papers/DXu_SIGCOMM20_5Gmeasure.pdf', p: 'ACM', n: 'NSA 5G는 제어를 LTE에 맡겨 5G 셀을 바꿀 때 5G를 놓고 LTE를 거쳐 다시 붙음: 평균 108ms(4G→5G 80ms), 5G가 낀 전환 직후 TCP 처리량 73~83% 감소' },
        { t: '5G 통신서비스 품질평가 결과 발표', u: 'https://www.korea.kr/briefing/policyBriefingView.do?newsId=156404679', p: '과학기술정보통신부', n: '2020년 발표 기준 국내 5G는 NSA 방식으로 제공 중이고 SA 전환은 예정 단계' },
      ] },
    { id: 'hn-captive', t: '공용 와이파이·회사망 제한', en: 'Captive portal, restrictive network',
      s: '카페 와이파이 로그인 페이지나 회사 방화벽이 게임 연결을 막습니다.',
      c: ['로그인 페이지 인증 전이거나 방화벽이 게임 포트·UDP를 차단', '접속 시도 자체가 막히거나 일부만 통과', '접속 불가, 로그인은 되는데 게임 입장 실패'],
      sym: ['noconnect'], fx: ['loss'], who: ['me'], when: ['login'],
      own: ['ext', 'cli', 'srv'],
      act: { game: '클라이언트: 막혔을 때 이유를 알려 주는 안내(로그인 페이지 인증 전, UDP 차단 등), UDP가 막히면 대체 경로로 자동 전환. 서버: TCP 443 같은 대체 경로 제공.', ext: '유저에게 공용 와이파이는 로그인 페이지 인증을 먼저 하고, 회사망처럼 막힌 곳에서는 다른 네트워크를 쓰도록 안내.' },
      ref: [
        { t: 'RFC 8952: Captive Portal Architecture', u: 'https://www.rfc-editor.org/rfc/rfc8952', p: 'IETF', n: '캡티브 포털: 약관 동의·인증 같은 요구 조건을 채울 때까지 접속이 제한되는 네트워크' },
        { t: 'RFC 9308: Applicability of the QUIC Transport Protocol', u: 'https://www.rfc-editor.org/rfc/rfc9308', p: 'IETF', n: '측정 연구상 네트워크의 3~5%는 UDP를 모두 막으므로, UDP 기반 앱은 TCP(TLS) 대체 경로를 준비해야 함' },
      ] },
  ]);

  /* ---------------- 4. 인터넷 회선 ---------------- */
  add('isp', [
    { id: 'isp-distance', t: '전파 지연 (물리적 거리)', en: 'Propagation delay',
      s: '빛도 광케이블에서 1초에 약 20만 km밖에 못 갑니다. 먼 서버는 아무리 좋아도 늦습니다.',
      c: ['서버가 멀리 있음 (해외 서버, 다른 대륙)', '거리만큼 왕복 시간이 늘어남(1,000km당 최소 10ms)', '모든 행동에 일정한 입력 지연, 판정에서 불리'],
      sym: ['delay'], fx: ['lat'], who: ['region'], when: ['always'],
      num: '서울–도쿄 약 30ms, 서울–싱가포르 약 75ms, 서울–미국 서부 약 140ms, 서울–유럽 약 230~270ms (왕복, 실제 경로 기준). 유럽은 직선 위로 큰 케이블이 거의 없어 동남아·수에즈나 미국을 돌아가므로 거리보다 훨씬 깁니다.',
      own: ['sys', 'net', 'srv'],
      act: { game: '물리 법칙은 코드로 못 고치므로 완화만 가능, 가까운 지역 서버를 고르게 하는 지역 선택, 지연 보상(되감기)으로 판정 불리 줄이기.', infra: '서버 장비·OS: 이용자가 많은 지역에 지역별 서버 두기. 네트워크: 가까운 곳에 접속 거점(엣지) 두기, 우회가 적은 회선·경로 고르기.' },
      sim: 'distance',
      ref: [
        { t: 'ITU-T G.114: One-way transmission time', u: 'https://www.itu.int/rec/T-REC-G.114-200305-I/en', p: 'ITU', n: '광케이블 전송 지연 계획값 5µs/km(초속 약 20만 km, 1,000km 왕복 10ms)' },
        { t: 'Azure network round-trip latency statistics', u: 'https://learn.microsoft.com/en-us/azure/networking/azure-network-latency', p: 'Microsoft Azure', n: '서울(Korea Central) 기준 실측 왕복 중앙값: 도쿄 30ms, 싱가포르 68ms, 미국 서부 124~136ms, 유럽 234~244ms' },
        { t: 'AAE-1 & SMW5 cable cuts impact millions of users across multiple countries', u: 'https://blog.cloudflare.com/aae-1-smw5-cable-cuts/', p: 'Cloudflare', n: '유럽–아시아 사이 트래픽은 대개 이집트(수에즈)를 지나는 해저 케이블로 감' },
      ] },
    { id: 'isp-routing', t: '우회 라우팅', en: 'Suboptimal routing',
      s: '통신사끼리의 연결 계약 때문에 가까운 서버도 먼 곳을 돌아서 갑니다.',
      c: ['내 통신사와 서버 쪽 통신사가 직접 연결되어 있지 않음', '다른 나라나 다른 도시를 경유해 거리와 장비가 늘어남', '특정 통신사 사용자만 핑이 유독 높음'],
      sym: ['delay'], fx: ['lat'], who: ['region'], when: ['always'],
      num: '같은 나라 안인데도 경로에 따라 핑이 두세 배 차이 나기도 합니다.',
      own: ['net', 'ext'],
      act: { infra: '여러 통신사와 연결(멀티홈), 통신사별 핑을 모니터링해 우회하는 통신사 찾기, 통신사와 경로 조정 협의.', ext: '해당 통신사에 경로 조정 요청.' },
      sim: 'distance',
      ref: [
        { t: 'Quantifying the Causes of Path Inflation (SIGCOMM 2003)', u: 'https://conferences.sigcomm.org/sigcomm/2003/papers/p113-spring.pdf', p: 'ACM', n: '65개 ISP 분석: ISP 사이 피어링 정책과 도메인 간 라우팅이 경로를 크게 늘림' },
        { t: 'The Internet at the Speed of Light (HotNets 2014)', u: 'https://conferences.sigcomm.org/hotnets/2014/papers/hotnets-XIII-final111.pdf', p: 'ACM', n: '실제 라우터 경로는 광케이블 직선 대비 중앙값 약 1.5배, 가까운 두 지점 사이 패킷이 지구 반대편을 돌아가는 사례(헤어피닝)도 있음' },
      ] },
    { id: 'isp-peak', t: '피크 시간 피어링 구간 혼잡', en: 'Peak-hour congestion at peering',
      s: '저녁 9~11시 무렵에는 영상 트래픽이 폭증해 통신사 간 연결 구간(피어링)이 붐비기 쉽습니다.',
      c: ['저녁 시간 스트리밍·다운로드가 몰림', '피어링 구간에 대기열과 손실 발생', '저녁에만 특정 통신사 사용자가 뚝뚝 끊김·순간이동'],
      sym: ['stutter', 'teleport', 'rubber'], fx: ['jit', 'loss', 'lat'], who: ['region'], when: ['peak'],
      own: ['net', 'ext'],
      act: { infra: '해당 통신사와 직접 연결 늘리기, 혼잡 경로 우회, 통신사별 저녁 시간 손실·핑 모니터링.', ext: '해당 통신사에 피어링 구간 증설 요청.' },
      sim: 'distance',
      ref: [
        { t: 'Inferring Persistent Interdomain Congestion (SIGCOMM 2018)', u: 'https://www.caida.org/catalog/papers/2018_inferring_persistent_interdomain_congestion/inferring_persistent_interdomain_congestion.pdf', p: 'ACM', n: '통신사 간 연결 구간 일부에서 매일 피크 시간마다 지연이 오르는 반복 혼잡, 혼잡 시간대에 손실률도 상승' },
      ] },
    { id: 'isp-cable', t: '해저 케이블·국제 회선 장애', en: 'Submarine cable fault',
      s: '해저 케이블이 끊기면 수리될 때까지 몇 주(길면 몇 달) 동안 먼 우회 경로로 돌아가고, 남은 회선은 붐빕니다.',
      c: ['케이블 절단·장비 고장', '트래픽이 먼 우회 경로와 남은 회선으로 몰림', '해외 접속자 핑 급등과 손실이 며칠~몇 주 지속'],
      sym: ['delay', 'teleport'], fx: ['lat', 'loss'], who: ['region'], when: ['always'],
      own: ['ext', 'net'],
      act: { infra: '다른 경로의 회선 확보, 장애 때 트래픽을 그 경로로 옮기기.', ext: '해외 접속자에게 원인과 복구 예상 시점 공지, 회선 사업자에 복구 일정 확인 요청.' },
      sim: 'distance',
      ref: [
        { t: 'AAE-1 & SMW5 cable cuts impact millions of users across multiple countries', u: 'https://blog.cloudflare.com/aae-1-smw5-cable-cuts/', p: 'Cloudflare', n: '해저 케이블 수리는 수리선을 보내야 해 보통 며칠~몇 주(통가 사례 38일), 절단 때 유럽–아시아 구간 지연·손실 증가' },
        { t: 'Q2 2024 Internet disruption summary', u: 'https://blog.cloudflare.com/q2-2024-internet-disruption-summary/', p: 'Cloudflare', n: '2024년 2월 손상된 홍해 케이블은 7월에도 수리 중(분쟁 지역), 5월의 EASSy·Seacom 절단은 19일 만에 복구' },
        { t: 'Q1 2024 Internet disruption summary', u: 'https://blog.cloudflare.com/q1-2024-internet-disruption-summary/', p: 'Cloudflare', n: '서아프리카 케이블 절단(3월 14일)은 3~6주 뒤 복구, 그동안 다른 케이블로 트래픽을 옮김' },
      ] },
    { id: 'isp-bgp', t: 'BGP 경로 변경·수렴', en: 'Route change / BGP convergence',
      s: '인터넷의 경로 정보가 바뀌어 다시 수렴하는 몇 초~몇십 초(드물게 몇 분) 동안 패킷이 유실됩니다.',
      c: ['어느 통신사 구간의 경로 정보가 바뀜', '몇 초~몇십 초 동안 패킷이 사라지거나 새 경로로 전환', '갑자기 몇 초 멈춘 뒤 핑 수치가 달라짐(예: 40 → 70ms)'],
      sym: ['freeze', 'teleport'], fx: ['loss', 'lat'], who: ['region'], when: ['random'],
      own: ['net', 'srv', 'ext'],
      act: { game: '짧은 끊김을 견디는 타임아웃(몇 초 멈춘 연결을 바로 끊지 않기).', infra: '경로 모니터링(우리 IP 대역의 경로·핑 변화 감시), 우리 회선 장애는 BFD로 1초 안에 감지해 전환(BGP 기본 홀드 타임은 90~180초), 먼 경로로 바뀐 채 돌아오지 않으면 다른 회선으로 트래픽 옮기기.', ext: '경로가 자주 바뀌는 통신사 구간은 해당 통신사에 원인 확인 요청.' },
      ref: [
        { t: 'RFC 4271: A Border Gateway Protocol 4 (BGP-4)', u: 'https://www.rfc-editor.org/rfc/rfc4271', p: 'IETF', n: 'BGP 홀드 타임 권장 기본값 90초(이 시간 동안 상대 메시지가 없으면 세션을 끊음)' },
        { t: 'BGP updates in 2024', u: 'https://blog.apnic.net/2025/01/07/bgp-updates-in-2024/', p: 'APNIC', n: '불안정해진 경로가 다시 안정되기까지 하루 평균 25~35초(IPv4), 40~50초(IPv6)' },
        { t: 'Delayed Internet Routing Convergence (SIGCOMM 2000)', u: 'https://conferences.sigcomm.org/sigcomm/2000/conf/paper/sigcomm2000-5-2.pdf', p: 'ACM', n: '경로 장애 뒤 수렴에 수 분까지 걸리고 그동안 손실·지연이 늘어남(2000년 당시 측정)' },
      ] },
    { id: 'isp-ecmp', t: 'ECMP 경로 하나의 불량', en: 'ECMP / link bundle member fault',
      s: '통신사와 데이터센터는 같은 목적지로 가는 경로를 여러 개 두고, 연결마다 경로 하나를 정해 보냅니다. 경로 하나만 고장 나면 그 경로에 배정된 사람만 계속 렉을 겪습니다.',
      c: ['여러 회선을 묶은 구간에서 한 회선이나 장비 하나가 불량이거나 붐빔', '주소·포트 조합(해시)으로 경로가 정해져, 그 경로에 배정된 연결만 손실·지연', '같은 지역·같은 통신사인데 일부만 꾸준히 순간이동. 재접속하면 멀쩡해지기도 함'],
      sym: ['teleport', 'rubber', 'stutter'], fx: ['loss', 'jit'], who: ['me', 'region'], when: ['always'],
      num: '경로가 4개면 사용자의 약 4분의 1만 겪습니다. 핑 측정은 게임과 다른 경로로 가서 멀쩡하게 나오기도 합니다.',
      own: ['net', 'srv', 'ext'],
      act: { game: '연결별 손실·재전송 통계를 남겨 겪는 사람의 IP·포트와 시각을 뽑을 수 있게 하기(TCP는 TCP_INFO의 재전송 수, UDP는 빠진 패킷 순번으로 계산).', infra: '겪는 사람의 IP·포트와 시각을 모아 통신사·데이터센터에 전달, 경로별 손실 모니터링, 경로 측정은 게임과 같은 프로토콜·포트로(mtr --tcp·--udp와 --port), 우리 장비의 경로면 불량 회선·장비를 묶음에서 빼기.', ext: '통신사에 불량 경로 확인·교체 요청, 유저에게 재접속으로 임시로 피하도록 안내(재접속으로 포트가 바뀌는 경우).' },
      more: '한 연결의 패킷 순서가 뒤섞이지 않게, 장비는 주소와 포트(장비 설정에 따라 주소만)로 계산한 값에 따라 연결마다 경로를 고정합니다(ECMP, LAG). 주소만 쓰는 곳에서는 재접속해도 같은 경로라 나아지지 않습니다. 그래서 “핑은 멀쩡한데 게임만 렉”, “재접속하니 나아짐” 같은 제보가 함께 들어오면 이 원인을 의심합니다.',
      ref: [
        { t: 'RFC 7424: Mechanisms for Optimizing Link Aggregation Group (LAG) and Equal-Cost Multipath (ECMP) Component Link Utilization in Networks', u: 'https://www.rfc-editor.org/rfc/rfc7424', p: 'IETF', n: 'LAG·ECMP는 헤더 필드의 해시로 흐름마다 링크 하나를 정해 패킷 순서를 지킴(흐름→링크 다대일 대응)' },
        { t: 'RFC 2991: Multipath Issues in Unicast and Multicast Next-Hop Selection', u: 'https://www.rfc-editor.org/rfc/rfc2991', p: 'IETF', n: '흐름 구분 기준은 구현마다 다름(목적지 주소만, 주소 쌍, 포트까지), 다중 경로에서는 ping·traceroute 결과를 믿기 어려움' },
      ] },
    { id: 'isp-shaping', t: '통신사 속도 제한·트래픽 관리', en: 'Traffic shaping, data caps',
      s: '데이터 사용량을 넘기거나 특정 트래픽을 관리하는 요금제에서는 패킷이 늦춰지거나 버려집니다.',
      c: ['요금제 데이터 소진 후 속도 제한, 또는 특정 트래픽 제한', '패킷이 대기하거나 버려짐', '일정 사용량 이후 렉, 특히 모바일'],
      sym: ['delay', 'teleport'], fx: ['lat', 'loss'], who: ['me', 'region'], when: ['always', 'peak'],
      num: '국내 모바일 요금제는 데이터를 다 쓰면 보통 1~5Mbps, 싼 요금제는 수백 kbps로 제한됩니다. 게임은 가벼워도 같은 폰의 다른 앱이 쓰면 속도 제한 장비 앞에 대기열이 생깁니다.',
      own: ['ext', 'srv', 'net'],
      act: { game: '게임 트래픽 줄이기(압축, 필요한 것만 전송).', infra: '특정 통신사에서만 게임 트래픽이 늦춰지거나 버려지면 자료를 모아 통신사에 에스컬레이션.', ext: '유저에게 요금제 데이터 소진·속도 제한 여부와 같은 폰의 다른 앱 사용 확인 안내, 통신사에 게임 트래픽 제한 여부 확인 요청.' },
      ref: [
        { t: 'SKT, 고객 선택권과 혜택 강화한 신규 5G 요금제 출시', u: 'https://news.sktelecom.com/180213', p: 'SK텔레콤', n: '5G 요금제의 기본 데이터 소진 뒤 속도 제어 예: 최대 400kbps, 1Mbps, 3Mbps' },
        { t: 'SKT, 요금제 개편', u: 'https://news.sktelecom.com/225487', p: 'SK텔레콤', n: '기본 제공 데이터를 다 쓴 뒤에도 최대 400kbps로 계속 이용(전 국민 안심 데이터)' },
      ] },
    { id: 'isp-line', t: '회선 품질 불량', en: 'Faulty last-mile line / modem',
      s: '단자 접촉 불량이나 낡은 선, 모뎀 이상은 꾸준한 손실과 주기적인 회선 끊김을 만듭니다.',
      c: ['케이블 손상, 접촉 불량, 모뎀·광단말 이상', '비트 오류로 패킷 폐기, 가끔 회선이 다시 연결되느라 수 초~1분쯤 단절되기도 함', '꾸준한 소량 손실, 가끔 수 초 멈춤이나 접속 끊김'],
      sym: ['teleport', 'freeze', 'disconnect'], fx: ['loss'], who: ['home'], when: ['random'],
      own: ['ext'],
      act: { ext: '유저에게 다른 게임·영상 통화도 끊기는지 확인하고, 그렇다면 통신사에 점검을 요청하도록 안내.' },
      ref: [
        { t: 'RFC 3635: Definitions of Managed Objects for the Ethernet-like Interface Types', u: 'https://www.rfc-editor.org/rfc/rfc3635', p: 'IETF', n: '프레임 검사(FCS)를 통과하지 못한 프레임은 FCS 오류(dot3StatsFCSErrors)로 세고 입력 오류(ifInErrors)에 합산' },
        { t: 'Understanding and Mitigating Packet Corruption in Data Center Networks (SIGCOMM 2017)', u: 'https://www.microsoft.com/en-us/research/wp-content/uploads/2017/06/CorrOpt_SIGCOMM2017.pdf', p: 'ACM', n: '패킷 깨짐의 주원인은 불량 광모듈·손상된 광섬유·더러운 커넥터·잘못된 설치, 깨짐 손실률은 사용량과 무관하게 꾸준함' },
      ] },
    { id: 'isp-dns', t: 'DNS 장애·지연', en: 'DNS failure / slowness',
      s: '서버 이름을 주소로 바꿔 주는 DNS가 느리거나 실패하면 로그인·패치 서버를 찾지 못합니다.',
      c: ['통신사 DNS 장애 또는 설정 오류', '로그인·패치 서버 주소를 못 찾음', '접속 버튼 뒤 한참 대기 또는 접속 불가. 이미 접속한 사람은 멀쩡'],
      sym: ['noconnect'], fx: ['lat', 'loss'], who: ['region', 'me'], when: ['login'],
      own: ['ext', 'cli'],
      act: { game: '주소 캐시(마지막으로 접속에 성공한 서버 주소 기억), 여러 DNS 준비(한 곳이 실패하면 다른 DNS로 다시 조회).', ext: '유저에게 DNS를 공용 DNS 등 다른 곳으로 바꿔 보도록 안내.' },
      ref: [
        { t: 'Cloudflare 1.1.1.1 Incident on July 14, 2025', u: 'https://blog.cloudflare.com/cloudflare-1-1-1-1-incident-on-july-14-2025/', p: 'Cloudflare', n: '공용 DNS 리졸버가 62분 동안 멈추자, 이름을 못 찾게 된 사용자에게는 사실상 모든 인터넷 서비스가 불가' },
        { t: 'RFC 8767: Serving Stale Data to Improve DNS Resiliency', u: 'https://www.rfc-editor.org/rfc/rfc8767', p: 'IETF', n: '권한 서버에 닿지 못할 때 만료된 캐시 기록을 계속 써서 장애를 버티는 방식(serve-stale)' },
      ] },
    { id: 'isp-ddos-path', t: 'DDoS로 인한 공유 회선 포화', en: 'DDoS saturating shared links',
      s: '게임사나 같은 망의 다른 곳을 향한 대량 공격이 공유 회선을 가득 채웁니다.',
      c: ['대량의 공격 트래픽이 발생', '같은 회선을 쓰는 정상 트래픽까지 밀리고 버려짐', '많은 사람이 동시에 순간이동·접속 끊김·접속 불가'],
      sym: ['teleport', 'disconnect', 'noconnect'], fx: ['loss', 'lat'], who: ['server', 'region'], when: ['random', 'event'],
      own: ['net', 'ext'],
      act: { infra: 'DDoS 방어 서비스, 공격 때 트래픽 우회, 서버 주소 숨기기(방어 장비 뒤에 두고 실제 주소 노출 막기).', ext: '같은 망의 다른 곳을 향한 공격이면 통신사에 상위 구간 차단 요청.' },
      ref: [
        { t: 'Infrastructure layer attacks', u: 'https://docs.aws.amazon.com/whitepapers/latest/aws-best-practices-ddos-resiliency/infrastructure-layer-attacks.html', p: 'AWS', n: 'UDP 반사·SYN 플러드 같은 대량 공격은 네트워크 용량을 넘치게 하거나 방화벽·로드밸런서 자원을 묶어 둠' },
        { t: 'Obfuscating AWS resources (BP1, BP4, BP5)', u: 'https://docs.aws.amazon.com/whitepapers/latest/aws-best-practices-ddos-resiliency/obfuscating-aws-resources-bp1-bp4-bp5.html', p: 'AWS', n: '원본 서버 앞에 CloudFront·로드밸런서 같은 엣지 서비스를 두어 직접 노출을 줄이기' },
        { t: 'RFC 7999: BLACKHOLE Community', u: 'https://www.rfc-editor.org/rfc/rfc7999', p: 'IETF', n: '특정 주소로 가는 트래픽을 인접 통신사가 버려 달라고 BGP로 알리는 BLACKHOLE 커뮤니티' },
      ] },
    { id: 'isp-cgnat', t: '통신사 공유 IP (CGNAT)', en: 'Carrier-grade NAT',
      s: '모바일망과 일부 통신사는 여러 가입자가 IP 하나를 나눠 쓰며, 유휴 연결의 매핑을 짧은 시간 안에 지웁니다.',
      c: ['통신사 장비가 수많은 가입자의 세션 테이블을 관리', '세션 테이블 한도, 짧은 유휴 타임아웃', '가만히 있다 접속 끊김, 같은 IP를 쓰는 사람들이 한꺼번에 차단되는 오탐'],
      sym: ['disconnect', 'noconnect'], fx: ['loss'], who: ['region'], when: ['idle'],
      num: '모바일망 UDP 유휴 타임아웃은 30초 안팎인 경우도 있습니다.',
      own: ['cli', 'srv', 'net'],
      act: { game: '클라이언트: 가장 짧은 유휴 타임아웃(모바일망은 30초 안팎인 경우도 있음)의 절반 이하 간격으로 하트비트 보내기(통신사 CGNAT 매핑은 안에서 나가는 패킷으로만 확실히 갱신되므로 클라이언트가 보냄), 끊기면 자동 재접속. 서버: 하트비트에 응답하고, 일정 시간 못 받으면 연결을 먼저 정리, 매핑이 바뀌어 주소·포트가 달라져도 세션 토큰으로 같은 플레이어로 이어 받기, IP 하나를 여러 사람이 나눠 쓸 수 있으니 IP 기준 차단 정책은 신중히(계정·기기 기준과 함께 판단).', infra: '방화벽·DDoS 방어 장비의 IP당 연결 수·초당 새 연결 수 제한을 통신사 공유 IP에 맞게 조정(모바일 통신사 대역은 기준을 높이거나 예외로).' },
      sim: 'timeouts',
      ref: [
        { t: 'A Multi-perspective Analysis of Carrier-Grade NAT Deployment (IMC 2016)', u: 'https://www.icir.org/vern/papers/cgn-imc16.pdf', p: 'ACM', n: '측정된 NAT의 UDP 매핑 유지 시간 10~200초, 74%가 1분 이하, CGN 중앙값은 모바일망 65초·유선망 35초' },
        { t: 'RFC 6888: Common Requirements for Carrier-Grade NATs (CGNs)', u: 'https://www.rfc-editor.org/rfc/rfc6888', p: 'IETF', n: 'CGN은 가입자당 외부 포트 수 제한과 새 매핑 생성 속도 제한을 지원해야 함' },
        { t: 'RFC 6269: Issues with IP Address Sharing', u: 'https://www.rfc-editor.org/rfc/rfc6269', p: 'IETF', n: '주소를 여럿이 나눠 쓰면 IP 기준 차단(penalty box)이 같은 주소의 다른 가입자까지 막음' },
      ] },
    { id: 'isp-vpn', t: 'VPN·게임 가속기 경유', en: 'VPN / game accelerator detour',
      s: 'VPN이나 게임 가속기를 켜면 패킷이 그 회사의 중계 서버를 거쳐 갑니다. 중계 서버가 멀거나 붐비면 오히려 느려집니다.',
      c: ['VPN·가속기가 게임 패킷을 모두 중계 서버로 돌려 보냄', '중계 서버까지의 거리와 혼잡이 더해지고, 터널 헤더 때문에 MTU(한 번에 보낼 수 있는 패킷 크기)도 줄어듦', '핑 상승과 손실, 같은 중계 주소를 쓰는 사람과 함께 차단되어 접속 불가'],
      sym: ['delay', 'teleport', 'noconnect'], fx: ['lat', 'loss'], who: ['me'], when: ['always', 'login'],
      num: '가까운 중계 서버면 수 ms, 다른 나라를 돌아가면 수십~100ms 넘게 더해집니다.',
      own: ['ext', 'net', 'srv'],
      act: { game: 'UDP 패킷은 1,200바이트 이하로 유지(터널 헤더로 MTU가 줄어도 단편화되지 않게), IP 기준 차단은 VPN·가속기의 공용 중계 주소를 고려해 계정·기기 기준과 함께 판단.', infra: '해외 이용자가 많으면 가까운 접속 거점을 직접 두기, “가속기를 켜니 좋아졌다”는 제보가 몰리는 통신사는 경로 점검.', ext: '유저에게 VPN·가속기를 끄고 비교해 보도록 안내.' },
      more: '반대로 통신사 경로가 나쁠 때는 가속기가 더 좋은 경로로 돌아가 핑이 줄기도 합니다. “가속기를 켜니 좋아졌다”는 제보는 우회 라우팅이나 저녁 혼잡 같은 통신사 경로 문제의 단서입니다.',
      ref: [
        { t: 'RFC 4459: MTU and Fragmentation Issues with In-the-Network Tunneling', u: 'https://www.rfc-editor.org/rfc/rfc4459', p: 'IETF', n: '망 중간 터널의 캡슐화 헤더 때문에 보낼 수 있는 크기가 줄어 생기는 단편화·경로 MTU 문제' },
        { t: 'RFC 8899: Packetization Layer Path MTU Discovery for Datagram Transports', u: 'https://www.rfc-editor.org/rfc/rfc8899', p: 'IETF', n: 'UDP 같은 데이터그램 전송의 기본 안전 크기(BASE_PLPMTU)로 1,200바이트 권장' },
        { t: 'Azure network round-trip latency statistics', u: 'https://learn.microsoft.com/en-us/azure/networking/azure-network-latency', p: 'Microsoft Azure', n: '다른 나라 거점을 거칠 때 더해지는 왕복 지연 규모: 서울–도쿄 30ms, 서울–홍콩 39ms, 서울–싱가포르 68ms' },
      ] },
  ]);
})();
