/* 용어 사전: [용어, 영어, 설명, 관련 장 id(선택)] */
DATA.glossary = [
  ['핑', 'Ping, RTT', '내가 보낸 신호가 서버에 갔다가 돌아오기까지 걸린 시간(왕복). 게임에 표시되는 핑에는 서버 처리 대기 시간이 섞여 있기도 합니다.', 'basics'],
  ['지연', 'Latency', '소식이 출발해서 도착하기까지 걸리는 시간. 한쪽 방향만 말할 때가 많아 핑의 절반쯤입니다.', 'basics'],
  ['지터', 'Jitter', '도착 간격의 흔들림. 평균 핑이 같아도 지터가 크면 화면이 뚝뚝 끊깁니다.', 'basics'],
  ['패킷', 'Packet', '네트워크로 보내는 편지 한 통. 보통 최대 1,500바이트이고, 게임 업데이트는 수십~수백 바이트입니다.', 'basics'],
  ['패킷 손실', 'Packet loss', '보낸 패킷이 도착하지 못하고 사라지는 것. 1%만 돼도 체감됩니다.', 'basics'],
  ['대역폭', 'Bandwidth', '회선이 1초에 보낼 수 있는 최대 양(Mbps). 도로의 차선 수에 해당하며, 속도(지연)와는 다른 개념입니다.', 'l-home'],
  ['틱', 'Tick', '서버가 게임 세계를 한 번 계산하는 단위. 20틱 서버는 1초에 20번, 50ms마다 계산합니다.', 'l-server-proc'],
  ['틱레이트', 'Tick rate', '1초에 틱을 몇 번 도는지. 높을수록 반응이 빠르지만 서버 비용과 전송량이 늘어납니다.', 'l-server-proc'],
  ['틱 예산', 'Tick budget', '한 틱을 끝내야 하는 시간 한도. 넘기면 서버 박자가 느려집니다.', 'l-server-proc'],
  ['FPS', 'Frames per second', '1초에 화면을 몇 번 그리는지. 60FPS면 한 프레임에 16.7ms.', 'l-client-game'],
  ['프레임 타임', 'Frame time', '한 프레임을 그리는 데 걸린 시간. 평균 FPS보다 가끔 튀는 프레임이 체감에 더 중요합니다.', 'l-client-game'],
  ['스냅샷', 'Snapshot', '서버가 틱마다 보내는 “지금 세계 상태” 요약. 위치, 체력, 상태 등이 담깁니다.', 'lab'],
  ['보간', 'Interpolation', '받은 두 스냅샷 사이를 이어 그려 매끄럽게 보이게 하는 기술. 대신 조금 과거를 보여 줍니다.', 'lab'],
  ['보간 버퍼', 'Interpolation buffer', '보간을 위해 일부러 늦게 그리는 시간. 지터를 흡수하는 쿠션입니다.', 'lab'],
  ['외삽', 'Extrapolation, Dead reckoning', '새 소식이 없을 때 마지막 속도로 앞으로 어디 있을지 추측해 그리는 기술. 틀리면 순간이동처럼 보입니다.', 'lab'],
  ['클라이언트 예측', 'Client-side prediction', '서버 확인을 기다리지 않고 내 캐릭터를 먼저 움직여 보여 주는 기술.', 'lab'],
  ['서버 보정', 'Reconciliation', '서버 결과가 오면 예측과 비교해 내 캐릭터 위치를 바로잡는 것. 차이가 크면 고무줄처럼 보입니다.', 'lab'],
  ['지연 보상', 'Lag compensation', '서버가 공격 판정을 할 때 공격자가 보던 과거 시점으로 되감아 맞았는지 확인하는 기술.', 'l-client-game'],
  ['권위 서버', 'Authoritative server', '최종 판정은 서버만 한다는 설계. 치팅을 막지만 모든 결과가 서버 왕복을 거칩니다.', 'l-server-proc'],
  ['TCP', 'Transmission Control Protocol', '순서대로, 빠짐없이 전달하는 프로토콜. 잃어버린 패킷을 다시 받을 때까지 뒤 패킷을 붙잡습니다.', 'l-socket'],
  ['UDP', 'User Datagram Protocol', '아무 보장 없이 보내는 대로 전달하는 프로토콜. 기다림이 없는 대신 손실·순서는 게임이 직접 처리합니다.', 'l-socket'],
  ['신뢰성 UDP', 'Reliable UDP (KCP, ENet…)', 'UDP 위에 필요한 만큼만 재전송·순서 보장을 직접 얹은 방식.', 'l-socket'],
  ['머리막힘', 'Head-of-line blocking', '앞의 하나가 막혀 뒤의 모두가 기다리는 현상. TCP 몰아치기의 원인입니다.', 'l-socket'],
  ['재전송 대기', 'RTO, Retransmission timeout', 'TCP가 패킷을 잃었다고 판단하고 다시 보내기까지 기다리는 시간. 리눅스는 핑 + 200ms 이상, 실패할수록 두 배.', 'l-socket'],
  ['Nagle 알고리즘', 'Nagle’s algorithm', '앞서 보낸 데이터의 확인(ACK)이 올 때까지 작은 조각을 모아 두었다가 한 번에 보내, 패킷 수를 아끼는 TCP 기능. 게임에서는 대개 꺼야 합니다.', 'l-socket'],
  ['TCP_NODELAY', 'TCP_NODELAY', 'Nagle 알고리즘을 끄는 소켓 옵션. 작은 메시지를 즉시 보냅니다.', 'l-socket'],
  ['지연 ACK', 'Delayed ACK', '받았다는 확인을 조금 늦게, 다른 데이터와 묶어 보내는 기능. 리눅스는 보통 40ms(최대 200ms), 윈도우는 200ms.', 'l-socket'],
  ['소켓 버퍼', 'SO_SNDBUF / SO_RCVBUF', 'OS가 소켓마다 두는 송신·수신 대기 공간의 크기. 너무 작으면 넘치고, 너무 크면 오래된 데이터가 줄을 섭니다.', 'l-socket'],
  ['keepalive', 'SO_KEEPALIVE', '조용한 연결이 살아 있는지 확인하는 TCP 기능. 기본으로 꺼져 있고, 켜도 기본값은 2시간 뒤에야 확인합니다.', 'l-socket'],
  ['하트비트', 'Heartbeat', '게임이 직접 주기적으로 보내는 “살아 있음” 신호. 끊김 감지와 중간 장비의 연결 유지에 씁니다.', 'l-dc-net'],
  ['타임아웃', 'Timeout', '이 시간 동안 응답이 없으면 실패로 보는 기준. 너무 짧으면 오판, 너무 길면 늦은 감지.', 'l-dc-net'],
  ['NAT', 'Network Address Translation', '공유기가 집 안 여러 기기를 공인 IP 하나로 내보내며 연결을 표로 기억하는 기능.', 'l-home'],
  ['CGNAT', 'Carrier-grade NAT', '통신사가 여러 가입자에게 IP 하나를 나눠 주는 대규모 NAT.', 'l-isp'],
  ['MTU', 'Maximum Transmission Unit', '한 번에 보낼 수 있는 패킷 최대 크기. 보통 1,500바이트이고, VPN·PPPoE 구간에서는 더 작습니다.', 'l-dc-net'],
  ['버퍼블로트', 'Bufferbloat', '장비가 대기열을 너무 크게 쌓아 두어 지연이 수백 ms로 늘어나는 현상.', 'l-home'],
  ['SQM', 'Smart Queue Management (fq_codel, CAKE)', '대기열을 짧게 유지하고 흐름별로 공정하게 내보내는 공유기 기능. 버퍼블로트 해결책.', 'l-home'],
  ['QoS', 'Quality of Service', '중요한 트래픽을 먼저 보내도록 우선순위를 주는 기능.', 'l-home'],
  ['피어링', 'Peering', '통신사끼리 서로의 망을 연결하는 지점. 저녁에 붐비기 쉽습니다.', 'l-isp'],
  ['BGP', 'Border Gateway Protocol', '인터넷에서 어느 길로 갈지 통신사끼리 알려 주는 규칙. 바뀌면 경로와 핑이 달라집니다.', 'l-isp'],
  ['DDoS', 'Distributed Denial of Service', '많은 곳에서 대량의 트래픽을 보내 서비스를 마비시키는 공격.', 'l-dc-net'],
  ['방화벽', 'Firewall', '허락된 연결만 통과시키는 장비나 프로그램. 연결을 표로 기억합니다.', 'l-dc-net'],
  ['로드밸런서', 'Load balancer', '들어오는 연결을 여러 서버에 나눠 주는 장비.', 'l-dc-net'],
  ['세션 테이블', 'Session table, conntrack', '장비나 OS가 현재 연결들을 기억해 두는 표. 크기에 한도가 있습니다.', 'l-dc-net'],
  ['마이크로버스트', 'Microburst', '평균은 낮지만 1ms 이하의 아주 짧은 순간에 트래픽이 몰리는 현상.', 'l-dc-net'],
  ['NIC', 'Network Interface Card', '서버의 네트워크 카드.', 'l-nic'],
  ['링 버퍼', 'Ring buffer', 'NIC가 받은 패킷을 CPU가 꺼내 갈 때까지 담아 두는 원형 칸.', 'l-nic'],
  ['인터럽트', 'Interrupt', '장치가 CPU에게 “일이 생겼다”고 알리는 신호.', 'l-nic'],
  ['RSS', 'Receive Side Scaling', '받은 패킷을 여러 줄로 나눠 여러 CPU 코어가 처리하게 하는 NIC 기능.', 'l-nic'],
  ['PPS', 'Packets per second', '초당 패킷 수. 게임 서버는 대역폭보다 이 숫자에서 먼저 한계에 닿곤 합니다.', 'l-nic'],
  ['커널', 'Kernel', '운영체제의 핵심. 네트워크, 메모리, CPU 배분을 담당합니다.', 'l-server-os'],
  ['backlog', 'Listen backlog', '서버가 아직 받아 가지 않은 새 접속 요청이 기다리는 줄.', 'l-server-os'],
  ['파일 디스크립터', 'File descriptor', '프로세스가 연 파일·연결마다 붙는 번호표. 개수에 한도가 있습니다.', 'l-server-os'],
  ['스레드', 'Thread', '프로그램 안에서 동시에 일하는 일꾼 하나.', 'l-server-proc'],
  ['문맥 전환', 'Context switch', 'CPU가 실행 중인 스레드를 다른 스레드로 바꿔 끼우는 일. 비용이 듭니다.', 'l-server-os'],
  ['락', 'Lock, Mutex', '공용 데이터를 한 번에 한 스레드만 쓰게 하는 열쇠.', 'l-server-proc'],
  ['데드락', 'Deadlock', '서로가 가진 열쇠를 기다리며 영원히 멈춘 상태.', 'l-server-proc'],
  ['스레드 풀', 'Thread pool', '미리 만들어 둔 일꾼 스레드 묶음. 모두 바쁘면 새 일은 기다립니다.', 'l-server-proc'],
  ['비동기 I/O', 'epoll, IOCP, io_uring', '입출력을 기다리지 않고 다른 일을 하다가 완료되면 알림을 받는 방식.', 'l-socket'],
  ['AOI', 'Area of Interest', '각 플레이어가 “볼 수 있는 범위”. 이 안의 변화만 보내 전송량을 줄입니다.', 'l-server-proc'],
  ['브로드캐스트', 'Broadcast, fan-out', '한 변화를 여러 명에게 보내는 것. 인원이 모일수록 제곱으로 늘어납니다.', 'l-server-proc'],
  ['GC', 'Garbage collection', '쓰고 버린 메모리를 자동으로 치우는 기능. 청소 중에 프로그램이 멈추기도 합니다.', 'l-memory'],
  ['힙', 'Heap', '프로그램이 실행 중에 필요할 때마다 빌려 쓰는 메모리 영역.', 'l-memory'],
  ['메모리 누수', 'Memory leak', '다 쓴 메모리를 돌려주지 않아 사용량이 계속 늘어나는 버그. GC가 있어도 다 쓴 객체를 어딘가에서 계속 붙잡고 있으면 생깁니다.', 'l-memory'],
  ['스왑', 'Swap, paging', '램이 모자라 메모리 일부를 디스크에 옮겨 두는 것. 수천 배 느려집니다.', 'l-memory'],
  ['OOM 킬러', 'Out-of-memory killer', '메모리가 바닥나면 리눅스가 메모리를 가장 많이 쓰는 프로세스를 골라 강제로 끝내는 기능.', 'l-server-os'],
  ['캐시 미스', 'Cache miss', 'CPU 가까운 캐시에 데이터가 없어 느린 메모리까지 가야 하는 일.', 'l-memory'],
  ['IOPS', 'I/O operations per second', '디스크가 1초에 처리할 수 있는 읽기·쓰기 횟수.', 'l-disk'],
  ['fsync', 'fsync', '데이터가 디스크에 확실히 기록될 때까지 기다리는 명령. 보통 쓰기는 OS 메모리에 먼저 담겼다가 나중에 디스크로 내려가서, 그 사이 서버가 꺼지면 사라집니다. fsync는 안전하지만 느립니다.', 'l-disk'],
  ['버스트 크레딧', 'Burst credits', '클라우드 디스크·서버가 잠깐 기준 이상 성능을 낼 수 있는 저금. 바닥나면 기준 성능으로 떨어집니다.', 'l-disk'],
  ['인덱스', 'Index', 'DB의 색인. 없으면 표 전체를 훑어야 합니다.', 'l-db'],
  ['풀 스캔', 'Full table scan', '인덱스 없이 표의 모든 행을 확인하는 조회.', 'l-db'],
  ['트랜잭션', 'Transaction', '“전부 되거나 전부 안 되거나” 하나로 묶인 DB 작업. 거래는 반드시 트랜잭션으로 처리합니다. 끝날 때까지 고친 행을 잠가 두므로 짧을수록 좋습니다.', 'l-db'],
  ['커넥션 풀', 'Connection pool', '미리 맺어 둔 DB 연결 묶음. 모두 쓰이면 새 요청은 기다립니다.', 'l-db'],
  ['핫 로우', 'Hot row', '많은 요청이 동시에 고치려는 한 행. 잠금 경합의 원인.', 'l-db'],
  ['복제 지연', 'Replication lag', '복제본 DB가 주 DB를 따라가지 못하고 뒤처진 시간.', 'l-db'],
  ['롤백', 'Rollback', '저장이 취소되어 이전 상태로 돌아가는 것. 플레이어는 “아이템이 사라졌다”고 느낍니다.', 'l-db'],
  ['캐시', 'Cache (Redis 등)', '자주 쓰는 데이터를 빠른 곳에 복사해 둔 것. DB 부하를 줄입니다.', 'l-infra'],
  ['캐시 쇄도', 'Cache stampede', '캐시가 한꺼번에 비어 요청이 원본(DB)으로 몰리는 현상.', 'l-db'],
  ['게이트웨이', 'Gateway', '클라이언트 연결을 받아 뒤쪽 게임 서버로 전달하는 중간 서버.', 'l-infra'],
  ['서킷 브레이커', 'Circuit breaker', '실패가 계속되는 서비스 호출을 잠시 끊어 연쇄 장애를 막는 장치.', 'l-infra'],
  ['연쇄 장애', 'Cascading failure', '한 곳의 장애가 호출 사슬을 따라 다른 서비스로 번지는 것.', 'l-infra'],
  ['오토스케일', 'Autoscaling', '부하에 따라 서버 수를 자동으로 늘리고 줄이는 기능. 늘어나는 데 시간이 걸립니다.', 'l-infra'],
  ['워치독', 'Watchdog', '서버가 멈췄는지 감시하다가 멈추면 강제로 재시작하는 감시 타이머.', 'l-server-proc'],
  ['이용률', 'Utilization', '창구가 바쁜 비율. 80~90%를 넘으면 대기가 급격히 늘어납니다.', 'basics'],
  ['p99', '99th percentile', '100번 중 99번은 이보다 빠르고 1번꼴로 이보다 느린 값. 평균보다 체감 렉을 더 잘 보여 줍니다.', 'l-db'],
  ['V-Sync', 'Vertical sync', '화면 갱신 주기에 맞춰 프레임을 내보내는 기능. 찢어짐은 없애지만 입력 지연이 생깁니다.', 'l-client-game'],
  ['셰이더 컴파일', 'Shader compilation', '그래픽 효과 프로그램을 GPU용으로 변환하는 작업. 처음 볼 때 끊김을 만듭니다.', 'l-client-game'],
  ['넷그래프', 'Net graph', '게임 화면에 핑·손실·FPS·틱을 실시간 그래프로 띄우는 개발·디버그 표시. 렉 제보 영상에 같이 찍히면 원인 찾기가 훨씬 쉬워집니다.', 'report'],
  ['핸드오버', 'Handover', '이동 중인 폰이 연결된 기지국을 바꾸는 것.', 'l-home'],
];
