/* 장별 출처: 기본 개념(basics), 렉 실험실(lab), 증상 사전(symptoms), 동기화 방식(sync), 일부에게만 생기는 문제(partial).
   본문·표, 시간 감각 표(DATA.times)·증상 정의(DATA.symptoms), 시뮬레이션 lab·queue·syncmodels·windows·chain·oneslow·npcmissing 의 근거. */
Object.assign(DATA.secRefs, {
  'basics': [
    { t: 'Teletraffic Engineering Handbook (ITU-D Study Group 2 Question 16/2)', u: 'https://www.itu.int/dms_pub/itu-d/opb/stg/D-STG-SG02.16.2.1-2002-PDF-E.pdf', p: 'ITU', n: 'M/M/1 평균 대기 W = A·s/(1−A): 이용률 50%·80%·90%에서 처리 시간의 1·4·9배. 같은 이용률이면 워커(서버)가 많을수록, 도착이 고를수록 대기가 짧음' },
    { t: 'CloudWatch metrics that are available for your instances', u: 'https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/viewing_metrics_with_cloudwatch.html', p: 'AWS', n: 'EC2 CPUUtilization은 인스턴스 전체 값이며 기본 5분, 상세 모니터링 1분 단위로 집계' },
    { t: 'Designs, Lessons and Advice from Building Large Distributed Systems (Jeff Dean, LADIS 2009 keynote)', u: 'https://www.cs.cornell.edu/projects/ladis2009/talks/dean-keynote-ladis2009.pdf', p: 'Google', n: '메인 메모리 참조 100ns, 같은 데이터센터 안 왕복 500,000ns(0.5ms)' },
    { t: 'ITU-T G.114: One-way transmission time', u: 'https://www.itu.int/rec/T-REC-G.114-200305-I/en', p: 'ITU', n: '광케이블 전파 지연 5µs/km(빛의 속도 한계 계산의 근거)' },
    { t: 'Latency Compensating Methods in Client/Server In-game Protocol Design and Optimization (Yahn W. Bernier, GDC 2001)', u: 'https://web.cs.wpi.edu/~claypool/courses/4513-B03/papers/games/bernier.pdf', p: 'Valve', n: 'Half-Life 기본값: 초당 20회 업데이트, 보간 100ms. 초당 10회라면 보간 200ms로 한 번의 누락을 견딤' },
    { t: 'IP Sysctl', u: 'https://docs.kernel.org/networking/ip-sysctl.html', p: 'Linux kernel', n: 'tcp_rto_min_us 기본값 200000(200ms)' },
    { t: 'Factors influencing the latency of simple reaction time (Frontiers in Human Neuroscience, 2015)', u: 'https://doi.org/10.3389/fnhum.2015.00131', p: 'Frontiers', n: '단순 반응 시간 평균 약 231ms(장비 지연 보정 시 213ms)' },
    { t: 'A Survey and Taxonomy of Latency Compensation Techniques for Network Computer Games (ACM Computing Surveys, 2022)', u: 'https://web.cs.wpi.edu/~claypool/papers/lag-taxonomy/paper.pdf', p: 'ACM', n: '100ms 미만의 지연도 게임 과제 성능에 영향, 드래그 같은 작업에서는 약 10ms도 알아챔' },
    { t: 'Peeking into VALORANT\'s Netcode', u: 'https://www.riotgames.com/en/news/peeking-valorants-netcode', p: 'Riot Games', n: '숙련 플레이어는 블라인드 테스트에서 약 10ms 차이도 알아챔' },
    { t: 'Latency and Player Actions in Online Games (Communications of the ACM, 2006)', u: 'https://web.cs.wpi.edu/~claypool/papers/precision-deadline/final.pdf', p: 'ACM', n: '장르별 지연 허용치: 1인칭 약 100ms, 3인칭(RPG·MMO) 약 500ms, RTS 약 1,000ms' },
    { t: 'JEP 333: ZGC: A Scalable Low-Latency Garbage Collector', u: 'https://openjdk.org/jeps/333', p: 'OpenJDK', n: 'G1은 128GB 힙에서 일시 정지 평균 157ms·최대 544ms, ZGC는 힙·살아 있는 데이터 크기와 무관하게 약 1~2ms' },
    { t: 'CommonNetworkParametersExtensions (Unity Transport 2.5)', u: 'https://docs.unity3d.com/Packages/com.unity.transport@2.5/api/Unity.Networking.Transport.CommonNetworkParametersExtensions.html', p: 'Unity', n: 'disconnectTimeoutMS: 이 시간 동안 아무것도 받지 못하면 연결을 끊음(기본 30,000ms)' },
  ],
  'lab': [
    { t: 'Latency Compensating Methods in Client/Server In-game Protocol Design and Optimization (Yahn W. Bernier, GDC 2001)', u: 'https://web.cs.wpi.edu/~claypool/courses/4513-B03/papers/games/bernier.pdf', p: 'Valve', n: '보간은 과거를 그리는 대신 매끄럽고 외삽은 방향 전환을 몰라 틀리면 튐. 예측 오차는 서버 결과로 보정' },
    { t: 'UDP vs. TCP', u: 'https://gafferongames.com/post/udp_vs_tcp/', p: 'Gaffer On Games', n: 'TCP는 패킷 하나를 잃으면 새 데이터가 도착해도 재전송될 때까지 넘겨주지 않음(보통 2×RTT 이상)' },
    { t: 'Deterministic Lockstep', u: 'https://gafferongames.com/post/deterministic_lockstep/', p: 'Gaffer On Games', n: '확인받지 못한 입력을 매 패킷에 중복해 보내면 재전송을 기다리지 않음(최악 2초 분량)' },
    { t: 'Snapshot Interpolation', u: 'https://gafferongames.com/post/snapshot_interpolation/', p: 'Gaffer On Games', n: '받은 즉시 그리면 지터로 끊기고 보간 버퍼는 지연을 조금 늘리는 대신 매끄럽게 함' },
    { t: 'Understanding Networked Movement in the Character Movement Component for Unreal Engine', u: 'https://dev.epicgames.com/documentation/en-us/unreal-engine/understanding-networked-movement-in-the-character-movement-component-for-unreal-engine', p: 'Epic Games', n: '클라이언트 이동이 연결 문제로 빠지거나 잘못되면 서버가 위치를 보정(고무줄)' },
    { t: 'Source SDK 2013: player.cpp', u: 'https://raw.githubusercontent.com/ValveSoftware/source-sdk-2013/master/src/game/server/player.cpp', p: 'Valve', n: '틱마다 쌓이는 명령 예산으로 몰려 온 명령을 제한. 너무 엄격하면 정상 유저도 뚝뚝 끊김' },
    { t: 'Introducing Time Dilation (TiDi)', u: 'https://www.eveonline.com/news/view/introducing-time-dilation-tidi', p: 'CCP Games', n: '서버 과부하 때 게임 시계를 늦춰(Time Dilation) 모든 것이 느리게 흐르게 하는 설계' },
    { t: 'CommonNetworkParametersExtensions (Unity Transport 2.5)', u: 'https://docs.unity3d.com/Packages/com.unity.transport@2.5/api/Unity.Networking.Transport.CommonNetworkParametersExtensions.html', p: 'Unity', n: '일정 시간 아무것도 받지 못하면 연결을 끊는 비활동 타임아웃' },
  ],
  'symptoms': [
    { t: 'Latency Compensating Methods in Client/Server In-game Protocol Design and Optimization (Yahn W. Bernier, GDC 2001)', u: 'https://web.cs.wpi.edu/~claypool/courses/4513-B03/papers/games/bernier.pdf', p: 'Valve', n: '업데이트가 빠지면 마지막 위치에 멈추거나(끊김) 외삽했다가 튐(순간이동). 외삽 시간은 제한해야 함' },
    { t: 'Understanding Networked Movement in the Character Movement Component for Unreal Engine', u: 'https://dev.epicgames.com/documentation/en-us/unreal-engine/understanding-networked-movement-in-the-character-movement-component-for-unreal-engine', p: 'Epic Games', n: '클라이언트 이동이 빠지거나 서버 계산과 다르면 서버가 보정을 보내 위치를 되돌림(고무줄)' },
    { t: 'UDP vs. TCP', u: 'https://gafferongames.com/post/udp_vs_tcp/', p: 'Gaffer On Games', n: 'TCP는 잃은 패킷을 재전송받을 때까지 뒤 데이터를 쌓아 두었다가 넘김(몰아치기)' },
    { t: 'Deterministic Lockstep', u: 'https://gafferongames.com/post/deterministic_lockstep/', p: 'Gaffer On Games', n: '밀린 입력이 한꺼번에 오면 여러 프레임을 몰아서 계산해 따라잡음' },
    { t: 'Introducing Time Dilation (TiDi)', u: 'https://www.eveonline.com/news/view/introducing-time-dilation-tidi', p: 'CCP Games', n: '서버가 과부하일 때 게임 시계를 늦추는 Time Dilation(TiDi), 과부하 때 작업이 몇 초씩 밀리는 현상' },
    { t: 'Peeking into VALORANT\'s Netcode', u: 'https://www.riotgames.com/en/news/peeking-valorants-netcode', p: 'Riot Games', n: '버퍼링 시간은 서버 틱레이트와 클라이언트 렌더 프레임에 따라 달라짐' },
    { t: 'Using Gameplay Abilities in Unreal Engine', u: 'https://dev.epicgames.com/documentation/en-us/unreal-engine/using-gameplay-abilities-in-unreal-engine', p: 'Epic Games', n: '예측 실행한 능력을 서버가 뒤집을 수 있음(씹힘·롤백)' },
    { t: 'Actor Relevancy in Unreal Engine', u: 'https://dev.epicgames.com/documentation/en-us/unreal-engine/actor-relevancy-in-unreal-engine', p: 'Epic Games', n: '서버가 관련 없다고 본 액터는 복제되지 않거나 클라이언트에서 지워짐(안 보임·유령 개체)' },
    { t: 'CommonNetworkParametersExtensions (Unity Transport 2.5)', u: 'https://docs.unity3d.com/Packages/com.unity.transport@2.5/api/Unity.Networking.Transport.CommonNetworkParametersExtensions.html', p: 'Unity', n: '비활동 타임아웃이 지나면 연결을 끊음(접속 끊김)' },
  ],
  'sync': [
    { t: 'Latency Compensating Methods in Client/Server In-game Protocol Design and Optimization (Yahn W. Bernier, GDC 2001)', u: 'https://web.cs.wpi.edu/~claypool/courses/4513-B03/papers/games/bernier.pdf', p: 'Valve', n: '권위 서버, 클라이언트 예측·보정, 보간, 지연 보상의 원리와 “코너 뒤에서 맞음” 같은 절충' },
    { t: 'What Every Programmer Needs To Know About Game Networking', u: 'https://gafferongames.com/post/what_every_programmer_needs_to_know_about_game_networking/', p: 'Gaffer On Games', n: 'P2P 락스텝에서 클라이언트/서버, 클라이언트 예측으로 이어진 넷코드의 발전' },
    { t: 'Using Gameplay Abilities in Unreal Engine', u: 'https://dev.epicgames.com/documentation/en-us/unreal-engine/using-gameplay-abilities-in-unreal-engine', p: 'Epic Games', n: 'Local Predicted와 Server Initiated의 반응성·정확성 절충' },
    { t: 'Peeking into VALORANT\'s Netcode', u: 'https://www.riotgames.com/en/news/peeking-valorants-netcode', p: 'Riot Games', n: '서버 권위·예측·버퍼링·되감기 판정과 되감기 한도' },
    { t: 'NetworkTime and ticks (Netcode for GameObjects 2.5)', u: 'https://docs.unity3d.com/Packages/com.unity.netcode.gameobjects@2.5/manual/advanced-topics/networktime-ticks.html', p: 'Unity', n: '서버 시각에 맞춰 이벤트를 예약해 재생하는 방법' },
    { t: '1500 Archers on a 28.8: Network Programming in Age of Empires and Beyond', u: 'https://www.gamedeveloper.com/programming/1500-archers-on-a-28-8-network-programming-in-age-of-empires-and-beyond', p: 'Game Developer', n: '락스텝: 명령을 두 턴 뒤로 예약, 가장 느린 컴퓨터에 맞춘 턴 길이, 일정한 500ms 지연은 괜찮지만 들쭉날쭉한 지연은 불편' },
    { t: 'Deterministic Lockstep', u: 'https://gafferongames.com/post/deterministic_lockstep/', p: 'Gaffer On Games', n: '락스텝은 모든 입력이 와야 진행, 재생 지연 버퍼로 지터를 흡수' },
    { t: 'GGPO Rollback Networking SDK', u: 'https://www.ggpo.net/', p: 'GGPO', n: '롤백: 상대 입력을 예측해 진행하고 틀리면 되감아 재계산' },
    { t: '8 Frames in 16ms: Rollback Networking in \'Mortal Kombat\' and \'Injustice 2\'', u: 'https://www.gdcvault.com/play/1025471/8-Frames-in-16ms-Rollback', p: 'GDC', n: '롤백은 락스텝의 로컬 입력 지연을 없앰, 최대 8프레임 재계산' },
    { t: 'Latency and Player Actions in Online Games (Communications of the ACM, 2006)', u: 'https://web.cs.wpi.edu/~claypool/papers/precision-deadline/final.pdf', p: 'ACM', n: '같은 지연도 행동의 정밀도·마감 시간과 시점(1인칭·3인칭·전지적)에 따라 영향이 다름' },
    { t: 'Networking Overview for Unreal Engine', u: 'https://dev.epicgames.com/documentation/en-us/unreal-engine/networking-overview-for-unreal-engine', p: 'Epic Games', n: '리슨 서버 호스트의 이점과 부하' },
    { t: 'Factors influencing the latency of simple reaction time (Frontiers in Human Neuroscience, 2015)', u: 'https://doi.org/10.3389/fnhum.2015.00131', p: 'Frontiers', n: '사람의 단순 반응 시간 약 0.23초' },
  ],
  'partial': [
    { t: 'Peeking into VALORANT\'s Netcode', u: 'https://www.riotgames.com/en/news/peeking-valorants-netcode', p: 'Riot Games', n: '한 사람이 어긋나면 그 사람에게만 보정하고 나머지 아홉 명은 매끄럽게 봄. 되감기 판정에는 한도를 둠' },
    { t: 'State Synchronization', u: 'https://gafferongames.com/post/state_synchronization/', p: 'Gaffer On Games', n: '패킷은 프레임마다 2개, 0개처럼 몰려 도착하고 지터 버퍼로 고르게 폄' },
    { t: 'Source SDK 2013: player.cpp', u: 'https://raw.githubusercontent.com/ValveSoftware/source-sdk-2013/master/src/game/server/player.cpp', p: 'Valve', n: '몰려 온 명령을 틱에 나눠 처리하는 명령 예산, 엄격한 제한의 부작용' },
    { t: 'Source SDK 2013: player_lagcompensation.cpp', u: 'https://raw.githubusercontent.com/ValveSoftware/source-sdk-2013/master/src/game/server/player_lagcompensation.cpp', p: 'Valve', n: 'Source 엔진 되감기 상한 sv_maxunlag 기본 1초' },
    { t: 'A Survey and Taxonomy of Latency Compensation Techniques for Network Computer Games (ACM Computing Surveys, 2022)', u: 'https://web.cs.wpi.edu/~claypool/papers/lag-taxonomy/paper.pdf', p: 'ACM', n: '지연 보상의 “코너 뒤에서 맞음”, 모두의 입력을 맞추는 입력 지연' },
    { t: 'send(2) — Linux manual page', u: 'https://man7.org/linux/man-pages/man2/send.2.html', p: 'Linux man-pages', n: '송신 버퍼가 차면 send()는 블로킹 모드에서 기다리고 논블로킹이면 EAGAIN으로 바로 돌아옴' },
    { t: 'Networking Overview for Unreal Engine', u: 'https://dev.epicgames.com/documentation/en-us/unreal-engine/networking-overview-for-unreal-engine', p: 'Epic Games', n: '리슨 서버 호스트는 다른 플레이어보다 유리' },
    { t: 'Authority (Netcode for GameObjects 2.5)', u: 'https://docs.unity3d.com/Packages/com.unity.netcode.gameobjects@2.5/manual/terms-concepts/authority.html', p: 'Unity', n: '분산 권한: 클라이언트마다 일부 개체를 맡아 계산' },
    { t: 'Actor Relevancy in Unreal Engine', u: 'https://dev.epicgames.com/documentation/en-us/unreal-engine/actor-relevancy-in-unreal-engine', p: 'Epic Games', n: '서버는 연결마다 관련 있는 액터만 보내고 관련 없어지면 클라이언트에서 지움' },
    { t: 'NetworkConfig class (Netcode for GameObjects 2.5)', u: 'https://docs.unity3d.com/Packages/com.unity.netcode.gameobjects@2.5/api/Unity.Netcode.NetworkConfig.html', p: 'Unity', n: '아직 생성되지 않은 개체의 메시지는 보류했다가 시간이 지나면 버림(SpawnTimeout)' },
    { t: 'RFC 8085: UDP Usage Guidelines', u: 'https://www.rfc-editor.org/rfc/rfc8085', p: 'IETF', n: '단편화된 UDP 패킷은 프래그먼트 하나만 잃어도 통째로 사라짐' },
    { t: 'Using SO_REUSEADDR and SO_EXCLUSIVEADDRUSE', u: 'https://learn.microsoft.com/en-us/windows/win32/winsock/using-so-reuseaddr-and-so-exclusiveaddruse', p: 'Microsoft', n: '같은 포트를 두 소켓이 공유하면 어느 쪽이 패킷을 받을지 알 수 없음' },
    { t: 'RFC 6269: Issues with IP Address Sharing', u: 'https://www.rfc-editor.org/rfc/rfc6269', p: 'IETF', n: 'IP 주소를 여러 가입자가 공유하면 IP만으로 사용자를 구분할 수 없음' },
    { t: 'Application.runInBackground', u: 'https://docs.unity3d.com/ScriptReference/Application-runInBackground.html', p: 'Unity', n: '백그라운드에서 앱이 일시 정지하는 기본 동작' },
    { t: 'Actor Priority in Unreal Engine', u: 'https://dev.epicgames.com/documentation/en-us/unreal-engine/actor-priority-in-unreal-engine', p: 'Epic Games', n: '대역폭이 포화되면 우선순위에 따라 일부 액터만 복제' },
  ],
});
