/* 장별 출처: 전체 지도(journey), 집 네트워크(l-home), 인터넷 회선(l-isp), 데이터센터 네트워크 장비(l-dc-net)
   본문·표와 시뮬레이션 journey·bloat·distance·timeouts의 근거 */
Object.assign(DATA.secRefs, {
  'journey': [
    { t: 'ITU-T G.114: One-way transmission time', u: 'https://www.itu.int/rec/T-REC-G.114-200305-I/en', p: 'ITU', n: '광케이블 전송 지연 5µs/km(1,000km 편도 5ms), 편도 150ms 이하면 대부분 응용에 거의 투명하지만 상호작용이 강한 작업은 100ms 아래에서도 영향' },
    { t: 'Azure network round-trip latency statistics', u: 'https://learn.microsoft.com/en-us/azure/networking/azure-network-latency', p: 'Microsoft Azure', n: '실험의 서버 위치별 인터넷 구간 규모: 서울 기준 부산 지역 8ms, 도쿄 30ms, 싱가포르 68ms, 미국 서부 124~136ms, 유럽 234~244ms(왕복 중앙값)' },
    { t: 'The Internet at the Speed of Light (HotNets 2014)', u: 'https://conferences.sigcomm.org/hotnets/2014/papers/hotnets-XIII-final111.pdf', p: 'ACM', n: '실험의 경로 배수 1.5: 실제 라우터 경로는 광케이블 직선 대비 중앙값 약 1.5배' },
    { t: 'Report ITU-R M.2134: Requirements related to technical performance for IMT-Advanced radio interface(s)', u: 'https://www.itu.int/pub/R-REP-M.2134-2008', p: 'ITU', n: 'LTE-Advanced 무선 구간 한 방향 지연 요구치 10ms 미만(무부하·작은 패킷 기준, 실험의 LTE 값은 여기에 부하와 스케줄링 대기를 더한 가정)' },
    { t: 'Report ITU-R M.2410: Minimum requirements related to technical performance for IMT-2020 radio interface(s)', u: 'https://www.itu.int/pub/R-REP-M.2410-2017', p: 'ITU', n: '5G(IMT-2020) 무선 구간 한 방향 지연 요구치 4ms(eMBB, 무부하 기준)' },
    { t: 'An Experimental Study of Home Gateway Characteristics (IMC 2010)', u: 'https://conferences.sigcomm.org/imc/2010/papers/p260.pdf', p: 'ACM', n: '실험의 공유기 대기열: 가정용 공유기는 업로드와 다운로드가 겹치면 대기 지연이 수백 ms(최대 약 400ms)까지 늘기도 함' },
    { t: 'Maximum transmission unit and maximum segment size', u: 'https://developers.cloudflare.com/magic-transit/reference/mtu-mss/', p: 'Cloudflare', n: '실험의 DDoS 방어 경유: 들어오는 트래픽만 방어망을 거치고 서버의 응답은 인터넷으로 바로 나감(DSR)' },
  ],
  'l-home': [
    { t: 'RFC 7567: IETF Recommendations Regarding Active Queue Management', u: 'https://www.rfc-editor.org/rfc/rfc7567', p: 'IETF', n: '장비 대기열이 쌓이는 것이 인터넷 지연의 주요 원인이고, 대기열 관리(AQM)를 기본으로 쓰라는 권고' },
    { t: 'RFC 8289: Controlled Delay Active Queue Management', u: 'https://www.rfc-editor.org/rfc/rfc8289', p: 'IETF', n: 'CoDel의 목표 대기 시간 5ms·관찰 간격 100ms(실험의 SQM 대기열 5ms 안팎)' },
    { t: 'RFC 8290: The Flow Queue CoDel Packet Scheduler and Active Queue Management Algorithm', u: 'https://www.rfc-editor.org/rfc/rfc8290', p: 'IETF', n: 'FQ-CoDel: 주소·포트로 흐름마다 대기열을 나누고, 대기열을 만들지 않는 작은 흐름을 먼저 내보냄' },
    { t: 'What Can I Do About Bufferbloat?', u: 'https://www.bufferbloat.net/projects/bloat/wiki/What_can_I_do_about_Bufferbloat/', p: 'Bufferbloat.net', n: 'cake·fq_codel 같은 SQM을 지원하는 공유기를 쓰고, 부하 중 지연을 재 가며 SQM 속도를 맞추기' },
    { t: 'An Experimental Study of Home Gateway Characteristics (IMC 2010)', u: 'https://conferences.sigcomm.org/imc/2010/papers/p260.pdf', p: 'ACM', n: '가정용 공유기 34종 측정: 업로드·다운로드가 겹칠 때 대기 지연 최대 약 400ms, UDP 매핑 유지 중앙값 90초' },
    { t: 'Ending the Anomaly: Achieving Low Latency and Airtime Fairness in WiFi (USENIX ATC 2017)', u: 'https://www.usenix.org/system/files/conference/atc17/atc17-hoiland-jorgensen.pdf', p: 'USENIX', n: '와이파이 무선 대기열에서도 부하 중 수백 ms 지연, 느린 기기가 다른 기기의 전송 시간까지 잡아먹음' },
    { t: 'RFC 4787: Network Address Translation (NAT) Behavioral Requirements for Unicast UDP', u: 'https://www.rfc-editor.org/rfc/rfc4787', p: 'IETF', n: 'NAT의 UDP 매핑 타이머 요구치(2분 이상, 기본 5분 이상 권장)와 안쪽에서 나가는 패킷으로 갱신' },
    { t: 'RFC 8325: Mapping Diffserv to IEEE 802.11', u: 'https://www.rfc-editor.org/rfc/rfc8325', p: 'IETF', n: '와이파이는 채널이 바쁘면 미루고 무작위 백오프 뒤에 보내는 CSMA/CA 방식' },
    { t: 'Resolve Wi-Fi and Bluetooth issues caused by wireless interference', u: 'https://support.apple.com/en-us/102319', p: 'Apple', n: '실험의 전자레인지 간섭: 전자레인지·블루투스 등이 2.4GHz 와이파이를 방해하고, 5GHz로 옮기면 나아짐' },
    { t: 'RFC 9438: CUBIC for Fast and Long-Distance Networks', u: 'https://www.rfc-editor.org/rfc/rfc9438', p: 'IETF', n: '실험의 업로드 속도 조절: CUBIC은 손실을 겪으면 전송 창을 0.7배(약 30% 감소)로 줄였다가 다시 늘림' },
  ],
  'l-isp': [
    { t: 'ITU-T G.114: One-way transmission time', u: 'https://www.itu.int/rec/T-REC-G.114-200305-I/en', p: 'ITU', n: '광케이블 전송 지연 5µs/km: 빛은 광케이블에서 초속 약 20만 km, 1,000km 왕복 최소 10ms' },
    { t: 'The Internet at the Speed of Light (HotNets 2014)', u: 'https://conferences.sigcomm.org/hotnets/2014/papers/hotnets-XIII-final111.pdf', p: 'ACM', n: '실제 라우터 경로는 광케이블 직선 대비 중앙값 약 1.5배, 최소 핑은 빛의 속도 대비 3.2배(광케이블 직선 대비 약 2배)' },
    { t: 'Azure network round-trip latency statistics', u: 'https://learn.microsoft.com/en-us/azure/networking/azure-network-latency', p: 'Microsoft Azure', n: '서울 기준 실측 왕복 중앙값: 도쿄 30ms, 미국 서부 124~136ms, 유럽 234~244ms(한국–유럽은 광케이블 직선의 약 2.8배)' },
    { t: 'AAE-1 & SMW5 cable cuts impact millions of users across multiple countries', u: 'https://blog.cloudflare.com/aae-1-smw5-cable-cuts/', p: 'Cloudflare', n: '유럽–아시아 트래픽은 대개 이집트를 지나고, 해저 케이블 수리는 며칠~몇 주' },
    { t: 'Quantifying the Causes of Path Inflation (SIGCOMM 2003)', u: 'https://conferences.sigcomm.org/sigcomm/2003/papers/p113-spring.pdf', p: 'ACM', n: '통신사 사이 피어링 정책과 도메인 간 라우팅이 경로를 크게 늘림' },
    { t: 'Inferring Persistent Interdomain Congestion (SIGCOMM 2018)', u: 'https://www.caida.org/catalog/papers/2018_inferring_persistent_interdomain_congestion/inferring_persistent_interdomain_congestion.pdf', p: 'ACM', n: '일부 통신사 간 연결 구간은 매일 피크 시간마다 지연과 손실이 오르는 반복 혼잡을 보임' },
    { t: 'RFC 4271: A Border Gateway Protocol 4 (BGP-4)', u: 'https://www.rfc-editor.org/rfc/rfc4271', p: 'IETF', n: '인터넷 경로 정보를 주고받는 BGP, 홀드 타임 권장 기본값 90초' },
    { t: 'BGP updates in 2024', u: 'https://blog.apnic.net/2025/01/07/bgp-updates-in-2024/', p: 'APNIC', n: '불안정해진 경로가 다시 안정되기까지 하루 평균 25~50초' },
    { t: 'Delayed Internet Routing Convergence (SIGCOMM 2000)', u: 'https://conferences.sigcomm.org/sigcomm/2000/conf/paper/sigcomm2000-5-2.pdf', p: 'ACM', n: '경로 장애 뒤 수렴에 수 분까지 걸리고 그동안 손실·지연이 늘어남(2000년 당시 측정)' },
  ],
  'l-dc-net': [
    { t: 'High-Resolution Measurement of Data Center Microbursts (IMC 2017)', u: 'https://conferences.sigcomm.org/imc/2017/papers/imc17-final60.pdf', p: 'ACM', n: '데이터센터 네트워크의 종단 간 지연은 1ms 미만이고, 버스트의 70% 이상이 수십 µs 안에 끝나 평균 사용률로는 안 보임' },
    { t: 'Data Center TCP (DCTCP) (SIGCOMM 2010)', u: 'https://conferences.sigcomm.org/sigcomm/2010/papers/sigcomm/p63.pdf', p: 'ACM', n: '범용 스위치는 여러 포트가 얕은 버퍼를 나눠 쓰고, 짧은 순간 여러 흐름이 한 포트로 몰리면 버퍼가 넘쳐 손실' },
    { t: 'Netfilter Conntrack Sysfs variables', u: 'https://docs.kernel.org/networking/nf_conntrack-sysctl.html', p: 'Linux kernel', n: '연결 추적 표의 최대 항목 수와 유지 시간 기본값(UDP 30초·스트림 120초, 성립된 TCP 5일)' },
    { t: 'Edit attributes for your Application Load Balancer', u: 'https://docs.aws.amazon.com/elasticloadbalancing/latest/application/edit-load-balancer-attributes.html', p: 'AWS', n: 'ALB 유휴 타임아웃 기본 60초, 시간이 되면 로드밸런서가 연결을 닫음' },
    { t: 'Network Load Balancers', u: 'https://docs.aws.amazon.com/elasticloadbalancing/latest/network/network-load-balancers.html', p: 'AWS', n: '실험의 로드밸런서 기본값: NLB TCP 350초, UDP 120초(변경 불가), 유휴 뒤에는 조용히 추적을 멈춤' },
    { t: 'Configure load balancer TCP reset and idle timeout', u: 'https://learn.microsoft.com/en-us/azure/load-balancer/load-balancer-tcp-idle-timeout', p: 'Microsoft Azure', n: 'Azure Load Balancer 유휴 타임아웃 기본 4분' },
    { t: 'Amazon EC2 security group connection tracking', u: 'https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/security-group-connection-tracking.html', p: 'AWS', n: '보안 그룹 연결 추적 기본값, 로드밸런서·방화벽의 TCP 유휴 타임아웃은 흔히 60~90분이라는 설명' },
    { t: 'Flow-Based Sessions', u: 'https://www.juniper.net/documentation/us/en/software/junos/flow-packet-processing/topics/topic-map/security-flow-based-session-for-srx-series-devices.html', p: 'Juniper Networks', n: '실험의 회사 방화벽: SRX 방화벽 기본 세션 타임아웃 TCP 1,800초(30분), UDP 60초' },
    { t: 'An Experimental Study of Home Gateway Characteristics (IMC 2010)', u: 'https://conferences.sigcomm.org/imc/2010/papers/p260.pdf', p: 'ACM', n: '실험의 가정 공유기 값: UDP 매핑 중앙값 90초(양방향 트래픽이면 180초), TCP 중앙값 약 60분' },
    { t: 'A Multi-perspective Analysis of Carrier-Grade NAT Deployment (IMC 2016)', u: 'https://www.icir.org/vern/papers/cgn-imc16.pdf', p: 'ACM', n: '실험의 CGNAT UDP 30초: CGN UDP 매핑 중앙값 유선망 35초·모바일망 65초, 측정된 NAT의 74%가 1분 이하' },
    { t: 'tcp(7) — Linux manual page', u: 'https://man7.org/linux/man-pages/man7/tcp.7.html', p: 'Linux man-pages', n: '실험의 TCP keepalive: 기본 2시간(7,200초) 유휴 뒤 75초 간격으로 9번 확인하고 응답이 없으면 끊음' },
    { t: 'Cached apps freezer', u: 'https://source.android.com/docs/core/perf/cached-apps-freezer', p: 'Android (Google)', n: '실험의 모바일 백그라운드: 안드로이드 14 이상은 캐시 상태에 들어간 앱 프로세스를 10초 뒤 얼림' },
    { t: 'RFC 5880: Bidirectional Forwarding Detection (BFD)', u: 'https://www.rfc-editor.org/rfc/rfc5880', p: 'IETF', n: '라우팅 프로토콜의 초 단위 Hello보다 빠르게 경로 고장을 감지하는 BFD' },
    { t: 'RFC 2923: TCP Problems with Path MTU Discovery', u: 'https://www.rfc-editor.org/rfc/rfc2923', p: 'IETF', n: 'ICMP가 막혀 큰 패킷만 사라지는 경로 MTU 블랙홀' },
  ],
});
